/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005b63f4  name=FUN_005b63f4  size=156  xrefs=7
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_005b63f4(int param_1)

{
  undefined4 uVar1;
  uint uVar2;
  
  uVar1 = (**(code **)(*(int *)(*(int *)(param_1 + 0xa8) + 0xc) + 0x18))
                    (*(int *)(param_1 + 0xa8),param_1 + 0x40);
  uVar2 = *(uint *)(param_1 + 0x70);
  *(uint *)(param_1 + 0x70) = uVar2 & 0xfffffffd;
  *(undefined4 *)(param_1 + 0x8c) = 0;
  if ((uVar2 & 4) != 0) {
    *(uint *)(param_1 + 0x70) = uVar2 & 0xfffffff9;
    (**(code **)(iRam0100b314 + 0x18))(0x100b308,param_1 + 0x50);
  }
  return uVar1;
}

