/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003b92ec  name=FUN_003b92ec  size=224  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


bool FUN_003b92ec(undefined4 param_1,undefined4 param_2)

{
  bool bVar1;
  int iVar2;
  int iVar3;
  uint uVar4;
  undefined4 *puVar5;
  int *piVar6;
  uint uVar7;
  int aiStack_2018 [2048];
  
  do {
    iVar2 = FUN_003ba2f4(param_1,param_2,1,1);
    if (iVar2 == 0) {
      return false;
    }
    piVar6 = aiStack_2018;
    puVar5 = (undefined4 *)0xd27c04;
    iVar2 = 0x7ff;
    do {
      puVar5 = puVar5 + 1;
      iVar3 = FUN_003bb4a4(param_1,*puVar5);
      piVar6 = piVar6 + 1;
      *piVar6 = iVar3;
      iVar2 = iVar2 + -1;
    } while (iVar2 != 0);
    uVar7 = 0;
    do {
      iVar2 = 1;
      while (uVar4 = *(uint *)(iVar2 * 4 + 0xd27c04),
            1 < (uVar7 + aiStack_2018[iVar2]) - ((uVar7 + aiStack_2018[iVar2]) / uVar4) * uVar4) {
        iVar2 = iVar2 + 1;
        if (0x7ff < iVar2) {
          iVar2 = FUN_003bb604(param_1,uVar7);
          return iVar2 != 0;
        }
      }
      bVar1 = uVar7 <= uVar7 + 2;
      uVar7 = uVar7 + 2;
    } while (bVar1);
  } while( true );
}

