/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003f16a0  name=FUN_003f16a0  size=1540  xrefs=5
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_003f16a0(int param_1,uint param_2,int param_3,undefined4 param_4,int param_5)

{
  bool bVar1;
  byte bVar2;
  ushort uVar3;
  undefined1 uVar4;
  undefined1 uVar5;
  undefined1 uVar6;
  undefined4 uVar7;
  int iVar8;
  int iVar9;
  uint uVar10;
  undefined1 *puVar11;
  int iVar12;
  undefined1 uVar13;
  byte *pbVar14;
  byte in_cr0;
  byte in_cr1;
  byte unaff_cr2;
  byte unaff_cr3;
  byte unaff_cr4;
  byte in_cr5;
  byte in_cr6;
  byte in_cr7;
  undefined1 auStack_40 [4];
  undefined4 uStack_3c;
  undefined2 uStack_36;
  uint uStack_2c;
  
  uStack_2c = (uint)(in_cr0 & 0xf) << 0x1c | (uint)(in_cr1 & 0xf) << 0x18 |
              (uint)(unaff_cr2 & 0xf) << 0x14 | (uint)(unaff_cr3 & 0xf) << 0x10 |
              (uint)(unaff_cr4 & 0xf) << 0xc | (uint)(in_cr5 & 0xf) << 8 | (uint)(in_cr6 & 0xf) << 4
              | (uint)(in_cr7 & 0xf);
  bVar1 = param_2 == 5;
  pbVar14 = *(byte **)(param_1 + 8);
  iVar8 = (*pbVar14 & 0xf) * 4;
  if (bVar1) {
    uVar3 = *(ushort *)(pbVar14 + 6);
  }
  else {
    uVar3 = *(ushort *)(pbVar14 + 6);
    iRam0100ab68 = iRam0100ab68 + 1;
  }
  if ((uVar3 & 0x9fff) != 0) goto LAB_003f18cc;
  if ((((((pbVar14[9] == 1 && param_2 != 5) && (iVar8 + 8U <= *(uint *)(param_1 + 0xc))) &&
        (bVar2 = pbVar14[iVar8], bVar2 != 0)) &&
       (((bVar2 != 8 && (bVar2 != 9)) && ((bVar2 != 10 && ((bVar2 != 0xd && (bVar2 != 0xe)))))))) &&
      (bVar2 != 0xf)) && (((bVar2 != 0x10 && (bVar2 != 0x11)) && (bVar2 != 0x12)))) {
    iRam0100ab70 = iRam0100ab70 + 1;
    goto LAB_003f18cc;
  }
  if ((*(ushort *)(param_1 + 0x12) & 0x300) != 0) goto LAB_003f18cc;
  uVar10 = (uint)*(ushort *)(pbVar14 + 2);
  if ((uint)(iVar8 + iRam00e28a3c) < (uint)*(ushort *)(pbVar14 + 2)) {
    uVar10 = iVar8 + iRam00e28a3c;
  }
  iVar8 = uVar10 + 0x1c;
  if (iVar8 < 0x80) {
    iVar8 = 0x80;
  }
  iVar8 = FUN_005df31c(uRam00e281f0,iVar8,1,2,1);
  if (iVar8 == 0) {
    FUN_003cb350(0xd70b7c);
    goto LAB_003f18cc;
  }
  *(ushort *)(iVar8 + 0x12) = *(ushort *)(iVar8 + 0x12) | 2;
  if (uVar10 < 0x14) {
    FUN_003cb350(0xd70b98);
    FUN_005df294(iVar8);
    goto LAB_003f18cc;
  }
  *(uint *)(iVar8 + 0xc) = uVar10 + 8;
  puVar11 = (undefined1 *)
            (*(int *)(iVar8 + 8) +
            (*(int *)(*(int *)(iVar8 + 0x38) + 4) - (uVar10 + 8) & 0xfffffffc));
  *(undefined1 **)(iVar8 + 8) = puVar11;
  uVar13 = (undefined1)param_2;
  uVar5 = (undefined1)(param_2 >> 8);
  uVar6 = (undefined1)(param_2 >> 0x10);
  uVar4 = (undefined1)(param_2 >> 0x18);
  if (param_2 < 0x13) {
    *(int *)(param_2 * 4 + 0x100ab74) = *(int *)(param_2 * 4 + 0x100ab74) + 1;
    *puVar11 = uVar13;
    if (bVar1) goto LAB_003f1800;
LAB_003f19f4:
    *(undefined4 *)(puVar11 + 4) = 0;
    if (param_2 == 0xc) {
      puVar11[4] = (char)param_3;
      param_3 = 0;
    }
    else if ((param_2 == 3 && param_3 == 4) && (param_5 != 0)) {
      if (*(char *)(param_5 + 0x4c) == -99) {
        auStack_40[0] = 2;
        uStack_3c = param_4;
        iVar12 = (**(code **)(param_5 + 0xb0))(param_5,0x4004651a,auStack_40);
        if (iVar12 == 0) {
          *(undefined2 *)(puVar11 + 6) = uStack_36;
        }
      }
      else {
        *(short *)(puVar11 + 6) = (short)*(undefined4 *)(param_5 + 0x54);
      }
    }
  }
  else {
    if (((iRam00e29390 != 0) && ((uRam00e9c3d0 & 0x1000001f) == 0x1000001f)) &&
       ((*(byte *)(iRam00e9bf84 + 7) & 2) != 0)) {
      uRam00fc0bb8 = 1;
      uRam00fc0bc0 = 0;
      uRam00fc0bb4 = (uint)bRam00e28972 << 0x18 | (uint)bRam00e28971 << 0x10 |
                     (uint)bRam00e28970 << 8 | 0x80000003;
      uRam00fc0bc1 = 10;
      uRam00fc0bbd = 10;
      uRam00fc0bbe = 0;
      uRam00fc0bbf = 0;
      uRam00fc0bb9 = uVar4;
      uRam00fc0bba = uVar6;
      uRam00fc0bbb = uVar5;
      uRam00fc0bbc = uVar13;
      (*pcRam00e9c4d0)(0x4fb0,3,uRam00fc0bb4,0x4016a0,0x1c,0,0,0,0xc,0xfc0bb8);
    }
    FUN_00419de0(0xd70b70);
    *(int *)(param_2 * 4 + 0x100ab74) = *(int *)(param_2 * 4 + 0x100ab74) + 1;
    *puVar11 = uVar13;
    if (!bVar1) goto LAB_003f19f4;
LAB_003f1800:
    *(undefined4 *)(puVar11 + 4) = param_4;
  }
  puVar11[1] = (char)param_3;
  FUN_003db870(param_1,0,puVar11 + 8,uVar10,0);
  iVar12 = *(int *)(iVar8 + 8);
  if (iVar12 - 0x14U < **(uint **)(iVar8 + 0x38)) {
    if (((iRam00e29390 != 0) && ((uRam00e9c3d0 & 0x1000001f) == 0x1000001f)) &&
       ((*(byte *)(iRam00e9bf84 + 7) & 2) != 0)) {
      uRam00fc0bb8 = 1;
      uRam00fc0bc0 = 0;
      uRam00fc0bc1 = 10;
      uRam00fc0bb4 = (uint)bRam00e28972 << 0x18 | (uint)bRam00e28971 << 0x10 |
                     (uint)bRam00e28970 << 8 | 0x80000004;
      uRam00fc0bbd = 10;
      uRam00fc0bbe = 0;
      uRam00fc0bbf = 0;
      uRam00fc0bb9 = uVar4;
      uRam00fc0bba = uVar6;
      uRam00fc0bbb = uVar5;
      uRam00fc0bbc = uVar13;
      (*pcRam00e9c4d0)(0x4fb0,3,uRam00fc0bb4,0x4016a0,1,0,0,0,0xc,0xfc0bb8);
    }
    FUN_00419de0(0xd70b64);
    iVar12 = *(int *)(iVar8 + 8);
  }
  uVar7 = *(undefined4 *)(param_1 + 0x18);
  iVar9 = *(int *)(iVar8 + 0xc) + 0x14;
  *(int *)(iVar8 + 8) = iVar12 + -0x14;
  *(int *)(iVar8 + 0x1c) = iVar9;
  *(undefined4 *)(iVar8 + 0x18) = uVar7;
  *(int *)(iVar8 + 0xc) = iVar9;
  FUN_0036c8ac(pbVar14,iVar12 + -0x14,0x14);
  uVar7 = *(undefined4 *)(iVar8 + 0xc);
  *(undefined1 *)(iVar12 + -0x14) = 0x45;
  *(undefined1 *)(iVar12 + -0x13) = 0;
  *(short *)(iVar12 + -0x12) = (short)uVar7;
  *(undefined1 *)(iVar12 + -0xb) = 1;
  FUN_003f11b0(iVar8);
LAB_003f18cc:
  FUN_005df2e0(param_1);
  return;
}

