/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001ed694  name=FUN_001ed694  size=104  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_001ed694(int *param_1)

{
  int iVar1;
  
  iVar1 = 0;
  if (-1 < param_1[1]) {
    if (param_1[9] != 0) {
      iVar1 = (**(code **)(*param_1 + 0xc))();
      return iVar1;
    }
    iVar1 = param_1[0xd];
  }
  return iVar1;
}

