/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0044c154  name=FUN_0044c154  size=776  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


/* WARNING: Type propagation algorithm not settling */

undefined4 FUN_0044c154(uint param_1,int *param_2,int *param_3)

{
  int *piVar1;
  int *piVar2;
  uint uVar3;
  int iVar4;
  int iVar5;
  undefined4 uVar6;
  undefined4 *puVar7;
  int iVar8;
  int *piVar9;
  int *piVar10;
  int aiStack_3c [10];
  
  iVar4 = FUN_004435c8();
  if (iVar4 != 0) {
    return 0xffffffff;
  }
  if (param_1 == 2) goto LAB_0044c338;
  if (2 < param_1) {
    uVar3 = uRam00e9c3e0;
    if ((param_1 != 3) && (uVar3 = param_1, uRam00e9c3e0 != param_1)) goto LAB_0044c338;
    param_1 = uVar3;
    iVar4 = iRam00e3a790;
    if (uRam00e9c3e0 != 0) {
      iVar4 = *(int *)(uRam00e9c3e0 + 0x94);
    }
    if (((iRam00e3a790 == iVar4) || (*(int *)(param_1 + 0x15c) == 0)) || (iRam00e9c2dc == 0))
    goto LAB_0044c338;
  }
  FUN_0043cdf4();
  iVar4 = FUN_004456c8(uRam00e2952c);
  if (iVar4 == 0) {
    return 0xffffffff;
  }
  FUN_00445840(iVar4,uRam00e2952c);
  *(ushort *)(iVar4 + 8) = *(ushort *)(iVar4 + 8) | 2;
  if ((*(int *)(uRam00e9c3e0 + 0x94) == iRam00e3a790) ||
     ((param_2 != (int *)0x0 && (param_2[2] == 2)))) {
    FUN_00445ac0(iVar4);
  }
  if (param_1 < 4) {
    iVar5 = FUN_005b4b00();
    *(int *)(iVar4 + 0x40) = iVar5;
    if (iVar5 == 0) goto LAB_0044c41c;
  }
  else {
    iVar5 = (*pcRam00e9c65c)();
    *(int *)(iVar4 + 0x40) = iVar5;
    if (iVar5 == 0) goto LAB_0044c41c;
    *(int *)(iVar5 + 0x14) = iVar4;
  }
  *(undefined4 *)(iVar4 + 0x44) = 0;
  uVar6 = FUN_005b2184();
  *(uint *)(iVar4 + 0x4c) = param_1;
  *(undefined4 *)(iVar4 + 0x48) = uVar6;
  if (param_2 == (int *)0x0) {
    aiStack_3c[2] = iVar4;
    aiStack_3c[1] = 0xe;
    aiStack_3c[3] = 4;
  }
  else {
    if (0x3e < *param_2 - 1U) {
      if (param_1 < 4) {
        FUN_005b4f8c(*(undefined4 *)(iVar4 + 0x40));
      }
      else {
        (*pcRam00e9bf28)(*(undefined4 *)(iVar4 + 0x40),param_1);
      }
      FUN_00445794(uRam00e2952c,iVar4);
LAB_0044c338:
      puVar7 = (undefined4 *)FUN_00442914();
      *puVar7 = 0x16;
      return 0xffffffff;
    }
    iVar5 = param_2[2];
    if (iVar5 == 1) {
      iVar5 = 4;
LAB_0044c380:
      param_2[2] = iVar5;
    }
    else {
      if (iVar5 == 2) {
        iVar5 = 8;
        goto LAB_0044c380;
      }
      if (iVar5 == 0x10) {
        iVar5 = 0x20;
        goto LAB_0044c380;
      }
    }
    iVar5 = 3;
    piVar1 = aiStack_3c;
    piVar2 = param_2 + -1;
    do {
      piVar10 = piVar2;
      piVar9 = piVar1;
      iVar8 = piVar10[2];
      piVar9[1] = piVar10[1];
      piVar9[2] = iVar8;
      iVar5 = iVar5 + -1;
      piVar1 = piVar9 + 2;
      piVar2 = piVar10 + 2;
    } while (iVar5 != 0);
    piVar9[3] = piVar10[3];
  }
  iVar5 = 3;
  piVar1 = (int *)(iVar4 + 0x50);
  piVar2 = aiStack_3c;
  do {
    piVar10 = piVar2;
    piVar9 = piVar1;
    iVar8 = piVar10[2];
    piVar9[1] = piVar10[1];
    piVar9[2] = iVar8;
    iVar5 = iVar5 + -1;
    piVar1 = piVar9 + 2;
    piVar2 = piVar10 + 2;
  } while (iVar5 != 0);
  piVar9[3] = piVar10[3];
  iVar5 = FUN_00448854(aiStack_3c + 1);
  *(int *)(iVar4 + 0x50) = iVar5;
  if (iVar5 != 0) {
    *(undefined4 *)(iVar4 + 0x70) = 0;
    *(undefined4 *)(iVar4 + 0x74) = 0;
    *(undefined4 *)(iVar4 + 0x78) = 0;
    *(undefined4 *)(iVar4 + 0x7c) = 0;
    *param_3 = iVar4;
    return 0;
  }
  if (param_1 < 4) {
    FUN_005b4f8c(*(undefined4 *)(iVar4 + 0x40));
  }
  else {
    (*pcRam00e9bf28)(*(undefined4 *)(iVar4 + 0x40),*(undefined4 *)(iVar4 + 0x4c));
  }
LAB_0044c41c:
  FUN_00445794(uRam00e2952c,iVar4);
  return 0xffffffff;
}

