/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002c2a08  name=FUN_002c2a08  size=24  xrefs=5
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002c2a08(int param_1)

{
  *(int *)(param_1 + 0x48) = *(int *)(param_1 + 0x48) + 1;
  return;
}

