/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00329030  name=FUN_00329030  size=100  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00329030(int param_1,int *param_2)

{
  int iVar1;
  undefined4 *puVar2;
  undefined4 uVar3;
  
  iVar1 = *(int *)(param_1 + 0x40);
  *param_2 = iVar1;
  if (((iVar1 == -1) || (uVar3 = 0, *(int *)(param_1 + 0x730) != 8)) ||
     (*(int *)(param_1 + 0x72c) != 2)) {
    puVar2 = (undefined4 *)FUN_00442914();
    *puVar2 = 0x1f50005;
    uVar3 = 0xffffffff;
  }
  return uVar3;
}

