/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0027c088  name=FUN_0027c088  size=124  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_0027c088(int param_1,undefined4 param_2)

{
  int iVar1;
  
  iVar1 = 0;
  if (((*(int *)(param_1 + 0x38) == 0) ||
      (iVar1 = FUN_00283830(*(int *)(param_1 + 0x38)), iVar1 == 0)) &&
     (*(int *)(param_1 + 0x3c) != 0)) {
    iVar1 = FUN_00283830(*(int *)(param_1 + 0x3c),param_2);
  }
  return iVar1;
}

