/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004bedc4  name=FUN_004bedc4  size=120  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_004bedc4(int param_1)

{
  undefined4 uVar1;
  int iVar2;
  
  uVar1 = 0;
  if (param_1 != 0) {
    if (*(int *)(param_1 + 8) == 0) {
      iVar2 = FUN_004a6a04(0x4cefd8,0x4cf020);
      *(int *)(param_1 + 8) = iVar2;
      if (iVar2 == 0) {
        return 0;
      }
    }
    uVar1 = 1;
  }
  return uVar1;
}

