/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001d970c  name=FUN_001d970c  size=44  xrefs=24
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_001d970c(void)

{
  int iVar1;
  
  iVar1 = FUN_005b05a0();
  return -(uint)(iVar1 != 0);
}

