/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003e4f14  name=FUN_003e4f14  size=120  xrefs=4
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_003e4f14(int *param_1,uint param_2,int param_3)

{
  undefined4 uVar1;
  int iVar2;
  
  if ((param_1 == (int *)0x0) || (*param_1 == 0)) {
    uVar1 = 0x6d0002;
  }
  else if ((*(ushort *)(param_1 + 2) == param_2) && (param_1[4] == param_3)) {
    iVar2 = FUN_003e4b8c();
    if (iVar2 == 0) {
      return 0;
    }
    uVar1 = 0x16;
  }
  else {
    uVar1 = 0x16;
  }
  FUN_00442990(uVar1);
  return 0xffffffff;
}

