/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002b4694  name=FUN_002b4694  size=844  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002b4694(int param_1)

{
  uint uVar1;
  int iVar2;
  undefined4 uVar3;
  uint uVar4;
  uint *puVar5;
  int iVar6;
  int *piVar7;
  int iVar8;
  int iStack_60;
  uint *puStack_5c;
  uint *puStack_58;
  undefined1 auStack_50 [64];
  
  puVar5 = *(uint **)(param_1 + 0x14);
  piVar7 = *(int **)(*(int *)(param_1 + 0x10) + 0x16f8);
  if (puVar5 != (uint *)0x0) goto LAB_002b46c8;
  iStack_60 = 6;
  puStack_5c = puVar5;
  puStack_58 = puVar5;
  FUN_002b52d8(param_1,&iStack_60);
  uVar1 = *(uint *)(param_1 + 0x6c);
  if ((uVar1 & 0x80) == 0) {
    if ((uVar1 & 0x20) != 0) {
      uVar3 = FUN_0028f64c(*(undefined4 *)(param_1 + 0x70));
      goto LAB_002b488c;
    }
    if ((uVar1 & 0x100) == 0) {
      if (iStack_60 != 2) {
        uVar3 = FUN_002a32f8(*(undefined4 *)(param_1 + 0x70),&iStack_60);
        uVar3 = FUN_0028f6a8(*(undefined4 *)(param_1 + 0x70),uVar3,0,0);
        goto LAB_002b488c;
      }
      iVar8 = FUN_00287b9c(&iStack_60,piVar7);
      if (iVar8 != 0) {
        iVar2 = FUN_00290b1c(*(int *)(param_1 + 0x70),
                             *(undefined4 *)(*(int *)(param_1 + 0x70) + 0x80),iVar8);
        if (iVar2 != 0) {
          uVar3 = FUN_0028f1bc(*(undefined4 *)(param_1 + 0x70),iVar2);
          *(undefined4 *)(param_1 + 0x14) = uVar3;
        }
        if (iVar8 != 0 && piVar7 != (int *)0x0) {
          (**(code **)(*piVar7 + 0x14))(piVar7,iVar8);
        }
      }
    }
    else {
      if ((*(int *)(param_1 + 0x68) == 0) || ((uVar1 & 0x1000) == 0)) {
        uVar3 = FUN_002a32f8(*(undefined4 *)(param_1 + 0x70),&iStack_60);
        uVar3 = FUN_0028f5b8(*(undefined4 *)(param_1 + 0x70),uVar3);
        goto LAB_002b488c;
      }
      iVar8 = FUN_00289650(*(int *)(param_1 + 0x68),0);
      if ((iVar8 != 0) && (*(int *)(iVar8 + 0x78) != 0)) {
        iVar8 = FUN_0028f5b8(*(undefined4 *)(param_1 + 0x70),
                             *(undefined4 *)(*(int *)(iVar8 + 0x78) + 0x14));
        *(int *)(param_1 + 0x14) = iVar8;
        if (iVar8 != 0) {
          iVar6 = *(int *)(param_1 + 0x68);
          iVar2 = *(int *)(iVar6 + 8);
          *(int *)(iVar8 + 0x558) = iVar6;
          *(int *)(iVar6 + 8) = iVar2 + 1;
        }
      }
    }
  }
  else {
    uVar3 = FUN_0028f14c(*(undefined4 *)(param_1 + 0x70),&iStack_60);
LAB_002b488c:
    *(undefined4 *)(param_1 + 0x14) = uVar3;
  }
  FUN_002875f0(&iStack_60);
  if (puStack_5c != (uint *)0x0) {
    uVar1 = *puStack_5c;
    uVar4 = ((int)(uVar1 << 1 | uVar1 >> 0x1f) >> 1) - 1;
    *puStack_5c = uVar4 & 0x7fffffff | uVar1 & 0x80000000;
    if ((int)(uVar4 * 2) < 1) {
      FUN_0028a778();
    }
  }
  puVar5 = *(uint **)(param_1 + 0x14);
LAB_002b46c8:
  if (puVar5 != (uint *)0x0) {
    iVar8 = param_1 + 0x18;
    FUN_002b5e34(puVar5 + 0x72,iVar8);
    FUN_002b5e34(*(int *)(param_1 + 0x14) + 0x208,iVar8);
    if (*(int *)(param_1 + 0x80) == 0) {
      iVar8 = FUN_002c32ac(*(int *)(*(int *)(param_1 + 0x14) + 0x29c) + 0x1364,iVar8,0);
      FUN_00289da4(*(int *)(param_1 + 0x14) + 0xd8,iVar8);
      if (*(int *)(iVar8 + 0x4c) == 0) {
        FUN_002c2040(iVar8,5);
      }
    }
    else {
      FUN_002b5c68(auStack_50,piVar7,*(undefined4 *)(param_1 + 0x1c),0,0);
      iVar2 = FUN_002b62f8(auStack_50);
      if (iVar2 == 0) {
        iVar2 = *(int *)(param_1 + 0x14);
        iVar8 = **(int **)(param_1 + 0x80);
      }
      else {
        uVar3 = FUN_002c1f28(**(undefined4 **)(param_1 + 0x80));
        iVar8 = FUN_002c32ac(*(int *)(*(int *)(param_1 + 0x14) + 0x29c) + 0x1364,iVar8,uVar3);
        if (*(int *)(iVar8 + 0x4c) == 0) {
          iVar2 = FUN_002c1f78(**(undefined4 **)(param_1 + 0x80));
          if (iVar2 == 0) {
            uVar3 = *(undefined4 *)(**(int **)(param_1 + 0x80) + 0x4c);
          }
          else {
            uVar3 = 7;
          }
          FUN_002c2040(iVar8,uVar3);
        }
        iVar2 = *(int *)(param_1 + 0x14);
      }
      FUN_00289da4(iVar2 + 0xd8,iVar8);
      FUN_002b5f40(auStack_50);
    }
  }
  return;
}

