/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005a81b4  name=FUN_005a81b4  size=152  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_005a81b4(int param_1)

{
  int iVar1;
  
  if (param_1 == 0) {
    uRam00e9c680 = 0;
  }
  else {
    if (iRam00e3a798 == 0) {
      iVar1 = FUN_005b4ac0(0x5b824c);
      if (iVar1 == -1) {
        return 0xffffffff;
      }
      iRam00e3a798 = 1;
    }
    uRam00e9c680 = 1;
    iRam00e9c404 = param_1;
  }
  return 0;
}

