/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004ad7f4  name=FUN_004ad7f4  size=32  xrefs=5
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_004ad7f4(void)

{
  FUN_003b9a78();
  return;
}

