/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0045f8f0  name=FUN_0045f8f0  size=564  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0045f8f0(char *param_1,undefined4 *param_2,int *param_3,int *param_4)

{
  int iVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  code *pcVar5;
  char *pcVar6;
  char cVar7;
  int *piStack_b8;
  int **ppiStack_b4;
  undefined4 uStack_b0;
  undefined1 auStack_ac [36];
  int aiStack_88 [12];
  undefined4 auStack_58 [14];
  
  piStack_b8 = (int *)0xe9c4a8;
  iVar3 = 0;
  memset(auStack_ac,0x84);
  if (*param_1 != '\0') {
    iVar1 = FUN_0039b0f0(param_1);
    if (param_1[iVar1 + -1] == '.') {
      param_1[iVar1 + -1] = '\0';
    }
    *param_3 = 0;
    cVar7 = *param_1;
    pcVar6 = param_1;
    while ((cVar7 != '\0' && (cVar7 != '.'))) {
      pcVar6 = pcVar6 + 1;
      cVar7 = *pcVar6;
    }
    cVar7 = *pcVar6;
    if (cVar7 == '.') {
      *pcVar6 = '\0';
    }
    iVar1 = *piStack_b8;
    if ((iVar1 != 0) && (*param_3 < 0xc)) {
      do {
        iVar2 = FUN_0039ad64(param_1,*(undefined4 *)(iVar1 + 0x18));
        iVar4 = iVar3;
        if (iVar2 == 0) {
          *param_2 = *(undefined4 *)(iVar1 + 8);
          param_2 = param_2 + 1;
          *param_3 = *param_3 + 1;
          if (cVar7 == '\0') {
            if (param_4 != (int *)0x0) {
              *param_4 = iVar1;
            }
            FUN_0045f120(iVar3,auStack_ac);
            return 0;
          }
          if (((*(uint *)(iVar1 + 0xc) & 0xf) != 1) ||
             ((pcVar5 = *(code **)(iVar1 + 0x1c), pcVar5 != reset_vector &&
              ((*(uint *)(iVar1 + 0xc) & 0x1000000) == 0)))) break;
          piStack_b8 = *(int **)(iVar1 + 0x10);
          if (pcVar5 != reset_vector) {
            ppiStack_b4 = &piStack_b8;
            uStack_b0 = 0;
            aiStack_88[iVar3] = iVar1;
            iVar1 = (*pcVar5)(iVar1,&ppiStack_b4,1,auStack_ac);
            if (iVar1 != 0) break;
            iVar4 = iVar3 + 1;
            auStack_58[iVar3] = uStack_b0;
          }
          if (piStack_b8 == (int *)0x0) {
            iVar1 = 0;
          }
          else {
            iVar1 = *piStack_b8;
          }
          param_1 = pcVar6 + 1;
          pcVar6 = pcVar6 + 1;
          cVar7 = *param_1;
          while ((cVar7 != '\0' && (cVar7 != '.'))) {
            pcVar6 = pcVar6 + 1;
            cVar7 = *pcVar6;
          }
          cVar7 = *pcVar6;
          if (cVar7 == '.') {
            *pcVar6 = '\0';
          }
        }
        else {
          iVar1 = *(int *)(iVar1 + 4);
        }
        iVar3 = iVar4;
        if ((iVar1 == 0) || (0xb < *param_3)) break;
      } while( true );
    }
    FUN_0045f120(iVar3,auStack_ac);
  }
  return 2;
}

