/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003ccff8  name=FUN_003ccff8  size=192  xrefs=4
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined8 FUN_003ccff8(undefined4 param_1,undefined4 param_2)

{
  int iVar1;
  undefined4 uVar2;
  undefined8 uVar3;
  
  FUN_00373704(param_1,param_2,0x3df00000,0);
  iVar1 = FUN_003740a0();
  uVar3 = FUN_00373dd0();
  if (iVar1 < 0) {
    uVar3 = FUN_00373370((int)((ulonglong)uVar3 >> 0x20),(int)uVar3,0x41f00000,0);
  }
  uVar3 = FUN_00373704((int)((ulonglong)uVar3 >> 0x20),(int)uVar3,0x41f00000,0);
  FUN_0037336c(param_1,param_2,(int)((ulonglong)uVar3 >> 0x20),(int)uVar3);
  uVar2 = FUN_003740a0();
  return CONCAT44(uVar2,iVar1);
}

