/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00554e24  name=FUN_00554e24  size=52  xrefs=97
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00554e24(short param_1)

{
  undefined4 uVar1;
  
  if (param_1 == 0) {
    uVar1 = 0;
  }
  else {
    FUN_00442990();
    uVar1 = 0xffffffff;
  }
  return uVar1;
}

