/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004cef4c  name=FUN_004cef4c  size=940  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_004cef4c(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3,undefined4 param_4,
                undefined4 param_5,undefined4 param_6,undefined4 param_7)

{
  undefined4 uVar1;
  int iVar2;
  uint uVar3;
  int iVar4;
  byte in_cr0;
  byte in_cr1;
  byte unaff_cr2;
  byte unaff_cr3;
  byte unaff_cr4;
  byte in_cr5;
  byte in_cr6;
  byte in_cr7;
  undefined1 auStack_68 [32];
  undefined4 uStack_48;
  undefined4 uStack_44;
  undefined4 uStack_40;
  undefined4 auStack_3c [2];
  uint uStack_34;
  
  uStack_34 = (uint)(in_cr0 & 0xf) << 0x1c | (uint)(in_cr1 & 0xf) << 0x18 |
              (uint)(unaff_cr2 & 0xf) << 0x14 | (uint)(unaff_cr3 & 0xf) << 0x10 |
              (uint)(unaff_cr4 & 0xf) << 0xc | (uint)(in_cr5 & 0xf) << 8 | (uint)(in_cr6 & 0xf) << 4
              | (uint)(in_cr7 & 0xf);
  iVar4 = 0;
  uStack_40 = 0;
  uStack_48 = 0;
  uStack_44 = 0;
  while( true ) {
    iVar2 = FUN_004ce7d0(param_5,&uStack_48,&uStack_44,&uStack_40,auStack_3c);
    uVar1 = uStack_48;
    if (iVar2 == 0) {
      uVar3 = FUN_004a62e0();
      if ((uVar3 & 0xfff) == 0x6c) {
        FUN_004a6688(2,0xd7cf68,param_4);
      }
      return 0;
    }
    iVar2 = FUN_0039ad64(uStack_48,param_4);
    if ((((iVar2 == 0) ||
         ((iVar2 = FUN_0039ad64(uVar1,0xd7a338), iVar2 == 0 &&
          (iVar2 = FUN_0039ad64(param_4,0xd7a31c), iVar2 == 0)))) ||
        (((iVar2 = FUN_0039ad64(uVar1,0xd7a000), iVar2 == 0 &&
          (iVar2 = FUN_0039ad64(param_4,0xd7a31c), iVar2 == 0)) ||
         ((((iVar2 = FUN_0039ad64(uVar1,0xd79fdc), iVar2 == 0 &&
            (iVar2 = FUN_0039ad64(param_4,0xd7a31c), iVar2 == 0)) ||
           ((iVar2 = FUN_0039ad64(uVar1,0xd79ffc), iVar2 == 0 &&
            (iVar2 = FUN_0039ad64(param_4,0xd7a31c), iVar2 == 0)))) ||
          ((iVar2 = FUN_0039ad64(uVar1,0xd7a02c), iVar2 == 0 &&
           (iVar2 = FUN_0039ad64(param_4,0xd7a31c), iVar2 == 0)))))))) ||
       (((iVar2 = FUN_0039ad64(uVar1,0xd7cf40), iVar2 == 0 &&
         (iVar2 = FUN_0039ad64(param_4,0xd7cf5c), iVar2 == 0)) ||
        ((((iVar2 = FUN_0039ad64(uVar1,0xd79fb8), iVar2 == 0 &&
           (iVar2 = FUN_0039ad64(param_4,0xd79fbc), iVar2 == 0)) ||
          ((iVar2 = FUN_0039ad64(uVar1,0xd7cf5c), iVar2 == 0 &&
           (iVar2 = FUN_0039ad64(param_4,0xd7cf54), iVar2 == 0)))) ||
         (((iVar2 = FUN_0039ad64(uVar1,0xd7cf40), iVar2 == 0 &&
           (iVar2 = FUN_0039ad64(param_4,0xd7cf54), iVar2 == 0)) ||
          ((iVar2 = FUN_0039ad64(uVar1,0xd7cf5c), iVar2 == 0 &&
           (iVar2 = FUN_0039ad64(param_4,0xdebf4c), iVar2 == 0)))))))))) break;
    FUN_004a8858(uStack_48);
    FUN_004a8858(uStack_44);
    FUN_004a8858(uStack_40);
  }
  iVar2 = FUN_004cdb60(uStack_44,auStack_68);
  if (iVar2 != 0) {
    iVar2 = FUN_004cd96c(auStack_68,uStack_40,auStack_3c,param_6,param_7);
    if (iVar2 != 0) {
      *param_1 = uStack_40;
      *param_2 = auStack_3c[0];
      if (param_3 != (undefined4 *)0x0) {
        *param_3 = uStack_48;
      }
      iVar4 = 1;
    }
  }
  if (iVar4 == 0 || param_3 == (undefined4 *)0x0) {
    FUN_004a8858(uStack_48);
  }
  FUN_004a8858(uStack_44);
  if (iVar4 == 0) {
    FUN_004a8858(uStack_40);
    return 0;
  }
  return iVar4;
}

