/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0045d2e0  name=FUN_0045d2e0  size=308  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0045d2e0(uint param_1,uint *param_2)

{
  uint *puVar1;
  int iVar2;
  uint auStack_18 [4];
  
  iVar2 = 0;
  auStack_18[0] = 0;
  puVar1 = (uint *)(iRam00e9c5b4 + -4);
  do {
    puVar1 = puVar1 + 1;
    if ((param_1 & *(uint *)(iRam00e9c190 + 4)) == *puVar1) {
      auStack_18[0] = auStack_18[0] | iVar2 << 1 | 1;
    }
    iVar2 = iVar2 + 1;
  } while (iVar2 < 0x20);
  iVar2 = 0;
  puVar1 = (uint *)(iRam00e9c378 + -4);
  do {
    puVar1 = puVar1 + 1;
    if ((param_1 & *(uint *)(iRam00e9c190 + 0x10)) == *puVar1) {
      auStack_18[0] = auStack_18[0] | iVar2 << 7;
    }
    iVar2 = iVar2 + 1;
  } while (iVar2 < 0x10);
  iVar2 = 0;
  puVar1 = (uint *)(iRam00e9c148 + -4);
  do {
    puVar1 = puVar1 + 1;
    if ((param_1 & *(uint *)(iRam00e9c190 + 8)) == *puVar1) {
      auStack_18[0] = auStack_18[0] | iVar2 << 6;
    }
    iVar2 = iVar2 + 1;
  } while (iVar2 < 2);
  if (pcRam0100b0cc != reset_vector) {
    (*pcRam0100b0cc)(param_1,auStack_18,0,0,0);
  }
  *param_2 = auStack_18[0];
  return 0;
}

