/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0001bb20  name=FUN_0001bb20  size=196  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0001bb20(int param_1,int param_2,undefined4 param_3)

{
  undefined4 uVar1;
  
  if (param_1 == 0) {
    FUN_0000e4e0(0xd34ae8,0x81);
  }
  else {
    uVar1 = 0x82;
    if ((param_2 != 0) && (uVar1 = 0x83, *(int *)(param_1 + 0x20) == 0x11111111)) {
      uRam00e9c0ec = 0;
      *(int *)(param_1 + 0x44) = param_2;
      *(undefined4 *)(param_1 + 0x48) = param_3;
      return;
    }
    uRam00e9c0ec = 0;
    FUN_0000e4e0(0xd34ae8,uVar1);
  }
  uRam00e9c0ec = 1;
  return;
}

