/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001148e4  name=FUN_001148e4  size=140  xrefs=9
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


uint FUN_001148e4(uint *param_1,uint *param_2)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  
  uVar1 = *param_1;
  uVar2 = 1;
  if (uVar1 == 0) {
    if (*param_2 == 0) {
      uVar2 = (uint)(param_1[1] < param_2[1]);
    }
  }
  else {
    uVar3 = *param_2;
    uVar2 = 0;
    if (uVar3 != 0) {
      uVar2 = (uint)(uVar1 < uVar3);
      if (uVar1 == uVar3) {
        uVar2 = FUN_0039ac2c(param_1 + 1,param_2 + 1,8);
        uVar2 = uVar2 >> 0x1f;
      }
    }
  }
  return uVar2;
}

