/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001c9368  name=FUN_001c9368  size=36  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_001c9368(undefined4 param_1)

{
  FUN_001c9100(param_1,0x3f19999a,0x42aa0000,0x442b4000,0x42480000);
  return;
}

