/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0042902c  name=FUN_0042902c  size=88  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0042902c(int param_1)

{
  uRam00e9c0fc = *(undefined4 *)(param_1 + 0xc);
  memset(0xfc189c,0x10);
  uRam00fc189c = 0x10;
  uRam00fc189d = 2;
  return 0;
}

