/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0034fe54  name=FUN_0034fe54  size=52  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0034fe54(undefined4 param_1,undefined2 *param_2)

{
  param_2[7] = 0x40;
  *param_2 = 0x40;
  param_2[1] = 0x40;
  param_2[2] = 0x40;
  param_2[3] = 0x40;
  param_2[4] = 0x40;
  param_2[5] = 0x40;
  param_2[6] = 0x40;
  return 8;
}

