/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00545efc  name=FUN_00545efc  size=496  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00545efc(int param_1,int param_2)

{
  int iVar1;
  int iVar2;
  undefined4 uVar3;
  
  FUN_004a782c(param_2 + 0x9c,1,0xe,0xd91bb0,0x1ad);
  FUN_004a76f8(9,0xc,0xd91bb0,0x1b0);
  iVar1 = FUN_004a7094(*(undefined4 *)(param_1 + 0x10),param_2);
  if (iVar1 == 0 || iVar1 == param_2) {
    if (iVar1 != 0) {
      uVar3 = 0;
      FUN_00545cac(iVar1);
      goto LAB_00545fa0;
    }
  }
  else {
    FUN_00545c24(param_1,iVar1);
    FUN_00545cac(iVar1);
  }
  if ((*(int *)(param_2 + 0xc4) != 0) && (*(int *)(param_2 + 0xc0) != 0)) {
    FUN_00545c24(param_1,param_2);
  }
  iVar1 = *(int *)(param_1 + 0x18);
  if (iVar1 == 0) {
    *(int *)(param_1 + 0x18) = param_2;
    *(int *)(param_1 + 0x1c) = param_2;
    *(int *)(param_2 + 0xc4) = param_1 + 0x1c;
    *(int *)(param_2 + 0xc0) = param_1 + 0x18;
  }
  else {
    *(int *)(iVar1 + 0xc0) = param_2;
    *(int *)(param_2 + 0xc4) = iVar1;
    *(int *)(param_2 + 0xc0) = param_1 + 0x18;
    *(int *)(param_1 + 0x18) = param_2;
  }
  iVar1 = FUN_0054161c(param_1,0x2b,0,0);
  uVar3 = 1;
  if (0 < iVar1) {
    while( true ) {
      iVar1 = FUN_0054161c(param_1,0x14,0,0);
      iVar2 = FUN_0054161c(param_1,0x2b,0,0);
      if ((iVar1 <= iVar2) ||
         (iVar1 = FUN_00545d84(param_1,*(undefined4 *)(param_1 + 0x1c),0), iVar1 == 0)) break;
      *(int *)(param_1 + 0x54) = *(int *)(param_1 + 0x54) + 1;
    }
  }
LAB_00545fa0:
  FUN_004a76f8(10,0xc,0xd91bb0,0x1e2);
  return uVar3;
}

