/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00036bf8  name=FUN_00036bf8  size=172  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00036bf8(int param_1,undefined4 param_2,int param_3,int param_4,uint *param_5)

{
  int iVar1;
  undefined4 uVar2;
  undefined1 uStack_20;
  undefined1 uStack_1f;
  
  iVar1 = (**(code **)(*(int *)(param_1 + 0x30) + 0x44))
                    (param_1,param_2,0,
                     *(int *)(*(int *)(param_1 + 0x30) + 0x58) + *(int *)(param_1 + 0x50) * param_3
                     + ((uint)(param_4 << 1) >> (*(byte *)(param_1 + 0x84) & 0x3f)),
                     *(ushort *)(param_1 + 0x5c) - 1 & param_4 << 1,&uStack_20,2,0);
  uVar2 = 0xffffffff;
  if (iVar1 == 0) {
    *param_5 = (uint)CONCAT11(uStack_1f,uStack_20);
    uVar2 = 0;
  }
  return uVar2;
}

