/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00456db4  name=FUN_00456db4  size=336  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00456db4(void)

{
  int iVar1;
  code *pcVar2;
  undefined4 *puVar3;
  undefined4 uVar4;
  
  uRam00e9c2e4 = 0x466fc4;
  uRam00e9c174 = 0x467048;
  uRam00e9c054 = 0x467050;
  puRam00e9c000 = &LAB_004670d4;
  uRam00e9c640 = 0x4668e4;
  pcRam00e9c010 = FUN_00466b78;
  uRam00e9c50c = 0x466c2c;
  iVar1 = FUN_0044b13c(0x466cc4);
  if (iVar1 == 0) {
    if (*(int *)(iRam00e9c3e0 + 0xdc) != 0) {
      return;
    }
    iVar1 = FUN_00456cc4(iRam00e9c3e0);
    if (iVar1 != -1) {
      return;
    }
    if (pcRam00e9c0b0 == reset_vector) {
      return;
    }
    puVar3 = (undefined4 *)FUN_00442914();
    uVar4 = *puVar3;
    pcVar2 = FUN_0046710c;
  }
  else {
    if (pcRam00e9c0b0 == reset_vector) {
      return;
    }
    pcVar2 = (code *)0x4670dc;
    uVar4 = 0;
  }
  (*pcRam00e9c0b0)(pcVar2,uVar4,0,0,0,0,0);
  return;
}

