/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0043fc90  name=FUN_0043fc90  size=360  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0043fc90(int param_1,int *param_2,undefined4 param_3)

{
  bool bVar1;
  
  if (((iRam00e2942c < 1) && (iRam00e9c05c != 1)) &&
     (bVar1 = iRam00e29390 != 0, *(int *)(iRam00e9c3e0 + 0x7c) = *(int *)(iRam00e9c3e0 + 0x7c) + 1,
     bVar1)) {
    if ((uRam00e9c3d0 & 0x10000001) == 0x10000001) {
      (*pcRam00e9c184)(0x39);
    }
    if ((uRam00e9bffc & 0x10000001) == 0x10000001) {
      (*pcRam00e9bf80)(0x39,0,0,0,0,0,0,0);
    }
  }
  *(int *)(param_1 + 0x78) = *param_2 - param_1;
  FUN_003cb2c0(FUN_004508e8,param_2,0x4508d1);
  FUN_005b3a18(param_3,FUN_004508e8,param_2);
  if (0 < param_2[1]) {
    param_2[1] = param_2[1] + -1;
    *param_2 = *param_2 + 1;
  }
  if ((iRam00e2942c < 1) && (iRam00e9c05c != 1)) {
    FUN_005b1894();
  }
  return;
}

