/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001d5c30  name=FUN_001d5c30  size=364  xrefs=10
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


bool FUN_001d5c30(int param_1,int param_2,int param_3)

{
  int iVar1;
  uint uVar2;
  int iVar3;
  undefined4 uStack_30;
  undefined4 uStack_2c;
  
  FUN_0039acec(param_2,0);
  iVar3 = 0;
  if (*(char *)(param_1 + 0x20e) != '\0') {
    param_3 = param_3 + 2;
  }
  if (param_3 != 0) {
    do {
      uVar2 = param_3 - iVar3;
      uStack_30 = 1;
      uStack_2c = 250000;
      if (0x10 < uVar2) {
        uVar2 = 0x10;
      }
      iVar1 = FUN_001d6a90(param_1,param_2 + iVar3,uVar2,&uStack_30);
      iVar3 = iVar3 + iVar1;
      if (iVar1 + 1U < 2) {
        *(undefined1 *)(param_1 + 0x20d) = 0;
        *(int *)(param_1 + 0x218) = iVar1;
        return false;
      }
    } while (iVar3 != param_3);
  }
  if (*(char *)(param_1 + 0x20e) == '\0') {
    return true;
  }
  iVar3 = FUN_001d5be4(param_1,0xff,param_2,iVar3);
  return iVar3 == 0;
}

