/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005ad9bc  name=FUN_005ad9bc  size=84  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_005ad9bc(int param_1,undefined1 param_2)

{
  *(undefined1 *)(param_1 + 0x41) = param_2;
  *(undefined4 *)(param_1 + 0x54) = 0;
  *(undefined2 *)(param_1 + 0x42) = 0;
  *(undefined1 *)(param_1 + 0x40) = 1;
  *(undefined4 *)(param_1 + 0x5c) = 0;
  *(undefined4 *)(param_1 + 0x58) = 0;
  *(undefined1 *)(param_1 + 0x60) = 0;
  *(undefined4 *)(param_1 + 100) = 0;
  FUN_00445840(param_1,uRam00e3a7c8);
  return 0;
}

