/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00016de4  name=FUN_00016de4  size=284  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00016de4(int *param_1,uint param_2)

{
  uint uVar1;
  undefined4 uVar2;
  
  if (param_1 == (int *)0x0) {
    FUN_0000e4e0(0xd345e0,0x176);
  }
  else {
    uVar2 = 0x177;
    if ((param_2 < 0x1d) && (uVar2 = 0x178, param_1[1] == 0x11111111)) {
      uRam00e9c0ec = 0;
      uVar1 = FUN_0000e898(*param_1 + 8,0x178);
      FUN_0000e900(*param_1 + 8,uVar1 & ~*(uint *)(param_2 * 4 + 0x100b174));
      *(undefined4 *)(param_2 * 8 + param_1[4] + 0x10) = 0x271c4;
      *(int **)(param_2 * 8 + param_1[4] + 0x14) = param_1;
      return;
    }
    uRam00e9c0ec = 0;
    FUN_0000e4e0(0xd345e0,uVar2);
  }
  uRam00e9c0ec = 1;
  return;
}

