/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004a72d0  name=FUN_004a72d0  size=104  xrefs=8
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


uint FUN_004a72d0(byte *param_1)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  uint uVar4;
  uint uVar5;
  
  uVar2 = 0;
  if (param_1 != (byte *)0x0) {
    uVar5 = (uint)*param_1;
    uVar3 = 0x100;
    if (uVar5 != 0) {
      do {
        uVar4 = uVar5 | uVar3;
        param_1 = param_1 + 1;
        uVar5 = (uint)*param_1;
        uVar3 = uVar3 + 0x100;
        uVar1 = (uVar4 >> 2 ^ uVar4) & 0xf;
        uVar2 = (uVar2 << uVar1 | uVar2 >> 0x20 - uVar1) ^ uVar4 * uVar4;
      } while (uVar5 != 0);
      return uVar2 >> 0x10 ^ uVar2;
    }
  }
  return 0;
}

