/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0037192c  name=FUN_0037192c  size=16  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0037192c(void)

{
  sync(0);
  TLBInvalidateAll();
  sync(0);
  return;
}

