/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002897f0  name=FUN_002897f0  size=28  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002897f0(undefined4 *param_1,undefined4 param_2)

{
  param_1[0x12] = 0;
  *param_1 = param_2;
  param_1[0x11] = 0;
  return;
}

