/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00311e04  name=FUN_00311e04  size=188  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


/* WARNING: Control flow encountered bad instruction data */

undefined4 FUN_00311e04(int *param_1)

{
  int iVar1;
  
  switch(param_1[7]) {
  case 200:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xc9:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xca:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xcb:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xcc:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xcd:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xce:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xcf:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xd0:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xd1:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  case 0xd2:
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  default:
    iVar1 = *param_1;
    *(undefined4 *)(iVar1 + 0x14) = 0x14;
    *(int *)(iVar1 + 0x18) = param_1[7];
    return 0xffffffec;
  }
}

