/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00404bf8  name=FUN_00404bf8  size=308  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00404bf8(void)

{
  uRam00e28bd0 = 0x11;
  uRam00e28bf4 = 0x10;
  uRam00e28bf0 = 0x11;
  uRam00e28bf5 = 2;
  uRam00e28bdf = 2;
  uRam00e28be0 = 0x11;
  uRam00e28bcf = 2;
  uRam00e28b58 = 0x4128d0;
  uRam00e28b5c = 0x42e9b0;
  uRam00e28b68 = 0x42e32c;
  uRam00e28b1c = 0x11;
  uRam00e28b20 = 0xdf5de0;
  uRam00e28b48 = 3;
  uRam00e28b52 = 3;
  uRam00e28b6c = 0;
  uRam00e28b70 = 0;
  uRam00e28b74 = 0;
  uRam00e28b44 = 0;
  uRam00e28b50 = 0;
  uRam00e28b78 = 0xe28b7c;
  uRam00e28b30 = 0xe28b48;
  uRam00e28b34 = 0xe28b7c;
  uRam00e28b4c = 0xe28b1c;
  uRam00e28b54 = 0;
  uRam00e28b60 = 0;
  uRam00e28b64 = 0;
  uRam00e28b24 = 0;
  uRam00e28b28 = 0;
  uRam00e28b2c = 0;
  uRam00e28b38 = 0;
  uRam00e28b3c = 0;
  uRam00e28b40 = 0;
  return 0;
}

