/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001e8390  name=FUN_001e8390  size=1368  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


/* WARNING: Removing unreachable block (ram,0x001e8860) */
/* WARNING: Removing unreachable block (ram,0x001e85b8) */
/* WARNING: Removing unreachable block (ram,0x001e8694) */
/* WARNING: Removing unreachable block (ram,0x001e85fc) */
/* WARNING: Removing unreachable block (ram,0x001e88e0) */
/* WARNING: Type propagation algorithm not settling */

undefined8
FUN_001e8390(undefined4 param_1,int param_2,uint param_3,uint *param_4,int param_5,uint param_6,
            int param_7)

{
  int iVar1;
  bool bVar2;
  undefined1 *puVar3;
  undefined4 *******pppppppuVar4;
  int iVar5;
  uint uVar6;
  undefined1 auStack_108 [8];
  undefined1 auStack_100 [4];
  int iStack_fc;
  int iStack_f8;
  int iStack_f4;
  undefined1 auStack_e0 [4];
  undefined4 *******apppppppuStack_dc [4];
  int iStack_cc;
  uint uStack_c8;
  undefined1 auStack_b0 [4];
  undefined4 uStack_ac;
  undefined4 uStack_98;
  undefined4 uStack_94;
  undefined1 *puStack_90;
  undefined4 uStack_8c;
  undefined1 *puStack_88;
  undefined1 *puStack_84;
  int iStack_7c;
  uint uStack_78;
  uint *puStack_74;
  int iStack_70;
  uint uStack_6c;
  int iStack_68;
  int iStack_60;
  int iStack_5c;
  int iStack_58;
  undefined1 *puStack_48;
  int iStack_44;
  int iStack_40;
  uint uStack_3c;
  undefined1 *puStack_38;
  int iStack_34;
  undefined4 *puStack_30;
  undefined4 *puStack_2c;
  undefined4 *puStack_28;
  int iStack_24;
  uint uStack_20;
  
  puStack_84 = &stack0xfffffef0;
  uStack_98 = 0x25710c;
  puStack_90 = auStack_108;
  uStack_94 = 0xe9a875;
  uStack_8c = 0x1f8870;
  puStack_88 = (undefined1 *)register0x00000004;
  iStack_7c = param_2;
  uStack_78 = param_3;
  puStack_74 = param_4;
  iStack_70 = param_5;
  uStack_6c = param_6;
  iStack_68 = param_7;
  FUN_003d1214(auStack_b0);
  iStack_60 = -1;
  iStack_58 = *(int *)(iStack_7c + 0x54);
  iStack_5c = -1;
  iStack_f4 = 0;
  iStack_fc = 0;
  iStack_f8 = 0;
  if (iStack_58 == 0) goto LAB_001e851c;
  puStack_48 = (undefined1 *)(iStack_7c + 0x88);
  if (auStack_100 != puStack_48) {
    iStack_44 = 0;
    if (*(int *)(iStack_7c + 0x8c) != 0) {
      iStack_44 = *(int *)(iStack_7c + 0x90) - *(int *)(iStack_7c + 0x8c) >> 2;
    }
    if (iStack_44 == 0) {
      iStack_5c = -1;
      iStack_60 = -1;
      iStack_f4 = iStack_44;
      iStack_fc = iStack_44;
      iStack_f8 = iStack_44;
    }
    else {
      iVar5 = 0;
      if (*(int *)(iStack_7c + 0x8c) != 0) {
        iVar5 = *(int *)(iStack_7c + 0x90) - *(int *)(iStack_7c + 0x8c) >> 2;
      }
      if (iVar5 == 0) {
LAB_001e8808:
        uStack_ac = 2;
        FUN_0039acb0(iStack_fc,*(int *)(puStack_48 + 4),
                     *(int *)(puStack_48 + 8) - *(int *)(puStack_48 + 4) & 0xfffffffc);
        iVar5 = 0;
        if (*(int *)(puStack_48 + 4) != 0) {
          iVar5 = *(int *)(puStack_48 + 8) - *(int *)(puStack_48 + 4) >> 2;
        }
        iStack_f8 = iStack_fc + iVar5 * 4;
      }
      else {
        iVar5 = 0;
        if (*(int *)(iStack_7c + 0x8c) != 0) {
          iVar5 = *(int *)(iStack_7c + 0x90) - *(int *)(iStack_7c + 0x8c) >> 2;
        }
        if (iVar5 == 0) {
          iStack_40 = *(int *)(iStack_7c + 0x8c);
          uStack_ac = 2;
          FUN_0039acb0(0,iStack_40,0);
          uStack_3c = *(int *)(puStack_48 + 8) - iStack_40 & 0xfffffffc;
          iStack_f8 = FUN_0039acb0(iStack_f8,iStack_40,uStack_3c);
          iStack_f8 = iStack_f8 + uStack_3c;
        }
        else {
          iStack_5c = -1;
          iStack_60 = -1;
          puStack_38 = auStack_100;
          uVar6 = 0;
          if (*(int *)(iStack_7c + 0x8c) != 0) {
            uVar6 = *(int *)(iStack_7c + 0x90) - *(int *)(iStack_7c + 0x8c) >> 2;
          }
          iStack_fc = 0;
          iStack_f8 = 0;
          iStack_f4 = 0;
          bVar2 = false;
          if (uVar6 != 0) {
            if (0x3fffffff < uVar6) {
              uStack_c8 = 0xf;
              apppppppuStack_dc[0] = (undefined4 *******)((uint)apppppppuStack_dc[0] & 0xffffff);
              iStack_cc = 0;
              iStack_34 = FUN_0039b0f0(uRam00d953ac);
              uStack_ac = 2;
              iVar5 = FUN_005f0030(auStack_e0,iStack_34,0);
              if (iVar5 != 0) {
                pppppppuVar4 = apppppppuStack_dc;
                if (0xf < uStack_c8) {
                  pppppppuVar4 = apppppppuStack_dc[0];
                }
                FUN_0039ac74(pppppppuVar4,uRam00d953ac,iStack_34);
                pppppppuVar4 = apppppppuStack_dc;
                if (0xf < uStack_c8) {
                  pppppppuVar4 = apppppppuStack_dc[0];
                }
                iStack_cc = iStack_34;
                *(undefined1 *)((int)pppppppuVar4 + iStack_34) = 0;
              }
              puStack_30 = (undefined4 *)FUN_00245cd8(0x20);
              *puStack_30 = 0xe08170;
              uStack_ac = 1;
              puStack_2c = puStack_30;
              puStack_28 = puStack_30;
              FUN_005f4290(puStack_30 + 1,auStack_e0);
              *puStack_2c = 0xe081b8;
              FUN_005e75e4(auStack_e0,1,0);
              uStack_ac = 2;
              FUN_00247c78(puStack_30,0xe08788,0x5f7a14);
              goto LAB_001e8808;
            }
            iStack_24 = uVar6 << 2;
            uStack_ac = 2;
            iVar5 = FUN_00248640(iStack_24);
            puVar3 = puStack_38;
            *(int *)(puStack_38 + 0xc) = iVar5 + iStack_24;
            *(int *)(puVar3 + 4) = iVar5;
            *(int *)(puVar3 + 8) = iVar5;
            bVar2 = true;
          }
          if (bVar2) {
            uStack_20 = *(int *)(puStack_48 + 8) - *(int *)(puStack_48 + 4) & 0xfffffffc;
            iStack_f8 = FUN_0039acb0(iStack_fc,*(int *)(puStack_48 + 4),uStack_20);
            iStack_f8 = iStack_f8 + uStack_20;
          }
        }
      }
    }
  }
  iVar5 = iStack_58 + -1;
  if (-1 < iVar5) {
    uVar6 = *puStack_74;
    do {
      if (uStack_78 <= uVar6) break;
      iVar1 = iVar5 * 4;
      iVar5 = iVar5 + -1;
      uVar6 = uVar6 + *(int *)(iStack_fc + iVar1);
      *puStack_74 = uVar6;
    } while (-1 < iVar5);
  }
  if (uStack_78 < *puStack_74) {
    iStack_5c = iVar5 * iStack_68 + uStack_6c;
    iStack_60 = iStack_70 + (uint)CARRY4(iVar5 * iStack_68,uStack_6c);
  }
LAB_001e851c:
  if (iStack_fc == 0) {
    iStack_f4 = 0;
    iStack_fc = 0;
    iStack_f8 = 0;
    FUN_003d12b8(auStack_b0);
    return CONCAT44(iStack_5c,iStack_60);
  }
  FUN_00245c34();
  iStack_f4 = 0;
  iStack_fc = 0;
  iStack_f8 = 0;
  FUN_003d12b8(auStack_b0);
  return CONCAT44(iStack_5c,iStack_60);
}

