/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002e848c  name=FUN_002e848c  size=808  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_002e848c(int param_1,int param_2,int param_3)

{
  int iVar1;
  undefined4 uVar2;
  int *piVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  int iVar7;
  int iVar8;
  int *piStack_40;
  int iStack_3c;
  int iStack_30;
  int iStack_2c;
  int iStack_28;
  int iStack_24;
  
  FUN_002578f8(&piStack_40,*(undefined4 *)(param_1 + 0x30),0xd61068);
  iVar7 = *(int *)(param_2 + 0x38) + 10000;
  *(int *)(param_2 + 0x38) = iVar7;
  iVar1 = FUN_002e8c88(param_1);
  iVar5 = 0;
  iVar4 = 0;
  if (iVar1 != 0) {
    *(int *)(param_2 + 0x30) = iVar1;
    FUN_00257e4c(&piStack_40,*(int *)(param_2 + 0x38) + -10000,10);
    iVar1 = iStack_3c;
    if (iStack_3c == 0) {
      iVar1 = 0xd6f55c;
    }
    iVar4 = FUN_00258c6c(piStack_40,iVar1);
    *(int *)(param_2 + 0x44) = iVar4;
    FUN_002f5d34(param_2);
    FUN_003067c0(param_2 + 0x18);
    FUN_0025d518(*(int *)(param_1 + 0x28) + 0x590,
                 *(undefined4 *)(*(int *)(*(int *)(param_1 + 0x20) + 0x20) + 0x78),iVar7);
    iVar5 = FUN_0025c5a0(*(int *)(param_1 + 0x28) + 0x590,
                         *(undefined4 *)(*(int *)(*(int *)(param_1 + 0x20) + 0x20) + 0x78),param_2);
    if ((iVar5 != 0) && (*(int *)(iVar5 + 0x20) != 0)) {
      iStack_30 = *(int *)(param_1 + 0x144);
      iStack_2c = *(int *)(param_1 + 0x148);
      iStack_28 = *(int *)(param_1 + 0x14c);
      iStack_24 = *(int *)(param_1 + 0x150);
      iVar7 = *(int *)(*(int *)(iVar5 + 0x20) + 0x78);
      iVar1 = *(int *)(*(int *)(param_3 + 0x20) + 0x78);
      if (iStack_2c == iStack_30) {
        uVar2 = FUN_00276a1c(*(undefined4 *)(param_1 + 0x20));
        FUN_002f4e38(*(int *)(param_1 + 0x20) + 0x24,uVar2,&iStack_30);
      }
      iVar6 = iStack_2c - iStack_30;
      iVar8 = iStack_24 - iStack_28;
      uVar2 = FUN_00248640(0x34);
      FUN_00277148(uVar2,*(undefined4 *)(param_1 + 0x30),iVar7);
      *(undefined4 *)(iVar7 + 0xb0) = uVar2;
      FUN_002771c8(uVar2,0xffffff,100,0);
      FUN_0027734c(*(undefined4 *)(iVar7 + 0xb0),0,0xffffff,100,0);
      FUN_00277264(*(undefined4 *)(iVar7 + 0xb0),0,0);
      FUN_002772d8(*(undefined4 *)(iVar7 + 0xb0),iVar6,0,1);
      iVar8 = iVar8 + -0x3c;
      FUN_002772d8(*(undefined4 *)(iVar7 + 0xb0),iVar6,iVar8,1);
      FUN_002772d8(*(undefined4 *)(iVar7 + 0xb0),0,iVar8,1);
      FUN_002772d8(*(undefined4 *)(iVar7 + 0xb0),0,0,1);
      FUN_002773b8(*(undefined4 *)(iVar7 + 0xb0));
      if ((iVar7 != 0 && iVar1 != 0) && (iVar7 != iVar1)) {
        *(undefined1 *)(iVar7 + 0x70) = 1;
        *(int *)(iVar7 + 0x6c) = iVar1;
        *(undefined2 *)(iVar7 + 0x68) = 0;
        *(int *)(iVar1 + 0x6c) = iVar7;
        *(undefined2 *)(iVar1 + 0x68) = 0;
        *(undefined1 *)(iVar1 + 0x70) = 0;
        FUN_00275030(iVar7);
        FUN_00275030(iVar1);
      }
    }
  }
  piVar3 = *(int **)(param_1 + 0x30);
  if (iVar4 != 0 && piVar3 != (int *)0x0) {
    (**(code **)(*piVar3 + 0x14))(piVar3,iVar4);
  }
  if (iStack_3c != 0 && piStack_40 != (int *)0x0) {
    (**(code **)(*piStack_40 + 0x14))();
  }
  return iVar5;
}

