/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00443280  name=FUN_00443280  size=8  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00443280(undefined4 param_1)

{
  FUN_00443204(param_1,1);
  return;
}

