/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00285994  name=FUN_00285994  size=952  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00285994(int param_1,int *param_2,undefined4 param_3,int param_4)

{
  undefined4 uVar1;
  uint uVar2;
  undefined1 uVar4;
  int *piVar3;
  int iVar5;
  uint uVar6;
  int iVar7;
  int iVar8;
  int iVar9;
  byte in_cr0;
  byte in_cr1;
  byte unaff_cr2;
  byte unaff_cr3;
  byte unaff_cr4;
  byte in_cr5;
  byte in_cr6;
  byte in_cr7;
  undefined4 uStack_40;
  uint *puStack_3c;
  undefined4 uStack_38;
  uint auStack_30 [4];
  uint uStack_20;
  
  uStack_20 = (uint)(in_cr0 & 0xf) << 0x1c | (uint)(in_cr1 & 0xf) << 0x18 |
              (uint)(unaff_cr2 & 0xf) << 0x14 | (uint)(unaff_cr3 & 0xf) << 0x10 |
              (uint)(unaff_cr4 & 0xf) << 0xc | (uint)(in_cr5 & 0xf) << 8 | (uint)(in_cr6 & 0xf) << 4
              | (uint)(in_cr7 & 0xf);
  FUN_0063b3ec();
  if ((*(int *)(param_1 + 0x18) != 0) && (iVar8 = *(int *)(param_1 + 0x90), iVar8 != 0)) {
    auStack_30[0] = *(ushort *)(param_2 + 8) & 0x10;
    if (((*(ushort *)(param_2 + 8) & 0x10) == 0) && (*(byte *)((int)param_2 + 0x23) < 0x40)) {
      FUN_002a822c();
      uVar4 = FUN_00283fc0();
      uVar1 = *(undefined4 *)(param_1 + 0x90);
      iVar5 = param_2[6];
      *(undefined1 *)(iVar8 + 0x14) = uVar4;
      iVar8 = FUN_002d153c(uVar1,iVar5,auStack_30);
      if ((iVar8 != 0) &&
         (iVar8 = FUN_002a0c94(*(undefined4 *)(param_1 + 0x18),auStack_30[0] + 8), iVar8 != 0)) {
        iVar9 = *(int *)(param_1 + 0x18);
        iVar7 = auStack_30[0] + 0x18;
        iVar5 = FUN_0029c114(iVar9);
        if ((iVar5 != 0) &&
           (((*(int *)(iVar9 + 0xc90) != 0 && (0 < *(int *)(iVar9 + 0xc98))) &&
            (0 < *(int *)(iVar9 + 0xc94))))) {
          FUN_00287e20(*(int *)(iVar9 + 0xc90) + *(int *)(iVar9 + 0xc94) * 0x10 + -0x10,iVar7);
        }
        iVar7 = *(int *)(param_1 + 0x18);
        iVar5 = FUN_0029c114(iVar7);
        if (((iVar5 != 0) && (*(int *)(iVar7 + 0xc90) != 0)) &&
           ((0 < *(int *)(iVar7 + 0xc98) && (0 < *(int *)(iVar7 + 0xc94))))) {
          FUN_00287e20(*(int *)(iVar7 + 0xc90) + *(int *)(iVar7 + 0xc94) * 0x10 + -0x10,param_3);
        }
        if ((param_4 == 0) || (iVar7 = 0, iVar5 = param_1, *param_2 != 6)) {
LAB_00285b40:
          iVar5 = *(int *)(param_1 + 0x18);
          piVar3 = param_2;
        }
        else {
          do {
            iVar5 = FUN_00285d4c(iVar5);
            iVar7 = iVar7 + 1;
            if (iVar5 == 0) goto LAB_00285b40;
            piVar3 = (int *)FUN_00285358(iVar5,param_2 + 6);
            if (piVar3 != (int *)0x0) {
              iVar5 = *(int *)(param_1 + 0x18);
              goto LAB_00285b44;
            }
          } while (iVar7 < 0x100);
          iVar5 = *(int *)(param_1 + 0x18);
          piVar3 = param_2;
          if (iVar5 != 0) {
            *(undefined4 *)(iVar5 + 0xca8) = 1;
          }
        }
LAB_00285b44:
        iVar7 = FUN_0029c114(iVar5);
        if ((((iVar7 != 0) && (*(int *)(iVar5 + 0xc90) != 0)) && (0 < *(int *)(iVar5 + 0xc98))) &&
           (0 < *(int *)(iVar5 + 0xc94))) {
          FUN_00287e20(*(int *)(iVar5 + 0xc90) + *(int *)(iVar5 + 0xc94) * 0x10 + -0x10,piVar3);
        }
        iVar5 = FUN_002a79e8(*(undefined4 *)(param_1 + 0x18));
        uStack_38 = 0;
        puStack_3c = (uint *)0x0;
        uStack_40 = 6;
        uVar1 = 0;
        if (piVar3[6] != 0) {
          uVar1 = *(undefined4 *)(piVar3[6] + 4);
        }
        FUN_00287888(&uStack_40,*(undefined4 *)(*(int *)(param_1 + 0x18) + 0x16f8),uVar1,iVar5);
        iVar9 = *(int *)(param_1 + 0x18);
        iVar7 = FUN_0029c114(iVar9);
        if (((iVar7 != 0) && (*(int *)(iVar9 + 0xc90) != 0)) &&
           ((0 < *(int *)(iVar9 + 0xc98) && (0 < *(int *)(iVar9 + 0xc94))))) {
          FUN_00287e20(*(int *)(iVar9 + 0xc90) + *(int *)(iVar9 + 0xc94) * 0x10 + -0x10,&uStack_40);
        }
        if (iVar5 < 7) {
          *(ushort *)(piVar3 + 8) = *(ushort *)(piVar3 + 8) | 0x3010;
        }
        else {
          *(char *)((int)piVar3 + 0x23) = *(char *)((int)piVar3 + 0x23) + '\x01';
        }
        iVar8 = FUN_0029f2f8(*(undefined4 *)(param_1 + 0x18),param_1,0,0xd6f55c,4,0,iVar8,0,0);
        if (iVar8 != 0) {
          FUN_00263440(*(undefined4 *)(param_1 + 0x18),1);
        }
        if (iVar5 < 7) {
          *(ushort *)(piVar3 + 8) = *(ushort *)(piVar3 + 8) & 0xcfef;
        }
        else {
          *(char *)((int)piVar3 + 0x23) = *(char *)((int)piVar3 + 0x23) + -1;
        }
        FUN_0029c354(*(undefined4 *)(param_1 + 0x18),param_3);
        FUN_002875f0(&uStack_40);
        if (puStack_3c != (uint *)0x0) {
          uVar2 = *puStack_3c;
          uVar6 = ((int)(uVar2 << 1 | uVar2 >> 0x1f) >> 1) - 1;
          *puStack_3c = uVar6 & 0x7fffffff | uVar2 & 0x80000000;
          if ((int)(uVar6 * 2) < 1) {
            FUN_0028a778();
          }
        }
      }
    }
  }
  return;
}

