/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0024e4a4  name=FUN_0024e4a4  size=1700  xrefs=40
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0024e4a4(undefined4 *param_1,undefined4 *param_2)

{
  uint uVar1;
  bool bVar2;
  undefined4 *puVar3;
  uint uVar4;
  byte in_cr0;
  byte in_cr1;
  byte unaff_cr2;
  byte unaff_cr3;
  byte unaff_cr4;
  byte in_cr5;
  byte in_cr6;
  byte in_cr7;
  undefined1 auStack_108 [24];
  undefined1 auStack_f0 [4];
  undefined4 uStack_ec;
  undefined4 uStack_d8;
  undefined4 uStack_d4;
  undefined1 *puStack_d0;
  undefined4 uStack_cc;
  undefined1 *puStack_c8;
  undefined1 *puStack_c4;
  undefined4 *puStack_bc;
  undefined4 *puStack_b8;
  undefined4 *puStack_b4;
  undefined4 *puStack_ac;
  undefined4 *puStack_a8;
  uint uStack_a4;
  undefined4 *puStack_a0;
  uint uStack_9c;
  undefined4 *puStack_98;
  uint uStack_94;
  int iStack_90;
  uint uStack_8c;
  undefined4 *puStack_88;
  undefined4 *puStack_84;
  undefined4 *puStack_80;
  undefined4 *puStack_7c;
  uint uStack_78;
  undefined4 *puStack_74;
  uint uStack_70;
  undefined4 *puStack_6c;
  uint uStack_68;
  int iStack_64;
  uint uStack_60;
  undefined4 *puStack_5c;
  uint uStack_4c;
  
  puStack_c4 = &stack0xfffffef0;
  uStack_4c = (uint)(in_cr0 & 0xf) << 0x1c | (uint)(in_cr1 & 0xf) << 0x18 |
              (uint)(unaff_cr2 & 0xf) << 0x14 | (uint)(unaff_cr3 & 0xf) << 0x10 |
              (uint)(unaff_cr4 & 0xf) << 0xc | (uint)(in_cr5 & 0xf) << 8 | (uint)(in_cr6 & 0xf) << 4
              | (uint)(in_cr7 & 0xf);
  uStack_d8 = 0x25710c;
  puStack_d0 = auStack_108;
  uStack_d4 = 0xe9b84c;
  uStack_cc = 0x25e930;
  puStack_c8 = (undefined1 *)register0x00000004;
  puStack_bc = param_1;
  puStack_b8 = param_2;
  FUN_003d1214(auStack_f0);
  puStack_b4 = puStack_bc + 1;
  *puStack_bc = 0;
  uStack_ec = 0xffffffff;
  FUN_002521d8(0);
  FUN_005e75e4(puStack_b4,0,0);
  FUN_005e75e4(puStack_bc + 8,0,0);
  puStack_a8 = (undefined4 *)FUN_003969c4(1,0);
  puStack_ac = puStack_b4;
  uStack_a4 = FUN_0039b0f0();
  puVar3 = puStack_ac + 1;
  if (0xf < (uint)puStack_ac[6]) {
    puVar3 = (undefined4 *)puStack_ac[1];
  }
  if (puStack_a8 < puVar3) {
LAB_0024e5fc:
    bVar2 = false;
  }
  else {
    puVar3 = puStack_ac + 1;
    if (0xf < (uint)puStack_ac[6]) {
      puVar3 = (undefined4 *)puStack_ac[1];
    }
    bVar2 = true;
    if ((undefined4 *)((int)puVar3 + puStack_ac[5]) <= puStack_a8) goto LAB_0024e5fc;
  }
  if (bVar2) {
    puVar3 = puStack_ac + 1;
    if (0xf < (uint)puStack_ac[6]) {
      puVar3 = (undefined4 *)puStack_ac[1];
    }
    uStack_ec = 7;
    FUN_005ea15c(puStack_ac,puStack_ac,(int)puStack_a8 - (int)puVar3,uStack_a4);
  }
  else {
    puStack_a0 = puStack_ac;
    uStack_9c = uStack_a4;
    if (0xfffffffe < uStack_a4) {
      uStack_ec = 7;
      FUN_002513e0(puStack_ac);
    }
    uVar4 = puStack_ac[6];
    if (uVar4 < uStack_a4) {
      uStack_8c = uStack_a4 | 0xf;
      puStack_98 = puStack_ac;
      iStack_90 = puStack_ac[5];
      uStack_94 = uStack_a4;
      if (uStack_8c == 0xffffffff) {
        uStack_8c = uStack_a4;
      }
      else {
        uVar1 = uVar4 >> 1;
        if ((uStack_8c / 3 < uVar1) && (uVar4 <= -uVar1 - 2)) {
          uStack_8c = uVar4 + uVar1;
        }
      }
      uStack_ec = 6;
      puStack_88 = (undefined4 *)FUN_00248640(uStack_8c + 1);
      if (iStack_90 != 0) {
        puVar3 = puStack_98 + 1;
        if (0xf < (uint)puStack_98[6]) {
          puVar3 = (undefined4 *)puStack_98[1];
        }
        FUN_0039ac74(puStack_88,puVar3,iStack_90);
      }
      FUN_005e75e4(puStack_98,1,0);
      puStack_98[6] = uStack_8c;
      puStack_98[1] = puStack_88;
      puVar3 = puStack_88;
      if (uStack_8c < 0x10) {
        puVar3 = puStack_98 + 1;
      }
      puStack_98[5] = iStack_90;
      *(undefined1 *)((int)puVar3 + iStack_90) = 0;
    }
    else if (uStack_9c == 0) {
      puVar3 = puStack_a0 + 1;
      if (0xf < (uint)puStack_a0[6]) {
        puVar3 = (undefined4 *)puStack_a0[1];
      }
      puStack_a0[5] = 0;
      *(undefined1 *)puVar3 = 0;
    }
    if (uStack_9c != 0) {
      puVar3 = puStack_ac + 1;
      if (0xf < (uint)puStack_ac[6]) {
        puVar3 = (undefined4 *)puStack_ac[1];
      }
      FUN_0039ac74(puVar3,puStack_a8,uStack_a4);
      puVar3 = puStack_ac + 1;
      if (0xf < (uint)puStack_ac[6]) {
        puVar3 = (undefined4 *)puStack_ac[1];
      }
      puStack_ac[5] = uStack_a4;
      *(undefined1 *)((int)puVar3 + uStack_a4) = 0;
    }
  }
  puStack_84 = puStack_bc + 8;
  if ((puStack_b8 == (undefined4 *)0x0) ||
     (puStack_7c = (undefined4 *)FUN_003969c4(1,puStack_b8), puStack_b8 = puStack_7c,
     puStack_7c == (undefined4 *)0x0)) {
    puStack_7c = (undefined4 *)0xd38c84;
  }
  puStack_80 = puStack_84;
  uStack_78 = FUN_0039b0f0(puStack_7c);
  puVar3 = puStack_80 + 1;
  if (0xf < (uint)puStack_80[6]) {
    puVar3 = (undefined4 *)puStack_80[1];
  }
  if (puVar3 <= puStack_7c) {
    puVar3 = puStack_80 + 1;
    if (0xf < (uint)puStack_80[6]) {
      puVar3 = (undefined4 *)puStack_80[1];
    }
    if (puStack_7c < (undefined4 *)((int)puVar3 + puStack_80[5])) {
      puVar3 = puStack_80 + 1;
      if (0xf < (uint)puStack_80[6]) {
        puVar3 = (undefined4 *)puStack_80[1];
      }
      uStack_ec = 7;
      FUN_005ea15c(puStack_80,puStack_80,(int)puStack_7c - (int)puVar3,uStack_78);
      goto LAB_0024e714;
    }
  }
  puStack_74 = puStack_80;
  uStack_70 = uStack_78;
  if (0xfffffffe < uStack_78) {
    uStack_ec = 7;
    FUN_002513e0(puStack_80);
  }
  uVar4 = puStack_80[6];
  if (uVar4 < uStack_78) {
    uStack_60 = uStack_78 | 0xf;
    puStack_6c = puStack_80;
    iStack_64 = puStack_80[5];
    uStack_68 = uStack_78;
    if (uStack_60 < 0xffffffff) {
      uVar1 = uVar4 >> 1;
      if ((uStack_60 / 3 < uVar1) && (uVar4 <= -uVar1 - 2)) {
        uStack_60 = uVar4 + uVar1;
      }
    }
    else {
      uStack_60 = uStack_78;
    }
    uStack_ec = 3;
    puStack_5c = (undefined4 *)FUN_00248640(uStack_60 + 1);
    if (iStack_64 != 0) {
      puVar3 = puStack_6c + 1;
      if (0xf < (uint)puStack_6c[6]) {
        puVar3 = (undefined4 *)puStack_6c[1];
      }
      FUN_0039ac74(puStack_5c,puVar3,iStack_64);
    }
    FUN_005e75e4(puStack_6c,1,0);
    puStack_6c[6] = uStack_60;
    puStack_6c[1] = puStack_5c;
    puVar3 = puStack_5c;
    if (uStack_60 < 0x10) {
      puVar3 = puStack_6c + 1;
    }
    puStack_6c[5] = iStack_64;
    *(undefined1 *)((int)puVar3 + iStack_64) = 0;
  }
  else if (uStack_70 == 0) {
    puVar3 = puStack_74 + 1;
    if (0xf < (uint)puStack_74[6]) {
      puVar3 = (undefined4 *)puStack_74[1];
    }
    puStack_74[5] = 0;
    *(undefined1 *)puVar3 = 0;
  }
  if (uStack_70 != 0) {
    puVar3 = puStack_80 + 1;
    if (0xf < (uint)puStack_80[6]) {
      puVar3 = (undefined4 *)puStack_80[1];
    }
    FUN_0039ac74(puVar3,puStack_7c,uStack_78);
    puVar3 = puStack_80 + 1;
    if (0xf < (uint)puStack_80[6]) {
      puVar3 = (undefined4 *)puStack_80[1];
    }
    puStack_80[5] = uStack_78;
    *(undefined1 *)((int)puVar3 + uStack_78) = 0;
  }
LAB_0024e714:
  FUN_003d12b8(auStack_f0);
  return;
}

