/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0051cc70  name=FUN_0051cc70  size=684  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0051cc70(int param_1,undefined4 param_2,int param_3)

{
  undefined4 uVar1;
  undefined4 uVar2;
  int iVar3;
  undefined4 *puVar4;
  undefined4 uVar5;
  int iVar6;
  
  uVar1 = FUN_004ad1f0();
  uVar2 = FUN_004ad1f0();
  iVar3 = FUN_004ad1f0();
  FUN_004c2db8(uVar2,1);
  if (param_3 == 0) {
    param_3 = FUN_004ad1f0();
    FUN_004ad634(param_3,200,0,0);
    uVar5 = FUN_0051ae44();
    *(undefined4 *)(param_3 + 0xc) = uVar5;
  }
  iVar6 = 0;
  while( true ) {
    iVar6 = iVar6 + 1;
    FUN_004c2fd8(uVar1,param_3,iVar6);
    FUN_004c2d38(uVar2,uVar2,uVar2);
    if (param_1 != 0) {
      if (iRam00e37a04 == 0) {
        FUN_004ad854(param_1,param_3);
        FUN_004a1ce8(param_1,0xd8cedc);
        FUN_004ad854(param_1,uVar2);
        FUN_004a1ce8(param_1,0xd5eed0);
      }
      FUN_004ad854(param_1,uVar1);
      FUN_004a1ce8(param_1,0xd37ae4);
    }
    FUN_004c2f98(iVar3,param_3,uVar2,param_2);
    FUN_004c2d58(iVar3,iVar3,uVar1);
    if (*(int *)(iVar3 + 4) != 0) break;
    if (99 < iVar6) {
      FUN_004ad194(param_3);
      FUN_004ad194(uVar1);
      FUN_004ad194(uVar2);
      FUN_004ad194(iVar3);
      return 1;
    }
  }
  puVar4 = (undefined4 *)FUN_00398e8c();
  FUN_0039995c(*puVar4,0xd8d01c);
  puVar4 = (undefined4 *)FUN_00398e8c();
  FUN_0039995c(*puVar4,0xd8cf68);
  puVar4 = (undefined4 *)FUN_00398e8c();
  FUN_004ad9b8(*puVar4,param_3);
  puVar4 = (undefined4 *)FUN_00398e8c();
  FUN_0039995c(*puVar4,0xd8cf6c);
  puVar4 = (undefined4 *)FUN_00398e8c();
  FUN_004ad9b8(*puVar4,uVar1);
  puVar4 = (undefined4 *)FUN_00398e8c();
  FUN_0039995c(*puVar4,0xd8d038);
  puVar4 = (undefined4 *)FUN_00398e8c();
  FUN_004ad9b8(*puVar4,uVar2);
  puVar4 = (undefined4 *)FUN_00398e8c();
  FUN_0039995c(*puVar4,0xd8d03c);
  puVar4 = (undefined4 *)FUN_00398e8c();
  FUN_004ad9b8(*puVar4,iVar3);
  puVar4 = (undefined4 *)FUN_00398e8c();
  FUN_0039995c(*puVar4,0xd37ae4);
  return 0;
}

