/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00591ee4  name=FUN_00591ee4  size=672  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00591ee4(int param_1,byte *param_2,uint *param_3)

{
  byte bVar1;
  int iVar2;
  uint uVar3;
  uint uVar4;
  uint uVar5;
  uint uVar6;
  uint uVar7;
  uint uVar8;
  uint uVar9;
  
  uVar5 = 0;
  bVar1 = param_2[4];
  for (param_2 = param_2 + *param_2; param_2[1] != 5; param_2 = param_2 + *param_2) {
  }
  uVar4 = 0;
  do {
    if (bVar1 <= uVar4) {
      return 1;
    }
    uVar3 = (uint)param_2[6];
    if (param_1 == 2) {
      uVar9 = ((uint)(*(ushort *)(param_2 + 4) >> 8) | (*(ushort *)(param_2 + 4) & 7) << 8) *
              ((((*(ushort *)(param_2 + 4) & 0xff) << 8) >> 0xb & 3) + 1);
      uVar3 = 1 << (uVar3 - 1 & 0x3f);
      if ((uVar3 & 7) == 0) {
        uVar8 = 1;
      }
      else {
        uVar8 = 8 / (uVar3 & 7);
      }
    }
    else {
      uVar9 = (uint)(*(ushort *)(param_2 + 4) >> 8) | (*(ushort *)(param_2 + 4) & 0xff) << 8;
      if ((param_2[2] & 0x80) == 0) {
        if ((param_2[3] & 3) == 3) {
          uVar8 = 4;
        }
        else {
          uVar8 = 1;
        }
      }
      else {
        uVar8 = 4;
      }
    }
    iVar2 = FUN_0056e6bc(2,param_2[2] & 0x80,param_2[3] & 3,uVar9);
    if ((param_2[3] & 3) == 1) {
      uVar3 = 0;
      for (uVar9 = 0; uVar9 < 0x400; uVar9 = uVar9 + 1) {
        param_3[uVar9] = iVar2 * uVar8 + param_3[uVar9];
        if (uVar3 < param_3[uVar9]) {
          uVar3 = param_3[uVar9];
        }
      }
      if (800000 < uVar3) {
        return 0;
      }
    }
    else if ((param_2[3] & 3) == 3) {
      uVar9 = *param_3;
      if (param_1 == 2) {
        if ((uVar3 & 7) == 0) {
          uVar3 = uVar3 >> 3;
        }
        else {
          uVar3 = 1;
        }
      }
      if (0x20 < uVar3) {
        uVar3 = 0x20;
      }
      for (uVar6 = 0; uVar7 = uVar5, uVar6 < uVar3; uVar6 = uVar6 + 1) {
        if (param_3[uVar6] < uVar9) {
          uVar9 = param_3[uVar6];
          uVar5 = uVar6;
        }
      }
      for (; uVar7 < 0x400; uVar7 = uVar7 + uVar3) {
        param_3[uVar7] = iVar2 * uVar8 + param_3[uVar7];
        if (800000 < param_3[uVar7]) {
          return 0;
        }
      }
    }
    param_2 = param_2 + *param_2;
    uVar4 = uVar4 + 1;
  } while( true );
}

