/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004c3098  name=FUN_004c3098  size=32  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_004c3098(void)

{
  FUN_003bb4a4();
  return;
}

