/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005c5654  name=FUN_005c5654  size=372  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_005c5654(int param_1,undefined4 param_2)

{
  FUN_004bdee0(param_2,0xd93668,*(undefined4 *)(param_1 + 0x24));
  FUN_004bdee0(param_2,0xd93688,*(undefined4 *)(param_1 + 0xc));
  FUN_004bdee0(param_2,0xd936a4,*(undefined4 *)(param_1 + 0x10));
  FUN_004bdee0(param_2,0xd936c0,*(undefined4 *)(param_1 + 0x28));
  FUN_004bdee0(param_2,0xd936e0,*(undefined4 *)(param_1 + 0x2c));
  FUN_004bdee0(param_2,0xd93700,*(undefined4 *)(param_1 + 0x30));
  FUN_004bdee0(param_2,0xd93720,*(undefined4 *)(param_1 + 0x34));
  FUN_004bdee0(param_2,0xd93740,*(undefined4 *)(param_1 + 0x38));
  FUN_004bdee0(param_2,0xd93760,*(undefined4 *)(param_1 + 0x3c));
  FUN_004bdee0(param_2,0xd93780,*(undefined4 *)(param_1 + 0x40));
  FUN_004bdee0(param_2,0xd937a0,*(undefined4 *)(param_1 + 0x44));
  FUN_004bdee0(param_2,0xd937c0,*(undefined4 *)(param_1 + 0x48));
  FUN_004bdee0(param_2,0xd937e0,*(undefined4 *)(param_1 + 0x4c));
  FUN_004bdee0(param_2,0xd93800,*(undefined4 *)(param_1 + 0x50));
  FUN_004bdee0(param_2,0xd93820,*(undefined4 *)(param_1 + 0x54));
  FUN_004bdee0(param_2,0xd93840,*(undefined4 *)(param_1 + 0x58));
  return;
}

