/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004a6304  name=FUN_004a6304  size=36  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_004a6304(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  FUN_004a6020(1,0,param_1,param_2,param_3,param_4);
  return;
}

