/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0033dca0  name=FUN_0033dca0  size=156  xrefs=8
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0033dca0(int param_1,int param_2,int param_3)

{
  int iVar1;
  
  iVar1 = FUN_001d9204(*(undefined4 *)(param_1 + 0x28),0xffffffff);
  if (iVar1 == 0) {
    *(undefined4 *)(param_2 + 8) = 1;
    *(undefined4 *)(param_2 + 0x10) = 0;
    *(undefined4 *)(param_2 + 0xc) = *(undefined4 *)(param_2 + 0x10);
    FUN_004978d0(param_1 + 0xac,param_2);
    FUN_001d92bc(*(undefined4 *)(param_1 + 0x2c));
    FUN_001d92bc(*(undefined4 *)(param_1 + 0x28));
    if (param_3 != 0) {
      FUN_004568e4(param_1 + 0xdc,1);
    }
  }
  return;
}

