/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004a2f64  name=FUN_004a2f64  size=276  xrefs=24
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_004a2f64(int *param_1,int param_2)

{
  int iVar1;
  int iVar2;
  
  iVar2 = *param_1;
  if (iVar2 < param_2) {
    if (param_1[2] < param_2) {
      iVar2 = ((param_2 + 3) / 3) * 4;
      if (param_1[1] == 0) {
        iVar1 = FUN_004a849c(iVar2,0xd726e0,0x6e);
      }
      else {
        iVar1 = FUN_004a85d8(param_1[1],iVar2,0xd726e0,0x70);
      }
      if (iVar1 == 0) {
        FUN_004a6438(7,100,0x41,0xd726e0,0x73);
        return 0;
      }
      param_1[1] = iVar1;
      param_1[2] = iVar2;
      FUN_0039acec(iVar1 + *param_1,0,param_2 - *param_1);
    }
    else {
      FUN_0039acec(param_1[1] + iVar2,0,param_2 - iVar2);
    }
  }
  *param_1 = param_2;
  return param_2;
}

