/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00510704  name=FUN_00510704  size=68  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


/* WARNING: Control flow encountered bad instruction data */

undefined4 FUN_00510704(undefined1 *param_1,undefined4 param_2)

{
  if (param_1 != (undefined1 *)0x0) {
                    /* WARNING (jumptable): Sanity check requires truncation of jumptable */
                    /* WARNING: Could not find normalized switch variable to match jumptable */
    switch(*param_1) {
    case 0x30:
                    /* WARNING: Bad instruction - Truncating control flow here */
      halt_baddata();
    case 0x31:
                    /* WARNING: Bad instruction - Truncating control flow here */
      halt_baddata();
    }
  }
  return param_2;
}

