/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003d88d8  name=FUN_003d88d8  size=96  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_003d88d8(int param_1,int param_2)

{
  int iVar1;
  
  if (param_1 == 0 || param_2 == 0) {
    FUN_00442990(0x320003);
    iVar1 = -1;
  }
  else {
    iVar1 = FUN_003d86e8();
    iVar1 = -(uint)(iVar1 == -1);
  }
  return iVar1;
}

