/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002e26d0  name=FUN_002e26d0  size=332  xrefs=8
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_002e26d0(int param_1)

{
  int *piVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  undefined1 auStack_40 [4];
  int iStack_3c;
  int iStack_38;
  int iStack_30;
  
  piVar1 = (int *)(param_1 + 0x1f8);
  FUN_00318718(piVar1,0);
  iVar2 = *(int *)(param_1 + 0x16c);
  if (iVar2 == 0) {
    (**(code **)(*piVar1 + 0x10))();
    iVar2 = 0;
  }
  else {
    iVar3 = FUN_002eac78(param_1);
    iVar4 = 0;
    if ((iVar3 != 0) && (*(int *)(param_1 + 0x16c) != 0)) {
      iVar2 = iVar2 - (uint)(*(int *)(*(int *)(*(int *)(param_1 + 0x16c) * 4 +
                                               *(int *)(param_1 + 0x168) + -4) + 0x1c) == 0);
    }
    if (0 < iVar2) {
      do {
        iVar3 = iVar2 + -1;
        FUN_002ee698(param_1,iVar3,auStack_40);
        if (*(int *)(param_1 + 0x140) - *(int *)(param_1 + 0x13c) < iVar4 + iStack_3c + iStack_38)
        break;
        iVar4 = iVar4 + iStack_30;
        iVar2 = iVar3;
      } while (0 < iVar3);
    }
    iVar3 = *(int *)(param_1 + 0x16c) + -1;
    if (iVar3 < iVar2) {
      iVar2 = iVar3;
    }
    (**(code **)(*piVar1 + 0x10))();
  }
  return iVar2;
}

