/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x000a79d4  name=FUN_000a79d4  size=192  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_000a79d4(int param_1)

{
  int iVar1;
  undefined4 uVar2;
  int iVar3;
  int iVar4;
  
  iVar3 = *(int *)(param_1 + 0xec);
  do {
    iVar4 = iVar3;
    if (iVar3 == *(int *)(param_1 + 0xf0)) {
      return;
    }
    while( true ) {
      iVar1 = FUN_005fbc34(param_1 + 0xf8,iVar4);
      iVar3 = iVar4 + 0x1c;
      if (iVar1 == *(int *)(param_1 + 0xfc)) break;
      uVar2 = 0;
      if ((*(char *)(*(int *)(iVar1 + 0x28) + 2) != '\0') &&
         (*(char *)(*(int *)(iVar1 + 0x28) + 4) != '\0')) {
        uVar2 = 1;
      }
      FUN_000a6dd8(param_1,iVar4,uVar2);
      iVar4 = iVar3;
      if (iVar3 == *(int *)(param_1 + 0xf0)) {
        return;
      }
    }
  } while( true );
}

