/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00554fa8  name=FUN_00554fa8  size=104  xrefs=4
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00554fa8(undefined4 param_1,undefined4 param_2,int *param_3)

{
  int iVar1;
  undefined4 uVar2;
  
  if (param_3 == (int *)0x0) {
    uVar2 = 0x830102;
  }
  else {
    iVar1 = FUN_005abb7c(0);
    *param_3 = iVar1;
    if (iVar1 != 0) {
      return 0;
    }
    uVar2 = 0x830107;
  }
  uVar2 = FUN_00554e24(uVar2);
  return uVar2;
}

