/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002cc1ac  name=FUN_002cc1ac  size=1652  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_002cc1ac(int param_1,undefined1 *param_2)

{
  char cVar1;
  uint uVar2;
  int iVar3;
  undefined4 uVar4;
  uint uVar5;
  undefined1 uVar6;
  undefined4 uVar7;
  int iVar8;
  int iVar9;
  char acStack_30 [4];
  int aiStack_2c [5];
  
  iVar3 = FUN_005accf4(*(undefined4 *)(param_1 + 0xe8),0xffffffff);
  if (iVar3 == -1) {
    FUN_00443f20(0xd5ee98,1,2,3,4,5,6);
  }
  *param_2 = 0;
  cVar1 = *(char *)(param_1 + 0xc4);
  if (cVar1 != '\x03') {
    if (cVar1 == '\x01') {
      uVar6 = FUN_002ccab4(param_1,*(undefined1 *)(param_1 + 0xd0));
      *param_2 = uVar6;
      *(undefined1 *)(param_1 + 0xc4) = 2;
    }
    else if ((cVar1 == '\x02') && (*(int *)(param_1 + 200) != 0)) {
      aiStack_2c[0] = 0x600 - *(int *)(param_1 + 0xcc);
      iVar3 = FUN_002cc820(param_1,*(int *)(param_1 + 200),aiStack_2c,param_1 + 0xcc,param_2);
      if (iVar3 != 0) {
        if (*(int *)(param_1 + 200) != 0) {
          FUN_00245be8();
        }
        *(undefined1 *)(param_1 + 0xc4) = 3;
        *(undefined4 *)(param_1 + 200) = 0;
      }
    }
LAB_002cc72c:
    iVar3 = FUN_005ad104(*(undefined4 *)(param_1 + 0xe8));
    if (iVar3 == -1) {
      FUN_00443f20(0xd5ee98,1,2,3,4,5,6);
    }
    return 0;
  }
  if (((*(char *)(param_1 + 0xa4) != '\0') && (*(char *)(param_1 + 0xb4) == '\0')) &&
     ((uint)(*(int *)(param_1 + 0xbc) + *(int *)(param_1 + 0xa8) * 10) < *(uint *)(param_1 + 0xb0)))
  goto LAB_002cc72c;
  iVar3 = *(int *)(param_1 + 4);
  uVar7 = 0;
  if (iVar3 != 0) goto LAB_002cc24c;
  acStack_30[0] = '\0';
  iVar8 = FUN_002cbfa0(param_1,acStack_30);
  *(int *)(param_1 + 4) = iVar8;
  iVar3 = 0;
  if (iVar8 == 0) goto LAB_002cc24c;
  *(undefined4 *)(param_1 + 0x88) = 0;
  *(undefined4 *)(param_1 + 0x84) = 0;
  iVar9 = *(int *)(iVar8 + 0x28) - *(int *)(iVar8 + 0x34);
  if (*(int *)(iVar8 + 0x30) < 0x40) {
    *(undefined1 *)(param_1 + 0x80) = *(undefined1 *)(iVar8 + 0x33);
    *(undefined4 *)(param_1 + 0x88) = 1;
  }
  else if (*(int *)(iVar8 + 0x30) < 0x140) {
    *(undefined1 *)(param_1 + 0x80) = 0;
    *(char *)(param_1 + 0x81) = *(char *)(iVar8 + 0x33) + -0x40;
    *(undefined4 *)(param_1 + 0x88) = 2;
  }
  else {
    *(undefined1 *)(param_1 + 0x80) = 1;
    *(char *)(param_1 + 0x81) = (char)*(undefined4 *)(iVar8 + 0x30) + -0x40;
    iVar3 = *(int *)(iVar8 + 0x30);
    *(undefined4 *)(param_1 + 0x88) = 3;
    uVar5 = iVar3 - 0x40;
    *(char *)(param_1 + 0x82) = (char)(uVar5 >> 8) + ((int)uVar5 < 0 && (uVar5 & 0xff) != 0);
  }
  *(undefined4 *)(param_1 + 0x7c) = 2;
  if (acStack_30[0] == '\0') {
    iVar3 = *(int *)(param_1 + 4);
LAB_002cc6b8:
    *(byte *)(param_1 + 0x80) = *(byte *)(param_1 + 0x80) | 0xc0;
  }
  else {
    iVar3 = *(int *)(param_1 + 4);
    *(undefined4 *)(iVar3 + 0x2c) = 0;
    iVar8 = FUN_002ca5fc(iVar3);
    if ((iVar8 == *(int *)(iVar3 + 0x24)) && (*(int *)(iVar3 + 0x34) != 0 && -1 < iVar9)) {
      uVar5 = FUN_002ca5c0(iVar3);
      iVar8 = *(int *)(iVar3 + 0x20);
      if ((uVar5 == ((uint)*(byte *)(iVar8 + 9) << 0x10 | (uint)*(byte *)(iVar8 + 10) << 8 |
                    (uint)*(byte *)(iVar8 + 0xb))) &&
         (uVar5 = FUN_002ca5ec(iVar3), uVar5 == *(byte *)(iVar8 + 8))) {
        iVar8 = FUN_002ca554(iVar3);
        if (iVar8 == iVar9) goto LAB_002cc6b8;
        *(byte *)(param_1 + 0x80) = *(byte *)(param_1 + 0x80) | 0x80;
      }
      else {
        *(byte *)(param_1 + 0x80) = *(byte *)(param_1 + 0x80) | 0x40;
        FUN_002ca6ec(iVar3,*(undefined1 *)(*(int *)(iVar3 + 0x20) + 8));
        iVar3 = *(int *)(*(int *)(param_1 + 4) + 0x20);
        FUN_002ca6c8(*(int *)(param_1 + 4),
                     (uint)*(byte *)(iVar3 + 9) << 0x10 | (uint)*(byte *)(iVar3 + 10) << 8 |
                     (uint)*(byte *)(iVar3 + 0xb));
        iVar3 = *(int *)(param_1 + 4);
      }
    }
    else {
      FUN_002ca6ec(iVar3,*(undefined1 *)(*(int *)(iVar3 + 0x20) + 8));
      FUN_002ca6fc(*(int *)(param_1 + 4),*(undefined4 *)(*(int *)(param_1 + 4) + 0x24));
      iVar3 = *(int *)(*(int *)(param_1 + 4) + 0x20);
      FUN_002ca6c8(*(int *)(param_1 + 4),
                   (uint)*(byte *)(iVar3 + 9) << 0x10 | (uint)*(byte *)(iVar3 + 10) << 8 |
                   (uint)*(byte *)(iVar3 + 0xb));
      iVar3 = *(int *)(param_1 + 4);
      iVar9 = *(int *)(iVar3 + 0x28);
    }
    FUN_002ca634(iVar3,iVar9);
    iVar3 = *(int *)(param_1 + 4);
  }
LAB_002cc24c:
  if ((iVar3 != 0) && (*(int *)(param_1 + 0x7c) == 2)) {
    iVar3 = FUN_002cc820(param_1,param_1 + 0x80,param_1 + 0x84,param_1 + 0x88,param_2);
    if (iVar3 == 0) {
      iVar3 = *(int *)(param_1 + 4);
    }
    else {
      iVar3 = *(int *)(param_1 + 4);
      *(undefined4 *)(param_1 + 0x7c) = 3;
      *(undefined4 *)(param_1 + 0x84) = 0;
      uVar4 = FUN_002ca510(iVar3,*(byte *)(param_1 + 0x80) & 0xc0);
      *(undefined4 *)(param_1 + 0x88) = uVar4;
    }
  }
  if ((iVar3 != 0) && (*(int *)(param_1 + 0x7c) == 3)) {
    iVar3 = FUN_002cc820(param_1,iVar3 + 0x38,param_1 + 0x84,param_1 + 0x88,param_2);
    if (iVar3 == 0) {
      iVar3 = *(int *)(param_1 + 4);
    }
    else {
      iVar3 = *(int *)(param_1 + 4);
      *(undefined4 *)(param_1 + 0x7c) = 4;
      *(undefined4 *)(param_1 + 0x84) = 0;
      iVar8 = FUN_002caa7c(iVar3);
      *(uint *)(param_1 + 0x88) = (uint)(iVar8 != 0) * 4;
    }
  }
  if ((iVar3 != 0) && (*(int *)(param_1 + 0x7c) == 4)) {
    iVar3 = FUN_002cc820(param_1,iVar3 + 0x43,param_1 + 0x84,param_1 + 0x88,param_2);
    if (iVar3 == 0) {
      iVar3 = *(int *)(param_1 + 4);
    }
    else {
      iVar3 = *(int *)(param_1 + 4);
      *(undefined4 *)(param_1 + 0x7c) = 5;
      iVar8 = FUN_002ca5c0(iVar3);
      iVar8 = iVar8 - *(int *)(iVar3 + 0x2c);
      if (*(int *)(param_1 + 0x90) < iVar8) {
        iVar8 = *(int *)(param_1 + 0x90);
      }
      *(int *)(param_1 + 0x88) = iVar8;
      *(undefined4 *)(param_1 + 0x84) = 0;
    }
  }
  if (((iVar3 != 0) && (*(int *)(param_1 + 0x7c) == 5)) &&
     (iVar3 = FUN_002cc820(param_1,*(int *)(*(int *)(iVar3 + 0x20) + 0x14) + *(int *)(iVar3 + 0x2c),
                           param_1 + 0x84,param_1 + 0x88,param_2), iVar3 != 0)) {
    iVar9 = *(int *)(param_1 + 4);
    iVar8 = *(int *)(iVar9 + 0x2c) + *(int *)(param_1 + 0x84);
    *(int *)(iVar9 + 0x2c) = iVar8;
    iVar3 = FUN_002ca5c0(iVar9);
    if (iVar8 == iVar3) {
      *(undefined4 *)(iVar9 + 0x34) = *(undefined4 *)(iVar9 + 0x28);
      if (*(int *)(iVar9 + 0x30) == 2) {
        FUN_002cd658(param_1,*(undefined4 *)(iVar9 + 0x20));
        iVar9 = *(int *)(param_1 + 4);
      }
      else {
        uVar7 = *(undefined4 *)(iVar9 + 0x20);
      }
      *(undefined4 *)(iVar9 + 0x20) = 0;
    }
    else {
      iVar3 = FUN_002cd858(*(undefined4 *)(iVar9 + 0x20));
      if (iVar3 == 0) {
        iVar3 = *(int *)(*(int *)(param_1 + 4) + 0x20);
        uVar2 = (uint)*(byte *)(iVar3 + 9) << 0x10 | (uint)*(byte *)(iVar3 + 10) << 8 |
                (uint)*(byte *)(iVar3 + 0xb);
        uVar5 = 0x400;
        if (uVar2 < 0x400) {
          uVar5 = uVar2;
        }
        if (*(int *)(param_1 + 0x90) < (int)uVar5) {
          FUN_002cc8d4(param_1);
        }
      }
    }
    *(undefined4 *)(param_1 + 4) = 0;
  }
  iVar3 = FUN_005ad104(*(undefined4 *)(param_1 + 0xe8));
  if (iVar3 != -1) {
    return uVar7;
  }
  FUN_00443f20(0xd5ee98,1,2,3,4,5,6);
  return uVar7;
}

