/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005d6fac  name=FUN_005d6fac  size=88  xrefs=4
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_005d6fac(int *param_1)

{
  undefined4 uVar1;
  
  if ((param_1 != (int *)0x0) && (*param_1 != 0)) {
    uVar1 = FUN_004cb574(*param_1 + 0x14);
    return uVar1;
  }
  return 0;
}

