/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003b61ec  name=FUN_003b61ec  size=100  xrefs=20
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_003b61ec(int *param_1,int *param_2)

{
  int iVar1;
  uint uVar2;
  uint uVar3;
  
  iVar1 = param_1[1];
  if (iVar1 - param_2[1] != 0) {
    return iVar1 - param_2[1];
  }
  do {
    iVar1 = iVar1 + -1;
    if (iVar1 < 0) {
      return 0;
    }
    uVar2 = *(uint *)(*param_1 + iVar1 * 4);
    uVar3 = *(uint *)(*param_2 + iVar1 * 4);
  } while (uVar2 == uVar3);
  if (uVar3 < uVar2) {
    return 1;
  }
  return -1;
}

