/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002a92bc  name=FUN_002a92bc  size=124  xrefs=4
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002a92bc(int *param_1,int param_2,int param_3)

{
  if (*(int *)(*param_1 + 0xfc) == 0) {
    param_1[10] = 0;
    if (param_2 < param_1[0x19]) {
      param_2 = param_1[0x19];
    }
    param_1[9] = param_2;
    param_1[0x17] = -0x80000000;
    param_1[8] = (uint)(3 < param_2);
    param_1[2] = param_3;
    param_1[0x18] = -0x80000000;
  }
  else {
    param_1[2] = param_3;
    if (param_2 < param_1[0x19]) {
      param_2 = param_1[0x19];
    }
    param_1[5] = param_2;
    param_1[9] = param_2;
  }
  return;
}

