/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005c4654  name=FUN_005c4654  size=124  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_005c4654(int param_1)

{
  undefined4 uVar1;
  int iVar2;
  
  uVar1 = 0;
  if (param_1 != 0) {
    if (((*(int *)(param_1 + 0x10) != 0) && (*(int *)(param_1 + 0xc) != 0)) &&
       (iVar2 = *(int *)(param_1 + 0x20), iVar2 != 0)) {
      if ((*(uint *)(param_1 + 0x14) & 0x200) != 0) {
        *(undefined4 *)(iVar2 + 4) = 0;
      }
      FUN_004a2f0c(iVar2);
      *(undefined4 *)(param_1 + 0x20) = 0;
    }
    uVar1 = 1;
  }
  return uVar1;
}

