/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003adf58  name=FUN_003adf58  size=300  xrefs=14
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_003adf58(int param_1,int param_2,int param_3)

{
  int iVar1;
  int iVar2;
  int iVar3;
  undefined4 uVar4;
  
  if (*(int *)(param_2 + 0xc) == 0) {
    iVar3 = param_2;
    param_2 = param_3;
    if (*(int *)(param_3 + 0xc) != 0) {
      uVar4 = 0;
      goto LAB_003adfac;
    }
  }
  else {
    iVar3 = param_3;
    if (*(int *)(param_3 + 0xc) == 0) {
      uVar4 = 1;
LAB_003adfac:
      iVar3 = FUN_003adb88();
      if (iVar3 == 0) {
        return 0;
      }
      goto LAB_003ae068;
    }
  }
  iVar2 = *(int *)(param_2 + 4);
  if (*(int *)(param_2 + 4) < *(int *)(iVar3 + 4)) {
    iVar2 = *(int *)(iVar3 + 4);
  }
  iVar1 = param_1;
  if (*(int *)(param_1 + 8) < iVar2) {
    iVar1 = FUN_003b5c28(param_1,iVar2);
  }
  if (iVar1 == 0) {
    return 0;
  }
  iVar2 = FUN_003b61ec(iVar3,param_2);
  if (iVar2 < 0) {
    iVar3 = FUN_003adcb8(param_1,param_2,iVar3);
    if (iVar3 == 0) {
      return 0;
    }
    uVar4 = 1;
  }
  else {
    iVar3 = FUN_003adcb8(param_1,iVar3,param_2);
    if (iVar3 == 0) {
      return 0;
    }
    uVar4 = 0;
  }
LAB_003ae068:
  *(undefined4 *)(param_1 + 0xc) = uVar4;
  return 1;
}

