/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002cbfa0  name=FUN_002cbfa0  size=524  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_002cbfa0(int *param_1,undefined1 *param_2)

{
  bool bVar1;
  int iVar2;
  int *piVar3;
  undefined4 uVar4;
  undefined4 uVar5;
  int iVar6;
  int *piVar7;
  int iVar8;
  int *piVar9;
  
  iVar2 = *param_1;
  piVar9 = (int *)0x0;
  *param_2 = 0;
  if (iVar2 == 0) {
    return 0;
  }
  FUN_002cbe70();
  piVar3 = (int *)*param_1;
  for (piVar7 = piVar3; piVar7 != (int *)0x0; piVar7 = (int *)*piVar7) {
    *(undefined1 *)(piVar7 + 6) = 0;
  }
  bVar1 = true;
  do {
    while (piVar3 == (int *)0x0) {
      if (bVar1) {
        return (int)piVar9;
      }
      iVar2 = *(int *)((int)piVar9 + 0x20);
      if (iVar2 == 0) {
        iVar6 = FUN_002caad0(piVar9);
        *(int *)((int)piVar9 + 0x20) = iVar6;
        if (iVar6 != 0) {
          iVar2 = *(int *)((int)piVar9 + 0x28);
          iVar8 = param_1[0x28];
          *param_2 = 1;
          *(int *)((int)piVar9 + 0x28) = iVar2 - iVar8;
          iVar2 = iVar6;
        }
      }
      bVar1 = iVar2 == 0;
      if (bVar1) {
        *(undefined1 *)((int)piVar9 + 0x18) = 1;
        piVar9 = (int *)0x0;
      }
      else {
        piVar3 = (int *)*param_1;
        *(int *)((int)piVar9 + 0x14) = *(int *)((int)piVar9 + 0x14) + 1;
        if (piVar3 == (int *)0x0) {
LAB_002cc168:
          iVar2 = param_1[0x1d];
        }
        else {
          iVar2 = param_1[0x1d];
          do {
            if (piVar3[0xc] == (uint)*(byte *)((int)param_1 + iVar2 + 0x10)) {
              piVar3[5] = piVar3[5] + -1;
              goto LAB_002cc168;
            }
            piVar3 = (int *)*piVar3;
          } while (piVar3 != (int *)0x0);
        }
        *(undefined1 *)((int)param_1 + iVar2 + 0x10) = *(undefined1 *)((int)piVar9 + 0x33);
        param_1[0x1d] = (iVar2 + 1) % 100;
        bVar1 = false;
      }
      if (!bVar1) {
        return (int)piVar9;
      }
      piVar3 = (int *)*param_1;
    }
    if (*(char *)(piVar3 + 6) == '\0') {
      if (!bVar1) {
        iVar2 = param_1[0x1e];
        uVar4 = FUN_002cabb4(piVar3,iVar2);
        uVar5 = FUN_002cabb4(piVar9,iVar2);
        iVar2 = FUN_00377fa8(uVar4,uVar5);
        if (-1 < iVar2) goto LAB_002cc0ac;
      }
      bVar1 = piVar3 == (int *)0x0;
      piVar9 = piVar3;
    }
LAB_002cc0ac:
    piVar3 = (int *)*piVar3;
  } while( true );
}

