/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004a18ac  name=FUN_004a18ac  size=144  xrefs=170
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_004a18ac(undefined4 param_1)

{
  int iVar1;
  int iVar2;
  
  iVar1 = FUN_004a849c(0x40,0xd726a8,0x46);
  if (iVar1 == 0) {
    FUN_004a6438(0x20,0x6c,0x41,0xd726a8,0x49);
    iVar1 = 0;
  }
  else {
    iVar2 = FUN_004a17e4(iVar1,param_1);
    if (iVar2 == 0) {
      FUN_004a8858(iVar1);
      iVar1 = 0;
    }
  }
  return iVar1;
}

