/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002b4ad4  name=FUN_002b4ad4  size=144  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002b4ad4(int param_1,undefined4 param_2)

{
  int iVar1;
  
  if ((((*(char *)(param_1 + 5) == '\0') && (*(int *)(param_1 + 0x70) != 0)) &&
      (FUN_002a6830(*(int *)(param_1 + 0x70),param_1,param_2), *(int *)(param_1 + 0x84) != 0)) &&
     ((iVar1 = FUN_002b5590(param_1), iVar1 == 0 && (iVar1 = FUN_002b52ac(param_1), iVar1 != 0)))) {
    FUN_002b55f0(param_1,0);
  }
  return;
}

