/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005e8e00  name=FUN_005e8e00  size=128  xrefs=742
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_005e8e00(int param_1)

{
  if (*(uint *)(param_1 + 0x18) < 0x10) {
    *(undefined4 *)(param_1 + 0x14) = 0;
    *(undefined1 *)(param_1 + 4) = 0;
    *(undefined4 *)(param_1 + 0x18) = 0xf;
    return;
  }
  FUN_00245c34(*(undefined4 *)(param_1 + 4));
  *(undefined4 *)(param_1 + 0x14) = 0;
  *(undefined1 *)(param_1 + 4) = 0;
  *(undefined4 *)(param_1 + 0x18) = 0xf;
  return;
}

