/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00033d94  name=FUN_00033d94  size=28  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00033d94(void)

{
  uRam00e29414 = 0x43a44;
  return;
}

