/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003c83e8  name=FUN_003c83e8  size=144  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_003c83e8(int param_1,int param_2,int param_3,int param_4)

{
  int iVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  
  iVar1 = iRam00e9bf90;
  param_2 = param_1 * (uint)uRam00e9c078 + param_2;
  iVar2 = *(int *)(iRam00e9bf90 + param_2 * 4);
  iVar4 = 0;
  iVar5 = 0;
  if (iVar2 != 0) {
    do {
      if ((*(int *)(iVar2 + 4) == param_3) && (*(int *)(iVar2 + 8) == param_4)) {
        iVar3 = iVar2;
        iVar4 = iVar2;
        if (iVar5 == 0) {
          *(undefined4 *)(iVar1 + param_2 * 4) = *(undefined4 *)(iVar2 + 0xc);
        }
        else {
          *(undefined4 *)(iVar5 + 0xc) = *(undefined4 *)(iVar2 + 0xc);
        }
      }
      else {
        iVar3 = *(int *)(iVar2 + 0xc);
        iVar5 = iVar2;
      }
    } while ((iVar3 != 0) && (iVar2 = iVar3, iVar4 == 0));
  }
  return iVar4;
}

