/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003812a8  name=FUN_003812a8  size=1140  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_003812a8(int param_1,int param_2,int param_3)

{
  bool bVar1;
  bool bVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  int unaff_r20;
  int iVar7;
  int iVar8;
  int iVar9;
  byte in_cr0;
  byte in_cr1;
  byte unaff_cr2;
  byte unaff_cr3;
  byte unaff_cr4;
  byte in_cr5;
  byte in_cr6;
  byte in_cr7;
  int iStack_58;
  int iStack_54;
  undefined4 uStack_50;
  undefined4 uStack_4c;
  undefined4 uStack_48;
  int iStack_44;
  int iStack_40;
  uint uStack_34;
  
  uStack_34 = (uint)(in_cr0 & 0xf) << 0x1c | (uint)(in_cr1 & 0xf) << 0x18 |
              (uint)(unaff_cr2 & 0xf) << 0x14 | (uint)(unaff_cr3 & 0xf) << 0x10 |
              (uint)(unaff_cr4 & 0xf) << 0xc | (uint)(in_cr5 & 0xf) << 8 | (uint)(in_cr6 & 0xf) << 4
              | (uint)(in_cr7 & 0xf);
  bVar1 = false;
  iVar7 = 0;
  FUN_00380e24(&iStack_58);
  if ((6 < param_2 - 1U) && (iVar6 = FUN_003802d4(0xd6d8f0,param_1), iVar6 != 0)) {
    if (*(int *)(param_3 + 0x40) != 0) {
      iStack_40 = 1;
    }
    param_1 = param_1 + 7;
    bVar1 = true;
    if (param_2 != 0) {
      param_2 = param_2 + -7;
    }
  }
  *(int *)(param_3 + 0x18) = *(int *)(param_3 + 0x18) + 1;
  uStack_50 = 1;
  iVar3 = FUN_00382e80(param_1,param_2,1,0,0,&iStack_58,param_3);
  iVar6 = iStack_54;
  *(int *)(param_3 + 0x18) = *(int *)(param_3 + 0x18) + -1;
  FUN_00380e24(&iStack_58);
  if (*(int *)(param_3 + 0x40) != 0) {
    iStack_40 = 1;
  }
  iVar4 = FUN_00380ea4(iVar3,param_1,param_2);
  if (iVar4 == 0) {
    iVar3 = FUN_00382e80(param_1,param_2,1,0,0,0,param_3);
    goto LAB_003813c0;
  }
  if ((iVar4 != 0x5f) || (iVar4 = FUN_00380ea4(iVar3 + 1,param_1,param_2), iVar4 != 0x5f)) {
    FUN_0038029c(param_3);
    goto LAB_003813c0;
  }
  iVar9 = iVar3 + 2;
  iVar5 = FUN_00380ea4(iVar9,param_1,param_2);
  iVar4 = 0;
  if (iVar5 == 0x4c) {
    iVar8 = (iVar9 - param_1) + -2;
    if (param_2 != 0) {
      param_2 = param_2 - ((iVar3 + 3) - param_1);
    }
    bVar2 = true;
    iVar7 = FUN_0038171c(iVar3 + 3,param_2,param_3);
    iVar3 = param_1 + iVar8;
  }
  else {
    iVar3 = iVar9;
    iVar8 = param_2;
    if (iVar5 != 0x46) {
      *(int *)(param_3 + 0x18) = *(int *)(param_3 + 0x18) + 1;
      if (iVar6 == 0) {
        uStack_50 = 1;
      }
      iVar3 = FUN_00381a8c(iVar9,0,&iStack_58,param_3);
      uStack_50 = 0;
      *(int *)(param_3 + 0x18) = *(int *)(param_3 + 0x18) + -1;
      iVar6 = FUN_00380ea4(iVar3,param_1,param_2);
      iVar4 = iVar9;
      if ((iVar6 == 0) ||
         ((iVar6 == 0x5f && (iVar6 = FUN_00380ea4(iVar3 + 1,param_1,param_2), iVar6 == 0x5f)))) {
        bVar2 = true;
        goto LAB_00381528;
      }
    }
    bVar2 = false;
    iVar6 = FUN_00380ea4(iVar3,param_1,param_2);
    iVar3 = iVar3 + (uint)(iVar6 == 0x53);
    unaff_r20 = FUN_00381c68(iVar3,0,1,param_3);
  }
LAB_00381528:
  iStack_58 = 0;
  if (iVar4 != 0) {
    if (iStack_54 != 0) {
      uStack_4c = 1;
    }
    FUN_00381a8c(iVar4,0,&iStack_58,param_3);
    uStack_4c = 0;
    FUN_0038023c(0xd44fbc,param_3);
  }
  FUN_00382e80(param_1,iVar8,1,0,iVar4,&iStack_58,param_3);
  if (!bVar2) {
    FUN_00381008(iVar3,0,param_3);
    iVar3 = unaff_r20;
  }
  if ((iStack_40 == 0) && (iStack_58 != 0)) {
    iStack_58 = iStack_40;
    iStack_44 = 1;
    *(int *)(param_3 + 0x18) = *(int *)(param_3 + 0x18) + 1;
    uStack_48 = 1;
    if (iVar4 != 0) {
      if (iStack_54 != 0) {
        uStack_4c = 1;
      }
      FUN_00381a8c(iVar4,0,&iStack_58,param_3);
    }
    uStack_4c = 0;
    FUN_00382e80(param_1,iVar8,1,0,iVar4,&iStack_58,param_3);
    *(int *)(param_3 + 0x18) = *(int *)(param_3 + 0x18) + -1;
    if (iStack_44 == 0) {
      FUN_003801cc(0x5d,param_3);
    }
  }
  param_2 = iVar8;
  if (iVar7 != 0) {
    iVar3 = iVar7;
  }
LAB_003813c0:
  if (bVar1) {
    while (iVar7 = FUN_00380ea4(iVar3,param_1,param_2), iVar7 != 0) {
      iVar3 = iVar3 + 1;
    }
  }
  return iVar3;
}

