/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00443f20  name=FUN_00443f20  size=204  xrefs=578
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4
FUN_00443f20(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4,
            undefined4 param_5,undefined4 param_6,undefined4 param_7)

{
  int iVar1;
  undefined4 uVar2;
  undefined4 uStack_44;
  undefined4 uStack_40;
  undefined4 uStack_3c;
  undefined4 uStack_38;
  undefined4 uStack_34;
  undefined4 uStack_30;
  undefined4 uStack_2c;
  undefined4 uStack_28;
  
  if (iRam00e2942c < 1) {
    uStack_44 = FUN_005b2184();
    uVar2 = 0xffffffff;
  }
  else {
    uStack_44 = 0xffffffff;
    uVar2 = 0;
  }
  uStack_40 = param_1;
  uStack_3c = param_2;
  uStack_38 = param_3;
  uStack_34 = param_4;
  uStack_30 = param_5;
  uStack_2c = param_6;
  uStack_28 = param_7;
  iVar1 = FUN_005aa0b4(uRam00e2944c,&uStack_44,0x20,uVar2,0);
  if (iVar1 == 0) {
    uVar2 = 0x20;
  }
  else {
    uVar2 = 0xffffffff;
    iRam00e29454 = iRam00e29454 + 1;
  }
  return uVar2;
}

