/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0001131c  name=FUN_0001131c  size=56  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0001131c(uint param_1)

{
  if (uRam00e10390 != param_1) {
    return 0;
  }
  return 0xe10390;
}

