/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00175a84  name=FUN_00175a84  size=128  xrefs=4
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00175a84(int param_1)

{
  undefined4 uVar1;
  int iVar2;
  
  *(undefined4 *)(param_1 + 0x6c) = 0;
  uVar1 = FUN_001b2964();
  iVar2 = FUN_0044e510(*(undefined4 *)(param_1 + 0x70),0x4c54000c,0);
  if (iVar2 != -1) {
    return uVar1;
  }
  return 0xffffffff;
}

