/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0050e4c8  name=FUN_0050e4c8  size=644  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0050e4c8(undefined4 param_1,int param_2,int param_3)

{
  int iVar1;
  undefined1 *puVar2;
  undefined4 uVar3;
  undefined1 *puVar4;
  undefined4 *puVar5;
  undefined1 auStack_418 [1028];
  
  iVar1 = FUN_0039b188(param_2,0xd890b8,5);
  if (iVar1 == 0) {
    puVar2 = (undefined1 *)(param_2 + 5);
  }
  else {
    iVar1 = FUN_0039b188(param_2,0xd890c0,4);
    if (iVar1 == 0) {
      puVar2 = (undefined1 *)FUN_0044259c(param_2 + 4);
      if (puVar2 == (undefined1 *)0x0) {
        FUN_004bdee0(param_1,0xd890c8,param_2 + 4);
        return 0;
      }
    }
    else {
      if ((param_3 == 0) || (iRam00e379a4 == 0)) {
        iVar1 = FUN_0039b188(param_2,0xd5eeb0,5);
        if (iVar1 == 0) {
          iRam00e379a4 = FUN_004a277c(param_2 + 5,0xd60c10);
          if (iRam00e379a4 == 0) {
            FUN_004bdee0(param_1,0xd890ec,param_2 + 5);
            return 0;
          }
        }
        else {
          iVar1 = FUN_0039b188(param_2,0xd89100,3);
          if (iVar1 == 0) {
            iVar1 = FUN_00399bcc(param_2 + 3);
            if ((iVar1 < 0) || (iRam00e379a4 = FUN_005c40d0(iVar1,0), iRam00e379a4 == 0)) {
              FUN_004bdee0(param_1,0xd89104,param_2 + 3);
              return 0;
            }
            FUN_005c023c();
            uVar3 = FUN_004a18ac();
            iRam00e379a4 = FUN_004a2314(uVar3,iRam00e379a4);
          }
          else {
            iVar1 = FUN_0039ad64(param_2,0xd8018c);
            if (iVar1 != 0) {
              FUN_004bdee0(param_1,0xd89168,param_2);
              return 0;
            }
            puVar5 = (undefined4 *)FUN_00398df4();
            iRam00e379a4 = FUN_004a288c(*puVar5,0);
            if (iRam00e379a4 == 0) {
              FUN_004bdee0(param_1,0xd89128);
              return 0;
            }
          }
        }
      }
      puVar2 = auStack_418;
      iVar1 = FUN_004a1e1c(iRam00e379a4,puVar2,0x400);
      if (param_3 != 1) {
        FUN_004a24e4(iRam00e379a4);
        iRam00e379a4 = 0;
      }
      if (iVar1 < 1) {
        FUN_004bdee0(param_1,0xd89144);
        return 0;
      }
      puVar4 = (undefined1 *)FUN_0039ad28(puVar2,10);
      if (puVar4 != (undefined1 *)0x0) {
        *puVar4 = 0;
      }
    }
  }
  uVar3 = FUN_004a32a8(puVar2);
  return uVar3;
}

