/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0045ebb0  name=FUN_0045ebb0  size=160  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int * FUN_0045ebb0(int *param_1,int param_2)

{
  int *piVar1;
  int iVar2;
  
  if ((param_1 == (int *)0x0) || (param_2 == 0)) {
    piVar1 = (int *)0x0;
  }
  else {
    piVar1 = (int *)FUN_0045ba88(uRam00e295c4,0xc);
    if (piVar1 == (int *)0x0) {
      piVar1 = (int *)0x0;
    }
    else {
      *piVar1 = param_2;
      iVar2 = *param_1;
      piVar1[1] = iVar2;
      if (iVar2 == 0) {
        param_1[1] = (int)(piVar1 + 1);
      }
      else {
        *(int **)(*param_1 + 8) = piVar1 + 1;
      }
      *param_1 = (int)piVar1;
      piVar1[2] = (int)param_1;
    }
  }
  return piVar1;
}

