/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003b8d48  name=FUN_003b8d48  size=164  xrefs=11
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_003b8d48(int *param_1,undefined4 param_2,undefined4 param_3)

{
  undefined4 uVar1;
  
  if (param_1 == (int *)0x0) {
    uVar1 = 1;
  }
  else if (*param_1 == 1) {
    if (param_1[2] == 0) {
      uVar1 = 1;
    }
    else {
      (*(code *)param_1[2])(param_2,param_3,param_1[1]);
      uVar1 = 1;
    }
  }
  else if (*param_1 == 2) {
    uVar1 = (*(code *)param_1[2])(param_2,param_3,param_1);
  }
  else {
    uVar1 = 0;
  }
  return uVar1;
}

