/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00021cb4  name=FUN_00021cb4  size=232  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


ushort FUN_00021cb4(int param_1,int param_2)

{
  int iVar1;
  ushort uVar2;
  int iVar3;
  
  iVar1 = param_1 * 0x430;
  uVar2 = 0;
  iVar3 = param_2 * 600 + iVar1 + 0x108e6a0;
  if ((((param_1 < 2 && -1 < (int)((-1 - param_2) + (uint)(param_2 == 0))) && (iRam00e10734 != 0))
      && (*(int *)(iVar1 + 0x108e9e4) != 0)) && (*(char *)(iVar3 + 0x234) == '\0')) {
    FUN_005accf4(iVar1 + 0x108e964,0xffffffff);
    FUN_00021a68(param_1,param_2,iVar3);
    FUN_005ad104(iVar1 + 0x108e964);
    uVar2 = *(ushort *)(iVar3 + 0xaa) & 1;
  }
  return uVar2;
}

