/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00130910  name=FUN_00130910  size=1396  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00130910(int param_1,int param_2,undefined4 param_3,int param_4,int param_5,int param_6,
                 int param_7,int param_8,int param_9)

{
  int iVar1;
  int iVar2;
  undefined4 uVar3;
  int iVar4;
  undefined4 uVar5;
  int iVar6;
  int iVar7;
  int iVar8;
  int iVar9;
  int iVar10;
  
  if (1 < *(int *)(param_1 + 0x14)) {
    *(undefined4 *)(param_1 + 0x18) = 100;
  }
  if (-1 < param_6) {
    if (*(int *)(param_1 + 0x18) == param_6) {
      FUN_0012f0a0(param_1,0,0,param_4 + -4,param_5,0xc0ff0000);
    }
    else {
      iVar9 = 0;
      iVar4 = *(int *)(param_6 * 4 + param_1 + 0x274);
      iVar2 = *(int *)(param_1 + 0xc);
      iVar1 = iVar4 * 4;
      iVar6 = iVar2 + iVar1;
      if (0 < param_5) {
        while( true ) {
          iVar7 = *(int *)(param_1 + 8) * iVar9;
          iVar9 = iVar9 + 1;
          FUN_0039ac74(iVar2 + iVar7 * 4,param_3,iVar1);
          if (param_5 <= iVar9) break;
          iVar2 = *(int *)(param_1 + 0xc);
        }
      }
      iVar2 = 0;
      if (0 < param_5) {
        do {
          iVar9 = *(int *)(param_1 + 8) * iVar2;
          iVar2 = iVar2 + 1;
          FUN_0039ac74(iVar9 * 4 + iVar6,iVar1 + param_2,(param_4 - iVar4) * 4);
        } while (iVar2 < param_5);
      }
    }
    if (*(int *)(param_1 + 0x14) < 2) {
      uVar3 = 0xf0;
      uVar5 = 1;
    }
    else {
      uVar3 = 0xd5;
      uVar5 = 2;
    }
    FUN_0012f0a0(param_1,uVar3,0,uVar5,param_5 + 2,0xc0ffffff);
  }
  if (-1 < param_7) {
    iVar6 = *(int *)(param_7 * 4 + param_1 + 0x274);
    iVar2 = *(int *)(param_1 + 0xc);
    iVar4 = *(int *)(param_1 + 8);
    iVar1 = iVar6 * 4;
    iVar9 = param_5 + 4;
    iVar7 = iVar2 + iVar1;
    iVar8 = iVar4 * iVar9;
    if (*(int *)(param_1 + 0x18) == param_7) {
      FUN_0012f0a0(param_1,0,iVar9,param_4 + -4,param_5,0xc0ff0000);
    }
    else {
      iVar10 = 0;
      if (0 < param_5) {
        while( true ) {
          iVar4 = iVar4 * iVar10;
          iVar10 = iVar10 + 1;
          FUN_0039ac74((iVar4 + iVar8) * 4 + iVar2,param_3,iVar1);
          if (param_5 <= iVar10) break;
          iVar2 = *(int *)(param_1 + 0xc);
          iVar4 = *(int *)(param_1 + 8);
        }
      }
      iVar2 = 0;
      if (0 < param_5) {
        do {
          iVar4 = *(int *)(param_1 + 8) * iVar2;
          iVar2 = iVar2 + 1;
          FUN_0039ac74((iVar4 + iVar8) * 4 + iVar7,iVar1 + param_2,(param_4 - iVar6) * 4);
        } while (iVar2 < param_5);
      }
    }
    if (*(int *)(param_1 + 0x14) < 2) {
      uVar3 = 0xf0;
      uVar5 = 1;
    }
    else {
      uVar3 = 0xd5;
      uVar5 = 2;
    }
    FUN_0012f0a0(param_1,uVar3,param_5 + 2,uVar5,iVar9,0xc0ffffff);
  }
  if (-1 < param_8) {
    iVar6 = *(int *)(param_8 * 4 + param_1 + 0x274);
    iVar2 = *(int *)(param_1 + 0xc);
    iVar4 = *(int *)(param_1 + 8);
    iVar1 = iVar6 * 4;
    iVar9 = param_5 * 2 + 8;
    iVar7 = iVar2 + iVar1;
    iVar8 = iVar4 * iVar9;
    if (*(int *)(param_1 + 0x18) == param_8) {
      FUN_0012f0a0(param_1,0,iVar9,param_4 + -4,param_5,0xc0ff0000);
    }
    else {
      iVar9 = 0;
      if (0 < param_5) {
        while( true ) {
          iVar4 = iVar4 * iVar9;
          iVar9 = iVar9 + 1;
          FUN_0039ac74((iVar4 + iVar8) * 4 + iVar2,param_3,iVar1);
          if (param_5 <= iVar9) break;
          iVar2 = *(int *)(param_1 + 0xc);
          iVar4 = *(int *)(param_1 + 8);
        }
      }
      iVar2 = 0;
      if (0 < param_5) {
        do {
          iVar4 = *(int *)(param_1 + 8) * iVar2;
          iVar2 = iVar2 + 1;
          FUN_0039ac74((iVar4 + iVar8) * 4 + iVar7,iVar1 + param_2,(param_4 - iVar6) * 4);
        } while (iVar2 < param_5);
      }
    }
    if (*(int *)(param_1 + 0x14) < 2) {
      uVar3 = 0xf0;
      uVar5 = 1;
    }
    else {
      uVar3 = 0xd5;
      uVar5 = 2;
    }
    FUN_0012f0a0(param_1,uVar3,param_5 * 2 + 6,uVar5,param_5 + 4,0xc0ffffff);
  }
  if (param_9 < 0) {
    return;
  }
  iVar6 = *(int *)(param_9 * 4 + param_1 + 0x274);
  iVar2 = *(int *)(param_1 + 0xc);
  iVar4 = *(int *)(param_1 + 8);
  iVar9 = param_5 * 3 + 0xc;
  iVar1 = iVar6 * 4;
  iVar7 = iVar2 + iVar1;
  iVar8 = iVar4 * iVar9;
  if (*(int *)(param_1 + 0x18) == param_9) {
    FUN_0012f0a0(param_1,0,iVar9,param_4 + -4,param_5,0xc0ff0000);
  }
  else {
    iVar9 = 0;
    if (0 < param_5) {
      while( true ) {
        iVar4 = iVar4 * iVar9;
        iVar9 = iVar9 + 1;
        FUN_0039ac74((iVar4 + iVar8) * 4 + iVar2,param_3,iVar1);
        if (param_5 <= iVar9) break;
        iVar2 = *(int *)(param_1 + 0xc);
        iVar4 = *(int *)(param_1 + 8);
      }
    }
    iVar2 = 0;
    if (0 < param_5) {
      do {
        iVar4 = *(int *)(param_1 + 8) * iVar2;
        iVar2 = iVar2 + 1;
        FUN_0039ac74((iVar4 + iVar8) * 4 + iVar7,iVar1 + param_2,(param_4 - iVar6) * 4);
      } while (iVar2 < param_5);
    }
  }
  if (*(int *)(param_1 + 0x14) < 2) {
    uVar3 = 0xf0;
    uVar5 = 1;
  }
  else {
    uVar3 = 0xd5;
    uVar5 = 2;
  }
  FUN_0012f0a0(param_1,uVar3,param_5 * 3 + 10,uVar5,param_5 + 2,0xc0ffffff);
  return;
}

