/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005df294  name=FUN_005df294  size=76  xrefs=33
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_005df294(int param_1)

{
  undefined4 uVar1;
  
  uVar1 = 0;
  if (param_1 != 0) {
    uVar1 = (**(code **)(*(int *)(*(int *)(param_1 + -4) + 0x60) + 0x10))
                      (*(int *)(param_1 + -4),param_1);
  }
  return uVar1;
}

