/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0043cdf4  name=FUN_0043cdf4  size=160  xrefs=4
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0043cdf4(void)

{
  undefined8 uVar1;
  undefined4 uVar2;
  int iVar3;
  
  if (iRam00e291d4 == 0) {
    iVar3 = FUN_00009518();
    if (iVar3 < 1) {
      uVar2 = 0xffffffff;
      uVar1 = CONCAT44(uRam0100b3e8._0_4_,uRam0100b3e8._4_4_);
    }
    else {
      iRam00e291d4 = 1;
      memset(0x100b3e8,0x10);
      uVar2 = FUN_0036fd0c();
      uRam0100b3e8 = FUN_005b4a78();
      FUN_0036fd24(uVar2);
      uVar2 = 0;
      uVar1 = uRam0100b3e8;
    }
  }
  else {
    uVar2 = 0xffffffff;
    uVar1 = uRam0100b3e8;
  }
  uRam0100b3e8._0_4_ = (undefined4)((ulonglong)uVar1 >> 0x20);
  uRam0100b3e8._4_4_ = (undefined4)uVar1;
  return uVar2;
}

