/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x000aa51c  name=FUN_000aa51c  size=732  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


/* WARNING: Removing unreachable block (ram,0x000aa71c) */

int FUN_000aa51c(int param_1)

{
  bool bVar1;
  uint uVar2;
  int iVar3;
  int iVar4;
  undefined4 ***pppuVar5;
  undefined1 auStack_98 [8];
  undefined1 auStack_90 [4];
  undefined4 **appuStack_8c [4];
  undefined4 uStack_7c;
  uint uStack_78;
  undefined1 auStack_70 [4];
  undefined4 uStack_6c;
  undefined4 uStack_58;
  undefined4 uStack_54;
  undefined1 *puStack_50;
  undefined4 uStack_4c;
  undefined1 *puStack_48;
  undefined1 *puStack_44;
  int iStack_3c;
  int iStack_38;
  int iStack_34;
  int iStack_30;
  int iStack_2c;
  int iStack_28;
  uint uStack_24;
  undefined4 uStack_20;
  uint uStack_1c;
  int iStack_18;
  int iStack_14;
  
  puStack_44 = &stack0xffffff60;
  uStack_58 = 0x25710c;
  puStack_50 = auStack_98;
  uStack_4c = 0xba7ec;
  uStack_54 = 0xe974c8;
  puStack_48 = (undefined1 *)register0x00000004;
  iStack_3c = param_1;
  FUN_003d1214(auStack_70);
  iStack_34 = *(int *)(iStack_3c + 0xec);
  iStack_38 = 0;
  if (iStack_34 != *(int *)(iStack_3c + 0xf0)) {
    do {
      iStack_2c = iStack_3c + 0xf8;
      iStack_30 = FUN_005fbc34(iStack_2c,iStack_34);
      bVar1 = false;
      if (((iStack_30 != *(int *)(iStack_2c + 4)) &&
          (*(int *)(*(int *)(iStack_30 + 0x28) + 0x5c) != 0)) &&
         (*(char *)(iStack_3c + 0x44) != '\0')) {
        bVar1 = true;
      }
      if (bVar1) {
        iVar4 = *(int *)(iStack_30 + 0x28);
        iStack_28 = iVar4 + 0x24;
        uStack_20 = 0xe9f3ac;
        if (0xf < uRam00e9f3c0) {
          uStack_20 = uRam00e9f3ac;
        }
        uStack_1c = uRam00e9f3bc;
        uStack_24 = *(uint *)(iVar4 + 0x38);
        if (*(uint *)(iVar4 + 0x38) < *(uint *)(iVar4 + 0x38)) {
          uStack_24 = *(uint *)(iVar4 + 0x38);
        }
        uVar2 = 0;
        if (uStack_24 != 0) {
          iVar3 = iVar4 + 0x28;
          if (0xf < *(uint *)(iVar4 + 0x3c)) {
            iVar3 = *(int *)(iVar4 + 0x28);
          }
          uVar2 = uRam00e9f3bc;
          if (uStack_24 < uRam00e9f3bc) {
            uVar2 = uStack_24;
          }
          uVar2 = FUN_0039ac2c(iVar3,uStack_20,uVar2);
        }
        if ((uVar2 == 0) && (uVar2 = (uint)(uStack_24 != uStack_1c), uStack_24 < uStack_1c)) {
          uVar2 = 0xffffffff;
        }
        if (uVar2 == 0) {
          iStack_14 = iStack_30 + 0xc;
          uStack_6c = 0xffffffff;
          iStack_18 = FUN_0013a9c4(*(undefined4 *)(*(int *)(iStack_30 + 0x28) + 0x5c));
          if (iStack_18 != 0) {
            FUN_005f4290(auStack_90,*(int *)(*(int *)(iStack_14 + 0x1c) + 0x5c) + 0xa4);
            pppuVar5 = appuStack_8c;
            if (0xf < uStack_78) {
              pppuVar5 = (undefined4 ***)appuStack_8c[0];
            }
            uStack_6c = 1;
            FUN_0005e784(0,3,4,0xd42e04,0x65f028,0x5a5,0xd431e8,pppuVar5);
            if (0xf < uStack_78) {
              FUN_00245c34(appuStack_8c[0]);
            }
            iStack_38 = iStack_18;
            uStack_78 = 0xf;
            appuStack_8c[0] = (undefined4 **)((uint)appuStack_8c[0] & 0xffffff);
            uStack_7c = 0;
          }
        }
      }
      iStack_34 = iStack_34 + 0x1c;
    } while (iStack_34 != *(int *)(iStack_3c + 0xf0));
  }
  FUN_003d12b8(auStack_70);
  return iStack_38;
}

