/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00348254  name=FUN_00348254  size=132  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00348254(uint param_1)

{
  FUN_0034c004(0x72,0x41,0x40,6,1);
  FUN_0034c004(0x72,0x41,0x40,6,0);
  FUN_0034c004(0x72,0xc9,0xf,0,
               ((int)(((int)param_1 >> 0x1f) - ((int)param_1 >> 0x1f ^ param_1)) >> 0x1f &
               0xfffffff1U) + 0xf);
  return;
}

