/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00257d18  name=FUN_00257d18  size=268  xrefs=102
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00257d18(undefined4 *param_1,undefined1 param_2)

{
  int iVar1;
  int iVar2;
  int *piVar3;
  
  iVar2 = param_1[2];
  if (param_1[3] + -1 <= iVar2) {
    iVar1 = (**(code **)(*(int *)*param_1 + 0x10))((int *)*param_1,param_1[3] + 0x100);
    if (iVar1 == 0) {
      return;
    }
    param_1[3] = param_1[3] + 0x100;
    iVar2 = 0;
    if (param_1[1] != 0) {
      FUN_0039ac74(iVar1,param_1[1],param_1[2] + 1);
      iVar2 = param_1[1];
    }
    piVar3 = (int *)*param_1;
    if (iVar2 != 0 && piVar3 != (int *)0x0) {
      (**(code **)(*piVar3 + 0x14))(piVar3,iVar2);
    }
    iVar2 = param_1[2];
    param_1[1] = iVar1;
  }
  *(undefined1 *)(param_1[1] + iVar2) = param_2;
  param_1[2] = iVar2 + 1;
  *(undefined1 *)(param_1[1] + iVar2 + 1) = 0;
  return;
}

