/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00373f30  name=FUN_00373f30  size=224  xrefs=123
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


uint FUN_00373f30(uint param_1,uint param_2)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  int iVar4;
  uint uVar5;
  uint uVar6;
  
  uVar3 = param_1 >> 0x14 & 0x7ff;
  uVar2 = param_2 << 0xb;
  uVar1 = param_1 << 0xb | param_2 >> 0x15 | 0x80000000;
  uVar5 = param_1 & 0x80000000;
  iVar4 = uVar3 - 0x380;
  if (0xfd < uVar3 - 0x381) {
    if ((iVar4 == 0x47f) &&
       (((param_1 << 0xb & 0x7fffffff) != 0 || param_2 >> 0x15 != 0) || uVar2 != 0)) {
      return uVar5 | 0x7fc00000;
    }
    if (0xfe < iVar4) {
      return uVar5 | 0x7f800000;
    }
    uVar3 = 1 - iVar4;
    if (uVar3 < 0x20) {
      uVar6 = uVar1 << (0x20 - uVar3 & 0x3f);
      uVar3 = uVar1 >> (uVar3 & 0x3f);
    }
    else {
      uVar3 = 0;
      uVar6 = uVar1;
    }
    uVar2 = uVar2 | uVar6;
    iVar4 = 0;
    uVar1 = uVar3 | 0x80000000;
  }
  if (uVar2 != 0) {
    uVar1 = uVar1 | 1;
  }
  return (uVar1 + 0x80) - (uVar1 + 0x80 >> 8 & 1) >> 8 & 0x7fffff |
         (iVar4 + (uint)(0xffffff7f < uVar1)) * 0x800000 | uVar5;
}

