/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00586514  name=FUN_00586514  size=312  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_00586514(int param_1,int param_2,byte *param_3)

{
  int *piVar1;
  int iVar2;
  byte bVar3;
  
  if ((param_2 != 0) && (param_3 != (byte *)0x0)) {
    for (bVar3 = 0; bVar3 < *(byte *)(param_2 + 0xe); bVar3 = bVar3 + 1) {
      piVar1 = *(int **)(param_2 + (uint)bVar3 * 4 + 0x44);
      if ((piVar1 != (int *)0x0) && (*piVar1 == param_1)) {
        if (*(char *)(param_2 + 0x42) == '\0') {
          *param_3 = 0xff;
          return param_2;
        }
        *param_3 = bVar3;
        return param_2;
      }
    }
    for (bVar3 = 0; bVar3 < *(byte *)(param_2 + 0xe); bVar3 = bVar3 + 1) {
      iVar2 = *(int *)(param_2 + (uint)bVar3 * 4 + 0x44);
      if (((iVar2 != 0) && (*(int *)(iVar2 + 0xc) != 0)) &&
         (iVar2 = FUN_00586514(param_1,*(undefined4 *)(iVar2 + 0xc),param_3), iVar2 != 0)) {
        if (*param_3 != 0xff) {
          return iVar2;
        }
        if (*(char *)(param_2 + 0x42) != '\0') {
          *param_3 = bVar3;
          return param_2;
        }
        return iVar2;
      }
    }
  }
  return 0;
}

