/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0050f2c0  name=FUN_0050f2c0  size=664  xrefs=17
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_0050f2c0(undefined4 param_1,int param_2,int param_3,int param_4,undefined4 param_5,
                undefined4 param_6,undefined4 param_7)

{
  int iVar1;
  int iVar2;
  undefined4 *puVar3;
  byte in_cr0;
  byte in_cr1;
  byte unaff_cr2;
  byte unaff_cr3;
  byte unaff_cr4;
  byte in_cr5;
  byte in_cr6;
  byte in_cr7;
  undefined4 uStack_40;
  int iStack_3c;
  int aiStack_30 [5];
  uint uStack_1c;
  
  uStack_1c = (uint)(in_cr0 & 0xf) << 0x1c | (uint)(in_cr1 & 0xf) << 0x18 |
              (uint)(unaff_cr2 & 0xf) << 0x14 | (uint)(unaff_cr3 & 0xf) << 0x10 |
              (uint)(unaff_cr4 & 0xf) << 0xc | (uint)(in_cr5 & 0xf) << 8 | (uint)(in_cr6 & 0xf) << 4
              | (uint)(in_cr7 & 0xf);
  aiStack_30[0] = 0;
  uStack_40 = param_5;
  iStack_3c = param_2;
  if ((param_2 == 0) && (param_4 == 0 || param_3 == 7)) {
    FUN_004bdee0(param_1,0xd89270);
    goto joined_r0x0050f3c8;
  }
  FUN_004a2768();
  iVar1 = FUN_004a18ac();
  if (iVar1 == 0) {
LAB_0050f54c:
    FUN_004d4bdc(param_1);
LAB_0050f3bc:
    if (iVar1 == 0) goto joined_r0x0050f3c8;
  }
  else if (param_2 == 0 && param_4 != 0) {
    puVar3 = (undefined4 *)FUN_00398df4();
    FUN_003988b0(*puVar3,0,2,0);
    puVar3 = (undefined4 *)FUN_00398df4();
    FUN_004a1ff0(iVar1,0x6a,0,*puVar3);
    if (param_3 != 1) goto LAB_0050f364;
LAB_0050f43c:
    aiStack_30[0] = FUN_004d914c(iVar1,0);
  }
  else {
    iVar2 = FUN_004a1ff0(iVar1,0x6c,3,param_2);
    if (iVar2 < 1) {
      FUN_004bdee0(param_1,0xd8921c,param_7,param_2);
      goto LAB_0050f54c;
    }
    if (param_3 == 1) goto LAB_0050f43c;
LAB_0050f364:
    if (param_3 == 3) {
      aiStack_30[0] = FUN_004bb234(iVar1,0,0x51e218,&uStack_40);
    }
    else {
      if (param_3 != 4 && param_3 != 8) {
        if (param_3 == 5) {
          FUN_0050e9c0(param_1,iVar1,param_7,0x51e218,&uStack_40,aiStack_30,0,0);
        }
        else {
          FUN_004bdee0(param_1,0xd89288);
        }
        goto LAB_0050f3bc;
      }
      aiStack_30[0] = FUN_0050eef0(param_1,iVar1,param_2,param_7,param_3);
    }
  }
  FUN_004a193c(iVar1);
joined_r0x0050f3c8:
  if (aiStack_30[0] == 0) {
    FUN_004bdee0(param_1,0xd530dc,param_7);
    return aiStack_30[0];
  }
  return aiStack_30[0];
}

