/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00350e7c  name=FUN_00350e7c  size=72  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00350e7c(int param_1)

{
  undefined4 uVar1;
  
  uVar1 = 0xd6715c;
  if (param_1 != 1) {
    uVar1 = 0xd67164;
    if ((param_1 != 0) && (uVar1 = 0xd6716c, param_1 != 2)) {
      uVar1 = 0xd670b0;
    }
  }
  return uVar1;
}

