/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004138bc  name=FUN_004138bc  size=120  xrefs=8
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_004138bc(int param_1,undefined4 param_2,uint param_3,uint param_4)

{
  int iVar1;
  undefined4 uVar2;
  uint uVar3;
  
  uVar3 = *(uint *)(param_1 + 0x10);
  if (param_4 <= uVar3) {
    if (param_3 < uVar3) {
      iVar1 = *(int *)(param_1 + 0x14);
      *(uint *)(param_1 + 0x10) = param_3;
      uVar3 = param_3;
    }
    else {
      iVar1 = *(int *)(param_1 + 0x14);
    }
    if (iVar1 == 0) {
      uVar2 = *(undefined4 *)(param_1 + 0xc);
    }
    else {
      uVar2 = *(undefined4 *)(param_1 + 0xc);
    }
    FUN_0036c8ac(uVar2,param_2,uVar3);
    return 0;
  }
  return 0x16;
}

