/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005d039c  name=FUN_005d039c  size=64  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


bool FUN_005d039c(int param_1,undefined4 param_2,undefined4 param_3)

{
  int iVar1;
  
  iVar1 = FUN_004d2a7c(param_1 + 8,0x9c,0x1001,param_2,param_3);
  return iVar1 != 0;
}

