/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00221500  name=FUN_00221500  size=68  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_00221500(int param_1)

{
  int iVar1;
  
  iVar1 = FUN_0021eeb8(0x400000c,param_1 << 3,8);
  return -(uint)(iVar1 == -1);
}

