/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002be718  name=FUN_002be718  size=100  xrefs=25
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_002be718(undefined4 *param_1)

{
  int iVar1;
  int *piVar2;
  
  piVar2 = (int *)*param_1;
  iVar1 = 0;
  if (((piVar2 != (int *)0x0) && (iVar1 = 0, *piVar2 != 0)) && (iVar1 = piVar2[4], iVar1 == 0)) {
    iVar1 = FUN_002c14e8();
    piVar2[4] = iVar1;
  }
  return iVar1;
}

