/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00551840  name=FUN_00551840  size=164  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


bool FUN_00551840(int param_1)

{
  bool bVar1;
  int *piVar2;
  int iVar3;
  int aiStack_18 [3];
  
  FUN_0054e924(*(undefined4 *)(param_1 + 0x1c));
  piVar2 = (int *)FUN_0054e680(*(undefined4 *)(param_1 + 0x1c),0);
  iVar3 = *piVar2;
  if (iVar3 == 0) {
    aiStack_18[0] = -1;
  }
  else {
    aiStack_18[0] = 0;
  }
  FUN_00372330(piVar2,1,4,aiStack_18);
  FUN_0036722c(2);
  bVar1 = *piVar2 == aiStack_18[0];
  if (bVar1) {
    *piVar2 = iVar3;
  }
  FUN_0054e9bc(*(undefined4 *)(param_1 + 0x1c));
  return bVar1;
}

