/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002269bc  name=FUN_002269bc  size=84  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


char FUN_002269bc(int param_1,undefined4 param_2)

{
  int iVar1;
  
  iVar1 = param_1 + 0x34;
  if (0xf < *(uint *)(param_1 + 0x48)) {
    iVar1 = *(int *)(param_1 + 0x34);
  }
  iVar1 = FUN_003c9eac(iVar1,0xd5e030,param_2);
  return (iVar1 != 1) * '\x02';
}

