/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0053ed7c  name=FUN_0053ed7c  size=584  xrefs=6
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0053ed7c(int param_1,int *param_2,int *param_3,undefined4 *param_4)

{
  bool bVar1;
  int iVar2;
  undefined4 uVar3;
  uint uVar4;
  uint uVar5;
  int iVar6;
  undefined4 auStack_28 [4];
  
  iVar6 = *(int *)(param_1 + 0xac);
  if (iVar6 == 0) {
    return 0;
  }
  if (param_4 != (undefined4 *)0x0) {
    FUN_0053ec48(0);
    iVar2 = iRam00e3943c;
    auStack_28[0] = *(undefined4 *)(param_1 + 0xa8);
    bVar1 = iRam00e3943c != 0;
    *param_4 = 0;
    if (bVar1) {
      iVar2 = FUN_004ace9c(iVar2,auStack_28);
      if (iVar2 < 0) {
        *param_4 = 0;
      }
      else {
        uVar3 = FUN_004acc80(iRam00e3943c);
        *param_4 = uVar3;
      }
    }
  }
  if (param_2 == (int *)0x0 || param_3 == (int *)0x0) {
    return 0;
  }
  uVar5 = *(uint *)(iVar6 + 0xc);
  uVar4 = uVar5 & 0x43f8000;
  if (uVar4 == 0x40000) {
    iVar6 = 3;
LAB_0053ef00:
    iVar2 = *(int *)(iVar6 * 4 + 0xe39448);
LAB_0053ef10:
    uVar5 = uVar5 & 0xc00000;
    *param_2 = iVar2;
    if (uVar5 == 0x400000) goto LAB_0053ee68;
LAB_0053ef24:
    if (uVar5 != 0x800000) {
      iVar6 = 0;
      *param_3 = 0;
      goto joined_r0x0053ef3c;
    }
    iVar6 = 1;
  }
  else {
    if (0x40000 < uVar4) {
      if (uVar4 != 0x200000) {
        if (uVar4 < 0x200001) {
          if (uVar4 == 0x80000) {
            iVar6 = 4;
            goto LAB_0053ef00;
          }
        }
        else if (uVar4 == 0x4000000) {
          if (*(int *)(iVar6 + 0x1c) == 0x80) {
            iVar6 = 7;
          }
          else {
            if (*(int *)(iVar6 + 0x1c) != 0x100) goto LAB_0053ee50;
            iVar6 = 8;
          }
          goto LAB_0053ef00;
        }
        goto LAB_0053ee50;
      }
      iVar2 = FUN_005c8fc8(0);
      uVar5 = *(uint *)(iVar6 + 0xc);
      goto LAB_0053ef10;
    }
    if (uVar4 == 0x10000) {
      iVar6 = 1;
      goto LAB_0053ef00;
    }
    if (uVar4 < 0x10001) {
      if (uVar4 == 0x8000) {
        iVar6 = 0;
        goto LAB_0053ef00;
      }
    }
    else if (uVar4 == 0x20000) {
      iVar6 = 2;
      goto LAB_0053ef00;
    }
LAB_0053ee50:
    uVar5 = uVar5 & 0xc00000;
    iVar2 = 0;
    *param_2 = 0;
    if (uVar5 != 0x400000) goto LAB_0053ef24;
LAB_0053ee68:
    iVar6 = 0;
  }
  iVar6 = *(int *)(iVar6 * 4 + 0xe39440);
  *param_3 = iVar6;
joined_r0x0053ef3c:
  if (iVar2 == 0) {
    uVar3 = 0;
  }
  else {
    uVar3 = 1;
    if (iVar6 == 0) {
      uVar3 = 0;
    }
  }
  return uVar3;
}

