/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0034d338  name=FUN_0034d338  size=652  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_0034d338(int param_1,uint *param_2)

{
  undefined4 *puVar1;
  uint uVar2;
  undefined4 uVar3;
  undefined4 uVar4;
  undefined4 uVar5;
  int iVar6;
  uint uVar7;
  int iVar8;
  uint uVar9;
  
  uVar7 = *param_2;
  uVar9 = param_2[1];
  iVar6 = -1;
  if (2 < uVar7) {
    puVar1 = (undefined4 *)FUN_00442914();
    *puVar1 = 0x1fd0002;
    uVar3 = 0xd66d84;
    if ((uRam00e262e8 & 1) == 0) {
      return -1;
    }
LAB_0034d41c:
    FUN_001d7360(0,0,0,uVar3,uVar7);
    return iVar6;
  }
  if (uVar9 < 6) {
    if (uVar9 == 5) {
      iVar8 = uVar7 * 0xc + param_1;
      uVar9 = FUN_000000dc(*(int *)(param_1 + 4) + 0x4c);
      FUN_000000e8(*(int *)(param_1 + 4) + 0x4c,
                   uVar9 & ~*(uint *)(iVar8 + 0xc) & ~(0x80 << (*(uint *)(iVar8 + 0x10) & 0x3f)));
      iVar6 = 0;
      uVar9 = uRam00e262e8 & 0x10;
      *(undefined4 *)(iVar8 + 0x14) = 5;
      if (uVar9 != 0) {
        uVar7 = FUN_00350ddc(uVar7);
        uVar3 = 0xd66d34;
        goto LAB_0034d41c;
      }
    }
    else {
      iVar8 = uVar7 * 0xc + param_1;
      *(uint *)(iVar8 + 0x14) = uVar9;
      if ((*(uint *)(uVar9 * 0x1e0 + param_1 + 0x30) & 0x10000000) == 0) {
        puVar1 = (undefined4 *)FUN_00442914();
        *puVar1 = 0x1fd0005;
      }
      else {
        iVar6 = 0;
        uVar2 = FUN_000000dc(*(int *)(param_1 + 4) + 0x4c);
        FUN_000000e8(*(int *)(param_1 + 4) + 0x4c,
                     uVar2 & ~*(uint *)(iVar8 + 0xc) | uVar9 << (*(uint *)(iVar8 + 0x10) & 0x3f));
      }
      if ((uRam00e262e8 & 0x10) != 0) {
        uVar3 = FUN_00350774(uVar9);
        uVar4 = FUN_00350ddc(uVar7);
        uVar5 = 0xd50060;
        if (iVar6 != 0) {
          uVar5 = 0xd572f8;
        }
        FUN_001d7360(0,0,0,0xd66d98,uVar3,uVar4,uVar5);
        return iVar6;
      }
    }
  }
  else {
    puVar1 = (undefined4 *)FUN_00442914();
    *puVar1 = 0x1fd0003;
    uVar3 = 0xd66d6c;
    uVar7 = uVar9;
    if ((uRam00e262e8 & 1) != 0) goto LAB_0034d41c;
  }
  return iVar6;
}

