/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0031a048  name=FUN_0031a048  size=40  xrefs=7
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0031a048(int param_1)

{
  *(uint *)(param_1 + 100) = *(uint *)(param_1 + 100) & 0xffffbfff;
  *(undefined4 *)(param_1 + 0x74) = 0xffffffff;
  *(undefined4 *)(param_1 + 0x78) = 0xffffffff;
  *(undefined4 *)(param_1 + 0x70) = 0xffffffff;
  return;
}

