/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0044e014  name=FUN_0044e014  size=12  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0044e014(undefined4 param_1,undefined4 param_2)

{
  FUN_0044e510(param_1,0x2e,param_2);
  return;
}

