/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002aff44  name=FUN_002aff44  size=252  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002aff44(int param_1)

{
  int iVar1;
  int *piVar2;
  
  while( true ) {
    iVar1 = FUN_005accf4(*(undefined4 *)(param_1 + 0x4c),0xffffffff);
    if (iVar1 == -1) {
      FUN_00443f20(0xd5ee98,1,2,3,4,5,6);
    }
    piVar2 = *(int **)(param_1 + 0x48);
    if (piVar2 != (int *)0x0) {
      *(int *)(param_1 + 0x48) = piVar2[3];
    }
    iVar1 = FUN_005ad104(*(undefined4 *)(param_1 + 0x4c));
    if (iVar1 == -1) {
      FUN_00443f20(0xd5ee98,1,2,3,4,5,6);
    }
    if (piVar2 == (int *)0x0) break;
    (**(code **)(*piVar2 + 4))(piVar2);
  }
  return;
}

