/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0047d328  name=FUN_0047d328  size=64  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0047d328(void)

{
  int iVar1;
  undefined4 uVar2;
  
  iVar1 = FUN_0047d0f0(0);
  if (iVar1 == 0) {
    uVar2 = 0xffffffff;
  }
  else {
    *(undefined4 *)(iVar1 + 0x424) = 1;
    uVar2 = 0;
  }
  return uVar2;
}

