/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002a6ef0  name=FUN_002a6ef0  size=108  xrefs=5
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002a6ef0(int param_1,int param_2)

{
  if (*(int *)(param_1 + 0xd20) != param_2) {
    FUN_002a6f5c();
    *(int *)(param_1 + 0xd20) = param_2;
    *(int *)(param_1 + 0x13f0) = param_2;
    if (param_2 == 0) {
      FUN_002f44a8(param_1 + 0x13f4);
    }
    else {
      FUN_002764f8(param_2);
    }
  }
  return;
}

