/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0033eefc  name=FUN_0033eefc  size=408  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_0033eefc(undefined4 param_1)

{
  bool bVar1;
  int iVar2;
  int iVar3;
  uint uVar4;
  undefined1 auStack_28 [2];
  char cStack_26;
  char cStack_1f;
  
  FUN_001d9a58(4000);
  iVar2 = FUN_0033ede0(param_1,auStack_28);
  if (iVar2 != -1) {
    if ((cStack_26 == '.') && (cStack_1f == '.')) {
      cRam00e2628c = '\x01';
    }
    else {
      cRam00e2628c = '\0';
    }
  }
  uVar4 = 0;
  if (cRam00e2628c == '\0') {
    do {
      while( true ) {
        iVar2 = uVar4 * 8;
        iVar3 = FUN_0033e8e0(param_1,*(undefined1 *)(iVar2 + 0xd22e74),
                             *(undefined1 *)(iVar2 + 0xd22e75));
        uVar4 = uVar4 + 1;
        if (iVar3 == -1) goto LAB_0033efc4;
        if (*(int *)(iVar2 + 0xd22e78) == 0) break;
        FUN_001d9a58();
        if (0x13 < uVar4) goto LAB_0033efc4;
      }
    } while (uVar4 < 0x14);
  }
  else {
    do {
      iVar2 = uVar4 * 8;
      iVar3 = FUN_0033e8e0(param_1,*(undefined1 *)(iVar2 + 0xd22f14),
                           *(undefined1 *)(iVar2 + 0xd22f15));
      uVar4 = uVar4 + 1;
      if (iVar3 == -1) break;
      if (*(int *)(iVar2 + 0xd22f18) != 0) {
        FUN_001d9a58();
      }
    } while (uVar4 < 0xd);
  }
LAB_0033efc4:
  if (iVar3 == 0) {
    uVar4 = 0;
    do {
      FUN_0033e8e0(param_1,0x19,1);
      FUN_001d9a58(100);
      FUN_0033e8e0(param_1,0x19,0);
      bVar1 = uVar4 != 2;
      uVar4 = uVar4 + 1;
      if (bVar1) {
        FUN_001d9a58(100);
      }
    } while (uVar4 < 3);
  }
  return iVar3;
}

