/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0045b9e4  name=FUN_0045b9e4  size=164  xrefs=15
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0045b9e4(int param_1,undefined4 param_2,undefined4 param_3)

{
  int iVar1;
  undefined4 uVar2;
  
  if ((param_1 == 0) || (iVar1 = FUN_005bad5c(param_1,uRam00e295c0), iVar1 != 0)) {
    uVar2 = 0;
  }
  else if (*(code **)(param_1 + 0xcc) == reset_vector) {
    uVar2 = FUN_0045b6b8(param_1,param_2,param_3);
  }
  else {
    uVar2 = (**(code **)(param_1 + 0xcc))(param_1,*(undefined4 *)(param_1 + 0xdc),param_2,param_3);
  }
  return uVar2;
}

