/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0015dfcc  name=FUN_0015dfcc  size=364  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0015dfcc(int param_1,char *param_2,undefined4 *param_3)

{
  int iVar1;
  undefined4 uVar2;
  undefined4 *puVar3;
  undefined8 uVar4;
  undefined4 uStack_28;
  undefined4 uStack_24;
  int aiStack_20 [5];
  
  *param_2 = '\0';
  uVar4 = FUN_001da9a8(&uStack_28);
  if ((int)((ulonglong)uVar4 >> 0x20) == -1) {
    iVar1 = param_1 + 0xc;
    if (0xf < *(uint *)(param_1 + 0x20)) {
      iVar1 = *(int *)(param_1 + 0xc);
    }
    puVar3 = (undefined4 *)FUN_00442914();
    FUN_0005e784(0,3,10,0xd4f894,0x66305c,0x12a,0xd4ff64,iVar1,*puVar3);
  }
  else {
    iVar1 = FUN_00176130(*(undefined4 *)(*(int *)(param_1 + 0x3d0) + 0x3d8),(int)uVar4,uStack_28,
                         uStack_24,param_2,param_3 + 2,aiStack_20);
    if (iVar1 != -1) {
      if (aiStack_20[0] != 0) {
        FUN_001da9f0();
      }
      *param_3 = uStack_28;
      param_3[1] = uStack_24;
      uVar2 = FUN_001da960(1);
      return uVar2;
    }
    if (*param_2 == '\0') {
      iVar1 = param_1 + 0xc;
      if (0xf < *(uint *)(param_1 + 0x20)) {
        iVar1 = *(int *)(param_1 + 0xc);
      }
      puVar3 = (undefined4 *)FUN_00442914();
      FUN_0005e784(0,3,10,0xd4f894,0x66305c,0x134,0xd4ff84,iVar1,*puVar3);
    }
  }
  return 0xffffffff;
}

