/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004a1e1c  name=FUN_004a1e1c  size=304  xrefs=24
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_004a1e1c(int *param_1,undefined4 param_2,undefined4 param_3)

{
  int iVar1;
  undefined4 uVar2;
  undefined4 uVar3;
  code *pcVar4;
  
  if (((param_1 == (int *)0x0) || (*param_1 == 0)) || (*(int *)(*param_1 + 0x14) == 0)) {
    uVar2 = 0x79;
    uVar3 = 0xfb;
  }
  else {
    pcVar4 = (code *)param_1[1];
    if ((pcVar4 != reset_vector) && (iVar1 = (*pcVar4)(param_1,5,param_2,param_3,0,1), iVar1 < 1)) {
      return iVar1;
    }
    if (param_1[3] != 0) {
      iVar1 = (**(code **)(*param_1 + 0x14))(param_1,param_2,param_3);
      if (pcVar4 == reset_vector) {
        return iVar1;
      }
      iVar1 = (*pcVar4)(param_1,0x85,param_2,param_3,0,iVar1);
      return iVar1;
    }
    uVar2 = 0x78;
    uVar3 = 0x107;
  }
  FUN_004a6438(0x20,0x68,uVar2,0xd726a8,uVar3);
  return -2;
}

