/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0046820c  name=FUN_0046820c  size=112  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0046820c(undefined4 *param_1)

{
  int iVar1;
  
  FUN_0045b580(param_1[4]);
  if (param_1[2] == 0) {
    FUN_0045b580(param_1[1]);
  }
  else if ((param_1[2] == 1) && (iVar1 = FUN_0044f9fc(*param_1), iVar1 != 0)) {
    return 0xffffffff;
  }
  return 0;
}

