/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004685f4  name=FUN_004685f4  size=16  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_004685f4(undefined4 param_1)

{
  uRam00e299b0 = param_1;
  return 0;
}

