/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005bf290  name=FUN_005bf290  size=204  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined8 FUN_005bf290(uint param_1,int param_2,int param_3,int param_4)

{
  bool bVar1;
  bool bVar2;
  undefined8 uVar3;
  
  bVar1 = param_1 < 0x80000000;
  if (!bVar1) {
    bVar2 = param_2 != 0;
    param_2 = -param_2;
    param_1 = -(bVar2 + param_1);
  }
  bVar2 = 0 < param_3;
  if (param_3 == 0) {
    bVar2 = param_4 != 0;
  }
  if (!bVar2) {
    if (param_3 == 0 && param_4 == 0) {
      if (bVar1) {
        uVar3 = 0x7fffffffffffffff;
      }
      else {
        uVar3 = 0x8000000000000000;
      }
      goto LAB_005bf340;
    }
    bVar2 = param_4 != 0;
    param_4 = -param_4;
    param_3 = -((uint)bVar2 + param_3);
  }
  uVar3 = FUN_005bf0f0(param_1,param_2,param_3,param_4);
  if (!bVar1) {
    uVar3 = CONCAT44(-((uint)((int)uVar3 != 0) + (int)((ulonglong)uVar3 >> 0x20)),-(int)uVar3);
  }
LAB_005bf340:
  return CONCAT44((int)uVar3,(int)((ulonglong)uVar3 >> 0x20));
}

