/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002c68e4  name=FUN_002c68e4  size=128  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002c68e4(void)

{
  int iVar1;
  undefined8 uVar2;
  undefined1 auStack_18 [12];
  
  FUN_0039c824(auStack_18);
  FUN_0039ba44(auStack_18);
  iVar1 = FUN_0039bc24();
  uVar2 = FUN_00373dd0();
  if (iVar1 < 0) {
    uVar2 = FUN_00373370((int)((ulonglong)uVar2 >> 0x20),(int)uVar2,0x41f00000,0);
  }
  FUN_00373704((int)((ulonglong)uVar2 >> 0x20),(int)uVar2,0x408f4000,0);
  return;
}

