/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x000000dc  name=FUN_000000dc  size=12  xrefs=405
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_000000dc(undefined4 *param_1)

{
  enforceInOrderExecutionIO();
  return *param_1;
}

