/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002f76e0  name=FUN_002f76e0  size=336  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_002f76e0(int param_1,int param_2,undefined4 param_3,int param_4,int param_5)

{
  int iVar1;
  int *piVar2;
  
  iVar1 = FUN_005accf4(*(undefined4 *)(param_1 + 0x1ac),0xffffffff);
  if (iVar1 == -1) {
    FUN_00443f20(0xd5ee98,1,2,3,4,5,6);
  }
  *(undefined1 *)(param_1 + 0x1b0) = 0;
  iVar1 = FUN_005ad104(*(undefined4 *)(param_1 + 0x1ac));
  if (iVar1 == -1) {
    FUN_00443f20(0xd5ee98,1,2,3,4,5,6);
  }
  piVar2 = (int *)FUN_00248640(0x14);
  *piVar2 = param_1;
  iVar1 = FUN_00258c6c(param_2,param_3);
  piVar2[1] = iVar1;
  piVar2[2] = param_4;
  piVar2[3] = param_5;
  piVar2[4] = param_2;
  FUN_002c77ac(param_1 + 0x18c,0x308450,piVar2,0,0xd61208);
  if (*(int *)(param_1 + 0x1a8) != 0) {
    FUN_002c7d20();
  }
  return 1;
}

