/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002e1088  name=FUN_002e1088  size=92  xrefs=4
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_002e1088(int param_1,uint param_2,int param_3)

{
  uint uVar1;
  int iVar2;
  int iVar3;
  
  param_3 = param_3 + -1;
  iVar2 = 0;
  if (-1 < param_3) {
    do {
      iVar3 = iVar2 + param_3 >> 1;
      uVar1 = (uint)*(ushort *)(iVar3 * 2 + param_1);
      if (param_2 == uVar1) {
        return 1;
      }
      if (param_2 < uVar1) {
        param_3 = iVar3 + -1;
      }
      else {
        iVar2 = iVar3 + 1;
      }
    } while (iVar2 <= param_3);
  }
  return 0;
}

