/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003bf91c  name=FUN_003bf91c  size=96  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_003bf91c(int param_1,int *param_2,int param_3)

{
  code *pcVar1;
  
  pcVar1 = *(code **)(*(int *)(*(int *)(*(int *)(iRam00e9c6a4 + 4) + *param_2 * 4) + 0x3c) + 0x3c);
  if (pcVar1 != reset_vector) {
    (*pcVar1)(*(undefined4 *)(param_1 + 8),param_2[2],*(undefined4 *)(param_3 + 8));
  }
  return;
}

