/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00206ee8  name=FUN_00206ee8  size=1880  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00206ee8(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4,
                 undefined4 param_5,undefined4 param_6)

{
  undefined8 uVar1;
  int iVar2;
  undefined4 uVar3;
  int *piVar4;
  int iVar5;
  byte in_cr0;
  byte in_cr1;
  byte unaff_cr2;
  byte unaff_cr3;
  byte unaff_cr4;
  byte in_cr5;
  byte in_cr6;
  byte in_cr7;
  undefined8 uVar6;
  undefined8 uVar7;
  undefined1 auStack_458 [1024];
  int aiStack_58 [5];
  uint uStack_44;
  
  uStack_44 = (uint)(in_cr0 & 0xf) << 0x1c | (uint)(in_cr1 & 0xf) << 0x18 |
              (uint)(unaff_cr2 & 0xf) << 0x14 | (uint)(unaff_cr3 & 0xf) << 0x10 |
              (uint)(unaff_cr4 & 0xf) << 0xc | (uint)(in_cr5 & 0xf) << 8 | (uint)(in_cr6 & 0xf) << 4
              | (uint)(in_cr7 & 0xf);
  FUN_003cb350(0xd599cc,param_1);
  uVar7 = 0;
  uVar1 = 0x40f869ffd70a3d71;
  iVar5 = 0;
  piVar4 = aiStack_58;
  do {
    FUN_003cada0(auStack_458,0x400,0xd599d8,param_1,iVar5);
    iVar2 = FUN_001abc80(auStack_458,1,0,1,param_2,param_3);
    *piVar4 = iVar2;
    iVar5 = iVar5 + 1;
    piVar4 = piVar4 + 1;
    if (iVar2 == 0) {
      uVar3 = FUN_00442920();
      FUN_0005da9c(1,0xd59ad0,uVar3);
      return;
    }
    uVar6 = FUN_00373dd0();
    if (iVar2 < 0) {
      uVar6 = FUN_00373370((int)((ulonglong)uVar6 >> 0x20),(int)uVar6,0x41f00000,0);
    }
    uVar6 = FUN_003739c0((int)((ulonglong)uVar6 >> 0x20),(int)uVar6,0x412e8480,0);
    uVar3 = (undefined4)((ulonglong)uVar6 >> 0x20);
    iVar2 = FUN_0037443c((int)((ulonglong)uVar1 >> 0x20),(int)uVar1,uVar3,(int)uVar6);
    if (0 < iVar2) {
      uVar1 = uVar6;
    }
    uVar7 = FUN_00373370((int)((ulonglong)uVar7 >> 0x20),(int)uVar7,uVar3,(int)uVar6);
  } while (iVar5 < 3);
  uVar7 = FUN_003739c0((int)((ulonglong)uVar7 >> 0x20),(int)uVar7,&MMIO_40080000,0);
  iVar5 = FUN_00377f7c((int)((ulonglong)uVar7 >> 0x20),(int)uVar7,param_5,param_6);
  if (iVar5 < 0) {
LAB_002075b8:
    uVar3 = 1;
  }
  else {
    iVar5 = FUN_00377f7c((int)((ulonglong)uVar1 >> 0x20),(int)uVar1,param_5,param_6);
    uVar3 = 0;
    if (iVar5 < 0) goto LAB_002075b8;
  }
  FUN_0005da9c(uVar3,0xd599e0,3);
  uVar7 = 0;
  uVar1 = 0x40f869ffd70a3d71;
  iVar5 = 0;
  piVar4 = aiStack_58;
  do {
    FUN_003cada0(auStack_458,0x400,0xd599d8,param_1,iVar5);
    iVar2 = FUN_001abcc0(auStack_458,1,0,1,param_2,param_3);
    *piVar4 = iVar2;
    iVar5 = iVar5 + 1;
    piVar4 = piVar4 + 1;
    if (iVar2 == 0) {
      uVar3 = FUN_00442920();
      FUN_0005da9c(1,0xd59af8,uVar3);
      return;
    }
    uVar6 = FUN_00373dd0();
    if (iVar2 < 0) {
      uVar6 = FUN_00373370((int)((ulonglong)uVar6 >> 0x20),(int)uVar6,0x41f00000,0);
    }
    uVar6 = FUN_003739c0((int)((ulonglong)uVar6 >> 0x20),(int)uVar6,0x412e8480,0);
    uVar3 = (undefined4)((ulonglong)uVar6 >> 0x20);
    iVar2 = FUN_0037443c((int)((ulonglong)uVar1 >> 0x20),(int)uVar1,uVar3,(int)uVar6);
    if (0 < iVar2) {
      uVar1 = uVar6;
    }
    uVar7 = FUN_00373370((int)((ulonglong)uVar7 >> 0x20),(int)uVar7,uVar3,(int)uVar6);
  } while (iVar5 < 3);
  uVar7 = FUN_003739c0((int)((ulonglong)uVar7 >> 0x20),(int)uVar7,&MMIO_40080000,0);
  iVar5 = FUN_00377f7c((int)((ulonglong)uVar7 >> 0x20),(int)uVar7,param_5,param_6);
  if (iVar5 < 0) {
LAB_002075c0:
    uVar3 = 1;
  }
  else {
    iVar5 = FUN_00377f7c((int)((ulonglong)uVar1 >> 0x20),(int)uVar1,param_5,param_6);
    uVar3 = 0;
    if (iVar5 < 0) goto LAB_002075c0;
  }
  FUN_0005da9c(uVar3,0xd59a1c,3);
  iVar5 = 0;
  do {
    FUN_003cada0(auStack_458,0x400,0xd599d8,param_1,iVar5);
    iVar5 = iVar5 + 1;
    FUN_0044ed80(auStack_458);
  } while (iVar5 < 3);
  uVar7 = 0;
  uVar1 = 0x40f869ffd70a3d71;
  iVar5 = 0;
  piVar4 = aiStack_58;
  do {
    FUN_003cada0(auStack_458,0x400,0xd599d8,param_1,iVar5);
    iVar2 = FUN_001abd00(auStack_458,1,1,1,param_2,param_3);
    *piVar4 = iVar2;
    iVar5 = iVar5 + 1;
    piVar4 = piVar4 + 1;
    if (iVar2 == 0) {
      uVar3 = FUN_00442920();
      FUN_0005da9c(1,0xd59b1c,uVar3);
      return;
    }
    uVar6 = FUN_00373dd0();
    if (iVar2 < 0) {
      uVar6 = FUN_00373370((int)((ulonglong)uVar6 >> 0x20),(int)uVar6,0x41f00000,0);
    }
    uVar6 = FUN_003739c0((int)((ulonglong)uVar6 >> 0x20),(int)uVar6,0x412e8480,0);
    uVar3 = (undefined4)((ulonglong)uVar6 >> 0x20);
    iVar2 = FUN_0037443c((int)((ulonglong)uVar1 >> 0x20),(int)uVar1,uVar3,(int)uVar6);
    if (0 < iVar2) {
      uVar1 = uVar6;
    }
    uVar7 = FUN_00373370((int)((ulonglong)uVar7 >> 0x20),(int)uVar7,uVar3,(int)uVar6);
  } while (iVar5 < 3);
  uVar7 = FUN_003739c0((int)((ulonglong)uVar7 >> 0x20),(int)uVar7,&MMIO_40080000,0);
  iVar5 = FUN_00377f7c((int)((ulonglong)uVar7 >> 0x20),(int)uVar7,param_5,param_6);
  if (iVar5 < 0) {
LAB_002075c8:
    uVar3 = 1;
  }
  else {
    iVar5 = FUN_00377f7c((int)((ulonglong)uVar1 >> 0x20),(int)uVar1,param_5,param_6);
    uVar3 = 0;
    if (iVar5 < 0) goto LAB_002075c8;
  }
  FUN_0005da9c(uVar3,0xd59a58,3);
  piVar4 = aiStack_58;
  uVar7 = 0;
  uVar1 = 0x40f869ffd70a3d71;
  iVar5 = 0;
  do {
    FUN_003cada0(auStack_458,0x400,0xd599d8,param_1,iVar5);
    iVar2 = FUN_001abcc0(auStack_458,1,1,1,param_2,param_3);
    *piVar4 = iVar2;
    iVar5 = iVar5 + 1;
    piVar4 = piVar4 + 1;
    if (iVar2 == 0) {
      uVar3 = FUN_00442920();
      FUN_0005da9c(1,0xd59b3c,uVar3);
      return;
    }
    uVar6 = FUN_00373dd0();
    if (iVar2 < 0) {
      uVar6 = FUN_00373370((int)((ulonglong)uVar6 >> 0x20),(int)uVar6,0x41f00000,0);
    }
    uVar6 = FUN_003739c0((int)((ulonglong)uVar6 >> 0x20),(int)uVar6,0x412e8480,0);
    uVar3 = (undefined4)((ulonglong)uVar6 >> 0x20);
    iVar2 = FUN_0037443c((int)((ulonglong)uVar1 >> 0x20),(int)uVar1,uVar3,(int)uVar6);
    if (0 < iVar2) {
      uVar1 = uVar6;
    }
    uVar7 = FUN_00373370((int)((ulonglong)uVar7 >> 0x20),(int)uVar7,uVar3,(int)uVar6);
  } while (iVar5 < 3);
  uVar7 = FUN_003739c0((int)((ulonglong)uVar7 >> 0x20),(int)uVar7,&MMIO_40080000,0);
  uVar6 = FUN_0037336c(param_5,param_6,0x40140000,0);
  uVar3 = (undefined4)((ulonglong)uVar6 >> 0x20);
  iVar5 = FUN_0037443c(uVar3,(int)uVar6,(int)((ulonglong)uVar7 >> 0x20),(int)uVar7);
  if (iVar5 < 1) {
    iVar5 = FUN_0037443c(uVar3,(int)uVar6,(int)((ulonglong)uVar1 >> 0x20),(int)uVar1);
    uVar3 = 0;
    if (iVar5 < 1) goto LAB_002074ec;
  }
  uVar3 = 1;
LAB_002074ec:
  FUN_0005da9c(uVar3,0xd59a94,3);
  iVar5 = 0;
  do {
    FUN_003cada0(auStack_458,0x400,0xd599d8,param_1,iVar5);
    iVar5 = iVar5 + 1;
    FUN_0044ed80(auStack_458);
  } while (iVar5 < 3);
  return;
}

