/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0000d5d0  name=FUN_0000d5d0  size=84  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0000d5d0(undefined4 param_1,undefined4 param_2)

{
  int iVar1;
  
  iVar1 = FUN_0000d350(0xd33c18,param_2,6,0x200);
  if (iVar1 == 0) {
    return;
  }
  FUN_003cb350(0xd33d38);
  return;
}

