/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0019427c  name=FUN_0019427c  size=204  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0019427c(void)

{
  undefined4 uVar1;
  
  uVar1 = 0;
  if (iRam00e129b4 == 0) {
    iRam00ea2030 = FUN_001d91b4();
    uVar1 = 0xffffffff;
    if (iRam00ea2030 != 0) {
      iRam00e129b0 = FUN_0044f4cc(0xd38cf8,2,0x1b6);
      if (iRam00e129b0 != -1) {
        iRam00e129b4 = 1;
        FUN_0044e510();
        return 0;
      }
      FUN_001d91d8(iRam00ea2030,0x69000001,0x16);
      uVar1 = 0xffffffff;
    }
  }
  return uVar1;
}

