/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0028973c  name=FUN_0028973c  size=152  xrefs=9
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_0028973c(int param_1)

{
  int iVar1;
  int iVar2;
  
  iVar2 = *(int *)(param_1 + 0x10);
  if (iVar2 == 0) {
    if (((*(int *)(param_1 + 0x18) == 0) && (*(int *)(param_1 + 0x1c) != 0)) &&
       (iVar2 = *(int *)(*(int *)(param_1 + 0x1c) + 0x38), iVar2 != 0)) {
      *(undefined4 *)(param_1 + 0x18) = *(undefined4 *)(iVar2 + 0x29c);
    }
    iVar2 = FUN_00248640(0x1c);
    FUN_00289364(iVar2,*(undefined4 *)(param_1 + 0x18),param_1,0);
    iVar1 = *(int *)(iVar2 + 8);
    *(int *)(param_1 + 0x10) = iVar2;
    *(int *)(iVar2 + 8) = iVar1 + 1;
  }
  return iVar2;
}

