/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00383dfc  name=FUN_00383dfc  size=188  xrefs=6
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


byte * FUN_00383dfc(byte *param_1,int *param_2,undefined4 param_3)

{
  bool bVar1;
  uint uVar2;
  int iVar3;
  
  iVar3 = 0;
  uVar2 = (uint)*param_1;
  bVar1 = uVar2 == 0x6e;
  if (bVar1) {
    param_1 = param_1 + 1;
    uVar2 = (uint)*param_1;
  }
  if ((*(byte *)(uVar2 + iRam00e272d8) & 4) == 0) {
    FUN_0038029c(param_3);
  }
  else {
    do {
      iVar3 = iVar3 * 10 + uVar2;
      param_1 = param_1 + 1;
      uVar2 = (uint)*param_1;
      iVar3 = iVar3 + -0x30;
    } while ((*(byte *)(uVar2 + iRam00e272d8) & 4) != 0);
  }
  if (bVar1) {
    iVar3 = -iVar3;
  }
  *param_2 = iVar3;
  return param_1;
}

