/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005c6f54  name=FUN_005c6f54  size=32  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_005c6f54(void)

{
  FUN_005de568();
  return;
}

