/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001fae5c  name=FUN_001fae5c  size=188  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_001fae5c(undefined4 *param_1)

{
  undefined1 auStack_48 [4];
  undefined4 uStack_44;
  undefined4 uStack_30;
  undefined4 uStack_2c;
  undefined1 *puStack_28;
  undefined4 uStack_24;
  undefined1 *puStack_20;
  undefined1 *puStack_1c;
  undefined4 *puStack_14;
  undefined4 uStack_10;
  
  puStack_1c = &stack0xffffffb0;
  uStack_30 = 0x25710c;
  puStack_28 = auStack_48;
  uStack_2c = 0xe9aba8;
  uStack_24 = 0x20af18;
  puStack_20 = (undefined1 *)register0x00000004;
  puStack_14 = param_1;
  FUN_003d1214(puStack_28);
  FUN_001f66c0(puStack_14,0x746d6364);
  *puStack_14 = 0xe094b0;
  uStack_44 = 2;
  uStack_10 = FUN_00248640(0x48);
  uStack_44 = 1;
  FUN_001fa1b8();
  uStack_44 = 2;
  FUN_001fadb8(puStack_14,uStack_10);
  FUN_003d12b8(auStack_48);
  return;
}

