/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0058f084  name=FUN_0058f084  size=1476  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0058f084(int *param_1)

{
  undefined4 uVar1;
  char cVar2;
  int *piVar3;
  byte bVar4;
  byte bVar5;
  int iVar6;
  undefined4 *puVar7;
  
  if (param_1 == (int *)0x0) {
    uVar1 = 0xfffffff9;
  }
  else {
    if (*param_1 == 0) {
      for (bVar5 = 0; bVar5 < 8; bVar5 = bVar5 + 1) {
        puVar7 = *(undefined4 **)((uint)bVar5 * 0x24 + 0xfc833c);
        while (puVar7 != (undefined4 *)0x0) {
          if (*(char *)(puVar7 + 4) == -1) {
            puVar7 = (undefined4 *)puVar7[0xd];
          }
          else if ((*(char *)(puVar7 + 4) == '\t') && (*(short *)(param_1 + 1) == 9)) {
            if (*(char *)((int)puVar7 + 5) == '\x01') {
              (**(code **)(iRam00e3a6d4 + 8))
                        (*puVar7,*(undefined1 *)((int)puVar7 + 6),*(undefined1 *)(puVar7 + 1));
            }
            else {
              cVar2 = (*(code *)param_1[3])(*puVar7,0,*(undefined1 *)(puVar7 + 1),puVar7 + 8);
              if (cVar2 == '\0') {
                FUN_005accf4(*(undefined4 *)((uint)*(byte *)((int)puVar7 + 6) * 0x24 + 0xfc8338),
                             0xffffffff);
                piVar3 = (int *)((uint)*(byte *)((int)puVar7 + 6) * 0x24 + 0xfc8334);
                *piVar3 = *piVar3 + 1;
                FUN_005ad104(*(undefined4 *)((uint)*(byte *)((int)puVar7 + 6) * 0x24 + 0xfc8338));
                puVar7[7] = param_1;
              }
            }
            puVar7 = (undefined4 *)puVar7[0xd];
          }
          else if (*(char *)(puVar7 + 4) == '\0') {
            if (*(char *)(puVar7 + 4) == '\0') {
              iVar6 = puVar7[0xc];
              for (bVar4 = 0; bVar4 < *(byte *)((int)puVar7 + 0x25); bVar4 = bVar4 + 1) {
                if (((((ushort)*(byte *)(iVar6 + (uint)bVar4 * 0x14 + 3) == *(ushort *)(param_1 + 1)
                      ) && ((*(short *)((int)param_1 + 6) == -1 ||
                            ((ushort)*(byte *)(iVar6 + (uint)bVar4 * 0x14 + 4) ==
                             *(ushort *)((int)param_1 + 6))))) &&
                    ((*(short *)(param_1 + 2) == -1 ||
                     ((ushort)*(byte *)(iVar6 + (uint)bVar4 * 0x14 + 5) == *(ushort *)(param_1 + 2))
                     ))) && (cVar2 = (*(code *)param_1[3])
                                               (*puVar7,*(undefined1 *)(iVar6 + (uint)bVar4 * 0x14),
                                                *(undefined1 *)(puVar7 + 1),
                                                iVar6 + (uint)bVar4 * 0x14 + 0xc), cVar2 == '\0')) {
                  FUN_005accf4(*(undefined4 *)((uint)*(byte *)((int)puVar7 + 6) * 0x24 + 0xfc8338),
                               0xffffffff);
                  piVar3 = (int *)((uint)*(byte *)((int)puVar7 + 6) * 0x24 + 0xfc8334);
                  *piVar3 = *piVar3 + 1;
                  FUN_005ad104(*(undefined4 *)((uint)*(byte *)((int)puVar7 + 6) * 0x24 + 0xfc8338));
                  *(int **)(iVar6 + (uint)bVar4 * 0x14 + 8) = param_1;
                }
              }
            }
            puVar7 = (undefined4 *)puVar7[0xd];
          }
          else if ((((ushort)*(byte *)(puVar7 + 4) == *(ushort *)(param_1 + 1)) &&
                   ((*(short *)((int)param_1 + 6) == -1 ||
                    ((ushort)*(byte *)((int)puVar7 + 0x11) == *(ushort *)((int)param_1 + 6))))) &&
                  ((*(short *)(param_1 + 2) == -1 ||
                   ((ushort)*(byte *)((int)puVar7 + 0x12) == *(ushort *)(param_1 + 2))))) {
            cVar2 = (*(code *)param_1[3])(*puVar7,0,*(undefined1 *)(puVar7 + 1),puVar7 + 8);
            if (cVar2 == '\0') {
              FUN_005accf4(*(undefined4 *)((uint)*(byte *)((int)puVar7 + 6) * 0x24 + 0xfc8338),
                           0xffffffff);
              piVar3 = (int *)((uint)*(byte *)((int)puVar7 + 6) * 0x24 + 0xfc8334);
              *piVar3 = *piVar3 + 1;
              FUN_005ad104(*(undefined4 *)((uint)*(byte *)((int)puVar7 + 6) * 0x24 + 0xfc8338));
              puVar7[7] = param_1;
            }
            puVar7 = (undefined4 *)puVar7[0xd];
          }
          else {
            puVar7 = (undefined4 *)puVar7[0xd];
          }
        }
      }
    }
    else {
      for (bVar5 = 0; bVar5 < 8; bVar5 = bVar5 + 1) {
        puVar7 = *(undefined4 **)((uint)bVar5 * 0x24 + 0xfc833c);
        while (puVar7 != (undefined4 *)0x0) {
          if (*(char *)(puVar7 + 4) == -1) {
            if ((((*(short *)(puVar7 + 6) == *(short *)(param_1 + 2)) &&
                 (*(short *)(puVar7 + 5) == *(short *)(param_1 + 1))) &&
                (*(short *)((int)puVar7 + 0x16) == *(short *)((int)param_1 + 6))) &&
               (cVar2 = (*(code *)param_1[3])(*puVar7,0,*(undefined1 *)(puVar7 + 1),puVar7 + 8),
               cVar2 == '\0')) {
              FUN_005accf4(*(undefined4 *)((uint)*(byte *)((int)puVar7 + 6) * 0x24 + 0xfc8338),
                           0xffffffff);
              piVar3 = (int *)((uint)*(byte *)((int)puVar7 + 6) * 0x24 + 0xfc8334);
              *piVar3 = *piVar3 + 1;
              FUN_005ad104(*(undefined4 *)((uint)*(byte *)((int)puVar7 + 6) * 0x24 + 0xfc8338));
              puVar7[7] = param_1;
            }
            puVar7 = (undefined4 *)puVar7[0xd];
          }
          else {
            iVar6 = puVar7[0xc];
            for (bVar4 = 0; bVar4 < *(byte *)((int)puVar7 + 0x25); bVar4 = bVar4 + 1) {
              if (((*(char *)(iVar6 + (uint)bVar4 * 0x14 + 3) == -1) &&
                  (*(short *)(puVar7 + 5) == *(short *)(param_1 + 1))) &&
                 ((*(short *)((int)puVar7 + 0x16) == *(short *)((int)param_1 + 6) &&
                  ((*(short *)(puVar7 + 6) == *(short *)(param_1 + 2) &&
                   (cVar2 = (*(code *)param_1[3])
                                      (*puVar7,*(undefined1 *)(iVar6 + (uint)bVar4 * 0x14),
                                       *(undefined1 *)(puVar7 + 1),iVar6 + (uint)bVar4 * 0x14 + 0xc)
                   , cVar2 == '\0')))))) {
                FUN_005accf4(*(undefined4 *)((uint)*(byte *)((int)puVar7 + 6) * 0x24 + 0xfc8338),
                             0xffffffff);
                piVar3 = (int *)((uint)*(byte *)((int)puVar7 + 6) * 0x24 + 0xfc8334);
                *piVar3 = *piVar3 + 1;
                FUN_005ad104(*(undefined4 *)((uint)*(byte *)((int)puVar7 + 6) * 0x24 + 0xfc8338));
                *(int **)(iVar6 + (uint)bVar4 * 0x14 + 8) = param_1;
              }
            }
            puVar7 = (undefined4 *)puVar7[0xd];
          }
        }
      }
    }
    uVar1 = 0;
  }
  return uVar1;
}

