/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0037e660  name=FUN_0037e660  size=64  xrefs=5
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


char FUN_0037e660(int *param_1)

{
  char cVar1;
  char *pcVar2;
  
  cVar1 = *(char *)param_1[1];
  pcVar2 = (char *)param_1[1] + 1;
  if (cVar1 != '\0') {
    if (pcVar2 == (char *)(*param_1 + 0x100)) {
      param_1[1] = *param_1;
    }
    else {
      param_1[1] = (int)pcVar2;
    }
  }
  return cVar1;
}

