/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002ea448  name=FUN_002ea448  size=132  xrefs=57
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_002ea448(int param_1)

{
  int iVar1;
  undefined4 uVar2;
  int iVar3;
  
  iVar3 = *(int *)(param_1 + 0x20);
  if (((iVar3 == 0) || (*(int *)(iVar3 + 0x10) == 0)) ||
     (iVar1 = *(int *)(*(int *)(iVar3 + 0x10) + 4), iVar1 == 0)) {
    if ((iVar3 == 0) || (*(int *)(iVar3 + 0x20) == 0)) {
      if (*(int *)(param_1 + 0x28) == 0) {
        return 7;
      }
      uVar2 = FUN_002a79e8();
      return uVar2;
    }
    iVar1 = *(int *)(*(int *)(iVar3 + 0x20) + 0x38);
  }
  uVar2 = FUN_002811a4(iVar1);
  return uVar2;
}

