/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0031a720  name=FUN_0031a720  size=92  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0031a720(int param_1)

{
  undefined4 uVar1;
  int iVar2;
  
  iVar2 = *(int *)(param_1 + 0x198);
  if (*(int *)(param_1 + 0x134) < 2) {
    if (*(uint *)(param_1 + 0x90) < *(int *)(param_1 + 300) - 1U) {
      uVar1 = *(undefined4 *)(*(int *)(param_1 + 0x138) + 0xc);
    }
    else {
      uVar1 = *(undefined4 *)(*(int *)(param_1 + 0x138) + 0x48);
    }
  }
  else {
    uVar1 = 1;
  }
  *(undefined4 *)(iVar2 + 0x1c) = uVar1;
  *(undefined4 *)(iVar2 + 0x18) = 0;
  *(undefined4 *)(iVar2 + 0x14) = 0;
  return;
}

