/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002f3b0c  name=FUN_002f3b0c  size=156  xrefs=7
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002f3b0c(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  int iVar1;
  
  iVar1 = FUN_00377ed4(param_3,param_4,0,0);
  if (iVar1 == 0) {
    FUN_002f3898();
    return;
  }
  FUN_003768e8(param_1,param_2,param_3,param_4);
  return;
}

