/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001328dc  name=FUN_001328dc  size=224  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_001328dc(int param_1,int param_2)

{
  int iVar1;
  int iVar2;
  char *pcVar3;
  
  pcVar3 = *(char **)(param_1 + 0x10c);
  iVar2 = -1;
  if (((*(int *)(pcVar3 + 4) != 0) && (*(int *)(pcVar3 + 0x10) != 0)) && (*pcVar3 != '\0')) {
    iVar1 = FUN_001da174();
    param_2 = param_2 * 1000;
    *pcVar3 = '\x01' - (iVar1 == 0);
    if (iVar1 == 0) {
      pcVar3 = *(char **)(param_1 + 0x10c);
      *(int *)(param_1 + 4) = param_2;
      if (((*(int *)(pcVar3 + 4) != 0) && (*(int *)(pcVar3 + 0x10) != 0)) && (*pcVar3 == '\0')) {
        *(int *)(pcVar3 + 8) = param_2;
        iVar2 = FUN_001da0bc(*(int *)(pcVar3 + 4),param_2,*(int *)(pcVar3 + 0x10),
                             *(undefined4 *)(pcVar3 + 0xc));
        *pcVar3 = iVar2 == 0;
      }
    }
  }
  return iVar2;
}

