/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003968cc  name=FUN_003968cc  size=20  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


byte FUN_003968cc(int param_1)

{
  return *(byte *)(iRam00e272d8 + param_1) & 3;
}

