/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003b7a34  name=FUN_003b7a34  size=276  xrefs=5
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_003b7a34(int param_1,undefined4 *param_2,int param_3,undefined4 *param_4,int param_5)

{
  undefined4 uVar1;
  undefined4 *puVar2;
  int iVar3;
  undefined4 *puVar4;
  
  puVar2 = param_2;
  iVar3 = param_3;
  if (param_3 < param_5) {
    puVar2 = param_4;
    param_4 = param_2;
    iVar3 = param_5;
    param_5 = param_3;
  }
  puVar4 = (undefined4 *)(param_1 + iVar3 * 4);
  if (param_5 < 1) {
    FUN_003ae2c8(param_1,puVar2,iVar3,0);
  }
  else {
    uVar1 = FUN_003ae2c8(param_1,puVar2,iVar3,*param_4);
    *puVar4 = uVar1;
    for (param_5 = param_5 + -1; 0 < param_5; param_5 = param_5 + -4) {
      uVar1 = FUN_003ae084(param_1 + 4,puVar2,iVar3,param_4[1]);
      puVar4[1] = uVar1;
      if (param_5 + -1 < 1) {
        return;
      }
      uVar1 = FUN_003ae084(param_1 + 8,puVar2,iVar3,param_4[2]);
      puVar4[2] = uVar1;
      if (param_5 + -2 < 1) {
        return;
      }
      uVar1 = FUN_003ae084(param_1 + 0xc,puVar2,iVar3,param_4[3]);
      puVar4[3] = uVar1;
      if (param_5 + -3 < 1) {
        return;
      }
      param_4 = param_4 + 4;
      uVar1 = FUN_003ae084(param_1 + 0x10,puVar2,iVar3,*param_4);
      puVar4 = puVar4 + 4;
      *puVar4 = uVar1;
      param_1 = param_1 + 0x10;
    }
  }
  return;
}

