/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002d68c8  name=FUN_002d68c8  size=852  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002d68c8(int *param_1)

{
  int iVar1;
  int iVar2;
  undefined4 uVar3;
  uint uVar4;
  int iVar5;
  int iVar6;
  int *piVar7;
  int *piVar8;
  int iVar9;
  undefined8 uVar10;
  undefined8 uVar11;
  undefined4 uStack_a0;
  undefined4 uStack_9c;
  undefined1 auStack_90 [48];
  undefined1 auStack_60 [16];
  undefined1 auStack_50 [16];
  int aiStack_40 [4];
  
  piVar7 = param_1 + 6;
  iVar9 = *param_1;
  piVar8 = *(int **)(iVar9 + 0x16f8);
  FUN_0028773c(piVar7,0);
  iVar1 = param_1[2];
  iVar6 = 0;
  iVar5 = 0;
  if (1 < iVar1) {
    aiStack_40[0] = 0;
    iVar6 = FUN_002a2d04(*param_1,param_1 + 10);
    uVar10 = FUN_002a3484(*param_1,param_1[3],0);
    uVar11 = FUN_002a3484(*param_1,param_1[3] + 0x10,0);
    iVar1 = 0;
    if (2 < param_1[2]) {
      iVar1 = FUN_002a29c4(*param_1,param_1[3] + 0x20);
    }
    iVar2 = FUN_00290a5c(iVar9,param_1[1],iVar6,0);
    if (iVar2 == 0) goto LAB_002d693c;
    FUN_00373704((int)((ulonglong)uVar10 >> 0x20),(int)uVar10,&MMIO_40340000,0);
    uStack_a0 = FUN_00374010();
    FUN_00373704((int)((ulonglong)uVar11 >> 0x20),(int)uVar11,&MMIO_40340000,0);
    uStack_9c = FUN_00374010();
    if (iVar1 == 0) {
      FUN_00294cc4(iVar9,*(undefined4 *)(iVar9 + 0x80),&uStack_a0,0);
      FUN_00294b4c(iVar9,*(undefined4 *)(iVar2 + 0x78),auStack_60,0);
      uVar4 = FUN_002f49b4(auStack_60,&uStack_a0);
    }
    else {
      FUN_00294cc4(iVar9,*(undefined4 *)(iVar9 + 0x80),&uStack_a0,1);
      FUN_003070d4(iVar9 + 0x720,&uStack_a0);
      FUN_00275198(*(undefined4 *)(iVar2 + 0x78),*(undefined4 *)(iVar2 + 0x78),auStack_90);
      FUN_00275a70(*(undefined4 *)(iVar2 + 0x78),aiStack_40,auStack_90,&uStack_a0,1,0);
      uVar4 = (uint)(aiStack_40[0] != 0);
    }
    FUN_0028773c(piVar7,uVar4);
    iVar1 = param_1[2];
  }
  if (iVar1 == 1) {
    iVar6 = FUN_002a2d04(*param_1,param_1 + 10);
    iVar5 = FUN_002a2d04(*param_1,param_1[3]);
    iVar1 = FUN_00290a5c(iVar9,param_1[1],iVar6,0);
    iVar2 = FUN_00290a5c(iVar9,param_1[1],iVar5,0);
    if (iVar1 != 0 && iVar2 != 0) {
      FUN_00294b4c(iVar9,*(undefined4 *)(iVar1 + 0x78),auStack_60,0);
      FUN_00294b4c(iVar9,*(undefined4 *)(iVar2 + 0x78),auStack_50,0);
      uVar3 = FUN_002f494c(auStack_50,auStack_60);
      FUN_0028773c(piVar7,uVar3);
    }
  }
LAB_002d693c:
  if (iVar6 != 0 && piVar8 != (int *)0x0) {
    (**(code **)(*piVar8 + 0x14))(piVar8,iVar6);
  }
  if (iVar5 != 0 && piVar8 != (int *)0x0) {
    (**(code **)(*piVar8 + 0x14))(piVar8,iVar5);
  }
  return;
}

