/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00349098  name=FUN_00349098  size=196  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00349098(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4,
                 undefined4 param_5)

{
  FUN_0034c004(0x72,0x15,0xe,1,param_1);
  FUN_0034c004(0x72,0x16,0x30,4,param_3);
  FUN_0034c004(0x72,0x16,0xc,2,param_2);
  FUN_0034c004(0x72,0x16,2,1,param_4);
  FUN_0034c004(0x72,0x16,1,0,param_5);
  return;
}

