/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005d0644  name=FUN_005d0644  size=292  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_005d0644(undefined4 param_1,undefined4 param_2,int param_3,undefined4 param_4,int param_5,
                undefined4 param_6)

{
  int iVar1;
  int iVar2;
  
  iVar1 = FUN_004c89a0(param_2);
  if (iVar1 == 0) {
    return 0;
  }
  if ((param_3 != 0) && (iVar2 = FUN_005d0358(iVar1,param_3), iVar2 == 0)) {
    return 0;
  }
  if (param_5 == -1) {
    iVar2 = FUN_004cf40c(iVar1);
  }
  else {
    iVar2 = FUN_004cf480(param_5,param_6,0xffffffff,0,0,param_4,iVar1);
    FUN_004cd5a4(iVar1);
  }
  if (iVar2 != 0) {
    iVar1 = FUN_005d0580(param_1,iVar2);
    if (iVar1 != 0) {
      return iVar2;
    }
    FUN_004cfc80(iVar2);
  }
  return 0;
}

