/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0063b9b4  name=FUN_0063b9b4  size=812  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0063b9b4(int *param_1,int *param_2,undefined4 param_3)

{
  char cVar1;
  int iVar2;
  undefined4 uVar3;
  undefined4 uVar4;
  int iVar5;
  int iVar6;
  int *piStack_70;
  int iStack_6c;
  int iStack_68;
  undefined4 uStack_64;
  int *piStack_60;
  int iStack_5c;
  undefined4 uStack_58;
  undefined4 uStack_54;
  char acStack_50 [40];
  
  piStack_70 = (int *)param_2[0x5be];
  iStack_6c = 0;
  iStack_68 = 0;
  uStack_64 = 0;
  iVar2 = (**(code **)(*param_2 + 0x1c))(param_2);
  if (iVar2 != 0) {
    uVar3 = (**(code **)(*param_2 + 0x1c))(param_2);
    uVar4 = FUN_002811a4(param_2 + 2);
    FUN_002c5448(uVar3,&piStack_70,uVar4);
  }
  iVar2 = iStack_6c;
  iVar6 = 0;
  piStack_60 = (int *)param_2[0x5be];
  uStack_54 = 0;
  iStack_5c = 0;
  uStack_58 = 0;
  if (0 < iStack_68) {
    do {
      if (*(char *)(iVar2 + iVar6) == ' ') {
        FUN_00257f34(&piStack_60,0xd5fcf4);
      }
      else {
        FUN_00257d18(&piStack_60,*(char *)(iVar2 + iVar6));
      }
      iVar6 = iVar6 + 1;
    } while (iVar6 < iStack_68);
  }
  iVar2 = *(int *)(param_2[0x59a] + 0x800);
  *(bool *)(param_1 + 5) = *(int *)(param_2[0x59a] + 0x7fc) == 1;
  *(bool *)((int)param_1 + 0x15) = iVar2 == 1;
  iVar2 = 0;
  cVar1 = *(char *)*param_1;
  iVar6 = 0;
  while (cVar1 != '\0') {
    if (cVar1 == ' ') {
      iVar5 = iVar6 + 3;
      acStack_50[iVar6] = '%';
      acStack_50[iVar6 + 1] = '2';
      acStack_50[iVar6 + 2] = '0';
    }
    else if (cVar1 == ',') {
      iVar5 = iVar6 + 3;
      acStack_50[iVar6] = '%';
      acStack_50[iVar6 + 1] = '2';
      acStack_50[iVar6 + 2] = 'C';
    }
    else {
      iVar5 = iVar6 + 1;
      acStack_50[iVar6] = cVar1;
    }
    iVar2 = iVar2 + 1;
    iVar6 = iVar5;
    cVar1 = *(char *)(*param_1 + iVar2);
  }
  acStack_50[iVar6] = '\0';
  iVar2 = iStack_5c;
  if (iStack_5c == 0) {
    iVar2 = 0xd6f55c;
  }
  FUN_00258eb8(param_3,0xd5fcf8,*(undefined1 *)(param_1 + 1),*(undefined1 *)((int)param_1 + 5),
               *(undefined1 *)((int)param_1 + 6),*(undefined1 *)((int)param_1 + 7),
               *(undefined1 *)(param_1 + 2),*(undefined1 *)((int)param_1 + 9),
               *(undefined1 *)((int)param_1 + 10),*(undefined1 *)((int)param_1 + 0xb),
               *(undefined1 *)(param_1 + 3),*(undefined1 *)((int)param_1 + 0xd),
               *(undefined1 *)((int)param_1 + 0xe),*(undefined1 *)((int)param_1 + 0xf),acStack_50,
               iVar2,param_1[4],*(undefined1 *)(param_1 + 5),*(undefined1 *)((int)param_1 + 0x15),
               *(undefined1 *)((int)param_1 + 0x16));
  if (iStack_5c != 0 && piStack_60 != (int *)0x0) {
    (**(code **)(*piStack_60 + 0x14))();
  }
  if (iStack_6c != 0 && piStack_70 != (int *)0x0) {
    (**(code **)(*piStack_70 + 0x14))();
  }
  return;
}

