/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00307bd4  name=FUN_00307bd4  size=56  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00307bd4(undefined4 *param_1)

{
  int iVar1;
  
  if ((param_1[3] != 6) && (iVar1 = param_1[7], param_1[7] = iVar1 + 1, iVar1 + 1 == 1)) {
    param_1[1] = *param_1;
  }
  return;
}

