/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0041d640  name=FUN_0041d640  size=68  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0041d640(void)

{
  undefined4 auStack_8 [2];
  
  iRam00e9c4e8 = iRam00e9c4e8 + 1;
  FUN_0041d544(iRam00e9c4e8);
  FUN_0041d110(auStack_8,4);
  return auStack_8[0];
}

