/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0039d0a4  name=FUN_0039d0a4  size=116  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0039d0a4(void)

{
  undefined4 *puVar1;
  undefined4 uVar2;
  
  puVar1 = puRam00e9c6a4;
  uRam00e9c528 = 0;
  uRam00e9c4d8 = 0;
  uRam00e9c5b0 = 0;
  *puRam00e9c6a4 = 10;
  uVar2 = FUN_0039efe4(0x28);
  puVar1[1] = uVar2;
  FUN_0039cd58(0x3b9400,0xe9c528);
  return;
}

