/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004c903c  name=FUN_004c903c  size=96  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


uint FUN_004c903c(int *param_1,uint param_2)

{
  int iVar1;
  uint uVar2;
  
  iVar1 = ((int)param_2 >> 3) + (uint)((int)param_2 < 0 && (param_2 & 7) != 0);
  uVar2 = 0;
  if (((param_1 != (int *)0x0) && (iVar1 + 1 <= *param_1)) && (param_1[2] != 0)) {
    uVar2 = -((uint)*(byte *)(param_1[2] + iVar1) & 1 << (~param_2 & 7)) >> 0x1f;
  }
  return uVar2;
}

