/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x000a8138  name=FUN_000a8138  size=376  xrefs=6
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_000a8138(int param_1,int param_2)

{
  bool bVar1;
  uint uVar2;
  int iVar3;
  uint uVar4;
  int iVar5;
  int iVar6;
  uint uVar7;
  uint uVar8;
  int iVar9;
  
  iVar6 = *(int *)(param_1 + 0xf0);
  iVar9 = *(int *)(param_1 + 0xec);
  if (iVar9 != iVar6) {
    uVar2 = *(uint *)(param_2 + 0x18);
    do {
      uVar8 = *(uint *)(iVar9 + 0x14);
      if (uVar2 < 0x10) {
        iVar5 = param_2 + 4;
      }
      else {
        iVar5 = *(int *)(param_2 + 4);
      }
      uVar7 = *(uint *)(param_2 + 0x14);
      if (uVar8 == 0) {
LAB_000a81d0:
        uVar4 = (uint)(uVar8 != uVar7);
        if (uVar8 < uVar7) {
          uVar4 = 0xffffffff;
        }
      }
      else {
        iVar3 = iVar9 + 4;
        if (0xf < *(uint *)(iVar9 + 0x18)) {
          iVar3 = *(int *)(iVar9 + 4);
        }
        uVar4 = uVar7;
        if (uVar8 < uVar7) {
          uVar4 = uVar8;
        }
        uVar4 = FUN_0039ac2c(iVar3,iVar5,uVar4);
        if (uVar4 == 0) goto LAB_000a81d0;
      }
    } while ((uVar4 != 0) && (iVar9 = iVar9 + 0x1c, iVar9 != iVar6));
  }
  if (iVar9 != *(int *)(param_1 + 0xf0)) {
    iVar6 = FUN_005fbc34(param_1 + 0xf8,iVar9);
    bVar1 = false;
    if ((iVar6 != *(int *)(param_1 + 0xfc)) && (*(int *)(*(int *)(iVar6 + 0x28) + 0x5c) != 0)) {
      bVar1 = true;
    }
    if (bVar1) {
      *(undefined1 *)(*(int *)(iVar6 + 0x28) + 4) =
           *(undefined1 *)(*(int *)(*(int *)(iVar6 + 0x28) + 0x5c) + 1);
      FUN_000a6dd8(param_1,param_2,0);
    }
  }
  return;
}

