/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005db3c8  name=FUN_005db3c8  size=320  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_005db3c8(int *param_1,undefined4 *param_2)

{
  int iVar1;
  int iVar2;
  undefined4 uVar3;
  undefined4 uVar4;
  
  FUN_004b09c8();
  iVar1 = FUN_004a18ac();
  if (iVar1 == 0) {
    uVar3 = 0x20;
    uVar4 = 0x6f;
  }
  else {
    FUN_004ab970(*param_2);
    FUN_004ab358();
    iVar2 = FUN_004aff1c();
    if (iVar2 != 0) {
      FUN_004a1ff0(iVar1,0x6f,0,iVar2);
      if (*param_1 == 0) {
        *param_1 = iVar1;
      }
      else {
        iVar2 = FUN_004a2314(*param_1,iVar1);
        if (iVar2 == 0) {
          uVar3 = 0x20;
          uVar4 = 0x7f;
          goto LAB_005db4ac;
        }
      }
      return 1;
    }
    uVar3 = 0x6d;
    uVar4 = 0x76;
  }
LAB_005db4ac:
  FUN_004a6438(0x21,0x7d,uVar3,0xd94c64,uVar4);
  if (iVar1 != 0) {
    FUN_004a193c(iVar1);
  }
  return 0;
}

