/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00460598  name=FUN_00460598  size=176  xrefs=13
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4
FUN_00460598(undefined4 param_1,int param_2,undefined4 param_3,int param_4,undefined4 param_5,
            undefined4 param_6)

{
  undefined4 uVar1;
  int iVar2;
  undefined1 auStack_18 [16];
  
  if (param_2 - 2U < 0xb) {
    iVar2 = FUN_00460498(0,param_1,param_2,param_3,param_4,param_5,param_6,auStack_18);
    uVar1 = 0;
    if (iVar2 != 0) {
      FUN_00442990();
      if (iVar2 != 0xc) {
        return 0xffffffff;
      }
      uVar1 = 0xffffffff;
    }
    if (param_4 != 0) {
      FUN_0036c8ac(auStack_18,param_4,4);
    }
  }
  else {
    FUN_00442990(0x16);
    uVar1 = 0xffffffff;
  }
  return uVar1;
}

