/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0035785c  name=FUN_0035785c  size=68  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


uint FUN_0035785c(int param_1,int param_2)

{
  return ((uint)((ulonglong)(uint)((param_2 + 100) * (0xe297d / param_1)) * 0x51eb851f >> 0x20) &
         0x1fffe0) << 0xb | (uint)((100 - param_2) * (0xe297d / param_1)) / 100;
}

