/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005b842c  name=FUN_005b842c  size=56  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_005b842c(uint *param_1)

{
  if (((*param_1 & 0xfc000001) != 0x48000001) && ((*param_1 & 0xfc000001) != 0x40000001)) {
    return 0;
  }
  return 1;
}

