/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002c0870  name=FUN_002c0870  size=212  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_002c0870(undefined4 param_1,char *param_2,int param_3,int param_4)

{
  char cVar1;
  int iVar2;
  undefined4 uVar3;
  
  while( true ) {
    cVar1 = *param_2;
    if (((cVar1 == '\0') || (cVar1 != ' ' && cVar1 != '=')) || (param_4 <= (int)param_2 - param_3))
    break;
    param_2 = param_2 + 1;
  }
  uVar3 = 0;
  if (((cVar1 != '\0') && ((int)param_2 - param_3 < param_4)) &&
     ((cVar1 == '1' ||
      ((iVar2 = FUN_0039b188(param_2,0xd3c1d0,4), iVar2 == 0 ||
       (iVar2 = FUN_0039b188(param_2,0xd3f98c,3), iVar2 == 0)))))) {
    uVar3 = 1;
  }
  return uVar3;
}

