/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0036932c  name=FUN_0036932c  size=52  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0036932c(void)

{
  FUN_003d97c0();
  FUN_003e6f5c();
  FUN_003e8148();
  FUN_003e6f98();
  FUN_003e7bfc();
  FUN_003daccc();
  return;
}

