/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0022fb38  name=FUN_0022fb38  size=1468  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_0022fb38(int param_1,int *param_2)

{
  int iVar1;
  bool bVar2;
  undefined4 ***pppuVar3;
  undefined1 *puVar4;
  undefined1 auStack_e8 [8];
  undefined4 uStack_e0;
  undefined4 uStack_dc;
  undefined1 uStack_d8;
  undefined1 auStack_d4 [4];
  undefined4 **appuStack_d0 [4];
  uint uStack_c0;
  uint uStack_bc;
  undefined1 auStack_b8 [4];
  undefined4 **appuStack_b4 [4];
  int iStack_a4;
  uint uStack_a0;
  undefined1 auStack_9c [4];
  undefined1 auStack_98 [16];
  undefined4 uStack_88;
  undefined4 uStack_84;
  undefined1 auStack_70 [4];
  undefined4 uStack_6c;
  undefined4 uStack_58;
  undefined4 uStack_54;
  undefined1 *puStack_50;
  undefined4 uStack_4c;
  undefined1 *puStack_48;
  undefined1 *puStack_44;
  int iStack_3c;
  int *piStack_38;
  int iStack_30;
  undefined1 *puStack_2c;
  int iStack_28;
  int iStack_24;
  undefined1 *puStack_20;
  int iStack_1c;
  int iStack_18;
  uint uStack_14;
  uint uStack_10;
  
  puStack_44 = &stack0xffffff10;
  uStack_58 = 0x25710c;
  puStack_50 = auStack_e8;
  uStack_54 = 0xe9b3d8;
  uStack_4c = 0x23ff78;
  puStack_48 = (undefined1 *)register0x00000004;
  iStack_3c = param_1;
  piStack_38 = param_2;
  FUN_003d1214(auStack_70);
  uStack_e0 = 0xe0a028;
  uStack_dc = 0;
  uStack_d8 = 0;
  FUN_005e8e80(auStack_d4);
  uStack_a0 = 0xf;
  appuStack_b4[0] = (undefined4 **)((uint)appuStack_b4[0] & 0xffffff);
  iStack_a4 = 0;
  iStack_30 = FUN_0039b0f0(uRam00d9541c);
  uStack_6c = 3;
  iVar1 = FUN_005f0030(auStack_b8,iStack_30,0);
  if (iVar1 != 0) {
    pppuVar3 = appuStack_b4;
    if (0xf < uStack_a0) {
      pppuVar3 = (undefined4 ***)appuStack_b4[0];
    }
    FUN_0039ac74(pppuVar3,uRam00d9541c,iStack_30);
    pppuVar3 = appuStack_b4;
    if (0xf < uStack_a0) {
      pppuVar3 = (undefined4 ***)appuStack_b4[0];
    }
    iStack_a4 = iStack_30;
    *(undefined1 *)((int)pppuVar3 + iStack_30) = 0;
  }
  puStack_2c = auStack_9c;
  uStack_84 = 0xf;
  auStack_98[0] = 0;
  uStack_88 = 0;
  iStack_28 = FUN_0039b0f0(uRam00d95420);
  uStack_6c = 2;
  iVar1 = FUN_005f0030(puStack_2c,iStack_28,0);
  if (iVar1 != 0) {
    puVar4 = auStack_98;
    if (0xf < *(uint *)(puStack_2c + 0x18)) {
      puVar4 = *(undefined1 **)(puStack_2c + 4);
    }
    FUN_0039ac74(puVar4,uRam00d95420,iStack_28);
    iVar1 = iStack_28;
    puVar4 = puStack_2c + 4;
    if (0xf < *(uint *)(puStack_2c + 0x18)) {
      puVar4 = *(undefined1 **)(puStack_2c + 4);
    }
    *(int *)(puStack_2c + 0x14) = iStack_28;
    puVar4[iVar1] = 0;
  }
  iStack_24 = FUN_0039b0f0(pppuRam00d95424);
  pppuVar3 = appuStack_b4;
  if (0xf < uStack_a0) {
    pppuVar3 = (undefined4 ***)appuStack_b4[0];
  }
  if (pppuRam00d95424 < pppuVar3) {
LAB_00230070:
    bVar2 = false;
  }
  else {
    pppuVar3 = appuStack_b4;
    if (0xf < uStack_a0) {
      pppuVar3 = (undefined4 ***)appuStack_b4[0];
    }
    bVar2 = true;
    if ((undefined4 ***)((int)pppuVar3 + iStack_a4) <= pppuRam00d95424) goto LAB_00230070;
  }
  if (bVar2) {
    pppuVar3 = appuStack_b4;
    if (0xf < uStack_a0) {
      pppuVar3 = (undefined4 ***)appuStack_b4[0];
    }
    uStack_6c = 1;
    FUN_005ea15c(auStack_b8,auStack_b8,0xd6f55c - (int)pppuVar3,iStack_24);
  }
  else {
    uStack_6c = 1;
    iVar1 = FUN_005f0030(auStack_b8,iStack_24,0);
    if (iVar1 != 0) {
      pppuVar3 = appuStack_b4;
      if (0xf < uStack_a0) {
        pppuVar3 = (undefined4 ***)appuStack_b4[0];
      }
      FUN_0039ac74(pppuVar3,pppuRam00d95424,iStack_24);
      pppuVar3 = appuStack_b4;
      if (0xf < uStack_a0) {
        pppuVar3 = (undefined4 ***)appuStack_b4[0];
      }
      iStack_a4 = iStack_24;
      *(undefined1 *)((int)pppuVar3 + iStack_24) = 0;
    }
  }
  puStack_20 = auStack_9c;
  iStack_1c = FUN_0039b0f0(pppuRam00d95424);
  pppuVar3 = (undefined4 ***)auStack_98;
  if (0xf < *(uint *)(puStack_20 + 0x18)) {
    pppuVar3 = *(undefined4 ****)(puStack_20 + 4);
  }
  if (pppuVar3 <= pppuRam00d95424) {
    puVar4 = puStack_20 + 4;
    if (0xf < *(uint *)(puStack_20 + 0x18)) {
      puVar4 = *(undefined1 **)(puStack_20 + 4);
    }
    bVar2 = true;
    if (pppuRam00d95424 < puVar4 + *(int *)(puStack_20 + 0x14)) goto LAB_0022fd78;
  }
  bVar2 = false;
LAB_0022fd78:
  if (bVar2) {
    puVar4 = puStack_20 + 4;
    if (0xf < *(uint *)(puStack_20 + 0x18)) {
      puVar4 = *(undefined1 **)(puStack_20 + 4);
    }
    uStack_6c = 1;
    FUN_005ea15c(puStack_20,puStack_20,0xd6f55c - (int)puVar4,iStack_1c);
  }
  else {
    uStack_6c = 1;
    iVar1 = FUN_005f0030(puStack_20,iStack_1c,0);
    if (iVar1 != 0) {
      puVar4 = puStack_20 + 4;
      if (0xf < *(uint *)(puStack_20 + 0x18)) {
        puVar4 = *(undefined1 **)(puStack_20 + 4);
      }
      FUN_0039ac74(puVar4,pppuRam00d95424,iStack_1c);
      iVar1 = iStack_1c;
      puVar4 = puStack_20 + 4;
      if (0xf < *(uint *)(puStack_20 + 0x18)) {
        puVar4 = *(undefined1 **)(puStack_20 + 4);
      }
      *(int *)(puStack_20 + 0x14) = iStack_1c;
      puVar4[iVar1] = 0;
    }
  }
  uStack_6c = 1;
  (**(code **)(*piStack_38 + 0x44))(piStack_38,&uStack_e0);
  uStack_10 = uStack_c0;
  uStack_14 = 0xffffffff;
  iStack_18 = iStack_3c;
  if (uStack_c0 != 0xffffffff) {
    uStack_14 = uStack_c0;
  }
  if (~*(uint *)(iStack_3c + 0x14) <= uStack_14) {
    uStack_6c = 1;
    FUN_002513e0(iStack_3c);
  }
  if (uStack_14 != 0) {
    uStack_10 = *(int *)(iStack_3c + 0x14) + uStack_14;
    uStack_6c = 1;
    iVar1 = FUN_005f0030(iStack_3c,uStack_10,0);
    if (iVar1 != 0) {
      iVar1 = iStack_3c + 4;
      if (0xf < *(uint *)(iStack_3c + 0x18)) {
        iVar1 = *(int *)(iStack_3c + 4);
      }
      pppuVar3 = appuStack_d0;
      if (0xf < uStack_bc) {
        pppuVar3 = (undefined4 ***)appuStack_d0[0];
      }
      FUN_0039ac74(iVar1 + *(int *)(iStack_18 + 0x14),pppuVar3,uStack_14);
      iVar1 = iStack_18 + 4;
      if (0xf < *(uint *)(iStack_18 + 0x18)) {
        iVar1 = *(int *)(iStack_18 + 4);
      }
      *(uint *)(iStack_18 + 0x14) = uStack_10;
      *(undefined1 *)(iVar1 + uStack_10) = 0;
    }
  }
  uStack_e0 = 0xe0a028;
  FUN_005e75e4(auStack_9c,1,0);
  FUN_005e75e4(auStack_b8,1,0);
  FUN_005e75e4(auStack_d4,1,0);
  uStack_e0 = 0xe08328;
  FUN_003d12b8(auStack_70);
  return iStack_3c;
}

