/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005fae2c  name=FUN_005fae2c  size=648  xrefs=6
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


/* WARNING: Removing unreachable block (ram,0x005fb070) */
/* WARNING: Removing unreachable block (ram,0x005fb100) */
/* WARNING: Removing unreachable block (ram,0x005fb104) */
/* WARNING: Removing unreachable block (ram,0x005fb114) */
/* WARNING: Removing unreachable block (ram,0x005fb080) */
/* WARNING: Removing unreachable block (ram,0x005fb088) */

undefined4 * FUN_005fae2c(undefined4 param_1)

{
  undefined1 auStack_e8 [8];
  undefined4 uStack_e0;
  int iStack_d0;
  undefined1 auStack_c0 [64];
  undefined4 uStack_80;
  undefined4 uStack_7c;
  undefined4 uStack_70;
  undefined4 uStack_6c;
  undefined4 *puStack_60;
  undefined4 *puStack_5c;
  undefined1 auStack_50 [4];
  undefined4 uStack_4c;
  undefined4 uStack_38;
  undefined4 uStack_34;
  undefined1 *puStack_30;
  undefined4 uStack_2c;
  undefined1 *puStack_28;
  undefined1 *puStack_24;
  undefined4 *puStack_1c;
  undefined4 uStack_18;
  undefined4 *puStack_14;
  undefined4 *puStack_10;
  undefined4 *puStack_c;
  undefined4 *puStack_8;
  
  puStack_24 = &stack0xffffff10;
  uStack_38 = 0x25710c;
  puStack_30 = auStack_e8;
  uStack_34 = 0xe973b1;
  uStack_2c = 0x60af4c;
  puStack_28 = (undefined1 *)register0x00000004;
  uStack_18 = param_1;
  FUN_003d1214(auStack_50);
  uStack_e0 = 0;
  uStack_4c = 0xffffffff;
  FUN_002521d8(0);
  puStack_1c = puRam00e960c8;
  if (iRam00ef92c4 == 0) {
    iStack_d0 = iRam00ef92c4;
    uStack_4c = 3;
    FUN_002521d8(0);
    if (iRam00ef92c4 == 0) {
      iRam00ef92c4 = iRam00ef92c8 + 1;
      iRam00ef92c8 = iRam00ef92c4;
    }
    uStack_4c = 3;
    FUN_0025224c(iStack_d0);
  }
  uStack_4c = 3;
  puStack_14 = (undefined4 *)FUN_0024dbd8(uStack_18,iRam00ef92c4);
  if (puStack_14 == (undefined4 *)0x0) {
    if (puStack_1c == (undefined4 *)0x0) {
      uStack_4c = 3;
      puStack_10 = (undefined4 *)FUN_00248640(0x10);
      *puStack_10 = 0xe082a0;
      puStack_10[1] = puStack_14;
      uStack_4c = 2;
      puStack_c = puStack_10;
      FUN_0024e4a4(auStack_c0,0xd91f1c);
      puStack_5c = puStack_14;
      uStack_4c = 1;
      puStack_60 = puStack_14;
      puStack_8 = puStack_10;
      uStack_80 = FUN_0025193c();
      puStack_5c = (undefined4 *)0x1;
      uStack_6c = 1;
      uStack_7c = 1;
      puStack_8[3] = 1;
      puStack_8[2] = uStack_80;
      uStack_4c = 2;
      uStack_70 = uStack_80;
      puStack_60 = (undefined4 *)uStack_80;
      FUN_0024dd04(auStack_c0);
      puStack_1c = puStack_10;
      puStack_14 = puStack_10;
      puRam00e960c8 = puStack_10;
      iStack_d0 = 0;
      uStack_4c = 3;
      FUN_002521d8(0);
      if (puStack_14[1] != -1) {
        puStack_14[1] = puStack_14[1] + 1;
      }
      uStack_4c = 3;
      FUN_0025224c(iStack_d0);
      FUN_0024dc70(puStack_14);
    }
    else {
      puStack_14 = puStack_1c;
    }
  }
  uStack_4c = 0xffffffff;
  FUN_0025224c(uStack_e0);
  FUN_003d12b8(auStack_50);
  return puStack_14;
}

