/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005ac874  name=FUN_005ac874  size=376  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_005ac874(uint param_1,int *param_2,int param_3)

{
  uint *puVar1;
  int iVar2;
  undefined4 uVar3;
  int iVar4;
  uint uVar5;
  
  if (iRam00e2942c < 1) {
    if ((param_1 & 1) == 0) {
      uVar3 = FUN_0036fd0c();
      iVar2 = FUN_005bad5c(param_1,uRam00e3a7c8);
      if (iVar2 != 0) {
        FUN_0036fd24(uVar3);
        return -1;
      }
      iVar2 = (**(code **)(*(int *)(param_1 + 0x50) + 0x30))(param_1 + 0x44,param_2,param_3);
      if ((*(char *)(param_1 + 0x40) == '\x04') && (0 < param_3 - iVar2)) {
        iVar4 = (**(code **)(*(int *)(*(int *)(param_1 + 0x68) + 0x20) + 0x30))
                          (*(int *)(param_1 + 0x68) + 0x14,param_2 + iVar2);
        iVar2 = iVar4 + iVar2;
        if (0 < param_3 - iVar2) {
          iVar4 = (**(code **)(*(int *)(*(int *)(param_1 + 0x68) + 0x10) + 0x30))
                            (*(int *)(param_1 + 0x68) + 4,param_2 + iVar2);
          iVar2 = iVar4 + iVar2;
        }
      }
      FUN_0036fd24(uVar3);
      if (param_2 == (int *)0x0) {
        return iVar2;
      }
      iVar4 = iVar2;
      if (iVar2 < 1) {
        return iVar2;
      }
      do {
        *param_2 = *param_2 + -0x40;
        param_2 = param_2 + 1;
        iVar4 = iVar4 + -1;
      } while (iVar4 != 0);
      return iVar2;
    }
    if (pcRam00e9c6bc != reset_vector) {
      iVar2 = (*pcRam00e9c6bc)(param_1 + iRam00e9c4e4);
      return iVar2;
    }
    uVar5 = 0x580000;
  }
  else {
    uVar5 = 0x430000;
  }
  puVar1 = (uint *)FUN_00442914();
  *puVar1 = uVar5 | 1;
  return -1;
}

