/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0043b52c  name=FUN_0043b52c  size=144  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0043b52c(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  *(undefined4 *)(param_1 + 0x590) = param_3;
  *(undefined4 *)(param_1 + 0x588) = *(undefined4 *)(param_1 + 8);
  *(undefined4 *)(param_1 + 0x594) = param_4;
  *(undefined4 *)(param_1 + 0x5a0) = 0;
  *(undefined4 *)(param_1 + 0x598) = *(undefined4 *)(param_1 + 0x2c);
  *(undefined4 *)(param_1 + 0x5a4) = 0;
  *(undefined4 *)(param_1 + 0x5a8) = 1;
  *(undefined4 *)(param_1 + 0x5ac) = 0x44b524;
  *(undefined4 *)(param_1 + 0x5b0) = *(undefined4 *)(param_1 + 4);
  *(undefined4 *)(param_1 + 0x5b4) = 0;
  FUN_005b80c8(*(undefined4 *)(param_1 + 8),(undefined4 *)(param_1 + 0x588));
  FUN_005accf4(*(undefined4 *)(param_1 + 4),0xffffffff);
  return *(undefined4 *)(param_1 + 0x5a4);
}

