/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002fc7c8  name=FUN_002fc7c8  size=152  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_002fc7c8(undefined4 *param_1,undefined4 param_2)

{
  uint uVar1;
  undefined4 uVar2;
  uint uVar3;
  undefined1 auStack_20 [4];
  uint *puStack_1c;
  
  FUN_002fa38c(auStack_20,param_1 + 1,param_2);
  uVar2 = FUN_002a29c4(*param_1,auStack_20);
  FUN_002875f0(auStack_20);
  if (puStack_1c != (uint *)0x0) {
    uVar1 = *puStack_1c;
    uVar3 = ((int)(uVar1 << 1 | uVar1 >> 0x1f) >> 1) - 1;
    *puStack_1c = uVar3 & 0x7fffffff | uVar1 & 0x80000000;
    if ((int)(uVar3 * 2) < 1) {
      FUN_0028a778(puStack_1c);
    }
  }
  return uVar2;
}

