/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0047bf44  name=FUN_0047bf44  size=88  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0047bf44(int param_1)

{
  int iVar1;
  undefined4 uVar2;
  
  if (param_1 == 0) {
    param_1 = FUN_0047bb68(0);
  }
  iVar1 = FUN_0047bbd0(param_1);
  if (iVar1 == 0) {
    uVar2 = *(undefined4 *)(param_1 + 0x414);
  }
  else {
    uVar2 = 0xffffffff;
  }
  return uVar2;
}

