/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0054f650  name=FUN_0054f650  size=16  xrefs=18
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0054f650(undefined1 *param_1,undefined4 param_2)

{
  *param_1 = (char)param_2;
  param_1[1] = (char)((uint)param_2 >> 8);
  return;
}

