/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002c7054  name=FUN_002c7054  size=44  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002c7054(undefined4 param_1,undefined4 param_2)

{
  FUN_002c7080(0,param_1,param_2);
  return;
}

