/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002900ac  name=FUN_002900ac  size=96  xrefs=4
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002900ac(int *param_1)

{
  FUN_0027f180(param_1 + 2);
  if (param_1[0x4bb] == 0) {
    FUN_00263440(param_1,0);
    (**(code **)(*param_1 + 0x50))(param_1);
  }
  return;
}

