/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0037fdc0  name=FUN_0037fdc0  size=328  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_0037fdc0(undefined4 param_1,int param_2,uint *param_3,undefined4 param_4,undefined4 param_5)

{
  bool bVar1;
  uint uVar2;
  uint uVar3;
  int iVar4;
  uint uVar5;
  int iVar6;
  int aiStack_28 [3];
  
  uVar2 = *param_3;
  iVar6 = 0;
  aiStack_28[0] = 0;
  uVar3 = uVar2;
  while( true ) {
    uVar5 = uVar3 + param_2 + 3 & 0xfffffffc;
    if (aiStack_28[0] == 0) {
      uVar5 = uVar3 + param_2;
    }
    uVar3 = (uVar5 + aiStack_28[0]) - param_2;
    if (uVar2 < uVar3) break;
    iVar4 = FUN_0037fb6c(param_1,param_2,param_3,uVar5,aiStack_28,param_4,param_5);
    bVar1 = 2 < iVar6;
    iVar6 = iVar6 + 1;
    if ((bVar1) || (iVar4 != 1)) {
      if (3 < iVar6 && iVar4 == 1) {
        return 2;
      }
      return iVar4;
    }
    uVar3 = *param_3;
  }
  *param_3 = uVar3;
  return 1;
}

