/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0058bb18  name=FUN_0058bb18  size=136  xrefs=4
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


uint FUN_0058bb18(int param_1,ushort param_2)

{
  ushort uVar1;
  uint uVar2;
  
  uVar2 = 0xffff;
  for (uVar1 = 0; uVar1 < param_2; uVar1 = uVar1 + 1) {
    uVar2 = FUN_0058ba5c(*(undefined1 *)(param_1 + (uint)uVar1),uVar2);
  }
  return (uVar2 ^ 0xffff) & 0xffff;
}

