/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004aa2e8  name=FUN_004aa2e8  size=268  xrefs=11
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_004aa2e8(int *param_1,int param_2,undefined4 param_3)

{
  int iVar1;
  int iVar2;
  
  if (*param_1 == 0) {
    iVar1 = FUN_004ac828();
    *param_1 = iVar1;
    if (iVar1 == 0) {
      FUN_004a6438(0xf,0x66,0x41,0xd72e58,0x259);
      return 0;
    }
  }
  iVar1 = FUN_004acc60();
  do {
    if (param_2 < iVar1) {
      FUN_004acccc(*param_1,param_2,param_3);
      return 1;
    }
    iVar1 = iVar1 + 1;
    iVar2 = FUN_004acae0(*param_1,0);
  } while (iVar2 != 0);
  FUN_004a6438(0xf,0x66,0x41,0xd72e58,0x263);
  return 0;
}

