/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005fb758  name=FUN_005fb758  size=324  xrefs=16
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_005fb758(undefined4 *param_1)

{
  int iVar1;
  undefined1 auStack_68 [8];
  undefined4 uStack_60;
  undefined1 auStack_50 [4];
  undefined4 uStack_4c;
  undefined4 uStack_38;
  undefined4 uStack_34;
  undefined1 *puStack_30;
  undefined4 uStack_2c;
  undefined1 *puStack_28;
  undefined1 *puStack_24;
  undefined4 *puStack_1c;
  undefined4 *puStack_18;
  int *piStack_14;
  int *piStack_10;
  
  puStack_24 = &stack0xffffff90;
  uStack_38 = 0x25710c;
  puStack_30 = auStack_68;
  uStack_34 = 0xe973e4;
  uStack_2c = 0x60b89c;
  puStack_28 = (undefined1 *)register0x00000004;
  puStack_1c = param_1;
  FUN_003d1214(auStack_50);
  puStack_18 = (undefined4 *)puStack_1c[0xe];
  *puStack_1c = 0xe08490;
  if (puStack_18 != (undefined4 *)0x0) {
    if ((int *)*puStack_18 != (int *)0x0) {
      uStack_60 = 0;
      uStack_4c = 1;
      piStack_14 = (int *)*puStack_18;
      FUN_002521d8(0);
      iVar1 = piStack_14[1];
      if ((iVar1 != 0) && (iVar1 != -1)) {
        piStack_14[1] = iVar1 + -1;
      }
      piStack_10 = piStack_14;
      if (piStack_14[1] != 0) {
        piStack_10 = (int *)0x0;
      }
      uStack_4c = 1;
      FUN_0025224c(uStack_60);
      if (piStack_10 != (int *)0x0) {
        (**(code **)(*piStack_10 + 4))(piStack_10);
      }
    }
    FUN_00245c34(puStack_18);
  }
  uStack_4c = 0xffffffff;
  FUN_00251b4c(puStack_1c + 1);
  FUN_003d12b8(auStack_50);
  return;
}

