/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002a9b8c  name=FUN_002a9b8c  size=156  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002a9b8c(int param_1)

{
  uint uVar1;
  uint uVar2;
  undefined4 uStack_20;
  uint *puStack_1c;
  undefined4 uStack_18;
  
  if (param_1 != 0) {
    uStack_20 = 6;
    puStack_1c = (uint *)0x0;
    uStack_18 = 0;
    FUN_00285e50(param_1,0xd5fc60,&uStack_20,0,0x47);
    FUN_002875f0(&uStack_20);
    if (puStack_1c != (uint *)0x0) {
      uVar1 = *puStack_1c;
      uVar2 = ((int)(uVar1 << 1 | uVar1 >> 0x1f) >> 1) - 1;
      *puStack_1c = uVar2 & 0x7fffffff | uVar1 & 0x80000000;
      if ((int)(uVar2 * 2) < 1) {
        FUN_0028a778(puStack_1c);
      }
    }
  }
  return;
}

