/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00278940  name=FUN_00278940  size=84  xrefs=8
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_00278940(undefined4 param_1,int param_2,int param_3)

{
  int iVar1;
  
  iVar1 = *(int *)(param_2 + 0xc);
  while( true ) {
    if (iVar1 == 0) {
      return 0;
    }
    if (((*(int *)(iVar1 + 0x14) == param_3) && (*(int *)(iVar1 + 0x10) != 0)) &&
       (*(char *)(*(int *)(iVar1 + 0x10) + 0xb) == '\x04')) break;
    iVar1 = *(int *)(iVar1 + 8);
  }
  return iVar1;
}

