/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002ec0f4  name=FUN_002ec0f4  size=244  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002ec0f4(int param_1,undefined4 param_2,undefined4 param_3)

{
  undefined4 uVar1;
  
  uVar1 = uRam00ef9490;
  *(undefined4 *)(param_1 + 0x38) = 6;
  *(undefined4 *)(param_1 + 0x30) = uVar1;
  *(undefined4 *)(param_1 + 0x40) = 0;
  *(undefined4 *)(param_1 + 0x3c) = 0;
  FUN_002f0e20(param_1 + 0x48);
  uVar1 = uRam00ef9490;
  *(undefined4 *)(param_1 + 0x5c) = 0;
  *(undefined4 *)(param_1 + 100) = 0;
  *(undefined4 *)(param_1 + 0x58) = 0;
  *(undefined4 *)(param_1 + 0x60) = 0;
  FUN_00318124(param_1 + 0x70,uVar1);
  uVar1 = uRam00ef9490;
  *(undefined4 *)(param_1 + 0x184) = uRam00ef9490;
  *(undefined4 *)(param_1 + 0x180) = 0;
  *(undefined4 *)(param_1 + 0x1b0) = uVar1;
  *(undefined4 *)(param_1 + 0x1bc) = 0;
  *(undefined4 *)(param_1 + 0x1b4) = 0;
  *(undefined4 *)(param_1 + 0x1b8) = 0;
  *(undefined4 *)(param_1 + 0x17c) = 0;
  FUN_002e1ea8();
  FUN_002bd7ac(param_1 + 0x1c0,uRam00ef9490);
  FUN_0031820c(param_1 + 0x1f8,param_2);
  FUN_002ec1e8(param_1,param_3,0,0);
  return;
}

