/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00299d90  name=FUN_00299d90  size=1972  xrefs=5
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00299d90(int *param_1,int param_2)

{
  bool bVar1;
  bool bVar2;
  uint uVar3;
  int iVar4;
  undefined1 *puVar5;
  int iVar6;
  int *piVar7;
  int iVar8;
  undefined4 extraout_r4;
  uint uVar9;
  int **ppiVar10;
  uint *puVar11;
  undefined4 uVar12;
  char *pcVar13;
  undefined4 *puVar14;
  undefined4 uVar15;
  int **ppiVar16;
  undefined4 *puVar17;
  byte in_cr0;
  byte in_cr1;
  byte unaff_cr2;
  byte unaff_cr3;
  byte unaff_cr4;
  byte in_cr5;
  byte in_cr6;
  byte in_cr7;
  undefined4 uStack_110;
  uint *puStack_10c;
  undefined4 uStack_108;
  undefined1 auStack_100 [16];
  undefined1 auStack_f0 [4];
  char *pcStack_ec;
  int iStack_bc;
  undefined1 auStack_b0 [64];
  int *apiStack_70 [4];
  undefined1 auStack_60 [16];
  undefined1 auStack_50 [4];
  int *apiStack_4c [4];
  int iStack_3c;
  uint uStack_30;
  
  puVar17 = (undefined4 *)param_1[0x322];
  uStack_30 = (uint)(in_cr0 & 0xf) << 0x1c | (uint)(in_cr1 & 0xf) << 0x18 |
              (uint)(unaff_cr2 & 0xf) << 0x14 | (uint)(unaff_cr3 & 0xf) << 0x10 |
              (uint)(unaff_cr4 & 0xf) << 0xc | (uint)(in_cr5 & 0xf) << 8 | (uint)(in_cr6 & 0xf) << 4
              | (uint)(in_cr7 & 0xf);
  param_1[0x322] = 0;
  param_1[0x323] = 0;
  if (puVar17 != (undefined4 *)0x0) {
    do {
      puVar14 = (undefined4 *)*puVar17;
      bVar2 = false;
      *puVar17 = 0;
      bVar1 = false;
      if ((param_2 == 0) && (puVar17[1] != 0)) {
        iVar4 = FUN_00258900(puVar17[1],0xd5f878);
        if (iVar4 != 0) {
          uVar12 = 0;
          iVar4 = FUN_00258c6c(param_1[0x5be],iVar4);
          if (iVar4 == 0) goto LAB_00299e14;
          puVar5 = (undefined1 *)FUN_00258dd0(iVar4,0x2c);
          if (puVar5 != (undefined1 *)0x0) {
            *puVar5 = 0;
            uStack_110 = 6;
            puStack_10c = (uint *)0x0;
            uStack_108 = 0;
            uVar12 = FUN_002a79e8(param_1);
            FUN_00287888(&uStack_110,param_1[0x5be],puVar5 + 1,uVar12);
            iVar6 = FUN_0029c114(param_1);
            uVar12 = 1;
            if ((((iVar6 != 0) && (param_1[0x324] != 0)) && (0 < param_1[0x326])) &&
               (0 < param_1[0x325])) {
              FUN_00287e20(param_1[0x324] + param_1[0x325] * 0x10 + -0x10,&uStack_110);
            }
            FUN_002875f0(&uStack_110);
            if (puStack_10c != (uint *)0x0) {
              uVar3 = *puStack_10c;
              uVar9 = ((int)(uVar3 << 1 | uVar3 >> 0x1f) >> 1) - 1;
              *puStack_10c = uVar9 & 0x7fffffff | uVar3 & 0x80000000;
              if ((int)(uVar9 * 2) < 1) {
                FUN_0028a778();
              }
            }
          }
          uVar15 = 0;
          iVar6 = 0;
          if ((puVar17[8] != 0) && (iVar6 = FUN_00289650(puVar17[8],0,0), iVar6 != 0)) {
            uVar15 = *(undefined4 *)(iVar6 + 0x1c);
          }
          FUN_002c3988(auStack_100,param_1,iVar6);
          iVar6 = FUN_0029f2f8(param_1,0,uVar15,iVar4,uVar12,0,0,0,0);
          if (iVar6 != 0) {
            FUN_00263440(param_1,1);
          }
          FUN_0029c2a0(param_1);
          piVar7 = (int *)param_1[0x5be];
          if (iVar4 != 0 && piVar7 != (int *)0x0) {
            (**(code **)(*piVar7 + 0x14))(piVar7,iVar4);
          }
          FUN_002c3b54(auStack_100);
          goto LAB_00299e20;
        }
        if (puVar17[2] == 0) {
          iVar4 = puVar17[7];
          if (iVar4 == 0) goto LAB_00299e14;
        }
        else {
          iVar4 = puVar17[7];
        }
        uVar3 = puVar17[6];
        iVar6 = 0;
        if (iVar4 == 0) {
          iVar4 = FUN_00290a5c(param_1,0,puVar17[2],0);
          if (iVar4 != 0) {
            iVar4 = iVar4 + 0xd8;
            goto LAB_0029a0a0;
          }
        }
        else {
LAB_0029a0a0:
          iVar6 = FUN_00289e6c(iVar4,1);
        }
        FUN_002b5b64(auStack_f0,param_1[0x5be]);
        iVar4 = FUN_002a79e8(param_1);
        if ((iVar4 < 6) || (param_1[0x599] == 0)) {
          pcVar13 = (char *)puVar17[1];
        }
        else {
          (**(code **)(*param_1 + 0x68))(auStack_b0,param_1,puVar17[1]);
          FUN_002b5e34(auStack_f0,auStack_b0);
          FUN_002b5f40(auStack_b0);
          pcVar13 = pcStack_ec;
        }
        if ((iVar6 == 0) || (*pcVar13 == '\0')) {
          iVar4 = puVar17[10];
LAB_0029a10c:
          if ((iVar4 == 0) ||
             (iVar4 = FUN_002a13f0(*(undefined4 *)(param_1[0x59a] + 8),pcVar13,iVar4,param_1,0),
             iVar4 != 0)) {
            if ((uVar3 & 0x80) == 0) {
LAB_0029a14c:
              if ((iVar6 == 0) && (iVar6 = puVar17[10], iVar6 == 0)) {
                iVar4 = FUN_002a79e8(param_1);
                iVar6 = FUN_002c32ac(param_1 + 0x4d9,param_1 + 0x74,6 < iVar4);
              }
              FUN_00299a64(param_1,puVar17,-(uVar3 & 0x80) >> 0x1f,iVar6);
              bVar2 = true;
            }
            else if (iVar6 == 0) {
              iVar6 = puVar17[10];
              if (iVar6 != 0) goto LAB_0029a14c;
            }
            else {
              iVar4 = FUN_002c1f28(iVar6);
              iVar8 = FUN_00248640(0x6c);
              FUN_002c2178(iVar8,param_1,iVar6,0x2a9b58,*(undefined4 *)(iVar6 + 4),pcVar13,
                           *(undefined4 *)(iVar6 + 4),pcVar13,(iVar4 == 0) + '\x01');
              iVar4 = param_1[0x59a];
              *(undefined4 **)(iVar8 + 0x5c) = puVar17;
              FUN_00295c58(*(undefined4 *)(iVar4 + 8),iVar8);
              bVar1 = true;
            }
          }
          else if ((puVar17[7] == 0) ||
                  ((iVar4 = *(int *)(puVar17[7] + 0x88), iVar4 != 10 && (iVar4 != 0x19)))) {
            if (puVar17[9] != 0) {
              iVar4 = 3;
              ppiVar10 = apiStack_70;
              do {
                ppiVar10[2] = (int *)0x0;
                *ppiVar10 = (int *)0x6;
                ppiVar10[1] = (int *)0x0;
                ppiVar10 = ppiVar10 + 4;
                iVar4 = iVar4 + -1;
              } while (iVar4 != 0);
              ppiVar10 = apiStack_4c + 3;
              FUN_002578f8(ppiVar10,param_1[0x5be],puVar17[2]);
              iVar4 = FUN_00290b1c(param_1,param_1[0x20],iStack_3c);
              if (iVar4 == 0) {
                FUN_002875f0(apiStack_70);
              }
              else {
                FUN_00287998(apiStack_70,iVar4);
              }
              FUN_00287888(auStack_60,param_1[0x5be],0xd5f884,7);
              FUN_002876e8(auStack_50,extraout_r4,0,0);
              FUN_002a75fc(param_1,*(undefined4 *)(puVar17[9] + 0x14),0xd5f894,apiStack_70,3,0);
              iVar4 = puVar17[9];
              if (*(int *)(iVar4 + 0x14) != 0) {
                FUN_0028497c();
                iVar4 = puVar17[9];
              }
              if (iVar4 != 0) {
                if (*(int *)(iVar4 + 8) != 0 && *(int **)(iVar4 + 4) != (int *)0x0) {
                  (**(code **)(**(int **)(iVar4 + 4) + 0x14))();
                }
                FUN_00245c34(iVar4);
              }
              puVar17[9] = 0;
              if (iStack_3c != 0 && apiStack_4c[3] != (int *)0x0) {
                (**(code **)(*apiStack_4c[3] + 0x14))();
              }
              while (ppiVar16 = ppiVar10 + -4, apiStack_70 != ppiVar10) {
                FUN_002875f0(ppiVar16);
                puVar11 = (uint *)ppiVar10[-3];
                ppiVar10 = ppiVar16;
                if (puVar11 != (uint *)0x0) {
                  uVar3 = *puVar11;
                  uVar9 = ((int)(uVar3 << 1 | uVar3 >> 0x1f) >> 1) - 1;
                  *puVar11 = uVar9 & 0x7fffffff | uVar3 & 0x80000000;
                  if ((int)(uVar9 * 2) < 1) {
                    FUN_0028a778(puVar11);
                  }
                }
              }
            }
          }
          else {
            uStack_110 = 6;
            puStack_10c = (uint *)0x0;
            uStack_108 = 0;
            iVar4 = FUN_0029c114(param_1);
            if ((((iVar4 != 0) && (param_1[0x324] != 0)) && (0 < param_1[0x326])) &&
               (0 < param_1[0x325])) {
              FUN_00287e20(param_1[0x324] + param_1[0x325] * 0x10 + -0x10,&uStack_110);
            }
            iVar4 = FUN_0029f2f8(param_1,puVar17[7],0,0xd5f5e8,1,0,0,0,0);
            if (iVar4 != 0) {
              FUN_00263440(param_1,1);
            }
            FUN_0029c2a0(param_1);
            FUN_002875f0(&uStack_110);
            if (puStack_10c != (uint *)0x0) {
              uVar3 = *puStack_10c;
              uVar9 = ((int)(uVar3 << 1 | uVar3 >> 0x1f) >> 1) - 1;
              *puStack_10c = uVar9 & 0x7fffffff | uVar3 & 0x80000000;
              if ((int)(uVar9 * 2) < 1) {
                FUN_0028a778();
              }
            }
          }
        }
        else {
          iVar4 = puVar17[10];
          if (((iVar4 == 0) || (*(int *)(iVar4 + 0x34) != 5)) || (iStack_bc != 2))
          goto LAB_0029a10c;
        }
        FUN_002b5f40(auStack_f0);
        if (!bVar1) {
          if (!bVar2) goto LAB_00299e14;
          goto LAB_00299e20;
        }
      }
      else {
LAB_00299e14:
        if (puVar17[7] != 0) {
          FUN_0028497c();
        }
LAB_00299e20:
        FUN_002a78b4(param_1[0x5be],puVar17);
        FUN_00245c34(puVar17);
      }
      puVar17 = puVar14;
    } while (puVar14 != (undefined4 *)0x0);
  }
  return;
}

