/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00512594  name=FUN_00512594  size=408  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_00512594(undefined4 param_1)

{
  uint uVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  uint uVar5;
  int iVar6;
  
  iVar4 = 0;
  uVar5 = 0xffffffff;
  iVar6 = 0;
  iVar2 = 0xfc76f0;
  do {
    uVar1 = *(uint *)(iVar2 + 0x98);
    if (uVar1 < uVar5) {
      iVar4 = iVar6;
      uVar5 = uVar1;
    }
  } while (((uVar1 == 0) || (iVar3 = FUN_0039b188(param_1,iVar2,0x80), iVar3 != 0)) &&
          (iVar6 = iVar6 + 1, iVar2 = iVar2 + 0x9c, iVar6 < 4));
  if (iVar6 == 4) {
    iRam00e379b4 = iRam00e379b4 + 1;
    iVar6 = FUN_003d8d3c(param_1);
    iVar2 = 0;
    if (iVar6 != 0) {
      uVar5 = FUN_0039b0f0(param_1);
      if (uVar5 < 0x80) {
        iVar4 = iVar4 * 0x9c;
        FUN_0039af30(iVar4 + 0xfc76f0,param_1);
        FUN_0039ac74(iVar4 + 0xfc7770,iVar6,0x18);
        *(int *)(iVar4 + 0xfc7788) = iRam00e379b4 + iRam00e379b0;
      }
      return iVar6;
    }
  }
  else {
    iRam00e379b0 = iRam00e379b0 + 1;
    *(int *)(iVar6 * 0x9c + 0xfc7788) = iRam00e379b4 + iRam00e379b0;
    iVar2 = iVar6 * 0x9c + 0xfc7770;
  }
  return iVar2;
}

