/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002f38c0  name=FUN_002f38c0  size=56  xrefs=7
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


uint FUN_002f38c0(uint param_1,uint param_2)

{
  param_2 = param_1 & 0x7fffffff ^ 0x7ff00000 | param_2;
  return (int)param_1 >> 0x1e & ~((int)(param_2 | -param_2) >> 0x1f);
}

