/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00414688  name=FUN_00414688  size=36  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00414688(int param_1)

{
  *(ushort *)(param_1 + 10) = *(ushort *)(param_1 + 10) & 0xfff5;
  *(ushort *)(param_1 + 10) = *(ushort *)(param_1 + 10) | 4;
  return;
}

