/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005fad00  name=FUN_005fad00  size=260  xrefs=19
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_005fad00(undefined4 *param_1)

{
  int iVar1;
  undefined1 auStack_58 [8];
  undefined4 uStack_50;
  undefined1 auStack_40 [4];
  undefined4 uStack_3c;
  undefined4 uStack_28;
  undefined4 uStack_24;
  undefined1 *puStack_20;
  undefined4 uStack_1c;
  undefined1 *puStack_18;
  undefined1 *puStack_14;
  undefined4 *puStack_c;
  int *piStack_8;
  int *piStack_4;
  
  puStack_14 = &stack0xffffffa0;
  uStack_28 = 0x25710c;
  puStack_20 = auStack_58;
  uStack_24 = 0xe973a4;
  uStack_1c = 0x60adf0;
  puStack_18 = (undefined1 *)register0x00000004;
  puStack_c = param_1;
  FUN_003d1214(auStack_40);
  if ((int *)*puStack_c != (int *)0x0) {
    uStack_50 = 0;
    uStack_3c = 1;
    piStack_8 = (int *)*puStack_c;
    FUN_002521d8(0);
    iVar1 = piStack_8[1];
    if ((iVar1 != 0) && (iVar1 != -1)) {
      piStack_8[1] = iVar1 + -1;
    }
    piStack_4 = piStack_8;
    if (piStack_8[1] != 0) {
      piStack_4 = (int *)0x0;
    }
    uStack_3c = 1;
    FUN_0025224c(uStack_50);
    if (piStack_4 != (int *)0x0) {
      (**(code **)(*piStack_4 + 4))(piStack_4);
    }
  }
  FUN_003d12b8(auStack_40);
  return;
}

