/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003517a4  name=FUN_003517a4  size=172  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_003517a4(int *param_1)

{
  int iVar1;
  int iVar2;
  uint uVar3;
  
  iVar1 = FUN_000000dc(0xe20001d8);
  if (iVar1 != param_1[1]) {
    iVar1 = FUN_005b4a28();
    do {
      iVar2 = FUN_0001426c(*param_1 + 0x14);
      if (iVar2 == 0) break;
      FUN_001d97d4();
      iVar2 = FUN_005b4a28();
      uVar3 = FUN_00009518();
    } while ((uint)(iVar2 - iVar1) <= uVar3 / 10);
    FUN_000000e8(0xe20001d8,param_1[1]);
  }
  return;
}

