/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00369990  name=FUN_00369990  size=36  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00369990(void)

{
  FUN_003fd818(0);
  return;
}

