/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0005ab34  name=FUN_0005ab34  size=132  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0005ab34(int param_1)

{
  int iVar1;
  undefined4 *puVar2;
  
  iVar1 = 0;
  *(undefined4 *)(param_1 + 0x60) = 0;
  do {
    for (puVar2 = *(undefined4 **)(param_1 + 0x68); puVar2 != *(undefined4 **)(param_1 + 0x6c);
        puVar2 = puVar2 + 1) {
      FUN_000587e4(*puVar2,iVar1);
      iVar1 = *(int *)(param_1 + 0x60);
    }
    iVar1 = iVar1 + 1;
    *(int *)(param_1 + 0x60) = iVar1;
  } while (iVar1 < 0xd);
  return 0;
}

