/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005a4438  name=FUN_005a4438  size=1016  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_005a4438(int param_1,int *param_2)

{
  ushort uVar1;
  uint uVar2;
  bool bVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  undefined4 uVar7;
  undefined4 uVar8;
  undefined4 *puVar9;
  undefined4 *puVar10;
  undefined4 *puVar11;
  uint uVar12;
  uint uVar13;
  int *piVar14;
  
  iVar5 = iRam00fc92d0;
  uVar8 = 0;
  puVar9 = (undefined4 *)0x0;
  puVar10 = (undefined4 *)0xfc8bc8;
  if (iRam00fc92dc == param_1) {
    iRam00fc92e0 = iRam00fc92e0 + 1;
  }
  else {
    FUN_005a4340(0xfc92d4);
    iRam00fc92dc = param_1;
  }
  if (iRam00fc92e4 == 0) {
    iVar4 = FUN_005accf4(*(undefined4 *)(iRam00e9bfe8 + 0x14),0xffffffff);
    if (iVar4 != 0) {
LAB_005a45f8:
      uVar8 = 0x504;
      goto LAB_005a45fc;
    }
    iRam00fc92e4 = *(int *)(iRam00e9bfe8 + 0x14);
  }
  iVar4 = FUN_0046984c(param_1);
  if (iVar4 == 0) {
LAB_005a45e4:
    uVar8 = 0x50f;
  }
  else {
    uVar13 = 0;
    uVar1 = *(ushort *)(param_1 + 0x530);
    bVar3 = true;
    param_2[3] = *(int *)(param_1 + 0x518);
    iVar4 = *(int *)(param_1 + 0x540);
    param_2[4] = (uint)uVar1;
    param_2[6] = iVar4;
    iVar4 = *(int *)(param_1 + 0x544);
    param_2[0x17] = 0;
    param_2[7] = iVar4;
    iVar4 = iRam00fc92e0;
    param_2[1] = 0;
    *param_2 = iVar4;
    iVar4 = *(int *)(param_1 + 0x538);
    iVar6 = *(int *)(param_1 + 0x534);
    param_2[5] = *(int *)(param_1 + 0x53c);
    param_2[9] = iVar4;
    iVar4 = 0;
    param_2[8] = iVar6;
    param_2[10] = 1;
    param_2[2] = 0;
    piVar14 = param_2;
    do {
      if (bVar3) {
        iVar4 = FUN_0046a3ac(param_1);
      }
      else {
        iVar4 = FUN_00469a54(iVar4);
      }
      uVar13 = uVar13 + 1;
      if (iVar4 == 0) goto LAB_005a45f8;
      piVar14[0xc] = *(int *)(iVar4 + 8);
      piVar14[0xd] = *(int *)(iVar4 + 0xc);
      piVar14[0xb] = *(int *)(iVar4 + 0x10);
      piVar14[0xe] = *(int *)(iVar4 + 0x14);
      iVar6 = iRam00fc92e8;
      piVar14 = piVar14 + 4;
      bVar3 = false;
    } while (uVar13 < 3);
    uVar13 = iVar5 - 0x6c;
    if (iRam00fc92e8 == 0) {
      if (iRam00fc92d8 == 0) {
        iRam00fc92d8 = *(int *)(param_1 + 0x14);
      }
      if ((*(int *)(param_1 + 4) != param_1) || (*(char *)(param_1 + 10) != 'h')) goto LAB_005a45e4;
      iVar4 = FUN_0039b0f0();
      uVar12 = iVar4 + 4U & 0xfffffffc;
      param_2[1] = iVar4 + 1;
      if (uVar13 < uVar12) {
        if (uVar13 == 0) {
          return 0;
        }
        FUN_0039ac74(0xfc8bc8,iRam00fc92d8,iVar5 + -0x6d);
        *(undefined1 *)(iVar5 + 0xfc8b5b) = 0;
        iRam00fc92d8 = iRam00fc92d8 + iVar5 + -0x6d;
        param_2[2] = 0xfc8bc8;
        return 0;
      }
      uVar13 = uVar13 - uVar12;
      param_2[2] = iRam00fc92d8;
      iRam00fc92d8 = iVar6;
      iRam00fc92e8 = 1;
    }
    if (iRam00fc92ec == 0) {
      iRam00fc92ec = FUN_0046a328(param_1);
    }
    while (iRam00fc92ec != 0) {
      if ((*(int *)(iRam00fc92ec + 4) != iRam00fc92ec) ||
         (*(char *)(*(int *)(iRam00fc92ec + 4) + 10) != 'l')) goto LAB_005a45e4;
      if (uVar13 < 0x2c) {
        return 0;
      }
      if (puVar9 == (undefined4 *)0x0) {
        param_2[0x17] = (int)puVar10;
      }
      else {
        *puVar9 = puVar10;
      }
      iVar4 = iRam00fc92ec;
      uVar12 = uVar13 - 0x2c;
      puVar10[2] = 0;
      iVar5 = iRam00fc92d4;
      uVar7 = *(undefined4 *)(iVar4 + 0x18);
      puVar10[3] = *(undefined4 *)(iVar4 + 0x20);
      puVar10[4] = uVar7;
      uVar7 = *(undefined4 *)(iVar4 + 0x1c);
      *puVar10 = 0;
      puVar10[5] = uVar7;
      uVar1 = *(ushort *)(iVar4 + 0x28);
      puVar10[6] = *(undefined4 *)(iVar4 + 0x24);
      puVar10[7] = (uint)uVar1;
      if (iVar5 == 0) {
        iRam00fc92d4 = *(int *)(iVar4 + 0x14);
      }
      iVar5 = FUN_0039b0f0();
      uVar2 = iVar5 + 4U & 0xfffffffc;
      puVar10[1] = iVar5 + 1;
      iVar5 = iRam00fc92ec;
      puVar11 = puVar10 + 8;
      if (uVar12 < uVar2) {
        if (uVar12 == 0) {
          return 0;
        }
        iVar5 = uVar13 - 0x2d;
        FUN_0039ac74(puVar11,iRam00fc92d4,iVar5);
        *(undefined1 *)((int)puVar11 + iVar5) = 0;
        puVar10[2] = puVar11;
        iRam00fc92d4 = iRam00fc92d4 + iVar5;
        return 0;
      }
      uVar13 = uVar12 - uVar2;
      puVar10[2] = iRam00fc92d4;
      iRam00fc92d4 = 0;
      iRam00fc92ec = FUN_0046a8f0(iVar5);
      puVar9 = puVar10;
      puVar10 = puVar11;
    }
    param_2[10] = 0;
  }
LAB_005a45fc:
  FUN_005a4340(0xfc92d4);
  return uVar8;
}

