/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003fe634  name=FUN_003fe634  size=436  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_003fe634(void)

{
  FUN_00460a04(uRam00e9c1f0,uRam00e28b10,0xffffffff,0xd717c0,0xc0000002,0xe9c3a8,1,0x46fc1c,0xda3a00
               ,0xd717d4,0xd7143c,0x177,0xd71438);
  FUN_00460a04(uRam00e9c1f0,uRam00e28b10,0xffffffff,0xd717f0,0xc0000002,0xe9c344,1,0x46fc1c,0xda3a00
               ,0xd71808,0xd7143c,0x17a,0xd71438);
  FUN_00460a04(uRam00e9c1f0,uRam00e28b10,0xffffffff,0xd71820,0xc0000002,0xe9c1cc,1,0x46fc1c,0xda3a00
               ,0xd7183c,0xd7143c,0x17d,0xd71438);
  FUN_00460a04(uRam00e9c1f0,uRam00e28b10,0xffffffff,0xd71868,0xc0000002,0xe9c32c,0,0x46fc1c,0xda3a00
               ,0xd71870,0xd7143c,0x180,0xd71438);
  return 0;
}

