/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002bfd98  name=FUN_002bfd98  size=52  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002bfd98(undefined4 param_1)

{
  FUN_002c0164();
  FUN_002bfadc(param_1);
  return;
}

