/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0037efbc  name=FUN_0037efbc  size=12  xrefs=4
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0037efbc(void)

{
  return;
}

