/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004347b0  name=FUN_004347b0  size=368  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


uint FUN_004347b0(undefined4 param_1,char *param_2,undefined4 *param_3)

{
  char cVar1;
  uint uVar2;
  uint uVar3;
  char *pcVar4;
  undefined4 uVar5;
  
  *param_3 = 0;
  cVar1 = *param_2;
  uVar3 = 0;
  do {
    if (cVar1 == '\0') {
LAB_004348f0:
      if (*param_2 != '\0') {
        uVar5 = 0x380019;
LAB_00434904:
        FUN_00442990(uVar5);
        uVar3 = 0xffffffff;
      }
      return uVar3;
    }
    cVar1 = *param_2;
    uVar2 = uVar3;
    if ((cVar1 == '/') || (cVar1 == '\\')) {
      param_2 = param_2 + 1;
    }
    else {
      if (cVar1 != '.') {
LAB_00434854:
        if (uVar3 < 0x7c) {
          param_3[uVar3 * 2] = param_2;
          pcVar4 = (char *)0x0;
          param_3[uVar3 * 2 + 2] = 0;
          if ((*param_2 != '/') && (*param_2 != '\\')) {
            while (cVar1 = *param_2, cVar1 != '\0') {
              if ((cVar1 != '.') && (cVar1 != ' ')) {
                pcVar4 = param_2;
              }
              param_2 = param_2 + 1;
              if ((*param_2 == '/') || (*param_2 == '\\')) break;
            }
            if (pcVar4 != (char *)0x0) {
              uVar2 = uVar3 + 1;
              *(short *)(param_3 + uVar3 * 2 + 1) = ((short)pcVar4 - (short)param_3[uVar3 * 2]) + 1;
              goto LAB_004348e4;
            }
          }
          uVar5 = 0x38000f;
          goto LAB_00434904;
        }
        goto LAB_004348f0;
      }
      cVar1 = param_2[1];
      if (((cVar1 == '\0') || (cVar1 == '/')) || (cVar1 == '\\')) {
        param_2 = param_2 + 1;
      }
      else {
        if ((cVar1 != '.') ||
           (((cVar1 = param_2[2], cVar1 != '\0' && (cVar1 != '/')) && (cVar1 != '\\'))))
        goto LAB_00434854;
        if (uVar3 != 0) {
          uVar3 = uVar3 - 1;
        }
        param_2 = param_2 + 2;
        uVar2 = uVar3;
      }
    }
LAB_004348e4:
    cVar1 = *param_2;
    uVar3 = uVar2;
  } while( true );
}

