/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00307cc8  name=FUN_00307cc8  size=292  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


bool FUN_00307cc8(int *param_1,undefined4 param_2,int param_3,int param_4,int param_5,int *param_6)

{
  int iVar1;
  int iVar2;
  bool bVar3;
  
  param_1[7] = 0;
  *param_1 = 0;
  param_1[1] = 0;
  param_1[2] = 0;
  iVar1 = FUN_00307c74(param_6);
  param_1[8] = iVar1;
  param_1[5] = param_5;
  param_1[3] = param_3;
  param_1[4] = param_4;
  iVar1 = FUN_0030725c(param_3,param_4);
  param_1[6] = iVar1;
  bVar3 = true;
  if (param_3 != 6) {
    if (param_3 < 4) {
      iVar2 = *param_6;
      iVar1 = FUN_00248640(0x404);
      param_1[2] = iVar1;
      if (iVar1 == 0) {
        return false;
      }
      FUN_0039ac74(iVar1,param_6,(0x100 - iVar2) * -4 + 0x404);
    }
    bVar3 = false;
    if (param_1[6] * param_1[5] == 0) {
      *param_1 = 0;
    }
    else {
      iVar1 = *param_1;
      if (iVar1 == 0) {
        iVar1 = FUN_00248300();
        *param_1 = iVar1;
      }
      bVar3 = iVar1 != 0;
    }
  }
  return bVar3;
}

