/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002e2968  name=FUN_002e2968  size=236  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_002e2968(int param_1,uint param_2)

{
  int iVar1;
  int iVar2;
  uint uVar3;
  int iVar4;
  int iVar5;
  undefined1 auStack_40 [16];
  int iStack_30;
  
  FUN_00318718((int *)(param_1 + 0x1f8),0);
  iVar2 = 0;
  uVar3 = *(uint *)(param_1 + 0x16c);
  if ((int)param_2 < (int)*(uint *)(param_1 + 0x16c)) {
    uVar3 = param_2;
  }
  uVar3 = uVar3 & (int)~uVar3 >> 0x1f;
  iVar1 = FUN_002ee63c(param_1);
  if (iVar1 == 0) {
    iVar1 = uVar3 + 1;
    if (0 < iVar1) {
      iVar4 = 0;
      do {
        iVar5 = iVar4 + 1;
        FUN_002ee698(param_1,iVar4,auStack_40);
        iVar2 = iVar2 + iStack_30;
        iVar4 = iVar5;
      } while (iVar5 < iVar1);
    }
  }
  else {
    iVar2 = iVar1 * uVar3;
  }
  (**(code **)(*(int *)(param_1 + 0x1f8) + 0x10))();
  return iVar2;
}

