/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003bcdc4  name=FUN_003bcdc4  size=64  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_003bcdc4(undefined4 param_1,undefined4 param_2)

{
  FUN_003bd6cc(uRam00e9c528,param_1,param_2);
  return param_2;
}

