/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005c90ac  name=FUN_005c90ac  size=196  xrefs=6
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_005c90ac(int *param_1)

{
  int iVar1;
  
  if ((param_1 != (int *)0x0) &&
     (iVar1 = FUN_004a782c(param_1 + 10,0xffffffff,4,0xd93b48,0x5d), iVar1 < 1)) {
    if (*param_1 != 0) {
      FUN_004cb824();
    }
    if (param_1[1] != 0) {
      FUN_004cc25c();
    }
    if (param_1[2] != 0) {
      FUN_005caca4();
    }
    if (param_1[9] == 0) {
      FUN_004a8858(param_1);
    }
    else {
      FUN_004a8858();
      FUN_004a8858(param_1);
    }
    return;
  }
  return;
}

