/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001cdf98  name=FUN_001cdf98  size=60  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_001cdf98(void)

{
  int iVar1;
  undefined4 uVar2;
  undefined4 auStack_8 [2];
  
  iVar1 = FUN_001ccc50(0x2d0,auStack_8,0);
  uVar2 = 0xffffffff;
  if (iVar1 == 0) {
    uVar2 = auStack_8[0];
  }
  return uVar2;
}

