/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001cb1c0  name=FUN_001cb1c0  size=100  xrefs=20
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


uint FUN_001cb1c0(uint param_1)

{
  uint uVar1;
  uint uVar2;
  
  uVar2 = 0;
  if (-1 < (int)param_1) {
    uVar1 = param_1 - 0x7c01;
    uVar2 = 0xfc00 - param_1;
    if ((((0x7c00 < (int)param_1) && (uVar2 = uVar1, 0x7c00 < uVar1)) && (0x3fe < param_1 - 0xf802))
       && (uVar2 = param_1, 0x3fe < param_1 - 0xfc01)) {
      uVar2 = 0;
    }
  }
  return uVar2;
}

