/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004cff7c  name=FUN_004cff7c  size=384  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_004cff7c(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4,
                undefined4 param_5,int param_6)

{
  int iVar1;
  undefined4 uVar2;
  int iVar3;
  int aiStack_20 [2];
  
  aiStack_20[0] = 0;
  iVar1 = FUN_004b92bc(4);
  if (iVar1 == 0) {
    FUN_004a6438(0x23,0x6c,0x41,0xd7d028,0x9e);
  }
  else {
    uVar2 = FUN_004b600c(param_5,aiStack_20,param_2);
    if (aiStack_20[0] == 0) {
      FUN_004a6438(0x23,0x6c,0x66,0xd7d028,0xa3,iVar1 + 8,iVar1,1);
    }
    else {
      iVar3 = FUN_004cfca8(param_1,param_3,param_4,aiStack_20[0],uVar2);
      if (iVar3 != 0) {
        if (param_6 != 0) {
          FUN_004a89ec(aiStack_20[0],uVar2);
        }
        FUN_004a8858(aiStack_20[0]);
        return iVar1;
      }
      FUN_004a6438(0x23,0x6c,0x67,0xd7d028,0xa8);
      FUN_004a8858(aiStack_20[0]);
    }
  }
  return 0;
}

