/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0054ddb4  name=FUN_0054ddb4  size=572  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0054ddb4(int param_1)

{
  ushort uVar3;
  uint uVar1;
  int iVar2;
  uint uVar4;
  int iVar5;
  int iVar6;
  uint uVar7;
  int iVar8;
  int iStack_18;
  
  if (*(int *)(param_1 + 0x4c) != -1) {
    FUN_0054ce40();
  }
  iVar5 = 0;
  if (*(short *)(param_1 + 0x14) != 0) {
    do {
      iVar6 = *(int *)(*(int *)(param_1 + 0x3c) + iVar5 * 4);
      iVar8 = iVar5 << (*(int *)(param_1 + 0xc) - 9U & 0x3f);
      if (iVar6 != 0) {
        iVar6 = FUN_0054b8f0(param_1,iVar6,&iStack_18);
        uVar3 = FUN_0054f660(iVar6 + 0x14);
        iVar6 = FUN_0054bad4(iVar6);
        if ((((iVar6 != 0) && (uVar3 < *(ushort *)(param_1 + 0x14))) &&
            (*(ushort *)(param_1 + 0x18) <= uVar3)) && (uVar7 = 0, *(int *)(param_1 + 0x30) != 0)) {
          do {
            uVar1 = FUN_0054f698(iStack_18 + uVar7 * 4);
            if (uVar1 != 0xffffffff) {
              if (uVar1 != 0xfffffffe) {
                if (((uVar1 == 0) || (uVar1 == 0x70)) || (uVar1 == 0x30)) goto LAB_0054dfb8;
                if ((uVar1 & 0x1ff) != 0x60) {
                  if ((uVar1 & 0x1ff) != 0x40) {
                    FUN_0054c028(param_1,iVar8,0,1);
                    goto LAB_0054dfb8;
                  }
                  uVar4 = (int)uVar1 >> 9;
                  if ((int)uVar1 < *(int *)(param_1 + 0x24)) {
                    uVar4 = uVar4 + *(int *)(param_1 + 0x1c);
                    if ((-1 < (int)uVar4) && (uVar4 < *(uint *)(param_1 + 0x20))) {
                      iVar6 = *(int *)(*(int *)(param_1 + 0x44) + uVar4 * 4);
joined_r0x0054df80:
                      if (iVar6 == iVar8) goto LAB_0054dfb8;
                    }
                  }
                  else if (uVar4 < *(uint *)(param_1 + 8)) {
                    uVar1 = uVar4 & 0x7f;
                    if (*(int *)(*(int *)(param_1 + 0x44) + (uVar4 >> 5 & 0x7fffffc)) != -1) {
                      iVar6 = FUN_0054b85c(param_1);
                      (**(code **)(param_1 + 0x84))(param_1 + 100,iVar6 + uVar1 * 4,4);
                      iVar2 = FUN_0054f698();
                      iVar6 = iVar2 >> 9;
                      if ((iVar2 != -1) && (iVar2 != 0)) goto joined_r0x0054df80;
                      FUN_0054d00c(param_1,uVar4 + *(int *)(param_1 + 0x1c),iVar8);
                      if (*(int *)(param_1 + 0x4c) != -1) {
                        FUN_0054ce40(param_1);
                      }
                    }
                    goto LAB_0054dfb8;
                  }
                }
              }
              FUN_0054c028(param_1,iVar8,0,1);
            }
LAB_0054dfb8:
            iVar8 = iVar8 + 1;
            uVar7 = uVar7 + 1;
          } while (uVar7 < *(uint *)(param_1 + 0x30));
        }
      }
      iVar5 = iVar5 + 1;
    } while (iVar5 < (int)(uint)*(ushort *)(param_1 + 0x14));
  }
  return;
}

