/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003c088c  name=FUN_003c088c  size=28  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_003c088c(int param_1,undefined1 param_2,int param_3)

{
  undefined1 *puVar1;
  
  if (param_3 == 0) {
    return;
  }
  puVar1 = (undefined1 *)(param_1 + -1);
  do {
    puVar1 = puVar1 + 1;
    *puVar1 = param_2;
    param_3 = param_3 + -1;
  } while (param_3 != 0);
  return;
}

