/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002f4674  name=FUN_002f4674  size=52  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002f4674(int *param_1)

{
  if ((*param_1 <= param_1[1]) && (param_1[2] <= param_1[3])) {
    return;
  }
  FUN_002f44a8();
  return;
}

