/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004abcbc  name=FUN_004abcbc  size=328  xrefs=4
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_004abcbc(undefined4 param_1,undefined4 param_2,undefined4 param_3)

{
  undefined4 uVar1;
  int iVar2;
  int iVar3;
  undefined4 uVar4;
  int iVar5;
  
  iVar5 = 0;
  iVar2 = FUN_004b312c(0,0,param_1,0xffffffff);
  uVar1 = 0;
  if (0 < iVar2) {
    iVar3 = FUN_004a849c(iVar2,0xd76ef0,0x2a0);
    if (iVar3 == 0) {
      FUN_004a6438(8,100,0x41,0xd76ef0,0x2a2);
      return 0;
    }
    iVar2 = FUN_004b312c(iVar3,iVar2,param_1,0xffffffff);
    uVar1 = 0;
    if (iVar2 != 0) {
      uVar4 = FUN_004ab008(1);
      iVar5 = FUN_004b3820(uVar4,iVar3,iVar2,param_2,param_3);
      if (iVar5 != 0) {
        uVar1 = FUN_004ab028();
      }
    }
    FUN_004b34ac(iVar5);
    FUN_004a8858(iVar3);
  }
  return uVar1;
}

