/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001a283c  name=FUN_001a283c  size=136  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_001a283c(undefined4 *param_1)

{
  undefined4 *puVar1;
  int iVar2;
  
  FUN_0019fb4c();
  *param_1 = 0xe09140;
  FUN_0039acec(param_1 + 0x6c,0,0xf0);
  FUN_0039acec(param_1 + 0xa8,0,0xf0);
  iVar2 = 4;
  puVar1 = param_1 + 0x114;
  do {
    *puVar1 = 0;
    puVar1 = puVar1 + 1;
    iVar2 = iVar2 + -1;
  } while (iVar2 != 0);
  *(undefined1 *)(param_1 + 0xe4) = 0;
  param_1[0x119] = 0;
  *(undefined2 *)(param_1 + 0x118) = 0;
  return;
}

