/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002ae304  name=FUN_002ae304  size=832  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002ae304(int param_1,int param_2)

{
  char cVar1;
  undefined8 uVar2;
  int iVar3;
  int iVar4;
  uint uVar5;
  undefined4 *puVar6;
  undefined8 uVar7;
  
  iVar3 = FUN_005accf4(*(undefined4 *)(param_1 + 0x138),0xffffffff);
  if (iVar3 == -1) {
    FUN_00443f20(0xd5ee98,1,2,3,4,5,6);
  }
  uVar5 = (uint)*(byte *)(param_2 + 0xf) << 0x18 | (uint)*(byte *)(param_2 + 0xc) << 0x10 |
          (uint)*(byte *)(param_2 + 0xd) << 8 | (uint)*(byte *)(param_2 + 0xe);
  uVar7 = FUN_00373dd0(uVar5);
  if ((int)uVar5 < 0) {
    uVar7 = FUN_00373370((int)((ulonglong)uVar7 >> 0x20),(int)uVar7,0x41f00000,0);
  }
  uVar7 = FUN_003739c0((int)((ulonglong)uVar7 >> 0x20),(int)uVar7,0x408f4000,0);
  puVar6 = (undefined4 *)(param_1 + 0xe8);
  if (*(char *)(param_1 + 0x150) == '\0') {
    iVar3 = FUN_005accf4(*(undefined4 *)(param_1 + 0xe8),0xffffffff);
    if (iVar3 == -1) {
      FUN_00443f20(0xd5ee98,1,2,3,4,5,6);
    }
    iVar3 = *(int *)(param_1 + 0xbc);
    iVar4 = FUN_005ad104(*puVar6);
    if (iVar4 == -1) {
      FUN_00443f20(0xd5ee98,1,2,3,4,5,6);
    }
    if (iVar3 != iVar3 + -1 + (uint)(iVar3 == 0)) {
      iVar3 = FUN_005accf4(*(undefined4 *)(param_1 + 0xe8),0xffffffff);
      if (iVar3 == -1) {
        FUN_00443f20(0xd5ee98,1,2,3,4,5,6);
      }
      cVar1 = *(char *)(param_1 + 0xa0);
      iVar3 = FUN_005ad104(*puVar6);
      if (iVar3 == -1) {
        FUN_00443f20(0xd5ee98,1,2,3,4,5,6);
      }
      if (cVar1 != '\0') {
        uVar2 = *(undefined8 *)(param_1 + 0x140);
        iVar3 = FUN_0037443c((int)((ulonglong)uVar7 >> 0x20),(int)uVar7,
                             *(undefined4 *)(param_1 + 0x140),*(undefined4 *)(param_1 + 0x144));
        if (iVar3 < 1) {
          uVar7 = uVar2;
        }
        *(undefined8 *)(param_1 + 0x140) = uVar7;
        goto LAB_002ae3fc;
      }
    }
  }
  *(undefined8 *)(param_1 + 0x140) = uVar7;
  iVar3 = FUN_005accf4(*(undefined4 *)(param_1 + 0xe8),0xffffffff);
  if (iVar3 == -1) {
    FUN_00443f20(0xd5ee98,1,2,3,4,5,6);
  }
  cVar1 = *(char *)(param_1 + 0xa3);
  iVar3 = FUN_005ad104(*puVar6);
  if (iVar3 == -1) {
    FUN_00443f20(0xd5ee98,1,2,3,4,5,6);
  }
  if (cVar1 != '\x01') {
    *(undefined1 *)(param_1 + 0x150) = 0;
  }
LAB_002ae3fc:
  iVar3 = FUN_005ad104(*(undefined4 *)(param_1 + 0x138));
  if (iVar3 == -1) {
    FUN_00443f20(0xd5ee98,1,2,3,4,5,6);
  }
  return;
}

