/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002b6d70  name=FUN_002b6d70  size=836  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002b6d70(byte *param_1,undefined4 *param_2)

{
  byte *pbVar1;
  byte bVar2;
  int iVar3;
  undefined1 uVar5;
  uint uVar4;
  uint uVar6;
  int *piVar7;
  
  piVar7 = (int *)*param_2;
  if (param_2[1] != 0 && piVar7 != (int *)0x0) {
    (**(code **)(*piVar7 + 0x14))(piVar7);
  }
  param_2[3] = 0;
  param_2[1] = 0;
  param_2[2] = 0;
  iVar3 = FUN_00258900(param_1,0xd5f4a0);
  if (((((((iVar3 == 0) && (iVar3 = FUN_00258900(param_1,0xd5f790), iVar3 == 0)) &&
         (iVar3 = FUN_00258900(param_1,0xd5f79c), iVar3 == 0)) &&
        ((iVar3 = FUN_00258900(param_1,0xd5468c), iVar3 == 0 &&
         (iVar3 = FUN_00258900(param_1,0xd5ff78), iVar3 == 0)))) &&
       ((iVar3 = FUN_00258900(param_1,0xd5ff88), iVar3 == 0 &&
        ((iVar3 = FUN_00258900(param_1,0xd5ffa0), iVar3 == 0 &&
         (iVar3 = FUN_00258900(param_1,0xd5ff90), iVar3 == 0)))))) &&
      (iVar3 = FUN_00258900(param_1,0xd5ff98), iVar3 == 0)) &&
     ((((iVar3 = FUN_00258900(param_1,0xd5ffa8), iVar3 == 0 &&
        (iVar3 = FUN_00258900(param_1,0xd5ffb0), iVar3 == 0)) &&
       (iVar3 = FUN_00258900(param_1,0xd5ffbc), iVar3 == 0)) &&
      (iVar3 = FUN_00258900(param_1,0xd5ffc4), iVar3 == 0)))) {
    iVar3 = FUN_00258dd0(param_1,0x3a);
    if ((iVar3 == 0) && (*param_1 != 0x5c)) {
      FUN_002585b0(param_2,0xd5f4a0);
      FUN_002585b0(param_2,param_1);
    }
    else {
      FUN_002585b0(param_2,0xd5ffd0);
      if (*param_1 == 0x5c) {
        param_1 = param_1 + (param_1[1] == 0x5c);
      }
      bVar2 = *param_1;
      while (uVar4 = (uint)bVar2, uVar4 != 0) {
        iVar3 = FUN_00295794();
        if (iVar3 == 0) {
          uVar6 = 0x7c;
          if (((uVar4 != 0x3a) && (uVar6 = 0x2f, uVar4 != 0x5c)) &&
             ((uVar6 = uVar4, 9 < uVar4 - 0x30 && 0x19 < uVar4 - 0x41 &&
              ((0x19 < uVar4 - 0x61 && uVar4 != 0x2e && ((bVar2 & 0x80) == 0)))))) {
            FUN_00257d18(param_2,0x25);
            uVar5 = FUN_00257aa8(bVar2 >> 4);
            FUN_00257d18(param_2,uVar5);
            uVar4 = FUN_00257aa8(uVar4 & 0xf);
            uVar6 = uVar4 & 0xff;
          }
LAB_002b7044:
          FUN_00257d18(param_2,uVar6);
        }
        else {
          FUN_00257d18(param_2,uVar4);
          pbVar1 = param_1 + 1;
          if (0x3f < *pbVar1) {
            param_1 = param_1 + 1;
            uVar6 = (uint)*pbVar1;
            goto LAB_002b7044;
          }
        }
        param_1 = param_1 + 1;
        bVar2 = *param_1;
      }
    }
  }
  else {
    FUN_00257b18(param_2,param_1);
  }
  return;
}

