/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0056466c  name=FUN_0056466c  size=1416  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0056466c(void)

{
  undefined4 uVar1;
  char cVar2;
  uint uVar3;
  uint uVar4;
  int *piVar5;
  
  if ((((iRam00e3a628 == 0) || (uRam00e26978 < uRam00e3a630)) || (uRam00e3a630 == 0)) ||
     ((iRam00e3a634 == 0 || (uVar4 = uRam00e3a630, iRam00e3a624 == 0)))) {
    FUN_0035ad18(0x27a6,0x575130,1);
    uVar1 = 0;
  }
  else {
    while (uVar4 = uVar4 - 1, uVar4 < uRam00e26978) {
      piVar5 = *(int **)(iRam00e3a624 + uVar4 * 4);
      cVar2 = FUN_00590cb4(uRam00e3a62c,uVar4,piVar5[0x530c]);
      if (cVar2 != '\0') {
        FUN_0035ad18(0x27a6,0x575160,1);
        return 0;
      }
      if (**(int **)(*piVar5 * 4 + 0x10cf458) == 0) {
        if (**(int **)(*piVar5 * 4 + 0x10cf458) == 0) {
          uVar3 = *(uint *)(piVar5[2] + 0x40);
        }
        else {
          uVar3 = (*(code *)**(undefined4 **)(*piVar5 * 4 + 0x10cf458))
                            (*(undefined4 *)(piVar5[2] + 0x40));
        }
        *(uint *)(piVar5[2] + 0x40) = uVar3 & 0xfffffffe;
      }
      else {
        if (**(int **)(*piVar5 * 4 + 0x10cf458) == 0) {
          uVar3 = *(uint *)(piVar5[2] + 0x40);
        }
        else {
          uVar3 = (*(code *)**(undefined4 **)(*piVar5 * 4 + 0x10cf458))
                            (*(undefined4 *)(piVar5[2] + 0x40));
        }
        uVar1 = (*(code *)**(undefined4 **)(*piVar5 * 4 + 0x10cf458))(uVar3 & 0xfffffffe);
        *(undefined4 *)(piVar5[2] + 0x40) = uVar1;
      }
      if (**(int **)(*piVar5 * 4 + 0x10cf458) == 0) {
        if (**(int **)(*piVar5 * 4 + 0x10cf458) == 0) {
          uVar3 = *(uint *)piVar5[2];
        }
        else {
          uVar3 = (*(code *)**(undefined4 **)(*piVar5 * 4 + 0x10cf458))(*(undefined4 *)piVar5[2]);
        }
        *(uint *)piVar5[2] = uVar3 & 0xfffffffe;
      }
      else {
        if (**(int **)(*piVar5 * 4 + 0x10cf458) == 0) {
          uVar3 = *(uint *)piVar5[2];
        }
        else {
          uVar3 = (*(code *)**(undefined4 **)(*piVar5 * 4 + 0x10cf458))(*(undefined4 *)piVar5[2]);
        }
        uVar1 = (*(code *)**(undefined4 **)(*piVar5 * 4 + 0x10cf458))(uVar3 & 0xfffffffe);
        *(undefined4 *)piVar5[2] = uVar1;
      }
      if (**(int **)(*piVar5 * 4 + 0x10cf458) == 0) {
        if (**(int **)(*piVar5 * 4 + 0x10cf458) == 0) {
          uVar3 = *(uint *)piVar5[2];
        }
        else {
          uVar3 = (*(code *)**(undefined4 **)(*piVar5 * 4 + 0x10cf458))(*(undefined4 *)piVar5[2]);
        }
        *(uint *)piVar5[2] = uVar3 & 0xffffffdf;
      }
      else {
        if (**(int **)(*piVar5 * 4 + 0x10cf458) == 0) {
          uVar3 = *(uint *)piVar5[2];
        }
        else {
          uVar3 = (*(code *)**(undefined4 **)(*piVar5 * 4 + 0x10cf458))(*(undefined4 *)piVar5[2]);
        }
        uVar1 = (*(code *)**(undefined4 **)(*piVar5 * 4 + 0x10cf458))(uVar3 & 0xffffffdf);
        *(undefined4 *)piVar5[2] = uVar1;
      }
      if (**(int **)(*piVar5 * 4 + 0x10cf458) == 0) {
        *(undefined4 *)(piVar5[2] + 8) = 0;
      }
      else {
        uVar1 = (*(code *)**(undefined4 **)(*piVar5 * 4 + 0x10cf458))(0);
        *(undefined4 *)(piVar5[2] + 8) = uVar1;
      }
      FUN_00561798(piVar5);
      FUN_00561718(piVar5);
      FUN_005554ec(piVar5);
      *(undefined4 *)(iRam00e3a624 + uVar4 * 4) = 0;
      uRam00e3a630 = uRam00e3a630 - 1;
    }
    cVar2 = FUN_0059084c(uRam00e3a62c);
    if (cVar2 == '\0') {
      uRam00e3a62c = 0;
      FUN_005554ec(iRam00e3a628);
      iRam00e3a628 = 0;
      FUN_0056cf9c();
      FUN_005ac50c(iRam00e3a634);
      iRam00e3a634 = 0;
      FUN_005554ec(iRam00e3a624);
      iRam00e3a624 = 0;
      FUN_0035ad18(0x27a6,0x5751c4,1);
      uVar1 = 1;
    }
    else {
      FUN_0035ad18(0x27a6,0x575190,1);
      uVar1 = 0;
    }
  }
  return uVar1;
}

