/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00539d2c  name=FUN_00539d2c  size=160  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00539d2c(int param_1)

{
  undefined4 uVar1;
  int iVar2;
  int aiStack_10 [3];
  
  uVar1 = (**(code **)(*(int *)(param_1 + 8) + 0x30))
                    (param_1,0x2180,0x2181,0xffffffff,*(undefined4 *)(param_1 + 0xfc),aiStack_10);
  if (aiStack_10[0] != 0) {
    iVar2 = *(int *)(param_1 + 0x58);
    uVar1 = 1;
    *(undefined4 *)(iVar2 + 0x364) = 1;
    if (*(int *)(iVar2 + 0x354) == 1) {
      if (*(int *)(iVar2 + 0x35c) == 0) {
        uVar1 = 2;
      }
      else {
        FUN_004c49dc();
        uVar1 = 2;
        *(undefined4 *)(*(int *)(param_1 + 0x58) + 0x35c) = 0;
      }
    }
  }
  return uVar1;
}

