/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0050fb6c  name=FUN_0050fb6c  size=304  xrefs=8
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0050fb6c(undefined4 param_1,int param_2,undefined4 param_3,uint param_4)

{
  bool bVar1;
  undefined4 uVar2;
  
  uVar2 = 0;
  if (param_2 != 0) {
    FUN_004a1ce8();
  }
  bVar1 = (param_4 & 0xf0000) == 0x40000;
  if (bVar1) {
    uVar2 = 4;
  }
  if (param_4 != 0) {
    if (bVar1) {
      FUN_004a1ce8(param_1,0xd37ae4);
    }
    FUN_004e3f94(param_1,param_3,uVar2,param_4);
    FUN_004a1ce8(param_1,0xd37ae4);
    return;
  }
  uVar2 = FUN_004d1d18(param_3,0,0);
  FUN_004a1ce8(param_1,uVar2);
  FUN_004a1ce8(param_1,0xd37ae4);
  FUN_004a8858(uVar2);
  return;
}

