/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00270c08  name=FUN_00270c08  size=832  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00270c08(int *param_1,undefined4 param_2)

{
  int iVar1;
  int iVar2;
  uint uVar3;
  int iVar4;
  int *piVar5;
  undefined4 uVar6;
  byte in_cr0;
  byte in_cr1;
  byte unaff_cr2;
  byte unaff_cr3;
  byte unaff_cr4;
  byte in_cr5;
  byte in_cr6;
  byte in_cr7;
  int *piStack_90;
  int iStack_8c;
  int iStack_88;
  undefined1 auStack_80 [12];
  int iStack_74;
  int iStack_40;
  undefined4 uStack_3c;
  int aiStack_38 [5];
  uint uStack_24;
  
  uStack_24 = (uint)(in_cr0 & 0xf) << 0x1c | (uint)(in_cr1 & 0xf) << 0x18 |
              (uint)(unaff_cr2 & 0xf) << 0x14 | (uint)(unaff_cr3 & 0xf) << 0x10 |
              (uint)(unaff_cr4 & 0xf) << 0xc | (uint)(in_cr5 & 0xf) << 8 | (uint)(in_cr6 & 0xf) << 4
              | (uint)(in_cr7 & 0xf);
  uVar6 = *(undefined4 *)(*param_1 + 0x16f8);
  FUN_002579e8(&piStack_90,param_1 + 0x19);
  iStack_40 = 0;
  if (iStack_88 == 0) {
    FUN_00257a0c(&piStack_90,param_2);
    FUN_0026b994(uVar6,&piStack_90);
    iVar1 = FUN_002c7080(uVar6,iStack_8c,&iStack_40);
  }
  else {
    FUN_0026b994(uVar6,&piStack_90);
    iVar1 = FUN_002c7080(uVar6,iStack_8c,&iStack_40);
  }
  if ((iVar1 == 0) || (iVar1 = FUN_00248300(iStack_40), iVar1 == 0)) goto LAB_00270cfc;
  iVar2 = FUN_002c6de4(uVar6,&uStack_3c,iStack_8c,0);
  if (iVar2 != 0) {
    uVar3 = FUN_002c6f48(uStack_3c,iVar1,iStack_40);
    FUN_002c7004(uStack_3c);
    if (9 < uVar3) {
      FUN_002deebc(auStack_80,iVar1,uVar3,*param_1,0);
      iVar2 = FUN_002c99b4(auStack_80,aiStack_38);
      if ((((iVar2 != 2) || (iStack_40 < iStack_74 + aiStack_38[0])) ||
          (iVar2 = FUN_002c9c5c(auStack_80), iVar2 != 0x5443534f)) ||
         (iVar2 = FUN_002c9b98(auStack_80), 2 < iVar2 - 2U)) {
        FUN_002def60(auStack_80);
        goto LAB_00270cf8;
      }
      if (3 < iVar2) {
        iVar2 = FUN_002c9c5c(auStack_80);
        param_1[0x27] = iVar2;
      }
      iVar2 = FUN_002c9e54(auStack_80,2);
      iVar4 = FUN_002589a0(iVar2,param_1[6]);
      if (iVar4 != 0) {
        FUN_002e07a8(auStack_80,param_1,iStack_74 + aiStack_38[0],1);
        piVar5 = (int *)FUN_002852ac(param_1[0x2d],0xd79bdc);
        if (((piVar5 != (int *)0x0) && (*piVar5 == 3)) && (iVar4 = piVar5[2], iVar4 != 0)) {
          for (piVar5 = *(int **)(iVar4 + 0x20); piVar5 != (int *)0x0; piVar5 = (int *)piVar5[5]) {
            if ((((*(ushort *)(piVar5 + 8) & 1) == 0) && (*piVar5 == 3)) &&
               ((*(int *)(piVar5[2] + 0x68) == 0 && (*(int *)(piVar5[2] + 0x70) == 0)))) {
              FUN_0026b424(iVar4);
            }
          }
        }
      }
      if (iVar2 != 0) {
        FUN_00245be8(iVar2);
      }
      FUN_002def60(auStack_80);
    }
    if (iStack_88 == 0) {
      param_1[0x2f] = 1;
      FUN_0026da04(param_1,1,0,0);
      FUN_002c6b94(uVar6,iStack_8c);
    }
  }
LAB_00270cf8:
  FUN_00245be8(iVar1);
LAB_00270cfc:
  if (iStack_8c != 0 && piStack_90 != (int *)0x0) {
    (**(code **)(*piStack_90 + 0x14))();
  }
  return;
}

