/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00380674  name=FUN_00380674  size=48  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00380674(char *param_1)

{
  if ((*param_1 != 'C') && (*param_1 != 'V')) {
    return 0;
  }
  return 1;
}

