/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003d9bf0  name=FUN_003d9bf0  size=24  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_003d9bf0(undefined4 param_1,undefined4 param_2)

{
  FUN_003d9934(param_1,0x80206910,param_2);
  return;
}

