/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002f8fd4  name=FUN_002f8fd4  size=380  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002f8fd4(int *param_1,int *param_2,int param_3,int *param_4)

{
  int iVar1;
  uint uVar2;
  uint uVar3;
  int iVar4;
  int iVar5;
  uint uVar6;
  int iVar7;
  int iVar8;
  int iVar9;
  int iVar10;
  uint uVar11;
  uint uVar12;
  uint uVar13;
  uint uVar14;
  uint uVar15;
  
  iVar7 = param_1[2];
  iVar8 = param_1[1];
  iVar9 = *param_1;
  iVar4 = *param_2 - iVar9;
  iVar5 = param_2[1] - iVar8;
  iVar10 = param_2[2] - iVar7;
  iVar1 = param_2[3] - param_1[3];
  uVar11 = param_3 * iVar1;
  uVar12 = param_3 * iVar10;
  uVar13 = param_3 * iVar5;
  uVar14 = param_3 * iVar4;
  uVar6 = uVar14 + 0x8000;
  uVar3 = uVar13 + 0x8000;
  uVar2 = uVar12 + 0x8000;
  uVar15 = uVar11 + 0x8000;
  param_4[3] = param_1[3] +
               (((uint)(uVar15 < uVar11) +
                (int)((ulonglong)((longlong)param_3 * (longlong)iVar1) >> 0x20)) * 0x10000 |
               uVar15 >> 0x10);
  *param_4 = iVar9 + (((uint)(uVar6 < uVar14) +
                      (int)((ulonglong)((longlong)param_3 * (longlong)iVar4) >> 0x20)) * 0x10000 |
                     uVar6 >> 0x10);
  param_4[1] = iVar8 + (((uint)(uVar3 < uVar13) +
                        (int)((ulonglong)((longlong)param_3 * (longlong)iVar5) >> 0x20)) * 0x10000 |
                       uVar3 >> 0x10);
  param_4[2] = iVar7 + (((uint)(uVar2 < uVar12) +
                        (int)((ulonglong)((longlong)param_3 * (longlong)iVar10) >> 0x20)) * 0x10000
                       | uVar2 >> 0x10);
  return;
}

