/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004a9760  name=FUN_004a9760  size=344  xrefs=5
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_004a9760(undefined4 param_1)

{
  undefined4 uVar1;
  int iVar2;
  undefined4 uStack_28;
  int iStack_24;
  undefined4 uStack_20;
  
  if ((iRam00e2b888 != 0) || (iRam00e2b890 != 0)) {
    FUN_004a8ae4(3);
    uStack_20 = 0;
    iStack_24 = 0;
    uStack_28 = param_1;
    if (iRam00e2b888 != 0) {
      FUN_004a6ebc(iRam00e2b888,0x4b94b0,&uStack_28);
    }
    iVar2 = iStack_24;
    if (iStack_24 == 0) {
      FUN_004a76f8(9,0x14,0xd72dac,0x2d8);
      uVar1 = iRam00e2b88c;
      iRam00e2b88c = iVar2;
      if (iRam00e2b888 != 0) {
        FUN_004a6b70();
        iRam00e2b888 = 0;
      }
      if ((iRam00e2b890 != 0) && (iVar2 = FUN_004a7338(), iVar2 == 0)) {
        FUN_004a6b70(iRam00e2b890);
        iRam00e2b890 = 0;
      }
      iRam00e2b88c = uVar1;
      FUN_004a76f8(10,0x14,0xd72dac,0x2ee);
      FUN_004a8ae4(2);
    }
    else {
      FUN_004bdee0(param_1,0xd72e38,uStack_20);
      FUN_004a8ae4(2);
    }
  }
  return;
}

