/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004b971c  name=FUN_004b971c  size=40  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_004b971c(void)

{
  FUN_004b7bd8();
  return;
}

