/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001a5f60  name=FUN_001a5f60  size=56  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_001a5f60(void)

{
  FUN_004a3a98(1);
  FUN_004aff40();
  FUN_004aa8f0();
  FUN_004a5e78(0);
  FUN_004a5948();
  return;
}

