/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004d55c4  name=FUN_004d55c4  size=216  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_004d55c4(int param_1,undefined4 param_2,uint *param_3)

{
  int iVar1;
  int iVar2;
  undefined4 uVar3;
  
  uVar3 = 0;
  *param_3 = 0;
  iVar1 = FUN_004ad1f0();
  if (iVar1 != 0) {
    FUN_004c2db8(iVar1,1);
    iVar2 = FUN_004c2dd8(param_2,iVar1);
    uVar3 = 1;
    if (iVar2 < 1) {
      *param_3 = *param_3 | 1;
    }
    FUN_004c2d98(iVar1,*(undefined4 *)(param_1 + 8));
    FUN_004c3058(iVar1,1);
    iVar2 = FUN_004c2dd8(param_2,iVar1);
    if (-1 < iVar2) {
      *param_3 = *param_3 | 2;
    }
    FUN_004ad194(iVar1);
  }
  return uVar3;
}

