/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003547c0  name=FUN_003547c0  size=300  xrefs=37
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


uint FUN_003547c0(int param_1,int param_2,uint param_3,uint param_4)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  int iVar4;
  uint uVar5;
  int iVar6;
  uint uVar7;
  
  if (((int)param_3 < param_2 && (int)param_4 <= (int)param_3) &&
     (iVar6 = param_3 - param_4, iVar6 < 0x20)) {
    uVar1 = 0;
    while ((int)param_4 <= (int)param_3) {
      iVar4 = param_3 + (((int)param_3 >> 3) + (uint)((int)param_3 < 0 && (param_3 & 7) != 0)) * -8;
      uVar3 = iVar4 + 1;
      uVar2 = iVar6 + 1;
      uVar5 = param_2 - param_3;
      uVar7 = (1 << (uVar3 & 0x3f)) - 1;
      if ((int)uVar2 < (int)uVar3) {
        uVar7 = (1 << (uVar2 & 0x3f)) + -1 <<
                (param_4 + (((int)param_4 >> 3) + (uint)((int)param_4 < 0 && (param_4 & 7) != 0)) *
                           -8 & 0x3f);
        uVar3 = uVar2;
      }
      uVar7 = *(byte *)(param_1 + ((int)uVar5 >> 3) + (uint)((int)uVar5 < 0 && (uVar5 & 7) != 0)) &
              uVar7;
      if (iVar6 < iVar4) {
        uVar7 = uVar7 >> (iVar4 - iVar6 & 0x3fU);
      }
      else {
        uVar7 = uVar7 << (iVar6 - iVar4 & 0x3fU);
      }
      param_3 = param_3 - uVar3;
      uVar1 = uVar1 | uVar7;
      iVar6 = param_3 - param_4;
    }
  }
  else {
    FUN_003cb350(0xd673e4);
    uVar1 = 0;
  }
  return uVar1;
}

