/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0026bb8c  name=FUN_0026bb8c  size=1288  xrefs=4
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0026bb8c(int *param_1,int *param_2,int param_3)

{
  bool bVar1;
  byte *pbVar2;
  int iVar3;
  int iVar4;
  byte in_cr0;
  byte in_cr1;
  byte unaff_cr2;
  byte unaff_cr3;
  byte unaff_cr4;
  byte in_cr5;
  byte in_cr6;
  byte in_cr7;
  int *piStack_a0;
  int iStack_9c;
  int iStack_90;
  int *piStack_8c;
  int iStack_88;
  int iStack_84;
  undefined4 uStack_80;
  undefined1 auStack_70 [4];
  undefined1 uStack_6c;
  undefined1 uStack_6b;
  undefined1 uStack_6a;
  undefined1 uStack_69;
  undefined1 uStack_68;
  undefined1 uStack_67;
  undefined1 uStack_66;
  undefined1 uStack_65;
  undefined1 uStack_64;
  undefined1 uStack_63;
  undefined1 uStack_62;
  undefined1 uStack_61;
  undefined1 uStack_60;
  undefined1 uStack_5f;
  undefined1 uStack_5e;
  undefined1 uStack_5d;
  undefined1 uStack_5c;
  undefined1 uStack_5b;
  undefined1 uStack_5a;
  undefined1 uStack_59;
  undefined1 uStack_58;
  undefined1 uStack_57;
  undefined1 uStack_56;
  undefined1 uStack_55;
  undefined1 uStack_54;
  undefined1 uStack_53;
  undefined1 uStack_52;
  undefined1 uStack_51;
  byte abStack_50 [16];
  int *piStack_40;
  int iStack_3c;
  uint uStack_30;
  
  uStack_30 = (uint)(in_cr0 & 0xf) << 0x1c | (uint)(in_cr1 & 0xf) << 0x18 |
              (uint)(unaff_cr2 & 0xf) << 0x14 | (uint)(unaff_cr3 & 0xf) << 0x10 |
              (uint)(unaff_cr4 & 0xf) << 0xc | (uint)(in_cr5 & 0xf) << 8 | (uint)(in_cr6 & 0xf) << 4
              | (uint)(in_cr7 & 0xf);
  iVar3 = FUN_002c70d0();
  if (iVar3 == 0) {
    return;
  }
  FUN_0026ba90(param_1,param_2);
  FUN_0026b90c(param_2,0xd5f3e8);
  FUN_0026b90c(param_2,0xd5f3f4);
  if (param_3 == 0) {
    return;
  }
  FUN_0026b90c(param_2,0xd5f404);
  FUN_0026b994(param_1,param_2);
  iVar3 = FUN_002c6c8c(param_1,param_2[1]);
  if (iVar3 == 0) {
    if (param_2[1] != 0 && (int *)*param_2 != (int *)0x0) {
      (**(code **)(*(int *)*param_2 + 0x14))();
    }
    param_2[3] = 0;
    param_2[1] = 0;
    param_2[2] = 0;
    return;
  }
  FUN_0026ba90(param_1,param_2);
  FUN_002579e8(&piStack_a0,param_2);
  FUN_0026b90c(&piStack_a0,0xd38c84);
  FUN_0026b994(param_1,&piStack_a0);
  uStack_80 = 0;
  iStack_88 = 0;
  iStack_84 = 0;
  piStack_8c = param_1;
  iVar3 = FUN_002c7144(param_1,iStack_9c,&iStack_90);
  bVar1 = false;
  if (iVar3 != 0) {
    do {
      if ((iStack_90 == 1) && (iStack_84 == 8)) {
        bVar1 = true;
        FUN_0026b90c(param_2,iStack_88);
      }
      iVar4 = FUN_002c7154(param_1,iVar3,&iStack_90);
    } while (iVar4 != 0);
    FUN_002c7164(iVar3);
  }
  if (!bVar1) {
    auStack_70[0] = uRam00cd8450;
    auStack_70[1] = uRam00cd8451;
    auStack_70[2] = uRam00cd8452;
    auStack_70[3] = uRam00cd8453;
    uStack_6c = uRam00cd8454;
    uStack_6b = uRam00cd8455;
    uStack_6a = uRam00cd8456;
    uStack_69 = uRam00cd8457;
    uStack_68 = uRam00cd8458;
    uStack_67 = uRam00cd8459;
    uStack_66 = uRam00cd845a;
    uStack_65 = uRam00cd845b;
    uStack_64 = uRam00cd845c;
    uStack_63 = uRam00cd845d;
    uStack_62 = uRam00cd845e;
    uStack_61 = uRam00cd845f;
    uStack_60 = uRam00cd8460;
    uStack_55 = uRam00cd846b;
    uStack_5f = uRam00cd8461;
    uStack_5e = uRam00cd8462;
    uStack_5d = uRam00cd8463;
    uStack_5c = uRam00cd8464;
    uStack_5b = uRam00cd8465;
    uStack_5a = uRam00cd8466;
    uStack_59 = uRam00cd8467;
    uStack_58 = uRam00cd8468;
    uStack_57 = uRam00cd8469;
    uStack_56 = uRam00cd846a;
    uStack_54 = uRam00cd846c;
    uStack_53 = uRam00cd846d;
    uStack_52 = uRam00cd846e;
    uStack_51 = uRam00cd846f;
    iVar3 = FUN_002c90ec(abStack_50,8);
    if (iVar3 == 0) {
      if (param_2[1] != 0 && (int *)*param_2 != (int *)0x0) {
        (**(code **)(*(int *)*param_2 + 0x14))();
      }
      param_2[3] = 0;
      bVar1 = iStack_88 == 0 || piStack_8c == (int *)0x0;
      param_2[1] = 0;
      param_2[2] = 0;
      goto LAB_0026bd94;
    }
    FUN_0026b90c(param_2,0xd6f55c);
    iVar3 = 0;
    do {
      pbVar2 = abStack_50 + iVar3;
      iVar3 = iVar3 + 1;
      FUN_00257d18(param_2,auStack_70[*pbVar2 & 0x1f]);
    } while (iVar3 < 8);
    FUN_002579e8(&piStack_40,param_2);
    FUN_0026b994(param_1,&piStack_40);
    iVar3 = FUN_002c6c8c(param_1,iStack_3c);
    if (iVar3 == 0) {
      if (param_2[1] != 0 && (int *)*param_2 != (int *)0x0) {
        (**(code **)(*(int *)*param_2 + 0x14))();
      }
      param_2[3] = 0;
      bVar1 = iStack_3c == 0 || piStack_40 == (int *)0x0;
      param_2[1] = 0;
      param_2[2] = 0;
    }
    else {
      bVar1 = iStack_3c == 0 || piStack_40 == (int *)0x0;
    }
    if (!bVar1) {
      (**(code **)(*piStack_40 + 0x14))();
    }
  }
  bVar1 = iStack_88 == 0 || piStack_8c == (int *)0x0;
LAB_0026bd94:
  if (!bVar1) {
    (**(code **)(*piStack_8c + 0x14))();
  }
  if (iStack_9c != 0 && piStack_a0 != (int *)0x0) {
    (**(code **)(*piStack_a0 + 0x14))();
  }
  return;
}

