/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005cb2d8  name=FUN_005cb2d8  size=40  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_005cb2d8(int *param_1)

{
  FUN_004d78c8(*(undefined4 *)(*param_1 + 0xc));
  return;
}

