/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00221164  name=FUN_00221164  size=64  xrefs=4
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_00221164(int param_1)

{
  int iVar1;
  
  iVar1 = FUN_0021eeb8(0x4000000,param_1 << 4,0x10);
  return -(uint)(iVar1 == -1);
}

