/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0039487c  name=FUN_0039487c  size=112  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0039487c(undefined4 param_1,undefined4 param_2,undefined4 param_3)

{
  undefined4 uVar1;
  undefined4 uVar2;
  undefined4 uVar3;
  
  uVar3 = *(undefined4 *)(iRam00e9c190 + 4);
  uVar2 = *(undefined4 *)(iRam00e9c5b4 + 0xc);
  uVar1 = (*pcRam01110ad0)(param_2);
  FUN_003944e0(param_1,uVar1,param_3,uVar3,uVar2,0);
  return;
}

