/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00253a68  name=FUN_00253a68  size=144  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00253a68(int *param_1)

{
  int iVar1;
  undefined4 uVar2;
  
  (**(code **)(*param_1 + 0x104))();
  iVar1 = param_1[1];
  uVar2 = 0;
  if (((iVar1 != 0) && (uVar2 = 0, *(int *)(iVar1 + 0x70) == 0)) && (*(int *)(iVar1 + 0x264) != 0))
  {
    uVar2 = 1;
  }
  (**(code **)(*param_1 + 0x108))(param_1);
  return uVar2;
}

