/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00251bcc  name=FUN_00251bcc  size=100  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00251bcc(undefined4 param_1,undefined4 param_2,int param_3)

{
  undefined8 uVar1;
  
  uVar1 = FUN_0039a988();
  for (; 0 < param_3; param_3 = param_3 + -1) {
    uVar1 = FUN_00373704((int)((ulonglong)uVar1 >> 0x20),(int)uVar1,&MMIO_40240000,0);
  }
  if (param_3 < 0) {
    param_3 = -param_3;
    do {
      uVar1 = FUN_003739c0((int)((ulonglong)uVar1 >> 0x20),(int)uVar1,&MMIO_40240000,0);
      param_3 = param_3 + -1;
    } while (param_3 != 0);
  }
  return;
}

