/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0059fc94  name=FUN_0059fc94  size=204  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0059fc94(undefined4 param_1,int *param_2)

{
  bool bVar1;
  bool bVar2;
  int iVar3;
  int iVar4;
  int *piVar5;
  
  iVar3 = FUN_005a0ae8();
  if (iVar3 != 0) {
    iVar3 = 0;
    piVar5 = param_2;
    do {
      piVar5 = piVar5 + 1;
      bVar2 = 0x13 < iVar3;
      bVar1 = *param_2 <= iVar3;
      iVar3 = iVar3 + 1;
      if (bVar1 || bVar2) {
        return 1;
      }
      iVar4 = FUN_005a08b0(param_1,piVar5);
    } while (iVar4 != 0);
  }
  return 0;
}

