/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001df858  name=FUN_001df858  size=564  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_001df858(undefined4 param_1,undefined4 param_2,int param_3)

{
  bool bVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  undefined4 *puVar5;
  int *piVar6;
  undefined4 uVar7;
  undefined1 auStack_78 [80];
  int aiStack_28 [4];
  
  iVar2 = FUN_002482e0(param_3,0xef9080);
  if (iVar2 == 0) {
    FUN_0005da9c(1,0xd57818);
    uVar7 = 0xffffffff;
  }
  else {
    aiStack_28[0] = param_3;
    iVar3 = FUN_001999e0(param_1,param_2,uRam00e14988,iVar2,aiStack_28,0,0);
    if (iVar3 == -1) {
      piVar6 = (int *)FUN_00442914();
      if (*piVar6 == 0x1f60002) {
        FUN_0005da9c(1,0xd577e8,param_2);
        uVar7 = 0xffffffff;
      }
      else {
        puVar5 = (undefined4 *)FUN_00442914();
        FUN_0005da9c(1,0xd577cc,param_2,*puVar5);
        uVar7 = 0xffffffff;
      }
    }
    else {
      if (iRam00e1498c != 0) {
        FUN_0005da9c(0,0xd577b0,param_2,aiStack_28[0]);
      }
      uVar7 = 0;
      if ((iRam00ea29cc != 0) && (aiStack_28[0] != 0)) {
        FUN_003cada0(auStack_78,0x50,0xd57770,0xe14998,param_2);
        iVar3 = FUN_003970e8(auStack_78,0xd3d0a0);
        if (iVar3 == 0) {
          puVar5 = (undefined4 *)FUN_00442914();
          FUN_0005da9c(1,0xd57800,auStack_78,*puVar5);
        }
        else {
          iVar4 = FUN_00397dc0(iVar2,1,aiStack_28[0],iVar3);
          bVar1 = aiStack_28[0] != iVar4;
          if (bVar1) {
            puVar5 = (undefined4 *)FUN_00442914();
            FUN_0005da9c(1,0xd5777c,iVar4,*puVar5);
          }
          FUN_00396a64(iVar3);
          if (!bVar1) {
            FUN_0005da9c(0,0xd5779c,auStack_78);
          }
        }
      }
    }
    FUN_00245c34(iVar2);
  }
  return uVar7;
}

