/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0059be60  name=FUN_0059be60  size=480  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0059be60(int param_1,undefined4 param_2,undefined4 param_3)

{
  int iVar1;
  code *pcVar2;
  int iVar3;
  undefined4 uVar4;
  undefined4 auStack_50 [13];
  
  uVar4 = 0x50d;
  auStack_50[0] = 1;
  if (*(code **)(iRam00e9c254 + 0x3c) == reset_vector) {
    iVar3 = FUN_005baf2c(0xfc874c);
  }
  else {
    uVar4 = (**(code **)(iRam00e9c254 + 0x3c))();
    iVar3 = FUN_005baf2c(0xfc874c);
  }
  if (iVar3 == 0) {
    FUN_005baf84(0xfc874c,1);
    FUN_005baf94(0xfc86a8,uRam00fc87f8,0x5ac12c,auStack_50);
    FUN_0036fb9c(0xfc86a8);
    iVar3 = 0;
    uRam00e3a71c = uRam00e3a71c | 1;
    uRam00fc87f0 = param_2;
    uRam00fc87f4 = param_3;
    do {
      iVar1 = iVar3 * 4;
      iVar3 = iVar3 + 1;
      pcVar2 = *(code **)(iVar1 + 0xfc8698);
      if (pcVar2 != reset_vector) {
        (*pcVar2)();
      }
    } while (iVar3 < 2);
    (*(code *)puRam00e9bfe4[3])(*puRam00e9bfe4,1);
    if (param_1 == 0) {
      iRam00e3a728 = 0xfc874c;
      FUN_005baf64(0xfc86a8);
    }
    else {
      iRam00e3a728 = param_1;
      FUN_005baf64(0xfc86a8);
    }
    pcVar2 = *(code **)(iRam00e9c254 + 0x40);
  }
  else {
    pcVar2 = *(code **)(iRam00e9c254 + 0x40);
  }
  if (pcVar2 == reset_vector) {
    return;
  }
  (*pcVar2)(uVar4);
  return;
}

