/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00306858  name=FUN_00306858  size=508  xrefs=5
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00306858(uint *param_1,ushort *param_2,int param_3)

{
  uint uVar1;
  ushort uVar2;
  
  if (*param_1 != 0) {
    if ((*param_1 & 1) == 0) {
      for (; param_3 != 0; param_3 = param_3 + -1) {
        uVar1 = (uint)param_2[3] + (int)*(short *)((int)param_1 + 6);
        if ((uVar1 & 0xff00) != 0) {
          uVar1 = ((int)(uVar1 | uVar1 - 1) >> 0x1f & 0xffffff01U) + 0xff;
        }
        param_2[3] = (ushort)uVar1;
        uVar1 = (uint)param_2[2] + (int)*(short *)((int)param_1 + 10);
        if ((uVar1 & 0xff00) != 0) {
          uVar1 = ((int)(uVar1 | uVar1 - 1) >> 0x1f & 0xffffff01U) + 0xff;
        }
        param_2[2] = (ushort)uVar1;
        uVar1 = (uint)param_2[1] + (int)*(short *)((int)param_1 + 0xe);
        if ((uVar1 & 0xff00) != 0) {
          uVar1 = ((int)(uVar1 | uVar1 - 1) >> 0x1f & 0xffffff01U) + 0xff;
        }
        param_2[1] = (ushort)uVar1;
        uVar1 = (uint)*param_2 + (int)*(short *)((int)param_1 + 0x12);
        if ((uVar1 & 0xff00) != 0) {
          uVar1 = ((int)(uVar1 | uVar1 - 1) >> 0x1f & 0xffffff01U) + 0xff;
        }
        *param_2 = (ushort)uVar1;
        param_2 = param_2 + 4;
      }
    }
    else {
      for (; param_3 != 0; param_3 = param_3 + -1) {
        uVar1 = ((int)((uint)param_2[3] * (int)*(short *)(param_1 + 1)) >> 8) +
                (int)*(short *)((int)param_1 + 6);
        uVar2 = (ushort)uVar1;
        if ((uVar1 & 0xff00) != 0) {
          uVar2 = ((short)((ushort)(uVar1 >> 0x10) | (ushort)(uVar1 - 1 >> 0x10)) >> 0xf & 0xff01U)
                  + 0xff;
        }
        param_2[3] = uVar2;
        uVar1 = ((int)((uint)param_2[2] * (int)*(short *)(param_1 + 2)) >> 8) +
                (int)*(short *)((int)param_1 + 10);
        uVar2 = (ushort)uVar1;
        if ((uVar1 & 0xff00) != 0) {
          uVar2 = ((short)((ushort)(uVar1 >> 0x10) | (ushort)(uVar1 - 1 >> 0x10)) >> 0xf & 0xff01U)
                  + 0xff;
        }
        param_2[2] = uVar2;
        uVar1 = ((int)((uint)param_2[1] * (int)*(short *)(param_1 + 3)) >> 8) +
                (int)*(short *)((int)param_1 + 0xe);
        uVar2 = (ushort)uVar1;
        if ((uVar1 & 0xff00) != 0) {
          uVar2 = ((short)((ushort)(uVar1 >> 0x10) | (ushort)(uVar1 - 1 >> 0x10)) >> 0xf & 0xff01U)
                  + 0xff;
        }
        param_2[1] = uVar2;
        uVar1 = ((int)((uint)*param_2 * (int)*(short *)(param_1 + 4)) >> 8) +
                (int)*(short *)((int)param_1 + 0x12);
        uVar2 = (ushort)uVar1;
        if ((uVar1 & 0xff00) != 0) {
          uVar2 = ((short)((ushort)(uVar1 >> 0x10) | (ushort)(uVar1 - 1 >> 0x10)) >> 0xf & 0xff01U)
                  + 0xff;
        }
        *param_2 = uVar2;
        param_2 = param_2 + 4;
      }
    }
  }
  return;
}

