/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00432784  name=FUN_00432784  size=20  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00432784(void)

{
  uRam00e107f4 = 0x443bf4;
  return;
}

