/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003b4b18  name=FUN_003b4b18  size=804  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4
FUN_003b4b18(undefined4 param_1,undefined4 param_2,int param_3,undefined4 param_4,undefined4 param_5
            )

{
  bool bVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  undefined4 uVar6;
  uint uVar7;
  uint uVar8;
  int iVar9;
  int aiStack_bc [35];
  
  uVar6 = 0;
  if ((*(uint *)(param_3 + 0x10) & 4) != 0) {
    FUN_003bccc8(3,0x7e,0x42,0,0);
    return 0xffffffff;
  }
  iVar2 = FUN_003b5930(param_3);
  if (iVar2 == 0) {
    uVar6 = FUN_003b5fa8(param_1,1);
    return uVar6;
  }
  FUN_003b2c6c(param_5);
  iVar3 = FUN_003b3030(param_5);
  aiStack_bc[1] = FUN_003b3030(param_5);
  if (((iVar3 == 0) || (aiStack_bc[1] == 0)) ||
     (iVar4 = FUN_003b6748(aiStack_bc[1],param_2,param_4,param_5), iVar4 == 0)) goto LAB_003b4e1c;
  if (*(int *)(aiStack_bc[1] + 4) == 0) {
    FUN_003b5fa8(param_1,0);
  }
  else {
    if (iVar2 < 0x2a0) {
      if (0xef < iVar2) {
        uVar7 = 5;
        goto LAB_003b4c4c;
      }
      if (0x4f < iVar2) {
        uVar7 = 4;
        goto LAB_003b4c4c;
      }
      if (0x17 < iVar2) {
        uVar7 = 3;
        goto LAB_003b4c4c;
      }
      uVar7 = 1;
    }
    else {
      uVar7 = 6;
LAB_003b4c4c:
      iVar4 = FUN_003b6974(iVar3,aiStack_bc[1],aiStack_bc[1],param_4,param_5);
      if (iVar4 == 0) goto LAB_003b4e1c;
      iVar4 = 1;
      iVar9 = 1 << (uVar7 - 1 & 0x3f);
      if (1 < iVar9) {
        do {
          iVar5 = FUN_003b3030(param_5);
          aiStack_bc[iVar4 + 1] = iVar5;
          if ((iVar5 == 0) ||
             (iVar5 = FUN_003b6974(aiStack_bc[iVar4 + 1],aiStack_bc[iVar4],iVar3,param_4,param_5),
             iVar5 == 0)) goto LAB_003b4e1c;
          iVar4 = iVar4 + 1;
        } while (iVar4 < iVar9);
      }
    }
    bVar1 = true;
    iVar2 = iVar2 + -1;
    iVar3 = FUN_003b5fa8(param_1,1);
    if (iVar3 == 0) goto LAB_003b4e1c;
    do {
      iVar3 = FUN_003b64c0(param_3,iVar2);
      while (iVar3 == 0) {
        if ((!bVar1) && (iVar3 = FUN_003b6974(param_1,param_1,param_1,param_4,param_5), iVar3 == 0))
        goto LAB_003b4e1c;
        if (iVar2 == 0) goto LAB_003b4e18;
        iVar2 = iVar2 + -1;
        iVar3 = FUN_003b64c0(param_3,iVar2);
      }
      uVar8 = 1;
      iVar3 = 0;
      iVar4 = 1;
      if (1 < uVar7) {
        iVar9 = iVar2 + -1;
        while (-1 < iVar9) {
          iVar9 = FUN_003b64c0(param_3,iVar2 - iVar4);
          if (iVar9 != 0) {
            uVar8 = uVar8 << (iVar4 - iVar3 & 0x3fU) | 1;
            iVar3 = iVar4;
          }
          iVar4 = iVar4 + 1;
          if ((int)uVar7 <= iVar4) break;
          iVar9 = iVar2 - iVar4;
        }
      }
      if ((!bVar1) && (iVar4 = 0, 0 < iVar3 + 1)) {
        do {
          iVar9 = FUN_003b6974(param_1,param_1,param_1,param_4,param_5);
          if (iVar9 == 0) goto LAB_003b4e1c;
          iVar4 = iVar4 + 1;
        } while (iVar4 < iVar3 + 1);
      }
      iVar4 = FUN_003b6974(param_1,param_1,aiStack_bc[((int)uVar8 >> 1) + 1],param_4,param_5);
      if (iVar4 == 0) goto LAB_003b4e1c;
      iVar2 = iVar2 - (iVar3 + 1);
      bVar1 = false;
    } while (-1 < iVar2);
  }
LAB_003b4e18:
  uVar6 = 1;
LAB_003b4e1c:
  FUN_003b311c(param_5);
  return uVar6;
}

