/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0029e858  name=FUN_0029e858  size=1116  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0029e858(int param_1)

{
  char cVar1;
  uint uVar2;
  undefined4 uVar3;
  int iVar4;
  int iVar5;
  uint uVar6;
  int iVar7;
  char *pcVar8;
  int iVar9;
  byte in_cr0;
  byte in_cr1;
  byte unaff_cr2;
  byte unaff_cr3;
  byte unaff_cr4;
  byte in_cr5;
  byte in_cr6;
  byte in_cr7;
  undefined8 uVar10;
  undefined1 auStack_80 [16];
  undefined4 uStack_70;
  uint *puStack_6c;
  int iStack_68;
  undefined4 uStack_60;
  uint *puStack_5c;
  undefined4 uStack_58;
  undefined4 uStack_50;
  uint *puStack_4c;
  undefined4 uStack_48;
  undefined4 auStack_40 [4];
  uint uStack_30;
  
  *(undefined4 *)(param_1 + 0x1328) = 1;
  uStack_30 = (uint)(in_cr0 & 0xf) << 0x1c | (uint)(in_cr1 & 0xf) << 0x18 |
              (uint)(unaff_cr2 & 0xf) << 0x14 | (uint)(unaff_cr3 & 0xf) << 0x10 |
              (uint)(unaff_cr4 & 0xf) << 0xc | (uint)(in_cr5 & 0xf) << 8 | (uint)(in_cr6 & 0xf) << 4
              | (uint)(in_cr7 & 0xf);
  if (*(int *)(param_1 + 0x142c) == 0) {
    pcVar8 = (char *)0xcd8b14;
    iVar7 = 0;
    cVar1 = cRam00cd8b14;
    while (cVar1 != '\0') {
      FUN_002d13d4(param_1 + 0x1424,pcVar8,iVar7);
      cVar1 = *pcVar8;
      while (cVar1 != '\0') {
        pcVar8 = pcVar8 + 1;
        cVar1 = *pcVar8;
      }
      pcVar8 = pcVar8 + 1;
      iVar7 = iVar7 + 1;
      cVar1 = *pcVar8;
    }
  }
  iVar7 = FUN_00248640(0x588);
  FUN_0027f64c(iVar7,*(undefined4 *)(param_1 + 0x1668));
  uVar3 = 0;
  if (iVar7 != 0) {
    *(int *)(iVar7 + 0x74) = param_1 + 0x590;
    FUN_0025a874(param_1 + 0x590,iVar7);
    uVar3 = *(undefined4 *)(param_1 + 0x135c);
    *(undefined4 *)(iVar7 + 0x6c) = 15999;
    *(int *)(iVar7 + 0x29c) = param_1;
    uVar3 = FUN_002c320c(param_1 + 0x1364,uVar3);
    FUN_002c38ec(auStack_80,param_1,uVar3);
    FUN_00289da4(iVar7 + 0xd8,uVar3);
    FUN_00289da4(param_1 + 0xe28,uVar3);
    iStack_68 = 0;
    uStack_70 = 6;
    puStack_6c = (uint *)0x0;
    FUN_00287c74(&uStack_70,param_1);
    uVar3 = FUN_002c1ed8(uVar3,2);
    FUN_002c2b6c(uVar3,iStack_68);
    iVar5 = iStack_68;
    FUN_0029dfd4(param_1,iStack_68,0xd5fa44,0x2ec564,0);
    FUN_0029dfd4(param_1,iVar5,0xd5fa50,0x2ec564,1);
    uStack_58 = 0;
    uStack_60 = 6;
    puStack_5c = (uint *)0x0;
    FUN_002dc3b0(param_1,0x65,9,1,&uStack_60);
    FUN_00285f0c(iVar5,param_1 + 0xd00,&uStack_60,0,0);
    iVar9 = param_1 + 0xd14;
    uStack_50 = 6;
    puStack_4c = (uint *)0x0;
    uStack_48 = 0;
    FUN_002dc3b0(param_1,0x65,9,1,&uStack_50);
    FUN_00285f0c(iVar5,iVar9,&uStack_50,0,0x80);
    FUN_002a0870(param_1,uStack_58,iVar9,1);
    FUN_002a0870(param_1,uStack_48,iVar9,1);
    FUN_0029e794(param_1);
    FUN_00256570(param_1,iVar5);
    uVar10 = FUN_002f3898();
    FUN_002868b8(iVar5,0xd5f720,(int)((ulonglong)uVar10 >> 0x20),(int)uVar10,0);
    uVar10 = FUN_002f38ac();
    FUN_002868b8(iVar5,0xd5f724,(int)((ulonglong)uVar10 >> 0x20),(int)uVar10,0);
    iVar9 = FUN_00248300(0x4526);
    if (iVar9 != 0) {
      auStack_40[0] = 0x4526;
      iVar4 = FUN_002cdd70(iVar9,auStack_40,0xe15874,0x1979);
      if (iVar4 == 0) {
        FUN_00282dd8(iVar7,iVar9,0x4526);
        FUN_00283388(iVar7);
        FUN_0027f168(iVar7);
        FUN_0029ecb4(param_1,iVar7);
      }
      FUN_00245be8(iVar9);
    }
    for (iVar5 = *(int *)(iVar5 + 0x20); iVar5 != 0; iVar5 = *(int *)(iVar5 + 0x14)) {
      *(ushort *)(iVar5 + 0x20) = *(ushort *)(iVar5 + 0x20) | 1;
    }
    FUN_0027f954(iVar7);
    FUN_00245c34(iVar7);
    *(undefined4 *)(param_1 + 0x1328) = 0;
    FUN_002875f0(&uStack_50);
    if (puStack_4c != (uint *)0x0) {
      uVar2 = *puStack_4c;
      uVar6 = ((int)(uVar2 << 1 | uVar2 >> 0x1f) >> 1) - 1;
      *puStack_4c = uVar6 & 0x7fffffff | uVar2 & 0x80000000;
      if ((int)(uVar6 * 2) < 1) {
        FUN_0028a778();
      }
    }
    FUN_002875f0(&uStack_60);
    if (puStack_5c != (uint *)0x0) {
      uVar2 = *puStack_5c;
      uVar6 = ((int)(uVar2 << 1 | uVar2 >> 0x1f) >> 1) - 1;
      *puStack_5c = uVar6 & 0x7fffffff | uVar2 & 0x80000000;
      if ((int)(uVar6 * 2) < 1) {
        FUN_0028a778();
      }
    }
    FUN_002875f0(&uStack_70);
    if (puStack_6c != (uint *)0x0) {
      uVar2 = *puStack_6c;
      uVar6 = ((int)(uVar2 << 1 | uVar2 >> 0x1f) >> 1) - 1;
      *puStack_6c = uVar6 & 0x7fffffff | uVar2 & 0x80000000;
      if ((int)(uVar6 * 2) < 1) {
        FUN_0028a778();
      }
    }
    FUN_002c3b54(auStack_80);
    uVar3 = 1;
  }
  return uVar3;
}

