/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0045ec9c  name=FUN_0045ec9c  size=348  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_0045ec9c(int param_1,int param_2,int param_3)

{
  int iVar1;
  int iVar2;
  
  if (param_1 == 0) {
    iVar1 = 0x16;
  }
  else if ((*(uint *)(param_1 + 0xc) & 0x2000000) == 0) {
    FUN_003cb350(0x470e2b);
    iVar1 = 0x16;
  }
  else {
    if (((*(uint *)(param_1 + 0xc) & 0xf) == 1) && (*(int *)(param_1 + 0x24) == 1)) {
      iVar1 = **(int **)(param_1 + 0x10);
      if (iVar1 != 0) {
        if (param_3 == 0) {
          return 0xf;
        }
        do {
          iVar2 = FUN_0045ec9c(iVar1,param_2,param_3);
          if (iVar2 != 0) {
            return iVar2;
          }
          iVar1 = *(int *)(iVar1 + 4);
        } while (iVar1 != 0);
      }
      if (param_2 != 0) {
        FUN_0045b5e4(uRam00e295c4,*(undefined4 *)(param_1 + 0x10));
      }
    }
    iVar1 = *(int *)(param_1 + 0x24);
    if (iVar1 < 2) {
      if (iVar1 == 0) {
        FUN_003cb350(0x470e4c,0,*(undefined4 *)(param_1 + 0x18));
        return 0x16;
      }
      FUN_0045eb40(param_1);
      if (param_2 != 0) {
        FUN_0045b5e4(uRam00e295c4,*(undefined4 *)(param_1 + 0x18));
        FUN_0045b5e4(uRam00e295c4,param_1);
        iRam00e29624 = iRam00e29624 + -1;
      }
    }
    else {
      *(int *)(param_1 + 0x24) = iVar1 + -1;
    }
    iVar1 = 0;
  }
  return iVar1;
}

