/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00474cc4  name=FUN_00474cc4  size=408  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00474cc4(char *param_1,int *param_2,int *param_3)

{
  char cVar1;
  int iVar2;
  char *pcVar3;
  char *pcVar4;
  undefined4 uVar5;
  
  iVar2 = FUN_0039b0f0();
  if (iVar2 != 0) {
    iVar2 = FUN_0039b0f0(param_1);
    pcVar4 = param_1 + iVar2 + -1;
    if (param_1 < pcVar4) {
      cVar1 = *pcVar4;
      while ((cVar1 == ' ' && (pcVar4 = pcVar4 + -1, param_1 < pcVar4))) {
        cVar1 = *pcVar4;
      }
    }
    pcVar4[1] = '\0';
    if (param_1 < pcVar4) {
      cVar1 = *pcVar4;
      while (((((cVar1 != ' ' && (cVar1 = *pcVar4, cVar1 != '<')) && (cVar1 != '>')) &&
              ((cVar1 != ')' && (cVar1 != ';')))) &&
             ((cVar1 != '\"' && (pcVar4 = pcVar4 + -1, param_1 < pcVar4))))) {
        cVar1 = *pcVar4;
      }
    }
    pcVar3 = pcVar4 + 1;
    if (param_1 < pcVar4) {
      cVar1 = *pcVar4;
      while ((cVar1 == ' ' && (pcVar4 = pcVar4 + -1, param_1 < pcVar4))) {
        cVar1 = *pcVar4;
      }
    }
    if (*pcVar4 == '>') {
      if ((pcVar4 != param_1) && (pcVar4[-1] == '>')) {
        return 0;
      }
      if (*param_3 != 0) {
        uVar5 = 0x48a9d1;
LAB_00474e28:
        FUN_003cb248(uVar5);
        return 0xffffffff;
      }
      *param_3 = (int)pcVar3;
    }
    else {
      if (*pcVar4 != '<') {
        return 0;
      }
      if ((pcVar4 != param_1) && (pcVar4[-1] == '<')) {
        return 0;
      }
      if (*param_2 != 0) {
        uVar5 = 0x48a9f7;
        goto LAB_00474e28;
      }
      *param_2 = (int)pcVar3;
    }
    *pcVar4 = '\0';
  }
  return 0;
}

