/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0059a15c  name=FUN_0059a15c  size=88  xrefs=4
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0059a15c(int param_1,undefined4 param_2)

{
  int iVar1;
  int iVar2;
  uint uVar3;
  
  iVar2 = 0xfc8458;
  if (param_1 == 0) {
    iVar2 = 0xfc8468;
  }
  uVar3 = 0;
  do {
    iVar1 = uVar3 * 4;
    uVar3 = uVar3 + 1;
    if (*(int *)(iVar1 + iVar2) == 0) {
      *(undefined4 *)(iVar1 + iVar2) = param_2;
      return 0;
    }
  } while (uVar3 < 4);
  return 0xffffffff;
}

