/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001da918  name=FUN_001da918  size=72  xrefs=4
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_001da918(undefined4 param_1)

{
  int iVar1;
  
  iVar1 = FUN_0044e510(uRam00e13d8c,0x5656002a,param_1);
  return -(uint)(iVar1 == -1);
}

