/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00457990  name=FUN_00457990  size=420  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


uint FUN_00457990(int param_1,undefined4 param_2,uint param_3)

{
  int iVar1;
  int iVar2;
  int *piVar3;
  
  while( true ) {
    FUN_005accf4(param_1 + 0x24,0xffffffff);
    FUN_005accf4(param_1 + 0x90,0xffffffff);
    if (*(short *)(param_1 + 0xfc) != 0) {
      *(short *)(param_1 + 0xfc) = *(short *)(param_1 + 0xfc) + -1;
      FUN_005ad104(param_1 + 0x90);
      FUN_00442990(0x48);
      return 0;
    }
    piVar3 = *(int **)(param_1 + 0x20);
    iVar1 = FUN_00499eb4(piVar3);
    if (iVar1 == 0) break;
    FUN_005ad104(param_1 + 0x90);
  }
  if ((*(ushort *)(param_1 + 0x17e) & 0x40) == 0) {
    param_3 = FUN_00499cd0(piVar3,param_2,param_3);
  }
  else {
    if ((*(char *)(param_1 + 0x17d) == '\0') && (iVar1 = piVar3[1], *piVar3 != iVar1)) {
      iVar2 = iVar1 + 1;
      *(undefined1 *)(param_1 + 0x17d) = *(undefined1 *)(piVar3[3] + iVar1);
      if (piVar3[2] == iVar2) {
        iVar2 = 0;
      }
      piVar3[1] = iVar2;
    }
    if ((int)(uint)*(byte *)(param_1 + 0x17d) < (int)param_3) {
      param_3 = (uint)*(byte *)(param_1 + 0x17d);
    }
    FUN_00499cd0(piVar3,param_2,param_3);
    *(char *)(param_1 + 0x17d) = *(char *)(param_1 + 0x17d) - (char)param_3;
  }
  if (((*(ushort *)(param_1 + 0x17e) & 4) != 0) && (*(char *)(param_1 + 0xfe) != '\0')) {
    iVar1 = FUN_00499efc(piVar3);
    if ((*(ushort *)(param_1 + 0x17e) & 0x40) != 0) {
      iVar1 = iVar1 - (*(byte *)(param_1 + 0x17c) + 1);
    }
    if (*(int *)(param_1 + 0x228) < iVar1) {
      FUN_004578ec(param_1,0);
    }
  }
  iVar1 = FUN_00499eb4(piVar3);
  if (iVar1 == 0) {
    FUN_005ad104(param_1 + 0x24);
  }
  FUN_005ad104(param_1 + 0x90);
  return param_3;
}

