/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002ab768  name=FUN_002ab768  size=204  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002ab768(int *param_1,int param_2)

{
  int iVar1;
  undefined4 uVar2;
  undefined4 uVar3;
  
  if (*param_1 != 0) {
    iVar1 = FUN_002852ac(*param_1,0xd5fd64);
    if (iVar1 != 0) {
      FUN_0028773c(iVar1,param_2);
    }
    if (param_1[0x17] == 0) {
      uVar3 = 0xd79e9c;
      uVar2 = 0xd5fd84;
      param_1[0x17] = 1;
      if (param_2 == 0) {
        uVar2 = 0xd5fda4;
        uVar3 = 0xd728ac;
      }
      FUN_002a9e98(param_1,uVar2,uVar3,0,0,0);
      param_1[0x17] = 0;
    }
  }
  return;
}

