/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0031e6f0  name=FUN_0031e6f0  size=340  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0031e6f0(int param_1,undefined4 param_2,undefined4 param_3,int param_4,int param_5,
                 int param_6,int param_7,int param_8,uint *param_9,uint param_10,uint param_11)

{
  int iVar1;
  uint uVar2;
  
  if (param_6 != 0 && param_7 != 0) {
    if (param_8 != 0 && param_9 != (uint *)0x0) {
      iVar1 = ((((int)param_11 >> 1) + (uint)((int)param_11 < 0 && (param_11 & 1) != 0)) * param_5 +
              ((int)param_10 >> 1) + (uint)((int)param_10 < 0 && (param_10 & 1) != 0)) * 2;
      uVar2 = *(int *)(param_1 + *(short *)(param_6 + (param_11 * param_4 + param_10) * 2) * 4) +
              *(int *)(*(short *)(param_8 + iVar1) * 4 + param_1 + 0x400) +
              *(int *)(*(short *)(param_7 + iVar1) * 4 + param_1 + 0x800) + 0x7fdff800;
      if ((uVar2 & 0x40100400) != 0) {
        if ((uVar2 & 0x400) != 0) {
          if ((uVar2 & 0x800) == 0) {
            uVar2 = uVar2 | 0x3ff;
          }
          else {
            uVar2 = (uVar2 & 0xfffffc00) + 0x400;
          }
        }
        if ((uVar2 & 0x100000) != 0) {
          if ((uVar2 & 0x200000) == 0) {
            uVar2 = uVar2 | 0xffc00;
          }
          else {
            uVar2 = (uVar2 & 0xfff003ff) + 0x100000;
          }
        }
        if ((uVar2 & 0x40000000) != 0) {
          if ((int)uVar2 < 0) {
            uVar2 = (uVar2 & 0xc00fffff) + 0x40000000;
          }
          else {
            uVar2 = uVar2 & 0x3fffffff | 0x3ff00000;
          }
        }
      }
      *param_9 = uVar2 >> 6 & 0xff0000 | uVar2 >> 4 & 0xff00 | uVar2 >> 2 & 0xff | 0xff000000;
    }
  }
  return;
}

