/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002976a4  name=FUN_002976a4  size=336  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4
FUN_002976a4(int param_1,undefined4 param_2,char *param_3,undefined4 param_4,undefined4 param_5)

{
  undefined4 uVar1;
  int iVar2;
  int iVar3;
  
  uVar1 = 0;
  if (param_3 != (char *)0x0) {
    uVar1 = FUN_002589a0(param_4,0xd4bc54);
    iVar3 = 0;
    if ((*(char *)(param_1 + 0x25) != '\0') &&
       (iVar3 = FUN_00297490(param_1,param_2,param_5), iVar3 == 0)) {
      return 0;
    }
    iVar2 = FUN_0039ad64(param_3,0xd38c84);
    if (((iVar2 == 0) ||
        (((*param_3 == '*' && (param_3[1] == '.')) &&
         (iVar2 = FUN_00297140(param_3 + 2), iVar2 != 0)))) ||
       ((iVar2 = FUN_00297140(param_3), iVar2 != 0 || (iVar2 = FUN_00297204(param_3), iVar2 != 0))))
    {
      FUN_00296ed4(param_1,param_2,param_3,uVar1,iVar3);
      uVar1 = 1;
    }
    else {
      if (iVar3 != 0) {
        FUN_00297380(iVar3);
        FUN_00245c34(iVar3);
      }
      uVar1 = 0;
    }
  }
  return uVar1;
}

