/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00253c70  name=FUN_00253c70  size=60  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00253c70(int param_1)

{
  undefined4 uVar1;
  
  uVar1 = 0;
  if (*(int *)(param_1 + 4) != 0) {
    uVar1 = FUN_002c80a8();
  }
  return uVar1;
}

