/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004499e8  name=FUN_004499e8  size=60  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_004499e8(int param_1,undefined4 param_2)

{
  int iVar1;
  
  if (param_1 == 0) {
    iVar1 = FUN_005bad3c(param_2);
  }
  else {
    iVar1 = FUN_005bad3c();
    iVar1 = iVar1 + 0x20;
  }
  return iVar1;
}

