/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0051dff0  name=FUN_0051dff0  size=524  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0051dff0(undefined4 param_1,undefined4 param_2)

{
  undefined4 uVar1;
  undefined4 uVar2;
  undefined4 uVar3;
  undefined4 uVar4;
  int iVar5;
  undefined4 *puVar6;
  undefined4 uVar7;
  int iVar8;
  undefined1 *puVar9;
  int iVar10;
  undefined1 auStack_78 [8];
  undefined4 auStack_70 [4];
  undefined4 uStack_60;
  undefined4 uStack_5c;
  undefined4 uStack_58;
  undefined4 uStack_54;
  undefined4 uStack_50;
  undefined4 uStack_40;
  undefined4 uStack_3c;
  undefined4 uStack_38;
  
  uStack_60 = uRam00d2fbfc;
  uStack_5c = uRam00d2fc00;
  uStack_58 = uRam00d2fc04;
  uStack_54 = uRam00d2fc08;
  uStack_50 = uRam00d2fc0c;
  uStack_3c = uRam00d2fc14;
  uVar7 = 0;
  iVar8 = 0;
  uStack_40 = uRam00d2fc10;
  uStack_38 = uRam00d2fc18;
  uVar1 = FUN_004ad1f0();
  auStack_70[0] = FUN_004ad1f0();
  auStack_70[1] = FUN_004ad1f0();
  uVar2 = FUN_004ad1f0();
  uVar3 = FUN_004ad1f0();
  uVar4 = FUN_004ad1f0();
  iVar5 = FUN_004ad1f0();
  FUN_005c6fd4(&uStack_60,auStack_70[0]);
  FUN_005c6fd4(&uStack_40,auStack_70[1]);
  do {
    FUN_004ad634(uVar1,0x200,0,0);
    iVar10 = 0;
    puVar9 = auStack_78;
    do {
      FUN_005c6dd4(uVar2,uVar1,*(undefined4 *)(puVar9 + 8));
      FUN_005c6f54(uVar3,uVar1,*(undefined4 *)(puVar9 + 8),param_2);
      puVar6 = (undefined4 *)(puVar9 + 8);
      puVar9 = puVar9 + 4;
      FUN_005c6e54(uVar4,uVar3,*puVar6,param_2);
      FUN_005c6d94(iVar5,uVar2,uVar4);
      iVar10 = iVar10 + 1;
      if (*(int *)(iVar5 + 4) != 0) {
        puVar6 = (undefined4 *)FUN_00398e8c();
        FUN_0039995c(*puVar6,0xd8d1a0);
        goto LAB_0051e17c;
      }
    } while (iVar10 < 2);
    iVar8 = iVar8 + 1;
  } while (iVar8 < 100);
  uVar7 = 1;
LAB_0051e17c:
  FUN_004ad194(uVar1);
  FUN_004ad194(auStack_70[0]);
  FUN_004ad194(auStack_70[1]);
  FUN_004ad194(uVar2);
  FUN_004ad194(uVar3);
  FUN_004ad194(uVar4);
  FUN_004ad194(iVar5);
  return uVar7;
}

