/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00257024  name=FUN_00257024  size=72  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00257024(undefined4 *param_1)

{
  *param_1 = 0xe0a768;
  FUN_002c757c(param_1 + 1,1);
  FUN_002c7590(param_1 + 1);
  return;
}

