/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0025e8c0  name=FUN_0025e8c0  size=104  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0025e8c0(int *param_1)

{
  int iVar1;
  
  iVar1 = *param_1;
  if (iVar1 != 0) {
    *param_1 = *(int *)(iVar1 + 0x10);
    FUN_0025ebe8(iVar1);
    FUN_00245c34(iVar1);
    if (*param_1 == 0) {
      param_1[1] = 0;
    }
  }
  return;
}

