/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005b1edc  name=FUN_005b1edc  size=508  xrefs=189
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_005b1edc(int param_1)

{
  undefined4 *puVar1;
  int iVar2;
  int iVar3;
  
  iVar2 = iRam00e9c3e0;
  if (iRam00e2942c < 1) {
    if (iRam00e29390 != 0) {
      if (((uRam00e9c3d0 & 0x10000007) == 0x10000007) && ((*(ushort *)(iRam00e9c3e0 + 8) & 4) != 0))
      {
        iVar3 = FUN_005bad5c(iRam00e9c3e0,uRam00e3a7f0);
        if (iVar3 == 0) {
          iVar3 = FUN_005bad5c(iVar2,uRam00e3a7f0);
          if ((iVar3 == 0) && ((*(ushort *)(iVar2 + 8) & 4) != 0)) {
            (**(code **)(*(int *)(iVar2 + 0x30) + 0x1c))(0x2712,1,param_1);
          }
        }
        else {
          (*pcRam00e9c6cc)(0x275d,2,iVar2,uRam00e3a7f0);
        }
      }
      if ((uRam00e9bffc & 0x10000100) == 0x10000100) {
        (*pcRam00e9bf80)(0x2712,2,iVar2,param_1,0,0,0,0);
      }
    }
    uRam00e9c05c = 1;
    if (param_1 == 0) {
      (**(code **)(iRam010d0590 + 0x18))(0x10d0584,iRam00e9c3e0 + 0x40);
      (**(code **)(iRam010d0590 + 0x10))
                (0x10d0584,iRam00e9c3e0 + 0x40,*(undefined4 *)(iRam00e9c3e0 + 0x74));
    }
    else {
      FUN_005b5d44(param_1);
    }
    iVar2 = FUN_00372534();
    if (iVar2 == 1) {
      iVar2 = -1;
      puVar1 = (undefined4 *)FUN_00442914();
      *puVar1 = 4;
    }
  }
  else {
    puVar1 = (undefined4 *)FUN_00442914();
    *puVar1 = 0x430001;
    iVar2 = -1;
  }
  return iVar2;
}

