/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00410348  name=FUN_00410348  size=40  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00410348(int param_1)

{
  uRam00e28cb0 = *(undefined4 *)(param_1 + 0x14);
  uRam00e9bfdc = *(undefined4 *)(param_1 + 4);
  return 0;
}

