/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00058258  name=FUN_00058258  size=204  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00058258(void)

{
  int iVar1;
  int iVar2;
  undefined4 uStack_20;
  undefined4 uStack_1c;
  undefined2 uStack_18;
  
  iVar1 = FUN_0044f4cc(uRam00e10950,0,0x1b6);
  if (-1 < iVar1) {
    uStack_18 = 0;
    uStack_20 = 0;
    uStack_1c = 0;
    iVar2 = FUN_0044e144(iVar1,&uStack_20,10);
    FUN_0044f9fc(iVar1);
    if (0 < iVar2) {
      iVar1 = FUN_0039b188(&uStack_20,0xd3d58c,8);
      if (iVar1 == 0) {
        return 2;
      }
      iVar1 = FUN_0039b188(&uStack_20,0xd3d584,7);
      if (iVar1 == 0) {
        return 1;
      }
    }
  }
  return 0;
}

