/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0048c5c0  name=FUN_0048c5c0  size=128  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0048c5c0(undefined4 param_1)

{
  undefined4 uVar1;
  undefined4 auStack_18 [3];
  
  if (pcRam00e9bf50 != reset_vector) {
    (*pcRam00e9bf50)(0,auStack_18);
  }
  uVar1 = FUN_0044e510(param_1,0x15,0);
  if (pcRam00e9bf50 != reset_vector) {
    (*pcRam00e9bf50)(auStack_18[0],0);
  }
  return uVar1;
}

