/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0058cfa8  name=FUN_0058cfa8  size=196  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


/* WARNING: Type propagation algorithm not settling */

int FUN_0058cfa8(undefined4 param_1,int param_2)

{
  int iVar1;
  char cVar2;
  int aiStack_18 [3];
  
  aiStack_18[0] = 0;
  aiStack_18[1] = 0;
  FUN_0035ad18(0x27c7,&LAB_005a1268,8);
  if (param_2 == 0) {
    iVar1 = -7;
  }
  else {
    FUN_0058a394(param_1,aiStack_18);
    if (aiStack_18[0] == 0) {
      iVar1 = -7;
    }
    else {
      aiStack_18[1] = 1;
      cVar2 = FUN_0058c7e8(aiStack_18[0],0x80,8,0,0,aiStack_18 + 1,param_2);
      iVar1 = (int)cVar2;
    }
  }
  return iVar1;
}

