/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005b72ec  name=FUN_005b72ec  size=380  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_005b72ec(int param_1,uint param_2)

{
  bool bVar1;
  uint uVar2;
  code *pcVar3;
  short sVar4;
  
  if (iRam00e29390 != 0) {
    if ((uRam00e9c3d0 & 0x10000003) == 0x10000003) {
      (*pcRam00e9c060)(0x263,param_1);
    }
    if ((uRam00e9bffc & 0x10000010) == 0x10000010) {
      (*pcRam00e9bf80)(0x263,1,0,param_1,0,0,0,0);
    }
  }
  FUN_0036fd0c();
  sVar4 = *(short *)(param_1 + 0x52) + -1;
  *(short *)(param_1 + 0x52) = sVar4;
  FUN_0036fd24();
  if (sVar4 == 0) {
    uVar2 = uRam00e9c310 + ((int)param_2 >> 0x1f) + (uint)CARRY4(uRam00e9c314,param_2);
    bVar1 = uVar2 < uRam00e9c310;
    if (uVar2 == uRam00e9c310) {
      bVar1 = uRam00e9c314 + param_2 < uRam00e9c314;
    }
    if (bVar1) {
      FUN_005b6f64();
      uRam00e9c310 = 0;
      uRam00e9c314 = 0;
    }
    if (*(short *)(param_1 + 0x50) == 1) {
      pcVar3 = *(code **)(iRam0100b314 + 0x1c);
    }
    else {
      pcVar3 = *(code **)(iRam0100b314 + 0x10);
    }
    (*pcVar3)(0x100b308,param_1 + 0x40,param_2);
    *(undefined2 *)(param_1 + 0x50) = 1;
  }
  return 0;
}

