/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004587a8  name=FUN_004587a8  size=240  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_004587a8(int param_1,int param_2,int param_3)

{
  int iVar1;
  int iVar2;
  
  FUN_005b1b88();
  iVar2 = param_3;
  while( true ) {
    if (iVar2 < 1) {
      FUN_005b1cdc();
      return param_3;
    }
    FUN_005accf4(param_1 + 0x108,0xffffffff);
    FUN_005accf4(param_1 + 0x90,0xffffffff);
    if (*(short *)(param_1 + 0x174) != 0) break;
    *(undefined1 *)(param_1 + 0x17a) = 1;
    iVar1 = FUN_00499da8(*(undefined4 *)(param_1 + 0x104),param_2,iVar2);
    *(undefined1 *)(param_1 + 0x17a) = 0;
    FUN_004581d4(param_1);
    iVar2 = iVar2 - iVar1;
    param_2 = param_2 + iVar1;
    iVar1 = FUN_00499efc(*(undefined4 *)(param_1 + 0x104));
    if (0 < iVar1) {
      FUN_005ad104(param_1 + 0x108);
    }
    FUN_005ad104(param_1 + 0x90);
  }
  *(short *)(param_1 + 0x174) = *(short *)(param_1 + 0x174) + -1;
  FUN_005ad104(param_1 + 0x90);
  FUN_00442990(0x48);
  FUN_005b1cdc();
  return param_3 - iVar2;
}

