/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004b3880  name=FUN_004b3880  size=100  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


uint FUN_004b3880(int param_1,int param_2)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  
  uVar3 = *(uint *)(param_1 + 4) & 0x100;
  uVar1 = *(uint *)(param_2 + 4) & 0x100;
  uVar2 = (int)-uVar3 >> 0x1f | 1;
  if (uVar1 == uVar3) {
    uVar3 = FUN_004b9568();
    uVar2 = -uVar3;
    if (uVar1 == 0) {
      uVar2 = uVar3;
    }
  }
  return uVar2;
}

