/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0019c068  name=FUN_0019c068  size=188  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0019c068(int param_1)

{
  int iVar1;
  undefined1 *puVar2;
  int iVar3;
  undefined1 uVar4;
  
  iVar3 = 0;
  iVar1 = param_1;
  do {
    uVar4 = (undefined1)iVar3;
    *(undefined1 *)(iVar1 + 0x3b5) = uVar4;
    *(undefined1 *)(iVar1 + 0x3bb) = uVar4;
    *(undefined1 *)(iVar1 + 0x3b7) = uVar4;
    *(undefined1 *)(iVar1 + 0x3bd) = uVar4;
    iVar3 = iVar3 + 1;
    *(undefined1 *)(iVar1 + 0x3b4) = 0;
    *(undefined1 *)(iVar1 + 0x3ba) = 3;
    *(undefined1 *)(iVar1 + 0x3b6) = 2;
    *(undefined1 *)(iVar1 + 0x3bc) = 1;
    iVar1 = iVar1 + 0x4b8;
  } while (iVar3 < 2);
  iVar1 = 0;
  if (0 < *(int *)(param_1 + 0x1320)) {
    puVar2 = (undefined1 *)(param_1 + 0xee9);
    do {
      uVar4 = (undefined1)iVar1;
      puVar2[5] = uVar4;
      puVar2[2] = uVar4;
      puVar2[-1] = uVar4;
      puVar2[8] = uVar4;
      puVar2[6] = 0;
      puVar2[7] = 1;
      puVar2[3] = 1;
      puVar2[4] = 1;
      *puVar2 = 0;
      puVar2[1] = 0;
      puVar2[9] = 1;
      puVar2[10] = 0;
      iVar1 = iVar1 + 1;
      puVar2 = puVar2 + 0xc;
    } while (iVar1 < *(int *)(param_1 + 0x1320));
  }
  return;
}

