/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003e91a4  name=FUN_003e91a4  size=212  xrefs=5
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int * FUN_003e91a4(undefined1 *param_1)

{
  int iVar1;
  int iVar2;
  int *piVar3;
  
  iVar2 = iRam00e9bfc8;
  do {
    if (iVar2 == 0) {
      return (int *)0x0;
    }
    if ((*(uint *)(iVar2 + 0x3c) & 0x10) != 0) {
      for (piVar3 = *(int **)(iVar2 + 0x20); piVar3 != (int *)0x0; piVar3 = (int *)piVar3[0x18]) {
        if (((*(char *)(*piVar3 + 1) == param_1[1]) && (piVar3[1] != 0)) &&
           (iVar1 = FUN_004965bc(param_1,piVar3[1],*param_1), iVar1 == 0)) {
          return piVar3;
        }
      }
    }
    iVar2 = *(int *)(iVar2 + 0x18);
  } while( true );
}

