/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0026e1f4  name=FUN_0026e1f4  size=404  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


char * FUN_0026e1f4(int *param_1,char *param_2)

{
  char cVar1;
  char *pcVar2;
  int iVar3;
  int *piStack_20;
  int iStack_1c;
  undefined4 uStack_18;
  undefined4 uStack_14;
  
  uStack_14 = 0;
  iStack_1c = 0;
  uStack_18 = 0;
  cVar1 = *param_2;
  pcVar2 = param_2;
  piStack_20 = param_1;
  if (cVar1 == '/') {
    pcVar2 = (char *)FUN_00258c6c(param_1,param_2 + 1);
    if (param_2 != (char *)0x0 && param_1 != (int *)0x0) {
      (**(code **)(*param_1 + 0x14))(param_1,param_2);
    }
    cVar1 = *pcVar2;
  }
  iVar3 = 0;
  if (cVar1 != '\0') {
    cVar1 = *pcVar2;
    do {
      iVar3 = iVar3 + 1;
      if (cVar1 == '/') {
        FUN_00257d18(&piStack_20,0x23);
        FUN_002585b0(&piStack_20,pcVar2);
        if (pcVar2 != (char *)0x0 && param_1 != (int *)0x0) {
          (**(code **)(*param_1 + 0x14))(param_1,pcVar2);
        }
        iVar3 = iStack_1c;
        if (iStack_1c == 0) {
          iVar3 = 0xd6f55c;
        }
        pcVar2 = (char *)FUN_00258c6c(piStack_20,iVar3);
        break;
      }
      cVar1 = pcVar2[iVar3];
    } while (cVar1 != '\0');
  }
  if (iStack_1c != 0 && piStack_20 != (int *)0x0) {
    (**(code **)(*piStack_20 + 0x14))();
  }
  return pcVar2;
}

