/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004a5a3c  name=FUN_004a5a3c  size=152  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_004a5a3c(uint param_1)

{
  int iVar1;
  uint auStack_20 [4];
  
  FUN_004a4ca8();
  auStack_20[0] = param_1 & 0xff000fff;
  iVar1 = (**(code **)(iRam00e2b528 + 8))(auStack_20);
  if ((iVar1 == 0) &&
     (auStack_20[0] = param_1 & 0xfff, iVar1 = (**(code **)(iRam00e2b528 + 8))(auStack_20),
     iVar1 == 0)) {
    return 0;
  }
  return *(undefined4 *)(iVar1 + 4);
}

