/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0020114c  name=FUN_0020114c  size=544  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


uint FUN_0020114c(int param_1,undefined1 *param_2,uint param_3,undefined4 param_4,undefined4 param_5
                 ,undefined4 param_6,undefined4 param_7,undefined4 param_8)

{
  undefined4 uVar1;
  undefined2 uVar4;
  int iVar2;
  int iVar3;
  
  *param_2 = (char)(param_3 >> 0x18);
  param_2[1] = (char)(param_3 >> 0x10);
  param_2[4] = 0x52;
  param_2[5] = 0x45;
  param_2[2] = (char)(param_3 >> 8);
  param_2[7] = 0x56;
  param_2[8] = (char)((uint)param_8 >> 0x18);
  param_2[6] = 0x44;
  param_2[9] = (char)((uint)param_8 >> 0x10);
  param_2[10] = (char)((uint)param_8 >> 8);
  param_2[0xb] = (char)param_8;
  param_2[3] = (char)param_3;
  uVar1 = *(undefined4 *)(param_1 + 0x5c);
  param_2[0xe] = (char)((uint)uVar1 >> 8);
  param_2[0x11] = 4;
  param_2[0xc] = (char)((uint)uVar1 >> 0x18);
  param_2[0xd] = (char)((uint)uVar1 >> 0x10);
  param_2[0xf] = (char)uVar1;
  param_2[0x13] = 0;
  param_2[0x14] = (char)((uint)param_7 >> 0x18);
  param_2[0x15] = (char)((uint)param_7 >> 0x10);
  param_2[0x16] = (char)((uint)param_7 >> 8);
  param_2[0x17] = (char)param_7;
  param_2[0x10] = 4;
  param_2[0x12] = 0;
  uVar1 = *(undefined4 *)(*(int *)(param_1 + 0x3c) + 0x10);
  param_2[0x19] = (char)((uint)uVar1 >> 0x10);
  param_2[0x1a] = (char)((uint)uVar1 >> 8);
  param_2[0x18] = (char)((uint)uVar1 >> 0x18);
  param_2[0x1b] = (char)uVar1;
  uVar1 = *(undefined4 *)(*(int *)(param_1 + 0x3c) + 0x14);
  param_2[0x1c] = (char)((uint)uVar1 >> 0x18);
  param_2[0x1d] = (char)((uint)uVar1 >> 0x10);
  param_2[0x1e] = (char)((uint)uVar1 >> 8);
  param_2[0x1f] = (char)uVar1;
  uVar4 = FUN_002005bc(param_2,param_3);
  param_2[0x12] = (char)((ushort)uVar4 >> 8);
  param_2[0x13] = (char)uVar4;
  uVar1 = FUN_001ed6fc(param_1 + 4);
  FUN_00204ac8(param_1 + 100,*(undefined4 *)(param_1 + 0x54),uVar1);
  FUN_00204ac8(param_1 + 0x80,*(undefined4 *)(param_1 + 0x54),param_3);
  iVar2 = FUN_00200e24(param_1,param_2,param_3,param_4,param_5);
  iVar3 = FUN_001edab4(param_1 + 4,param_2,iVar2);
  *(int *)(param_1 + 0x54) = *(int *)(param_1 + 0x54) + 1;
  *(int *)(param_1 + 0x5c) = *(int *)(param_1 + 0x5c) + 1;
  if (*(uint *)(param_1 + 0xd4) < param_3) {
    *(uint *)(param_1 + 0xd4) = param_3;
  }
  if (iVar3 != iVar2) {
    param_3 = 0;
  }
  return param_3;
}

