/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002e8d10  name=FUN_002e8d10  size=1080  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002e8d10(int param_1,int param_2,int param_3,int param_4)

{
  int iVar1;
  int iVar2;
  int iVar3;
  undefined4 uVar4;
  undefined4 uVar5;
  int iVar6;
  int *piStack_100;
  int iStack_fc;
  undefined1 auStack_f0 [24];
  undefined1 auStack_d8 [20];
  uint uStack_c4;
  undefined4 uStack_c0;
  undefined4 uStack_bc;
  undefined4 uStack_b8;
  undefined2 uStack_b4;
  undefined2 uStack_b2;
  undefined1 uStack_b0;
  undefined4 uStack_ac;
  undefined4 uStack_a8;
  undefined4 uStack_a0;
  undefined4 uStack_9c;
  undefined1 uStack_98;
  int iStack_94;
  undefined1 auStack_90 [92];
  int iStack_34;
  
  if (((param_2 != 0) && (*(int *)(param_1 + 0x20) != 0)) &&
     (*(int *)(*(int *)(param_1 + 0x20) + 0x20) != 0)) {
    uVar4 = 0;
    if (*(int *)(param_2 + 0x1c) != 0) {
      uVar4 = *(undefined4 *)(*(int *)(param_2 + 0x1c) + 4);
    }
    FUN_002578f8(&piStack_100,*(undefined4 *)(param_1 + 0x30),uVar4);
    iVar6 = *(int *)(param_1 + 0x2cc);
    if (iVar6 != 0) {
LAB_002e8db8:
      if (((*(int *)(iVar6 + 0x18) == 0) ||
          (iVar3 = FUN_00257fd8(*(int *)(iVar6 + 0x18),&piStack_100), iVar3 == 0)) ||
         (*(char *)(iVar6 + 8) == '\0')) goto LAB_002e8dcc;
      iVar3 = *(int *)(param_2 + 0x20);
      *(int *)(iVar6 + 0x38) = param_2;
      *(undefined1 *)(iVar6 + 9) = 1;
      iVar3 = *(int *)(iVar3 + 0x78);
      if ((*(int *)(iVar6 + 0xc) == 0) ||
         (iVar1 = *(int *)(iVar6 + 0x10), iVar2 = *(int *)(iVar6 + 0xc), *(int *)(iVar6 + 0x10) == 0
         )) {
        iVar1 = param_4;
        iVar2 = param_3;
      }
      uVar4 = FUN_00248640(0x34);
      FUN_00277148(uVar4,*(undefined4 *)(param_1 + 0x30),iVar3);
      *(undefined4 *)(iVar3 + 0xb0) = uVar4;
      FUN_00277264(uVar4,0,0);
      FUN_002772d8(*(undefined4 *)(iVar3 + 0xb0),iVar2 * 0x14,0,1);
      FUN_002772d8(*(undefined4 *)(iVar3 + 0xb0),iVar2 * 0x14,iVar1 * 0x14,1);
      FUN_002772d8(*(undefined4 *)(iVar3 + 0xb0),0,iVar1 * 0x14,1);
      FUN_002772d8(*(undefined4 *)(iVar3 + 0xb0),0,0,1);
      uStack_b8 = *(undefined4 *)(param_2 + 0x14);
      uStack_c4 = 2;
      uStack_98 = 0;
      uStack_b2 = 0;
      uStack_b4 = 0;
      uStack_b0 = 0;
      uStack_ac = 0;
      uStack_bc = 0;
      uStack_a8 = 0;
      uStack_a0 = 0;
      uStack_9c = 0;
      iStack_94 = 0;
      uStack_c0 = 0;
      FUN_002f5d34(auStack_f0);
      FUN_003067c0(auStack_d8);
      uStack_b2 = 0;
      uStack_c4 = uStack_c4 | 0x20;
      uStack_b4 = 0xffff;
      uStack_ac = 0;
      uStack_a0 = 0;
      if ((*(int *)(iVar6 + 0xc) == 0) || (*(int *)(iVar6 + 0x10) == 0)) {
        *(int *)(iVar6 + 0xc) = param_3;
        *(int *)(iVar6 + 0x10) = param_4;
        FUN_002eff38(param_1);
        FUN_0039ac74(auStack_90,auStack_f0,0x60);
        uVar4 = FUN_002e848c(param_1,auStack_90,param_2);
        *(undefined4 *)(iVar6 + 0x3c) = uVar4;
        if (iStack_34 != 0) {
          FUN_002c1fb8(iStack_34);
        }
        FUN_002e9148(param_1);
        for (iVar6 = *(int *)(param_1 + 0x2cc); iVar6 != 0; iVar6 = *(int *)(iVar6 + 0x44)) {
          *(undefined4 *)(iVar6 + 0x34) = 0;
        }
        FUN_002e7048(param_1,0,0);
        uVar4 = FUN_002e26d0(param_1);
        *(undefined4 *)(param_1 + 0x2b4) = uVar4;
        uVar4 = FUN_002e91c4(param_1);
        iVar3 = *(int *)(param_1 + 0x2cc);
        iVar6 = 0;
        if (iVar3 != 0) {
          do {
            FUN_002e895c(param_1,iVar3);
            FUN_002e87b4(param_1,iVar3,uVar4);
            iVar3 = *(int *)(iVar3 + 0x44);
          } while (iVar3 != 0);
          iVar6 = *(int *)(param_1 + 0x2cc);
        }
        if (iVar6 != 0) {
          FUN_002e8a90(param_1);
        }
      }
      else {
        FUN_0039ac74(auStack_90,auStack_f0,0x60);
        uVar4 = FUN_002e848c(param_1,auStack_90,param_2);
        *(undefined4 *)(iVar6 + 0x3c) = uVar4;
        if (iStack_34 != 0) {
          FUN_002c1fb8(iStack_34);
        }
        uVar4 = *(undefined4 *)(*(int *)(iVar6 + 0x38) + 0x20);
        uVar5 = *(undefined4 *)(param_1 + 0x28);
        FUN_00373dd0((*(int *)(iVar6 + 0xc) * 100) / param_3);
        FUN_00291d0c(uVar5,uVar4,2);
        uVar5 = *(undefined4 *)(*(int *)(iVar6 + 0x38) + 0x20);
        uVar4 = *(undefined4 *)(param_1 + 0x28);
        FUN_00373dd0((*(int *)(iVar6 + 0x10) * 100) / param_4);
        FUN_00291d0c(uVar4,uVar5,3);
      }
      if (iStack_94 != 0) {
        FUN_002c1fb8();
      }
    }
LAB_002e8dd8:
    if (iStack_fc != 0 && piStack_100 != (int *)0x0) {
      (**(code **)(*piStack_100 + 0x14))();
    }
  }
  return;
LAB_002e8dcc:
  iVar6 = *(int *)(iVar6 + 0x44);
  if (iVar6 == 0) goto LAB_002e8dd8;
  goto LAB_002e8db8;
}

