/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004a1f4c  name=FUN_004a1f4c  size=164  xrefs=5
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_004a1f4c(undefined4 param_1,uint param_2,uint param_3)

{
  int iVar1;
  
  param_2 = param_2 & (int)~param_2 >> 0x1f;
  if ((int)param_3 < (int)param_2) {
    param_2 = param_3;
  }
  do {
    if (param_2 == 0) {
      return 1;
    }
    param_2 = param_2 - 1;
    iVar1 = FUN_004a1ce8(param_1,0xd7dbc0);
  } while (iVar1 == 1);
  return 0;
}

