/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0037412c  name=FUN_0037412c  size=24  xrefs=8
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


uint FUN_0037412c(uint param_1)

{
  return param_1 ^ 0x80000000;
}

