/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005c2828  name=FUN_005c2828  size=384  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_005c2828(int *param_1,int param_2,int *param_3,int param_4)

{
  int iVar1;
  int iVar2;
  undefined4 uVar3;
  int iVar4;
  int iVar5;
  
  uVar3 = 0;
  FUN_005c1e10();
  iVar1 = FUN_004a18ac();
  iVar5 = 0;
  iVar4 = iVar1;
  if (iVar1 != 0) {
    FUN_005c1e10();
    iVar5 = FUN_004a18ac();
    if ((((iVar5 != 0) &&
         ((param_2 == 0 || (iVar2 = FUN_004a1ff0(iVar1,0x88,param_2,0), iVar2 != 0)))) &&
        ((param_4 == 0 || (iVar2 = FUN_004a1ff0(iVar5,0x88,param_4,0), iVar2 != 0)))) &&
       (iVar2 = FUN_004a1ff0(iVar1,0x8a,0,iVar5), iVar2 != 0)) {
      uVar3 = 1;
      iVar1 = iVar5;
      goto LAB_005c28c4;
    }
    iVar4 = 0;
    FUN_004a193c(iVar1);
  }
  iVar1 = 0;
  if (iVar5 != 0) {
    FUN_004a193c(iVar5);
    *param_1 = iVar4;
    *param_3 = 0;
    return 0;
  }
LAB_005c28c4:
  *param_1 = iVar4;
  *param_3 = iVar1;
  return uVar3;
}

