/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00228f10  name=FUN_00228f10  size=372  xrefs=6
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00228f10(int param_1,int param_2)

{
  uint uVar1;
  int iVar2;
  uint uVar3;
  bool bVar4;
  int iVar5;
  uint uVar6;
  int iVar7;
  
  uVar6 = param_1 + 0x24;
  if (0xf < *(uint *)(param_1 + 0x38)) {
    uVar6 = *(uint *)(param_1 + 0x24);
  }
  iVar7 = param_2 + 0x20;
  iVar2 = FUN_0039b0f0(uVar6);
  uVar3 = *(uint *)(param_2 + 0x38);
  uVar1 = param_2 + 0x24;
  if (0xf < uVar3) {
    uVar1 = *(uint *)(param_2 + 0x24);
  }
  if (uVar1 <= uVar6) {
    iVar5 = param_2 + 0x24;
    if (0xf < uVar3) {
      iVar5 = *(int *)(param_2 + 0x24);
    }
    bVar4 = true;
    if (uVar6 < (uint)(iVar5 + *(int *)(param_2 + 0x34))) goto LAB_00228fa4;
  }
  bVar4 = false;
LAB_00228fa4:
  if (bVar4) {
    iVar5 = param_2 + 0x24;
    if (0xf < uVar3) {
      iVar5 = *(int *)(param_2 + 0x24);
    }
    FUN_005ea15c(iVar7,iVar7,uVar6 - iVar5,iVar2);
  }
  else {
    iVar7 = FUN_005f0030(iVar7,iVar2,0);
    if (iVar7 != 0) {
      iVar7 = param_2 + 0x24;
      if (0xf < *(uint *)(param_2 + 0x38)) {
        iVar7 = *(int *)(param_2 + 0x24);
      }
      FUN_0039ac74(iVar7,uVar6,iVar2);
      iVar7 = param_2 + 0x24;
      if (0xf < *(uint *)(param_2 + 0x38)) {
        iVar7 = *(int *)(param_2 + 0x24);
      }
      *(int *)(param_2 + 0x34) = iVar2;
      *(undefined1 *)(iVar7 + iVar2) = 0;
      *(undefined4 *)(param_2 + 0xc) = *(undefined4 *)(param_1 + 0xc);
      return;
    }
  }
  *(undefined4 *)(param_2 + 0xc) = *(undefined4 *)(param_1 + 0xc);
  return;
}

