/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001b2228  name=FUN_001b2228  size=512  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_001b2228(int param_1)

{
  int iVar1;
  undefined4 *puVar2;
  undefined4 *puVar3;
  undefined4 uVar4;
  undefined4 uVar5;
  
  if (param_1 == 0x19) {
    uVar5 = 0xe1347c;
    uVar4 = 0xe13498;
  }
  else if ((param_1 < 0x1a) && (param_1 == 0x18)) {
    uVar5 = 0xe134c8;
    uVar4 = 0xe134e4;
  }
  else {
    uVar5 = 0xe13430;
    uVar4 = 0xe1344c;
  }
  if (iRam00e1333c == -1) {
    puVar2 = (undefined4 *)FUN_00398e40();
    puVar3 = (undefined4 *)FUN_00442914();
    FUN_0039995c(*puVar2,0xd54e8c,0x663bc0,0x2b8,*puVar3);
    uVar4 = 0xffffffff;
  }
  else {
    iVar1 = FUN_0044e510(iRam00e1333c,0x6a010000,0);
    if (iVar1 == -1) {
      puVar2 = (undefined4 *)FUN_00398e40();
      puVar3 = (undefined4 *)FUN_00442914();
      FUN_0039995c(*puVar2,0xd54ec4,0x663bc0,0x2c1,*puVar3);
      uVar4 = 0xffffffff;
    }
    else {
      iVar1 = FUN_0044e510(iRam00e1333c,0x6a010001,uVar5);
      if (iVar1 == -1) {
        puVar2 = (undefined4 *)FUN_00398e40();
        puVar3 = (undefined4 *)FUN_00442914();
        FUN_0039995c(*puVar2,0xd54ef4,0x663bc0,0x2ca,*puVar3);
        uVar4 = 0xffffffff;
      }
      else {
        iVar1 = FUN_0044e510(iRam00e1333c,0x6a010002,uVar4);
        if (iVar1 == -1) {
          puVar2 = (undefined4 *)FUN_00398e40();
          puVar3 = (undefined4 *)FUN_00442914();
          FUN_0039995c(*puVar2,0xd54f24,0x663bc0,0x2d3,*puVar3);
          uVar4 = 0xffffffff;
        }
        else {
          iVar1 = FUN_0044e510(iRam00e1333c,0x6a010003,0);
          uVar4 = 0;
          if (iVar1 == -1) {
            puVar2 = (undefined4 *)FUN_00398e40(0);
            puVar3 = (undefined4 *)FUN_00442914();
            FUN_0039995c(*puVar2,0xd54f54,0x663bc0,0x2dc,*puVar3);
            uVar4 = 0xffffffff;
          }
        }
      }
    }
  }
  return uVar4;
}

