/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003fe520  name=FUN_003fe520  size=276  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_003fe520(void)

{
  FUN_00460a04(uRam00e9c1f0,uRam00e28b10,8,0xdfdbe8,0xc0000002,0xe9c488,0,0x46fc1c,0xda3a00,0xd71778
               ,0xd7143c,0x161,0xd71438);
  FUN_00460a04(uRam00e9c1f0,uRam00e28b10,9,0xdfdb9c,0xc0000002,0xe9c684,0,0x46fc1c,0xda3a00,0xd7179c
               ,0xd7143c,0x163,0xd71438);
  return 0;
}

