/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0019607c  name=FUN_0019607c  size=728  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_0019607c(int param_1,int param_2,int param_3)

{
  short sVar1;
  int iVar2;
  uint uVar3;
  int iVar4;
  
  if (param_2 == 0x10) {
    if (param_3 != 0x8e) {
      if (param_3 == 0x128f) {
        if (-1 < *(short *)(param_1 + 0x2891a)) {
          return 0xf;
        }
        if (-1 < *(short *)(param_1 + 0x2d59e)) {
          return 0xd;
        }
        sVar1 = *(short *)(param_1 + 0x2d59a);
      }
      else {
        param_1 = (param_3 + 0x13200) * 2 + param_1;
        if (-1 < *(short *)(param_1 + 0x4c80)) {
          return 0xd;
        }
        if (-1 < *(short *)(param_1 + -4)) {
          return 0xf;
        }
        if (-1 < *(short *)(param_1 + 4)) {
          return 0xc;
        }
        sVar1 = *(short *)(param_1 + 0x4c7c);
      }
      uVar3 = (int)sVar1 >> 0x1f & 0xfffffff3;
LAB_0019614c:
      return uVar3 + 0xe;
    }
    iVar2 = 0xb;
    if ((*(short *)(param_1 + 0x26520) < 0) && (iVar2 = 0xd, *(short *)(param_1 + 0x2b19c) < 0)) {
      uVar3 = (int)*(short *)(param_1 + 0x2b1a0) >> 0x1f & 0xfffffff5;
      goto LAB_001961e4;
    }
  }
  else {
    if (param_2 == 0xa03) {
      if (param_3 == 0x8e) {
        return ((int)*(short *)(param_1 + 0x17ef3e0) >> 0x1f & 0xfffffffeU) + 0xb;
      }
      if (param_3 == 0x128f) {
        sVar1 = *(short *)(param_1 + 0x17f17da);
      }
      else {
        param_1 = (param_3 + 0xbf7960) * 2 + param_1;
        if (-1 < *(short *)(param_1 + 4)) {
          return 0xb;
        }
        sVar1 = *(short *)(param_1 + -4);
      }
      return ((int)sVar1 >> 0x1f & 0xfffffffaU) + 0xf;
    }
    if (param_3 == 0x8e) {
      iVar2 = 0xb;
      param_1 = (param_2 * 0x1320 + 0x8e) * 2 + param_1;
      if ((*(short *)(param_1 + 4) < 0) && (iVar2 = 0xd, *(short *)(param_1 + 0x4c80) < 0)) {
        uVar3 = (int)*(short *)(param_1 + 0x4c84) >> 0x1f & 0xfffffffd;
LAB_001961e4:
        return uVar3 + 0xc;
      }
    }
    else if (param_3 == 0x128f) {
      iVar2 = 0xf;
      param_1 = (param_2 * 0x1320 + 0x128f) * 2 + param_1;
      if ((*(short *)(param_1 + -4) < 0) && (iVar2 = 0xd, *(short *)(param_1 + 0x4c80) < 0)) {
        uVar3 = (int)*(short *)(param_1 + 0x4c7c) >> 0x1f & 0xfffffffb;
        goto LAB_0019614c;
      }
    }
    else {
      iVar4 = (param_2 * 0x1320 + param_3) * 2 + param_1;
      if (*(short *)(iVar4 + 0x4c80) < 0) {
        if ((*(short *)(iVar4 + -4) < 0) || (iVar2 = 0x1d, *(short *)(iVar4 + 4) < 0)) {
          param_1 = (param_2 * 0x1320 + param_3) * 2 + param_1;
          if (-1 < *(short *)(param_1 + 0x4c7c)) {
            return 0x14 - ((int)*(short *)(param_1 + 0x4c84) >> 0x1f);
          }
          iVar2 = 0x16;
          if ((*(short *)(param_1 + 0x4c84) < 0) && (iVar2 = 6, *(short *)(param_1 + 4) < 0)) {
            return ((uint)(int)*(short *)(param_1 + -4) >> 0x1e & 2) + 7;
          }
        }
      }
      else if ((*(short *)(iVar4 + -4) < 0) || (iVar2 = 0x1c, *(short *)(iVar4 + 4) < 0)) {
        iVar2 = 0x1e;
      }
    }
  }
  return iVar2;
}

