/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0054daf4  name=FUN_0054daf4  size=272  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0054daf4(int param_1)

{
  ushort uVar2;
  uint uVar1;
  int iVar3;
  int iVar4;
  int iVar5;
  uint uVar6;
  int iStack_18;
  
  iVar3 = 0;
  if (*(short *)(param_1 + 0x14) != 0) {
    do {
      iVar5 = *(int *)(*(int *)(param_1 + 0x3c) + iVar3 * 4);
      iVar4 = iVar3 << (*(int *)(param_1 + 0xc) - 9U & 0x3f);
      if (iVar5 != 0) {
        iVar5 = FUN_0054b8f0(param_1,iVar5,&iStack_18);
        uVar2 = FUN_0054f660(iVar5 + 0x14);
        iVar5 = FUN_0054bad4(iVar5);
        if ((((iVar5 != 0) && (uVar2 < *(ushort *)(param_1 + 0x14))) &&
            (*(ushort *)(param_1 + 0x18) <= uVar2)) && (uVar6 = 0, *(int *)(param_1 + 0x30) != 0)) {
          do {
            uVar1 = FUN_0054f698(iStack_18 + uVar6 * 4);
            if (((uVar1 & 0x1ff) == 0x60) && (*(int *)(param_1 + 0x48) != iVar4)) {
              FUN_0054c028(param_1,iVar4,0,1);
            }
            iVar4 = iVar4 + 1;
            uVar6 = uVar6 + 1;
          } while (uVar6 < *(uint *)(param_1 + 0x30));
        }
      }
      iVar3 = iVar3 + 1;
    } while (iVar3 < (int)(uint)*(ushort *)(param_1 + 0x14));
  }
  return;
}

