/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002e7168  name=FUN_002e7168  size=2872  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002e7168(int param_1,int param_2,undefined4 param_3,int param_4)

{
  bool bVar1;
  bool bVar2;
  bool bVar3;
  bool bVar4;
  bool bVar5;
  int iVar6;
  undefined4 uVar7;
  int iVar8;
  int iVar9;
  uint uVar10;
  uint uVar11;
  int iVar12;
  short *psVar13;
  uint uVar14;
  int iVar15;
  uint uVar16;
  uint uVar17;
  uint uVar18;
  undefined2 uVar19;
  short sVar20;
  uint uVar21;
  uint uVar22;
  int iVar23;
  int iVar24;
  undefined2 uVar25;
  longlong lVar26;
  
  FUN_00318718((int *)(param_1 + 0x1f8),0);
  if (param_2 < *(int *)(param_1 + 0x16c)) {
    do {
      iVar15 = *(int *)(param_2 * 4 + *(int *)(param_1 + 0x168));
      uVar17 = *(uint *)(iVar15 + 0x1c);
      bVar5 = false;
      if ((0 < (int)uVar17) && ((*(uint *)(param_1 + 300) & 0x40) != 0)) {
        iVar12 = *(int *)(param_1 + 0x2cc);
        bVar2 = false;
        if ((iVar12 != 0) && ((*(char *)(iVar12 + 0x40) != '\0' && (param_2 == 0)))) {
          FUN_002e7ca0(param_1,0,iVar15,0,1);
          iVar12 = *(int *)(param_1 + 0x2cc);
        }
        iVar24 = *(int *)(param_1 + 0x1d4) + (uint)*(ushort *)(*(int *)(iVar15 + 4) + 4) * 0x44;
        if (iVar12 == 0) {
          iVar12 = FUN_002edbb4(param_1,*(undefined4 *)(iVar24 + 0x20),0);
          uVar7 = *(undefined4 *)(iVar24 + 0x1c);
        }
        else {
          uVar7 = FUN_002e20a0(iVar24,param_2);
          iVar12 = FUN_002edbb4(param_1,uVar7,0);
          uVar7 = FUN_002e2054(iVar24,param_2);
        }
        iVar8 = FUN_002edbb4(param_1,uVar7,0);
        iVar24 = *(int *)(param_1 + 0x138);
        iVar6 = *(int *)(param_1 + 0x134);
        iVar23 = iVar24 - iVar12;
        if (iVar24 - iVar12 < iVar6) {
          iVar23 = iVar6;
        }
        if (iVar6 + iVar8 < iVar24) {
          iVar24 = iVar6 + iVar8;
        }
        uVar14 = uVar17 - 1;
        uVar22 = uVar14;
        if (0 < param_4) {
          iVar12 = (iVar23 - iVar24) / param_4;
          uVar22 = iVar12 + ((iVar12 == 1) - 1);
          if (iVar12 == 0) {
            uVar22 = uVar14;
          }
        }
        if ((int)uVar17 <= (int)uVar22) {
          uVar22 = uVar14;
        }
        if (-1 < (int)uVar22) {
          psVar13 = (short *)(uVar22 * 6 + *(int *)(iVar15 + 4));
          uVar21 = uVar22;
          do {
            sVar20 = *psVar13;
            uVar21 = uVar21 - 1;
            psVar13 = psVar13 + -3;
            if (sVar20 == 10 || sVar20 == 0xd) {
              bVar2 = true;
              break;
            }
          } while (-1 < (int)uVar21);
        }
        bVar2 = !bVar2;
        uVar21 = uVar22;
        if (bVar2) {
          uVar21 = uVar22 - 1;
          if (-1 < (int)uVar21) {
            iVar12 = uVar21 * 6;
            iVar24 = iVar12 + 6;
            while( true ) {
              uVar25 = 0;
              uVar19 = *(undefined2 *)(*(int *)(iVar15 + 4) + iVar12);
              if ((int)(uVar21 + 1) < (int)uVar17) {
                uVar25 = *(undefined2 *)(*(int *)(iVar15 + 4) + iVar24);
              }
              iVar6 = FUN_002ea448(param_1);
              uVar7 = 0;
              iVar24 = iVar24 + -6;
              if (iVar6 < 6) {
                uVar10 = *(uint *)(*(int *)(param_1 + 0x1d0) +
                                   (uint)*(ushort *)(*(int *)(iVar15 + 4) + iVar12 + 2) * 0x80 + 100
                                  ) >> 6 & 1;
              }
              else {
                uVar7 = FUN_002ef6c4(param_1,uVar25,0);
                uVar10 = 0;
              }
              iVar6 = FUN_002e0e1c(uVar19,uVar25,uVar7,uVar10);
              if (iVar6 != 0) break;
              iVar12 = iVar12 + -6;
              if ((!bVar2) || (uVar21 = uVar21 - 1, (int)uVar21 < 0)) goto LAB_002e73e8;
            }
            bVar2 = false;
          }
LAB_002e73e8:
          if (!bVar2) goto LAB_002e73ec;
          bVar2 = false;
        }
        else {
LAB_002e73ec:
          uVar22 = uVar21 & (int)~uVar21 >> 0x1f;
          bVar2 = true;
          uVar21 = uVar22;
        }
        uVar10 = uVar17;
        if ((int)(uVar22 + 1) < (int)uVar17) {
          uVar10 = uVar22 + 1;
        }
        iVar12 = FUN_002e9678(param_1,param_2,0,uVar10,0,0,1);
        bVar1 = iVar23 < iVar12;
        bVar4 = false;
        iVar24 = 1;
        uVar10 = uVar22;
        if (bVar1) {
          do {
            bVar3 = false;
            if ((bVar2) && (uVar21 = uVar10 - 1, -1 < (int)uVar21)) {
              iVar6 = uVar21 * 6;
              iVar8 = iVar6 + 6;
              do {
                uVar25 = 0;
                uVar19 = *(undefined2 *)(*(int *)(iVar15 + 4) + iVar6);
                if ((int)(uVar21 + 1) < (int)uVar17) {
                  uVar25 = *(undefined2 *)(*(int *)(iVar15 + 4) + iVar8);
                }
                iVar9 = FUN_002ea448(param_1);
                uVar7 = 0;
                iVar8 = iVar8 + -6;
                if (iVar9 < 6) {
                  uVar22 = *(uint *)(*(int *)(param_1 + 0x1d0) +
                                     (uint)*(ushort *)(*(int *)(iVar15 + 4) + iVar6 + 2) * 0x80 +
                                    100) >> 6 & 1;
                }
                else {
                  uVar7 = FUN_002ef6c4(param_1,uVar25,0);
                  uVar22 = 0;
                }
                iVar9 = FUN_002e0e1c(uVar19,uVar25,uVar7,uVar22);
                if (iVar9 != 0) {
                  bVar3 = true;
                  break;
                }
                uVar21 = uVar21 - 1;
                iVar6 = iVar6 + -6;
              } while (-1 < (int)uVar21);
            }
            uVar22 = uVar21;
            if (!bVar3) {
              bVar2 = false;
              uVar22 = uVar10 - 1;
            }
            if ((int)uVar22 < 0) break;
            iVar24 = FUN_002e9678(param_1,param_2,uVar22,uVar10 + iVar24,0,1,1);
            iVar12 = iVar12 - iVar24;
            bVar1 = iVar23 < iVar12;
            if (!bVar1) {
              bVar4 = true;
              uVar22 = uVar22 - 1;
            }
            iVar24 = 0;
            uVar10 = uVar22;
          } while (bVar1);
          if (!bVar4) goto LAB_002e752c;
        }
        else {
LAB_002e752c:
          uVar16 = uVar22 + 1;
          bVar2 = false;
          uVar10 = uVar16;
          uVar18 = uVar22;
          while ((uVar22 = uVar18, ((-1 - iVar12) + (uint)(iVar12 == 0) >> 0x1f & (uint)!bVar1) != 0
                 && (bVar1 = false, uVar22 = uVar14, (int)uVar18 < (int)uVar14))) {
            bVar4 = true;
            uVar22 = uVar16;
            if (!bVar2) {
              do {
                uVar21 = uVar22;
                if ((int)uVar17 <= (int)uVar21) goto LAB_002e7608;
                uVar22 = uVar21 + 1;
                sVar20 = *(short *)(*(int *)(iVar15 + 4) + uVar21 * 6);
                uVar19 = 0;
                if (sVar20 == 10 || sVar20 == 0xd) break;
                if ((int)uVar22 < (int)uVar17) {
                  uVar19 = *(undefined2 *)(*(int *)(iVar15 + 4) + uVar22 * 6);
                }
                lVar26 = FUN_002ea448(param_1);
                uVar7 = 0;
                if (lVar26 < 0x600000000) {
                  uVar11 = *(uint *)(*(int *)(param_1 + 0x1d0) +
                                     (uint)*(ushort *)(*(int *)(iVar15 + 4) + uVar21 * 6 + 2) * 0x80
                                    + 100) >> 6 & 1;
                }
                else {
                  uVar7 = FUN_002ef6c4(param_1,(int)lVar26,0);
                  uVar11 = 0;
                }
                iVar6 = FUN_002e0e1c(sVar20,uVar19,uVar7,uVar11);
              } while (iVar6 == 0);
              bVar1 = true;
LAB_002e7608:
              bVar4 = !bVar1;
              if (!bVar4) {
                if ((uVar21 != uVar14) ||
                   ((sVar20 = *(short *)(*(int *)(iVar15 + 4) + uVar14 * 6), sVar20 != 0x20 &&
                    (sVar20 != 10)))) goto LAB_002e7618;
                bVar4 = true;
              }
              bVar2 = true;
            }
LAB_002e7618:
            if (bVar4) {
              uVar22 = uVar10;
              uVar11 = uVar10;
              if ((int)uVar14 < (int)uVar10) break;
            }
            else {
              uVar16 = uVar21 + 1;
              uVar11 = uVar21;
            }
            uVar10 = uVar11 + 1;
            uVar22 = uVar17;
            if ((int)uVar10 < (int)uVar17) {
              uVar22 = uVar10;
            }
            iVar6 = FUN_002e9678(param_1,param_2,uVar18 - (-iVar24 >> 0x1f),uVar22,0,1,1);
            iVar12 = iVar12 + iVar6;
            uVar22 = uVar18;
            if (iVar23 < iVar12) break;
            bVar1 = false;
            uVar18 = uVar11;
          }
        }
        if ((~uVar22 >> 0x1f & (uint)((int)uVar22 < (int)uVar17)) != 0) {
          uVar10 = uVar22 + 1;
          uVar21 = uVar17;
          if (uVar10 != uVar17) {
            sVar20 = *(short *)(*(int *)(iVar15 + 4) + uVar10 * 6);
            if ((sVar20 == 0x20) || (sVar20 == 10)) {
              uVar21 = uVar22 + 2;
              if ((int)uVar14 < (int)(uVar22 + 2)) {
                uVar21 = uVar17;
              }
            }
            else {
              uVar19 = *(undefined2 *)(*(int *)(iVar15 + 4) + uVar22 * 6);
              if ((int)uVar17 <= (int)uVar10) {
                sVar20 = 0;
              }
              iVar12 = FUN_002ea448(param_1);
              if (iVar12 < 6) {
                uVar14 = *(uint *)(*(int *)(param_1 + 0x1d0) +
                                   (uint)*(ushort *)(*(int *)(iVar15 + 4) + uVar22 * 6 + 2) * 0x80 +
                                  100) >> 6 & 1;
                uVar7 = 0;
              }
              else {
                uVar7 = FUN_002ef6c4(param_1);
                uVar14 = 0;
              }
              iVar12 = FUN_002e0e1c(uVar19,sVar20,uVar7,uVar14);
              uVar21 = uVar10;
              if (iVar12 == 0) {
                iVar12 = uVar22 - 1;
                uVar14 = 0xffffffff;
                bVar2 = false;
                if (iVar12 < 0) {
                  bVar1 = true;
                }
                else {
                  iVar24 = iVar12 * 6;
                  do {
                    if (uVar14 == 0xffffffff) {
                      uVar14 = uVar22;
                    }
                    uVar19 = *(undefined2 *)(*(int *)(iVar15 + 4) + iVar24);
                    uVar25 = 0;
                    if (iVar12 + 1 < (int)uVar17) {
                      uVar25 = *(undefined2 *)(*(int *)(iVar15 + 4) + (iVar12 + 1) * 6);
                    }
                    iVar23 = FUN_002ea448(param_1);
                    if (iVar23 < 6) {
                      uVar21 = *(uint *)(*(int *)(param_1 + 0x1d0) +
                                         (uint)*(ushort *)(*(int *)(iVar15 + 4) + iVar24 + 2) * 0x80
                                        + 100) >> 6 & 1;
                      uVar7 = 0;
                    }
                    else {
                      uVar7 = FUN_002ef6c4(param_1);
                      uVar21 = 0;
                    }
                    iVar23 = FUN_002e0e1c(uVar19,uVar25,uVar7,uVar21);
                    if (iVar23 != 0) {
                      bVar2 = true;
                    }
                    bVar1 = !bVar2;
                    if (!bVar1) goto LAB_002e7acc;
                    iVar12 = iVar12 + -1;
                    iVar24 = iVar24 + -6;
                  } while (-1 < iVar12);
                }
                if (bVar1) {
                  uVar21 = uVar14 + 1;
                }
                else {
LAB_002e7acc:
                  uVar21 = iVar12 + 1;
                }
              }
            }
          }
          if ((0 < (int)uVar21) && (iVar12 = uVar17 - uVar21, iVar12 != 0)) {
            iVar24 = FUN_002e42f0(param_1,param_2 + 1);
            if (iVar24 != 0) {
              uVar7 = *(undefined4 *)(param_2 * 4 + *(int *)(param_1 + 0x168) + 4);
              FUN_002e14d8(uVar7,0,*(int *)(iVar15 + 4) + uVar21 * 6,iVar12,0);
              FUN_002e1334(iVar15,uVar21,iVar12);
              if (*(int *)(param_1 + 0x2cc) != 0) {
                FUN_002e7ca0(param_1,uVar21,uVar7,param_2,0);
              }
            }
            break;
          }
        }
      }
      bVar2 = true;
      iVar12 = 0;
      if (0 < (int)(uVar17 - 1)) {
        iVar24 = 0;
        iVar23 = 0;
        do {
          sVar20 = *(short *)(*(int *)(iVar15 + 4) + iVar23);
          if (sVar20 == 10 || sVar20 == 0xd) {
            iVar6 = FUN_002e42f0(param_1,param_2 + 1);
            iVar12 = iVar12 + 1;
            iVar24 = iVar24 + 6;
            bVar5 = true;
            if (iVar6 == 0) goto LAB_002e7870;
            FUN_002e14d8(*(undefined4 *)(param_2 * 4 + *(int *)(param_1 + 0x168) + 4),0,
                         *(int *)(iVar15 + 4) + iVar24,uVar17 - iVar12,0);
            iVar23 = iVar23 + 6;
            FUN_002e1334(iVar15,iVar12,uVar17 - iVar12);
            param_2 = param_2 + 1;
          }
          iVar12 = iVar12 + 1;
          iVar23 = iVar23 + 6;
          iVar24 = iVar24 + 6;
        } while (iVar12 < (int)(uVar17 - 1));
        bVar2 = !bVar5;
      }
      if (bVar2) {
        if ((uVar17 != 0) &&
           (sVar20 = *(short *)(*(int *)(iVar15 + 4) + (uVar17 - 1) * 6),
           sVar20 == 10 || sVar20 == 0xd)) {
          if (*(int *)(param_1 + 0x16c) <= param_2 + 1) {
            FUN_002e42f0(param_1);
            break;
          }
          if (((*(int *)(param_1 + 0x2cc) != 0) &&
              (iVar12 = *(int *)(param_2 * 4 + *(int *)(param_1 + 0x168) + 4), iVar12 != 0)) &&
             (*(int *)(iVar12 + 0x1c) != 0)) {
            FUN_002e7ca0(param_1,uVar17,iVar12,param_2,0);
          }
        }
        bVar5 = true;
        if (((uVar17 == 0) ||
            (sVar20 = *(short *)(*(int *)(iVar15 + 4) + (uVar17 - 1) * 6),
            sVar20 != 10 && sVar20 != 0xd)) &&
           (iVar12 = param_2 + 1, iVar12 < *(int *)(param_1 + 0x16c))) {
          iVar24 = *(int *)(param_2 * 4 + *(int *)(param_1 + 0x168) + 4);
          bVar5 = false;
          FUN_002e14d8(iVar15,uVar17,*(undefined4 *)(iVar24 + 4),*(undefined4 *)(iVar24 + 0x1c),0);
          FUN_002e41f8(param_1,iVar12,iVar12);
        }
        if (bVar5) break;
      }
    } while (param_2 < *(int *)(param_1 + 0x16c));
  }
LAB_002e7870:
  (**(code **)(*(int *)(param_1 + 0x1f8) + 0x10))();
  return;
}

