/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004ad9b8  name=FUN_004ad9b8  size=124  xrefs=11
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_004ad9b8(undefined4 param_1,undefined4 param_2)

{
  int iVar1;
  undefined4 uVar2;
  
  FUN_004a2768();
  iVar1 = FUN_004a18ac();
  uVar2 = 0;
  if (iVar1 != 0) {
    FUN_004a1ff0(iVar1,0x6a,0,param_1);
    uVar2 = FUN_004ad854(iVar1,param_2);
    FUN_004a193c(iVar1);
  }
  return uVar2;
}

