/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005c68a0  name=FUN_005c68a0  size=476  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_005c68a0(undefined4 param_1,int *param_2)

{
  int iVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  char cVar5;
  char *pcVar6;
  char *pcVar7;
  int iVar8;
  int iVar9;
  int iVar10;
  int iVar11;
  int iVar12;
  int iVar13;
  
  iVar8 = -1;
  iVar9 = 0;
  iVar1 = FUN_004a2e98();
  if (iVar1 != 0) {
    iVar11 = 0;
    iVar2 = FUN_004acc60(param_2[1]);
    iVar12 = *param_2;
    iVar10 = iVar9;
    if (0 < iVar2) {
      do {
        iVar13 = 0;
        iVar9 = 0;
        iVar3 = FUN_004acc80(param_2[1],iVar11);
        if (0 < iVar12) {
          do {
            iVar4 = iVar13 * 4;
            iVar13 = iVar13 + 1;
            if (*(int *)(iVar3 + iVar4) != 0) {
              iVar4 = FUN_0039b0f0();
              iVar9 = iVar9 + iVar4;
            }
          } while (iVar13 < iVar12);
        }
        iVar13 = FUN_004a3078(iVar1,iVar9 * 2 + iVar12);
        iVar9 = iVar8;
        if (iVar13 == 0) break;
        iVar13 = 0;
        pcVar6 = *(char **)(iVar1 + 4);
        if (0 < iVar12) {
          do {
            pcVar7 = *(char **)(iVar3 + iVar13 * 4);
            if (pcVar7 != (char *)0x0) {
              while( true ) {
                cVar5 = *pcVar7;
                if (cVar5 == '\0') break;
                if (cVar5 == '\t') {
                  *pcVar6 = '\\';
                  pcVar6 = pcVar6 + 1;
                  cVar5 = *pcVar7;
                }
                *pcVar6 = cVar5;
                pcVar7 = pcVar7 + 1;
                pcVar6 = pcVar6 + 1;
              }
            }
            iVar13 = iVar13 + 1;
            *pcVar6 = '\t';
            pcVar6 = pcVar6 + 1;
          } while (iVar13 < iVar12);
        }
        pcVar6[-1] = '\n';
        iVar13 = (int)pcVar6 - *(int *)(iVar1 + 4);
        iVar3 = FUN_004a1b68(param_1,*(int *)(iVar1 + 4),iVar13);
        if (iVar3 != iVar13) break;
        iVar11 = iVar11 + 1;
        iVar9 = iVar10 + iVar13;
        iVar10 = iVar9;
      } while (iVar11 < iVar2);
    }
    FUN_004a2f0c(iVar1);
    iVar8 = iVar9;
  }
  return iVar8;
}

