/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00545eec  name=FUN_00545eec  size=16  xrefs=5
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00545eec(undefined4 param_1,undefined4 param_2)

{
  FUN_00545d84(param_1,param_2,1);
  return;
}

