/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0036ddac  name=FUN_0036ddac  size=68  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0036ddac(undefined4 param_1,undefined4 param_2)

{
  int iVar1;
  undefined4 uVar2;
  
  iVar1 = FUN_0036d220();
  if (iVar1 == 0) {
    uVar2 = 0xffffffff;
  }
  else {
    uVar2 = FUN_0036daf4(param_1,param_2);
  }
  return uVar2;
}

