/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002207f4  name=FUN_002207f4  size=68  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_002207f4(undefined4 param_1)

{
  int iVar1;
  
  iVar1 = FUN_0021eeb8(0x3000018,param_1,0xf);
  return -(uint)(iVar1 == -1);
}

