/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0021c464  name=FUN_0021c464  size=28  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0021c464(void)

{
  *(undefined4 *)(iRam0100b41c + 0x8c) = 0;
  return;
}

