/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005b09d4  name=FUN_005b09d4  size=84  xrefs=6
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_005b09d4(undefined4 param_1,undefined4 param_2)

{
  undefined4 uVar1;
  
  FUN_005b17d0();
  uVar1 = FUN_0044633c(6,param_1,param_2);
  FUN_005b1894();
  return uVar1;
}

