/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0000960c  name=FUN_0000960c  size=128  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0000960c(void)

{
  uint uVar1;
  
  if (iRam00e0c230 != 0) {
    return;
  }
  uVar1 = FUN_0037202c();
  FUN_00372034(uVar1 | 0x4000000);
  uVar1 = FUN_0037201c();
  FUN_00372024(uVar1 & 0xfcffffff | uRam00e0bf20);
  uVar1 = FUN_0037201c();
  FUN_00372024(uVar1 | 0x800000);
  iRam00e0c230 = 1;
  return;
}

