/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005532f0  name=FUN_005532f0  size=292  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4
FUN_005532f0(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4,
            undefined4 param_5,undefined4 param_6)

{
  undefined4 *puVar1;
  undefined4 uVar2;
  char cVar3;
  undefined1 auStack_78 [84];
  
  if ((uRam00e3a5e0 & 1) != 0) {
    FUN_0039b1d4(auStack_78,param_1 + 3,0x20);
    FUN_00252340(auStack_78,0x564314);
    FUN_0035ad18(23000,auStack_78,1);
  }
  puVar1 = (undefined4 *)FUN_00555488(0x1c);
  if (puVar1 == (undefined4 *)0x0) {
    uVar2 = 0xffffffff;
  }
  else {
    *puVar1 = param_5;
    *(undefined2 *)(puVar1 + 1) = param_2;
    *(undefined2 *)((int)puVar1 + 6) = param_3;
    *(undefined2 *)(puVar1 + 2) = param_4;
    puVar1[3] = 0x564064;
    puVar1[4] = 0x56410c;
    puVar1[5] = 0x564190;
    puVar1[6] = 0x564214;
    cVar3 = FUN_0058fcd8(puVar1,0);
    if (cVar3 == '\0') {
      *param_1 = param_2;
      param_1[1] = param_3;
      param_1[2] = param_4;
      *(undefined4 *)(param_1 + 0x14) = param_6;
      *(undefined4 **)(param_1 + 0x22) = puVar1;
      uVar2 = 0;
    }
    else {
      FUN_005554ec(puVar1);
      uVar2 = 0xffffffff;
    }
  }
  return uVar2;
}

