/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003a92c0  name=FUN_003a92c0  size=196  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_003a92c0(uint *param_1,uint *param_2)

{
  uint uVar1;
  undefined4 uVar2;
  uint uVar3;
  
  uVar2 = 1;
  if ((((*param_1 >> 0xe & 0xf) == uRam00e9c528) && ((*param_2 >> 0xe & 0xf) == uRam00e9c528)) &&
     ((*param_1 >> 2 & 0xff) == (*param_2 >> 2 & 0xff))) {
    uVar3 = param_2[0xf];
    if (param_1[0xf] != 0) {
      FUN_0039f2f4(param_1[0xf]);
    }
    FUN_003a91f8(param_1);
    uVar1 = FUN_0039f1b4();
    param_1[0xf] = uVar1;
    if ((uVar1 != 0) && (uVar3 != 0)) {
      uVar2 = FUN_003a91f8(param_2);
      FUN_0039ac74(uVar1,uVar3,uVar2);
      uVar2 = 0;
    }
  }
  return uVar2;
}

