/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001b8830  name=FUN_001b8830  size=104  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_001b8830(undefined4 param_1)

{
  undefined1 auStack_78 [48];
  undefined1 auStack_48 [52];
  
  FUN_001b80bc(auStack_78);
  FUN_001b8798(auStack_48,0xbdccccd0);
  FUN_001b4fa4(param_1,auStack_48,auStack_78);
  return;
}

