/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002849f8  name=FUN_002849f8  size=136  xrefs=13
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002849f8(int param_1)

{
  int iVar1;
  
  if ((*(int *)(param_1 + 0x14) == 0) && (*(int *)(param_1 + 0x1c) == 0)) {
    iVar1 = *(int *)(param_1 + 0x40) + -1;
    *(int *)(param_1 + 0x40) = iVar1;
    if ((iVar1 == 0) && ((*(int *)(param_1 + 0x44) == 0 && (param_1 != 0)))) {
      FUN_00284f10();
      (**(code **)(*piRam00ef9490 + 0xc))(piRam00ef9490,param_1);
    }
  }
  return;
}

