/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002cf288  name=FUN_002cf288  size=48  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002cf288(int param_1)

{
  if (*(int *)(param_1 + 0x94) != 0) {
    FUN_002b49e0();
  }
  return;
}

