/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00355464  name=FUN_00355464  size=316  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_00355464(int param_1,undefined4 param_2,undefined4 param_3)

{
  int iVar1;
  int iVar2;
  int aiStack_48 [3];
  int iStack_3c;
  int iStack_38;
  int iStack_34;
  int iStack_30;
  int iStack_2c;
  undefined4 uStack_28;
  undefined4 uStack_24;
  int iStack_20;
  
  iVar1 = FUN_003560d0();
  if (iVar1 == 0) {
    iVar1 = FUN_005accf4(uRam00fbbf50,0xffffffff);
    if (iVar1 == -1) {
      FUN_00442990(6);
      iVar1 = -1;
    }
    else {
      iVar1 = FUN_00354970();
      if (iVar1 == 0) {
        aiStack_48[2] = param_1 << 9;
        aiStack_48[1] = 0x19000000;
        aiStack_48[0] = iVar1;
        iStack_3c = iVar1;
        iStack_38 = iVar1;
        iStack_34 = iVar1;
        iStack_30 = iVar1;
        iStack_2c = iVar1;
        uStack_28 = param_3;
        uStack_24 = param_2;
        iStack_20 = iVar1;
        iVar1 = FUN_00355bf0(aiStack_48);
        if ((iVar1 == 0) && (iVar2 = FUN_0035491c(aiStack_48,0xc,0), iVar2 != 0)) {
          FUN_00442990(5);
          iVar1 = -1;
        }
      }
      else {
        FUN_00442990(5);
      }
      FUN_005ad104(uRam00fbbf50);
    }
  }
  else {
    FUN_00442990(0xd);
    iVar1 = -1;
  }
  return iVar1;
}

