/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x000ccbec  name=FUN_000ccbec  size=188  xrefs=4
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_000ccbec(undefined4 param_1,int param_2)

{
  undefined1 uStack_10;
  undefined1 uStack_f;
  undefined1 uStack_e;
  
  if (iRam00e9fb50 == -1) {
    return;
  }
  uStack_10 = 2;
  uStack_f = 6;
  if (param_2 == 2) {
    uStack_e = 4;
  }
  else {
    if (param_2 < 3) {
      if (param_2 != 1) {
LAB_000ccc30:
        uStack_e = 6;
        FUN_0044e510(iRam00e9fb50,0x6a020002,&uStack_10);
        return;
      }
    }
    else if (param_2 != 3) {
      uStack_e = 0;
      if (param_2 == 4) goto LAB_000ccc78;
      goto LAB_000ccc30;
    }
    uStack_e = 2;
  }
LAB_000ccc78:
  FUN_0044e510(iRam00e9fb50,0x6a020002,&uStack_10);
  return;
}

