/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00574060  name=FUN_00574060  size=228  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00574060(uint param_1)

{
  undefined4 uVar1;
  undefined1 uVar2;
  int iVar3;
  int iVar4;
  
  if ((param_1 & 0xff) < uRam00e2697c) {
    iVar4 = iRam00e3a6a8 + (param_1 & 0xff) * 0x3c;
    iVar3 = *(int *)(iRam00e3a6a8 + (param_1 & 0xff) * 0x3c);
    if (**(int **)((param_1 & 0xff) * 4 + 0x108b76c) == 0) {
      uVar2 = (undefined1)*(undefined4 *)(iVar3 + 0x48);
    }
    else {
      uVar2 = (*(code *)**(undefined4 **)((param_1 & 0xff) * 4 + 0x108b76c))
                        (*(undefined4 *)(iVar3 + 0x48));
    }
    *(undefined1 *)(iVar4 + 0x35) = uVar2;
    uVar1 = 0;
  }
  else {
    uVar1 = 0xfffffff9;
  }
  return uVar1;
}

