/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x000185d0  name=FUN_000185d0  size=336  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_000185d0(int *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  int iVar1;
  uint uVar2;
  undefined4 uVar3;
  
  if (param_1 == (int *)0x0) {
    FUN_0000e4e0(0xd347e0,0x6f);
    uVar3 = 0;
    uRam00e9c0ec = 1;
  }
  else {
    uRam00e9c0ec = 0;
    iVar1 = FUN_0001851c(param_2);
    uVar3 = 2;
    if (iVar1 == 0) {
      param_1[2] = 0;
    }
    else {
      param_1[4] = iVar1;
      *param_1 = *(int *)(iVar1 + 4);
      param_1[1] = *(int *)(iVar1 + 8);
      *(undefined1 *)(param_1 + 3) = *(undefined1 *)(iVar1 + 0x1e);
      FUN_0000e900(*param_1 + 0x1c,0);
      uVar2 = FUN_0000e898(*param_1 + 8);
      FUN_0000e900(*param_1 + 8,uVar2 & 0xfffffff3);
      uVar2 = FUN_0000e898(*param_1);
      FUN_0000e900(*param_1,uVar2 & 0xc);
      uVar2 = FUN_0000e898(*param_1 + 0x28);
      FUN_0000e900(*param_1 + 0x28,uVar2 & 0xffffe000);
      uVar2 = FUN_0000e898(*param_1 + 0x20);
      FUN_0000e900(*param_1 + 0x20,uVar2 & 0x1fff);
      FUN_00018554(param_1,param_3,param_4);
      param_1[2] = 0x11111111;
      uVar3 = 0;
    }
  }
  return uVar3;
}

