/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003c9b64  name=FUN_003c9b64  size=840  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_003c9b64(byte *param_1,code *param_2,undefined4 param_3,uint *param_4,undefined4 param_5)

{
  byte bVar1;
  byte bVar2;
  bool bVar3;
  undefined4 *puVar4;
  int iVar5;
  undefined4 uVar6;
  int iVar7;
  byte *pbVar8;
  uint uStack_38;
  int iStack_34;
  byte *pbStack_30;
  int iStack_2c;
  
  bVar3 = false;
  iStack_34 = 0;
  iVar7 = 0;
  puVar4 = (undefined4 *)FUN_003c66b8(param_5,1);
  uVar6 = *puVar4;
  uStack_38 = (*param_2)(param_3);
  bVar1 = *param_1;
  while (bVar1 != 0) {
    bVar1 = *param_1;
    bVar2 = 1;
    if (((bVar1 == 9) || (bVar1 == 10)) || (bVar1 == 0x20)) {
      param_1 = param_1 + 1;
      bVar1 = *(byte *)(iRam00e272d8 + uStack_38);
      while ((bVar1 & 0x28) != 0) {
        iStack_34 = iStack_34 + 1;
        uStack_38 = (*param_2)(param_3,0xffffffff);
        bVar1 = *(byte *)(iRam00e272d8 + uStack_38);
      }
    }
    else {
      pbVar8 = param_1;
      if (bVar1 == 0x25) {
        pbVar8 = param_1 + 1;
        bVar1 = *pbVar8;
        if (bVar1 == 0x25) goto LAB_003c9e20;
        if (bVar1 < 100) {
          if (bVar1 != 99) {
            if (bVar1 == 0x2a) {
              if ((param_1[2] != 0x5b) && (param_1[2] != 99)) {
                bVar1 = *(byte *)(iRam00e272d8 + uStack_38);
                while ((bVar1 & 0x28) != 0) {
                  iStack_34 = iStack_34 + 1;
                  uStack_38 = (*param_2)(param_3,0xffffffff);
                  bVar1 = *(byte *)(iRam00e272d8 + uStack_38);
                }
              }
            }
            else {
              if (bVar1 == 0x4c) goto LAB_003c9cfc;
              if (bVar1 != 0x5b) goto LAB_003c9d54;
            }
          }
        }
        else {
          if ((bVar1 == 0x68) || (bVar1 == 0x6c)) {
LAB_003c9cfc:
            if (param_1[2] == 0x6e) goto LAB_003c9cf4;
            if ((bVar1 == 0x6c) && (param_1[2] == 0x6c)) {
              bVar1 = param_1[3];
              goto joined_r0x003c9c88;
            }
          }
          else {
joined_r0x003c9c88:
            if (bVar1 == 0x6e) {
LAB_003c9cf4:
              bVar2 = 0;
              goto LAB_003c9d68;
            }
          }
LAB_003c9d54:
          while ((*(byte *)(iRam00e272d8 + uStack_38) & 0x28) != 0) {
            iStack_34 = iStack_34 + 1;
            uStack_38 = (*param_2)(param_3,0xffffffff);
          }
        }
LAB_003c9d68:
        if (uStack_38 == 0xffffffff) {
          bVar1 = *pbVar8;
          if (((bVar1 == 0x4c) || (bVar1 == 0x68)) || (bVar1 == 0x6c)) {
            if (param_1[2] != 0x6e) {
              if ((bVar1 == 0x6c) && (param_1[2] == 0x6c)) {
                bVar1 = param_1[3];
                goto joined_r0x003c9dc0;
              }
              goto LAB_003c9dc4;
            }
          }
          else {
joined_r0x003c9dc0:
            if (bVar1 != 0x6e) {
LAB_003c9dc4:
              bVar3 = true;
            }
          }
        }
        pbStack_30 = pbVar8;
        iVar5 = FUN_003c97f0(&pbStack_30,uVar6,param_2,param_3,&iStack_2c,&uStack_38,&iStack_34);
        param_1 = pbStack_30;
        if (iVar5 != 0) {
          if (iStack_2c == 0) {
            iVar7 = iVar7 + (uint)bVar2;
            puVar4 = (undefined4 *)FUN_003c66b8(param_5,1);
            uVar6 = *puVar4;
          }
          goto LAB_003c9e5c;
        }
      }
      else {
LAB_003c9e20:
        param_1 = pbVar8;
        if (*pbVar8 == uStack_38) {
          iStack_34 = iStack_34 + 1;
          uStack_38 = (*param_2)(param_3,0xffffffff);
          param_1 = pbVar8 + 1;
          goto LAB_003c9e5c;
        }
      }
      bVar3 = true;
    }
LAB_003c9e5c:
    if (bVar3) break;
    bVar1 = *param_1;
  }
  *param_4 = uStack_38;
  if ((iVar7 == 0) && (uStack_38 == 0xffffffff)) {
    iVar7 = -1;
  }
  return iVar7;
}

