/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00591b98  name=FUN_00591b98  size=844  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00591b98(int param_1,uint param_2,int param_3)

{
  int iVar1;
  undefined4 uVar2;
  int iVar3;
  int iVar4;
  uint uVar5;
  uint uVar6;
  int *piVar7;
  int *piVar8;
  ushort *puVar9;
  
  iVar1 = FUN_005552a4(0x87e0);
  if (iVar1 == 0) {
    uVar2 = 0xfffffffe;
  }
  else {
    FUN_0039acec(iVar1,0,0x87e0);
    FUN_005accf4(*(undefined4 *)(param_1 + 0x14c38),0xffffffff);
    for (uVar6 = 0; uVar6 < 0x400; uVar6 = uVar6 + 1) {
      for (uVar5 = 0; uVar5 < 8; uVar5 = uVar5 + 1) {
        *(undefined4 *)(iVar1 + uVar6 * 0x20 + uVar5 * 4 + 0x7e0) =
             *(undefined4 *)(param_1 + uVar6 * 0x30 + uVar5 * 4 + 0x801c);
      }
    }
    for (uVar6 = 0; uVar6 < 0x3f; uVar6 = uVar6 + 1) {
      for (uVar5 = 0; uVar5 < 8; uVar5 = uVar5 + 1) {
        *(undefined4 *)(iVar1 + uVar6 * 0x20 + uVar5 * 4) =
             *(undefined4 *)(param_1 + uVar6 * 0x30 + uVar5 * 4 + 0x1401c);
      }
    }
    FUN_005ad104(*(undefined4 *)(param_1 + 0x14c38));
    for (uVar6 = 0; uVar6 < 0x3f; uVar6 = uVar6 + 1) {
      iVar3 = *(int *)(param_1 + uVar6 * 0x30 + 0x14040);
      piVar7 = (int *)(iVar3 + -0x14);
      if ((*(int *)(param_1 + uVar6 * 0x30 + 0x14044) != iVar3) && (*piVar7 != 0)) {
        do {
          piVar7 = (int *)*piVar7;
          if (*(byte *)(piVar7[3] + 7) == param_2) {
            for (uVar5 = 0; uVar5 < 8; uVar5 = uVar5 + 1) {
              if (((int)(uint)*(byte *)(piVar7[3] + 0x20) >> (uVar5 & 0x3f) & 1U) != 0) {
                piVar8 = (int *)(iVar1 + uVar6 * 0x20 + uVar5 * 4);
                *piVar8 = *piVar8 - *(int *)(piVar7[3] + 2);
              }
            }
          }
        } while ((int *)(*(int *)(param_1 + uVar6 * 0x30 + 0x14044) + -0x14) != piVar7);
      }
    }
    for (puVar9 = *(ushort **)(param_1 + 0x14c20); puVar9 != (ushort *)0x0;
        puVar9 = *(ushort **)((int)puVar9 + 0x21)) {
      if (*(byte *)((int)puVar9 + 7) == param_2) {
        for (uVar6 = (uint)*puVar9; uVar6 < 0x400; uVar6 = uVar6 + 1) {
          for (uVar5 = 0; uVar5 < 8; uVar5 = uVar5 + 1) {
            if (((int)(uint)*(byte *)(puVar9 + 0x10) >> (uVar5 & 0x3f) & 1U) != 0) {
              piVar7 = (int *)(iVar1 + uVar6 * 0x20 + uVar5 * 4 + 0x7e0);
              *piVar7 = *piVar7 - *(int *)(puVar9 + 1);
            }
          }
        }
      }
    }
    for (uVar6 = 0; uVar6 < 0x400; uVar6 = uVar6 + 1) {
      for (uVar5 = 0; uVar5 < 8; uVar5 = uVar5 + 1) {
        iVar4 = *(int *)(iVar1 + uVar6 * 0x20 + uVar5 * 4 + 0x7e0);
        for (iVar3 = *(int *)(param_1 + uVar6 * 0x30 + 0x803c); iVar3 != -1;
            iVar3 = *(int *)(param_1 + iVar3 * 0x30 + 0x1403c)) {
          iVar4 = iVar4 + *(int *)(iVar1 + iVar3 * 0x20 + uVar5 * 4);
        }
        piVar7 = (int *)(param_3 + uVar6 * 4);
        *piVar7 = iVar4 + *piVar7;
      }
    }
    FUN_005554ec(iVar1);
    uVar2 = 0;
  }
  return uVar2;
}

