/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003ed604  name=FUN_003ed604  size=756  xrefs=5
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_003ed604(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  byte bVar1;
  undefined1 uVar2;
  int iVar3;
  undefined4 uVar4;
  undefined4 uVar5;
  int iVar6;
  undefined2 uVar7;
  undefined2 *puVar8;
  undefined1 uStack_30;
  undefined1 uStack_2f;
  undefined1 auStack_2e [12];
  undefined2 uStack_22;
  
  iVar3 = FUN_003dd0a4(1,1);
  if (iVar3 == 0) {
    if (iRam00e29390 == 0) {
      return;
    }
    if ((uRam00e9c3d0 & 0x1000001f) != 0x1000001f) {
      return;
    }
    if ((*(byte *)(iRam00e9bf84 + 0x17) & 2) == 0) {
      return;
    }
    uVar4 = 0x4fce;
    uVar5 = 8;
    uRam00fc0b6c = (uint)bRam00e288e7 << 0x18 | (uint)bRam00e288e6 << 0x10 | (uint)bRam00e288e5 << 8
                   | 0x80000005;
  }
  else {
    *(undefined4 *)(iVar3 + 0x18) = 0;
    iVar6 = (uint)*(byte *)(param_1 + 0x4e) * 2 + 0x10;
    *(int *)(iVar3 + 0xc) = iVar6;
    *(int *)(iVar3 + 0x1c) = iVar6;
    puVar8 = (undefined2 *)
             (*(int *)(iVar3 + 8) + (*(int *)(*(int *)(iVar3 + 0x38) + 4) - iVar6 & 0xfffffffcU));
    *(undefined2 **)(iVar3 + 8) = puVar8;
    bVar1 = *(byte *)(param_1 + 0x4c);
    if ((bVar1 < 7) || ((uVar7 = 6, 10 < bVar1 && (uVar7 = 0x13, bVar1 != 0x25)))) {
      uStack_22 = 0x806;
      uVar7 = 1;
      FUN_0039ac74(auStack_2e,0xe27ad8,6);
    }
    *puVar8 = uVar7;
    puVar8[1] = 0x800;
    uVar2 = *(undefined1 *)(param_1 + 0x4e);
    *(undefined1 *)((int)puVar8 + 5) = 4;
    *(undefined1 *)(puVar8 + 2) = uVar2;
    puVar8[3] = 1;
    FUN_0039ac74(puVar8 + 4,param_4,*(undefined1 *)(puVar8 + 2));
    FUN_0039ac74((int)puVar8 + *(byte *)(puVar8 + 2) + 8,param_2,*(undefined1 *)((int)puVar8 + 5));
    FUN_0039ac74((int)puVar8 +
                 (uint)*(byte *)((int)puVar8 + 5) + (uint)*(byte *)(puVar8 + 2) * 2 + 8,param_3);
    uStack_2f = 0;
    uStack_30 = 0x10;
    (**(code **)(param_1 + 0xa4))(param_1,iVar3,&uStack_30,0);
    if (iRam00e29390 == 0) {
      return;
    }
    if ((uRam00e9c3d0 & 0x1000001f) != 0x1000001f) {
      return;
    }
    if ((*(byte *)(iRam00e9bf84 + 0x1f) & 2) == 0) {
      return;
    }
    uVar4 = 0x4fdd;
    uVar5 = 5;
    uRam00fc0b6c = (uint)bRam00e288e7 << 0x18 | (uint)bRam00e288e6 << 0x10 | (uint)bRam00e288e5 << 8
                   | 0x80000006;
  }
  (*pcRam00e9c4d0)(uVar4,3,uRam00fc0b6c,0x3fd604,uVar5,0,0,0,0,0);
  return;
}

