/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0030198c  name=FUN_0030198c  size=76  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0030198c(int param_1)

{
  if (*(int *)(param_1 + 0x18) != 0) {
    FUN_00301814();
    FUN_002ffe54(param_1);
    *(undefined4 *)(param_1 + 4) = 1;
  }
  return;
}

