/* AUTO-GENERATED by ghidra_decompile_addrs.py (on-demand export)
 * address=0x0058eb0c name=FUN_0058eb0c size=504 xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PPC405, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0058eb0c(void)

{
  undefined4 uVar1;
  byte bVar2;
  
  if (cRam00e3a6d0 == '\0') {
    uVar1 = FUN_0036fd0c();
    cRam00e3a6d0 = cRam00e3a6d0 + '\x01';
    FUN_0036fd24(uVar1);
    FUN_005555ec();
    for (bVar2 = 0; bVar2 < 4; bVar2 = bVar2 + 1) {
      FUN_0039acec((uint)bVar2 * 0x30 + 0xfc825c,0,0x30);
    }
    for (bVar2 = 0; bVar2 < 8; bVar2 = bVar2 + 1) {
      FUN_0039acec((uint)bVar2 * 0x24 + 0xfc831c,0,0x24);
    }
    uRam00e3a6dc = 0;
    iRam00e3a6e0 = FUN_005ab360(1,1);
    if (iRam00e3a6e0 == 0) {
      FUN_0035ad18(0x27c4,0x5a150c,8);
      uVar1 = FUN_0036fd0c();
      cRam00e3a6d0 = cRam00e3a6d0 + -1;
      FUN_0036fd24(uVar1);
      uVar1 = 0xffffffff;
    }
    else {
      iRam00e3a6d8 = FUN_005ab360(1,1);
      if (iRam00e3a6d8 == 0) {
        FUN_0035ad18(0x27c4,0x5a1548,8);
        FUN_005ac50c(iRam00e3a6e0);
        uVar1 = FUN_0036fd0c();
        cRam00e3a6d0 = cRam00e3a6d0 + -1;
        FUN_0036fd24(uVar1);
        uVar1 = 0xffffffff;
      }
      else {
        uRam00e3a6d4 = 0;
        FUN_0035ad18(0x27c4,0x5a1580,8);
        uVar1 = 0;
      }
    }
  }
  else {
    FUN_0035ad18(0x27c4,0x5a14dc,8);
    uVar1 = 0xffffffff;
  }
  return uVar1;
}

