/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003f3d20  name=FUN_003f3d20  size=468  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_003f3d20(void)

{
  uRam00e289c8 = FUN_00460a04(uRam00e9c1f0,uRam00e289c0,0xff,0xd3af48,0xc0000001,0,0,0,0xd48f14,
                              0xd710c4,0xd70d84,0x1b3,0xd6ff0c);
  FUN_00460a04(uRam00e9c1f0,uRam00e289c8,0xffffffff,0xd710cc,0xc0000002,0xe28ad4,0,0x46fc1c,0xda3a00
               ,0xd710d8,0xd70d84,0x1b5,0xd3af48);
  FUN_00460a04(uRam00e9c1f0,uRam00e289c8,0xffffffff,0xdfdb9c,0xc0000002,0xe28ad0,0,0x46fc1c,0xda3a00
               ,0xd71100,0xd70d84,0x1b7,0xd3af48);
  FUN_00460a04(uRam00e9c1f0,uRam00e289c8,0xffffffff,0xd71148,0x80000000,0,0,0x403a38,0xd71150,
               0xd71128,0xd70d84,0x1b9,0xd3af48);
  return 0;
}

