/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00216a50  name=FUN_00216a50  size=36  xrefs=5
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00216a50(int param_1)

{
  FUN_002174f4(param_1 + 4);
  return;
}

