/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004a0508  name=FUN_004a0508  size=716  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_004a0508(undefined4 param_1,int param_2)

{
  bool bVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  undefined4 uVar5;
  int iVar6;
  uint uVar7;
  int iStack_238;
  int iStack_234;
  int iStack_230;
  undefined1 auStack_22c [12];
  undefined1 auStack_220 [256];
  undefined1 uStack_120;
  undefined1 auStack_11c [256];
  undefined1 uStack_1c;
  
  uVar5 = *(undefined4 *)(param_2 + 0xc);
  FUN_004976dc(auStack_22c);
  FUN_0049ab54(param_1,uVar5,0,auStack_22c);
  FUN_0049ab54(param_1,uVar5,1,auStack_22c);
  for (iVar2 = FUN_0049783c(auStack_22c); iVar2 != 0; iVar2 = FUN_004978e4(iVar2)) {
    iVar3 = FUN_004978e4(iVar2);
    while (iVar6 = iVar3, iVar6 != 0) {
      iVar3 = FUN_004978e4(iVar6);
      iVar4 = FUN_0039ad64(*(undefined4 *)(iVar2 + 8),*(undefined4 *)(iVar6 + 8));
      if (iVar4 == 0) {
        FUN_00497774(auStack_22c,iVar6);
        FUN_0045b580(iVar6);
      }
    }
  }
  iVar2 = FUN_00497844(auStack_22c);
  while (iVar2 != 0) {
    iStack_238 = *(int *)(iVar2 + 0x10);
    bVar1 = false;
    uVar5 = *(undefined4 *)(iVar2 + 8);
    if (iStack_238 == 0) {
      uStack_120 = 0;
      iStack_230 = 0x100;
      FUN_0037f0fc(uVar5,auStack_220,&iStack_230,2,&iStack_238);
      iVar3 = FUN_0039ad64(iStack_238,uVar5);
      if (iVar3 == 0) {
        iStack_238 = 0;
        bVar1 = true;
      }
    }
    iStack_234 = *(int *)(iVar2 + 0xc);
    if ((iStack_234 == 0) && (!bVar1)) {
      iStack_230 = 0x100;
      uStack_1c = 0;
      FUN_0037f0fc(uVar5,auStack_11c,&iStack_230,1,&iStack_234);
      iVar3 = FUN_0039ad64(iStack_234,uVar5);
      if (iVar3 == 0) {
        iStack_234 = 0;
      }
    }
    if (iStack_238 == 0) {
      iVar3 = 0;
    }
    else {
      iVar3 = FUN_0039b0f0(iStack_238);
      iVar3 = iVar3 + 1;
    }
    if (iStack_234 == 0) {
      iVar6 = 0;
    }
    else {
      iVar6 = FUN_0039b0f0(iStack_234);
      iVar6 = iVar6 + 1;
    }
    iVar4 = FUN_0039b0f0(uVar5);
    iStack_230 = iVar4 + iVar3 + iVar6 + 0x19;
    iVar3 = FUN_0045b974();
    if (iVar3 != 0) {
      *(int *)(iVar3 + 8) = iVar3 + 0x18;
      FUN_0039af30(iVar3 + 0x18,uVar5);
      iVar6 = FUN_0039b0f0(uVar5);
      iVar6 = *(int *)(iVar3 + 8) + iVar6 + 1;
      if (*(uint *)(iVar2 + 0x14) < 4) {
        uVar7 = (uint)*(byte *)(*(uint *)(iVar2 + 0x14) + 0xd2bb78);
      }
      else {
        uVar7 = 0;
      }
      *(uint *)(iVar3 + 0x14) = uVar7;
      if (iStack_238 != 0) {
        *(int *)(iVar3 + 0xc) = iVar6;
        FUN_0039af30(iVar6,iStack_238);
        iVar6 = FUN_0039b0f0(*(undefined4 *)(iVar3 + 0xc));
        iVar6 = *(int *)(iVar3 + 0xc) + iVar6 + 1;
      }
      if (iStack_234 != 0) {
        *(int *)(iVar3 + 0x10) = iVar6;
        FUN_0039af30(iVar6,iStack_234);
      }
      FUN_004978d0(param_2,iVar3);
    }
    FUN_0045b580(iVar2);
    iVar2 = FUN_00497844(auStack_22c);
  }
  return 0;
}

