/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0041e01c  name=FUN_0041e01c  size=32  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0041e01c(void)

{
  FUN_0045b580();
  return;
}

