/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001aa604  name=FUN_001aa604  size=44  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_001aa604(undefined4 *param_1)

{
  param_1[3] = 0x39f;
  *param_1 = 0;
  param_1[1] = 0x9f;
  param_1[2] = 0x350;
  return;
}

