/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0059e9c8  name=FUN_0059e9c8  size=136  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0059e9c8(undefined4 *param_1,undefined4 param_2,undefined4 param_3,int param_4,
                 undefined4 param_5)

{
  *param_1 = param_2;
  FUN_0059f494(param_1 + 1,0,0,0);
  param_1[9] = param_5;
  param_1[10] = 0;
  param_1[6] = 0;
  param_1[8] = 0;
  *(undefined4 *)(param_4 + 0x10) = 0;
  *(undefined4 *)(param_4 + 0xc) = 0;
  param_1[5] = param_3;
  param_1[7] = param_4;
  return;
}

