/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00542fe4  name=FUN_00542fe4  size=76  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00542fe4(int *param_1)

{
  int iVar1;
  undefined4 uVar2;
  
  iVar1 = *param_1;
  uVar2 = 0xd8f654;
  if (iVar1 != 0x301) {
    uVar2 = 0xd8f64c;
    if ((iVar1 != 0x300) && (uVar2 = 0xd8e074, iVar1 != 2)) {
      uVar2 = 0xd90540;
    }
  }
  return uVar2;
}

