/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001c04bc  name=FUN_001c04bc  size=944  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_001c04bc(int param_1,undefined4 *param_2,undefined4 *param_3,undefined4 *param_4,
                 undefined4 *param_5,undefined4 *param_6,undefined4 *param_7,undefined4 *param_8,
                 undefined4 *param_9,int param_10)

{
  int iVar1;
  undefined4 uVar2;
  undefined4 uVar3;
  uint uVar4;
  undefined4 uVar5;
  undefined4 uVar6;
  int iVar7;
  undefined4 *puVar8;
  int iVar9;
  int iVar10;
  uint uVar11;
  uint uVar12;
  undefined4 uVar13;
  int iVar14;
  undefined4 uStack_c8;
  undefined4 uStack_c4;
  undefined4 uStack_c0;
  undefined4 uStack_bc;
  undefined4 uStack_b8;
  undefined4 uStack_b4;
  undefined4 uStack_b0;
  undefined4 uStack_ac;
  undefined4 uStack_a8;
  undefined4 uStack_a4;
  undefined4 uStack_a0;
  undefined4 uStack_9c;
  undefined4 uStack_98;
  undefined4 uStack_94;
  undefined4 uStack_90;
  undefined4 uStack_8c;
  undefined4 uStack_88;
  undefined4 uStack_84;
  undefined4 uStack_80;
  undefined4 uStack_7c;
  undefined4 uStack_78;
  undefined4 uStack_74;
  undefined4 uStack_70;
  undefined4 uStack_6c;
  undefined4 uStack_58;
  undefined4 uStack_54;
  
  iVar7 = (param_10 << 1) / 0xc;
  uVar2 = FUN_00374be8(*param_2,*param_2);
  puVar8 = &uStack_c8;
  uStack_c8 = FUN_00374be4(uVar2,*param_3);
  uVar2 = FUN_00374be8(param_2[1],param_2[1]);
  uStack_c4 = FUN_00374be4(uVar2,param_3[1]);
  uStack_98 = *param_6;
  uStack_94 = param_6[1];
  uStack_bc = param_2[1];
  uStack_b0 = *param_3;
  uStack_a8 = *param_4;
  uStack_a0 = *param_5;
  uStack_9c = param_5[1];
  uStack_8c = param_7[1];
  uStack_c0 = *param_2;
  uStack_ac = param_3[1];
  uStack_a4 = param_4[1];
  uStack_90 = *param_7;
  uStack_84 = param_8[1];
  uStack_88 = *param_8;
  uStack_80 = *param_9;
  uStack_7c = param_9[1];
  uStack_78 = *param_9;
  uStack_b8 = uStack_c0;
  uStack_b4 = uStack_bc;
  uStack_74 = uStack_7c;
  uVar2 = FUN_00374be8(uStack_78,uStack_78);
  uVar11 = 0;
  uStack_70 = FUN_00374be4(uVar2,*param_8);
  uVar2 = FUN_00374be8(param_9[1],param_9[1]);
  iVar9 = 0;
  uStack_6c = FUN_00374be4(uVar2,param_8[1]);
  do {
    while (iVar10 = 0, iVar7 < 1) {
      iVar9 = iVar9 + 1;
      puVar8 = puVar8 + 2;
      if (8 < iVar9) goto LAB_001c078c;
    }
    uVar2 = FUN_0037517c(iVar7 + -1);
    uVar12 = uVar11;
    do {
      uVar3 = FUN_0037517c(iVar10);
      uVar3 = FUN_00374f8c(uVar3,uVar2);
      FUN_001c0260(puVar8,puVar8 + 2,puVar8 + 4,puVar8 + 6,uVar3,&uStack_58);
      uVar3 = FUN_0037517c(param_10);
      FUN_00374e00(uStack_58,uVar3);
      uVar4 = FUN_00375230();
      uVar4 = uVar4 & (int)~uVar4 >> 0x1f;
      uVar11 = param_10 - 1;
      if ((int)uVar4 < param_10) {
        uVar11 = uVar4;
      }
      iVar14 = uVar12 + 1;
      *(undefined4 *)(param_1 + uVar11 * 4) = uStack_54;
      if (iVar14 < (int)uVar11) {
        uVar13 = *(undefined4 *)(param_1 + uVar12 * 4);
        uVar3 = FUN_00374be4(uStack_54,uVar13);
        uVar5 = FUN_0037517c(uVar11 - uVar12);
        do {
          uVar6 = FUN_0037517c(iVar14 - uVar12);
          uVar6 = FUN_00374f8c(uVar6,uVar5);
          uVar6 = FUN_00374e00(uVar3,uVar6);
          iVar1 = iVar14 * 4;
          iVar14 = iVar14 + 1;
          uVar6 = FUN_00374be8(uVar6,uVar13);
          *(undefined4 *)(iVar1 + param_1) = uVar6;
        } while (iVar14 < (int)uVar11);
      }
      iVar10 = iVar10 + 1;
      uVar12 = uVar11;
    } while (iVar10 < iVar7);
    iVar9 = iVar9 + 1;
    puVar8 = puVar8 + 2;
  } while (iVar9 < 9);
LAB_001c078c:
  uVar2 = FUN_0037517c(param_10);
  FUN_00374e00(*param_2,uVar2);
  iVar7 = FUN_00375230();
  FUN_00374e00(*param_9,uVar2);
  iVar9 = FUN_00375230();
  iVar10 = 0;
  if (0 < iVar7) {
    do {
      *(undefined4 *)(param_1 + iVar10 * 4) = param_2[1];
      iVar10 = iVar10 + 1;
      iVar7 = iVar7 + -1;
    } while (iVar7 != 0);
  }
  if (iVar9 < param_10) {
    param_10 = param_10 - iVar9;
    do {
      iVar7 = iVar9 * 4;
      iVar9 = iVar9 + 1;
      *(undefined4 *)(param_1 + iVar7) = param_9[1];
      param_10 = param_10 + -1;
    } while (param_10 != 0);
  }
  return;
}

