/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x000068d4  name=FUN_000068d4  size=456  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_000068d4(void)

{
  ushort uStack_8;
  
  FUN_00000f54();
  FUN_003cb350(0xd32af0,uStack_8);
  if ((uStack_8 & 0x10) != 0) {
    FUN_003cb350(0xd32b14);
  }
  if ((uStack_8 & 0x20) != 0) {
    FUN_003cb350(0xd32b1c);
  }
  if ((uStack_8 & 0x40) != 0) {
    FUN_003cb350(0xd32b24);
  }
  if ((uStack_8 & 0x80) != 0) {
    FUN_003cb350(0xd32b2c);
  }
  if ((uStack_8 & 0x100) == 0) {
    FUN_003cb350(0xd32b04,uStack_8 >> 9 & 3);
  }
  else {
    FUN_003cb350(0xd32b34);
    FUN_003cb350(0xd32b04,uStack_8 >> 9 & 3);
  }
  if ((uStack_8 & 0x800) != 0) {
    FUN_003cb350(0xd32b48);
  }
  if ((uStack_8 & 0x1000) != 0) {
    FUN_003cb350(0xd32b58);
  }
  if ((uStack_8 & 0x2000) != 0) {
    FUN_003cb350(0xd32b68);
  }
  if ((uStack_8 & 0x4000) != 0) {
    FUN_003cb350(0xd32b78);
  }
  if ((uStack_8 & 0x8000) == 0) {
    FUN_003cb350(0xd32b10);
    return 0;
  }
  FUN_003cb350(0xd32b88);
  FUN_003cb350(0xd32b10);
  return 0;
}

