/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00472f98  name=FUN_00472f98  size=28  xrefs=5
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00472f98(uint param_1)

{
  if ((param_1 & 0x2e) == 4) {
    return 2;
  }
  return 3;
}

