/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001a64f4  name=FUN_001a64f4  size=1264  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


/* WARNING: Removing unreachable block (ram,0x001a66d8) */

undefined4 FUN_001a64f4(undefined4 param_1,undefined4 param_2)

{
  bool bVar1;
  bool bVar2;
  bool bVar3;
  bool bVar4;
  undefined4 *puVar5;
  undefined4 uVar6;
  int iVar7;
  int iVar8;
  int iVar9;
  int iVar10;
  undefined4 uVar11;
  int iVar12;
  undefined4 *puVar13;
  undefined4 uVar14;
  int iVar15;
  byte in_cr0;
  byte in_cr1;
  byte unaff_cr2;
  byte unaff_cr3;
  byte unaff_cr4;
  byte in_cr5;
  byte in_cr6;
  byte in_cr7;
  undefined1 auStack_c8 [16];
  undefined1 auStack_b8 [32];
  undefined1 auStack_98 [16];
  undefined1 auStack_88 [16];
  undefined4 uStack_78;
  undefined4 uStack_74;
  undefined4 uStack_70;
  undefined4 uStack_6c;
  undefined4 uStack_68;
  undefined4 uStack_64;
  undefined4 uStack_60;
  undefined4 uStack_5c;
  undefined4 uStack_58;
  undefined4 auStack_48 [4];
  uint uStack_38;
  
  uStack_38 = (uint)(in_cr0 & 0xf) << 0x1c | (uint)(in_cr1 & 0xf) << 0x18 |
              (uint)(unaff_cr2 & 0xf) << 0x14 | (uint)(unaff_cr3 & 0xf) << 0x10 |
              (uint)(unaff_cr4 & 0xf) << 0xc | (uint)(in_cr5 & 0xf) << 8 | (uint)(in_cr6 & 0xf) << 4
              | (uint)(in_cr7 & 0xf);
  auStack_48[0] = 0;
  FUN_001a5f3c();
  iVar15 = 0;
  uStack_78 = 0x4d314835;
  uStack_74 = 0x67774f58;
  uStack_70 = 0x68373537;
  uStack_6c = 0x72495256;
  uStack_68 = 0x5936476a;
  uStack_64 = 0x32744e30;
  uStack_60 = 0x38304159;
  uStack_5c = 0x53583033;
  uStack_58 = 0;
  FUN_0039b1d4(&uStack_78,0xd53140,0x24);
  puVar5 = (undefined4 *)FUN_004afef8(0xd53164);
  uVar14 = 2;
  if (puVar5 == (undefined4 *)0x0) {
    puVar5 = (undefined4 *)FUN_00398e8c();
    FUN_0039995c(*puVar5,0xd531f0,0xd53164);
    return 2;
  }
  uVar6 = FUN_004affc8();
  iVar7 = FUN_004a849c(0x2c52,0xd52ffc,0x202);
  if (iVar7 == 0) {
    puVar5 = (undefined4 *)FUN_00398e8c();
    FUN_0039995c(*puVar5,0xd5320c,0x2c52);
    return 2;
  }
  FUN_004a2768();
  iVar8 = FUN_004a18ac();
  FUN_004a2768();
  iVar9 = FUN_004a18ac();
  bVar1 = iVar9 != 0;
  bVar3 = iVar8 != 0;
  bVar4 = bVar3 && bVar1;
  bVar2 = true;
  if (bVar3 && bVar1) {
    iVar10 = FUN_004a1ff0(iVar8,0x6c,3,param_2);
    bVar2 = bVar4;
    if (iVar10 < 1) {
      puVar5 = (undefined4 *)FUN_00398e8c();
      puVar13 = (undefined4 *)FUN_00442914();
      FUN_0039995c(*puVar5,0xd5319c,param_2,*puVar13);
    }
    else {
      iVar10 = FUN_004a1ff0(iVar9,0x6c,5,param_1);
      if (0 < iVar10) {
        iVar10 = FUN_004a1a24(iVar8,auStack_c8,8);
        if (iVar10 == 8) {
          iVar10 = FUN_004a1a24(iVar8,auStack_88,8);
          if (iVar10 == 8) {
            iVar10 = FUN_0039ac2c(auStack_c8,0x663850,8);
            if (iVar10 == 0) {
              uVar11 = FUN_0039b0f0(&uStack_78);
              FUN_004afaf8(puVar5,uVar6,auStack_88,&uStack_78,uVar11,1,auStack_b8,auStack_98);
              uVar6 = FUN_0039b0f0(&uStack_78);
              FUN_004a89ec(&uStack_78,uVar6);
              FUN_004b0e48();
              iVar15 = FUN_004a18ac();
              bVar2 = iVar15 == 0;
              if (!bVar2) {
                FUN_004a1ff0(iVar15,0x81,0,auStack_48);
                iVar10 = FUN_004af448(auStack_48[0],puVar5,0,0,0,0);
                if ((iVar10 == 0) ||
                   (iVar10 = FUN_004af448(auStack_48[0],0,0,auStack_b8,auStack_98,0), iVar10 == 0))
                {
                  puVar13 = (undefined4 *)FUN_00398e8c();
                  uVar6 = FUN_004ab358(*puVar5);
                  FUN_0039995c(*puVar13,0xd531d4,uVar6);
                }
                else {
                  uVar6 = FUN_004a2314(iVar15,iVar9);
                  while (iVar10 = FUN_004a1a24(iVar8,iVar7,0x2000), 0 < iVar10) {
                    iVar12 = FUN_004a1b68(uVar6,iVar7,iVar10);
                    if (iVar12 != iVar10) {
                      puVar5 = (undefined4 *)FUN_00398e8c(5);
                      FUN_00397dc0(0xd53228,1,0x1a,*puVar5);
                      goto LAB_001a6754;
                    }
                    FUN_001d9a58();
                  }
                  iVar10 = FUN_004a1ff0(uVar6,0xb,0,0);
                  uVar14 = 0;
                  if (iVar10 == 0) {
                    puVar5 = (undefined4 *)FUN_00398e8c();
                    FUN_00397dc0(0xd5318c,1,0xc,*puVar5);
                    uVar14 = 5;
                  }
                }
              }
            }
            else {
              puVar5 = (undefined4 *)FUN_00398e8c();
              FUN_00397dc0(0xd531c0,1,0x11,*puVar5);
            }
            goto LAB_001a6754;
          }
        }
        puVar5 = (undefined4 *)FUN_00398e8c();
        FUN_00397dc0(0xd53170,1,0x19,*puVar5);
      }
    }
  }
LAB_001a6754:
  FUN_004a8858(iVar7);
  if (bVar3) {
    FUN_004a193c(iVar8);
  }
  if (bVar1) {
    FUN_004a24e4(iVar9);
  }
  if (!bVar2) {
    FUN_004a193c(iVar15);
  }
  FUN_001a5f60();
  return uVar14;
}

