/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004c90d4  name=FUN_004c90d4  size=128  xrefs=5
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_004c90d4(undefined4 *param_1,undefined4 param_2,undefined4 param_3)

{
  undefined4 *apuStack_10 [2];
  
  if (param_1[1] == 0) {
    param_1[1] = param_3;
    *param_1 = param_2;
    return;
  }
  apuStack_10[0] = param_1;
  FUN_004b4bc0(apuStack_10,0);
  apuStack_10[0][1] = param_3;
  *apuStack_10[0] = param_2;
  return;
}

