/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00219558  name=FUN_00219558  size=60  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00219558(void)

{
  int iVar1;
  
  iVar1 = FUN_00557644(uRam00eb4ffc,2);
  if (iVar1 == 0) {
    uRam00eb5000 = 0;
  }
  return;
}

