/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0036fbb8  name=FUN_0036fbb8  size=40  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0036fbb8(int param_1,uint param_2)

{
  *(uint *)(param_1 + 0x80) = *(uint *)(param_1 + 0x80) & 0xfffd7fff | param_2 & 0x28000;
  return;
}

