/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0032a02c  name=FUN_0032a02c  size=20  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0032a02c(int param_1,undefined4 param_2)

{
  *(undefined4 *)(param_1 + 0x744) = param_2;
  return 0;
}

