/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003ba74c  name=FUN_003ba74c  size=632  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_003ba74c(int param_1,int param_2,int param_3,int param_4,undefined4 param_5)

{
  int iVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  undefined4 uVar5;
  undefined4 uVar6;
  
  uVar6 = 0;
  FUN_003b2c6c(param_5);
  iVar1 = FUN_003b3030(param_5);
  iVar2 = FUN_003b3030(param_5);
  if (param_1 == 0) {
    param_1 = FUN_003b3030(param_5);
  }
  if (param_2 == 0) {
    param_2 = FUN_003b3030(param_5);
  }
  if ((((iVar1 != 0) && (iVar2 != 0)) && (param_1 != 0)) && (param_2 != 0)) {
    iVar3 = FUN_003b61ec(param_3,param_4);
    if (iVar3 < 0) {
      FUN_003b5fa8(param_1,0);
      iVar1 = FUN_003b5c98(param_2,param_3);
      if (iVar1 == 0) {
        return 0;
      }
      FUN_003b311c(param_5);
      return 1;
    }
    iVar4 = FUN_003b5930(param_3);
    iVar3 = *(int *)(param_4 + 0x28) << 1;
    if (iVar4 < iVar3) {
      iVar4 = iVar3;
    }
    if (*(int *)(param_4 + 0x2c) != iVar4) {
      uVar5 = FUN_003ba6b8(param_4 + 0x14,param_4,iVar4,param_5);
      *(undefined4 *)(param_4 + 0x2c) = uVar5;
    }
    if (((*(int *)(param_4 + 0x2c) != -1) &&
        (iVar3 = FUN_003bae88(iVar1,param_3,*(undefined4 *)(param_4 + 0x28)), iVar3 != 0)) &&
       ((iVar1 = FUN_003b8894(iVar2,iVar1,param_4 + 0x14,param_5), iVar1 != 0 &&
        (iVar1 = FUN_003bae88(param_1,iVar2,iVar4 - *(int *)(param_4 + 0x28)), iVar1 != 0)))) {
      *(undefined4 *)(param_1 + 0xc) = 0;
      iVar1 = FUN_003b8894(iVar2,param_4,param_1,param_5);
      if ((iVar1 != 0) && (iVar1 = FUN_003adcb8(param_2,param_3,iVar2), iVar1 != 0)) {
        iVar1 = 0;
        *(undefined4 *)(param_2 + 0xc) = 0;
        while (iVar2 = FUN_003b61ec(param_2,param_4), -1 < iVar2) {
          if (2 < iVar1) {
            FUN_003bccc8(3,0x82,0x65,0,0);
            goto LAB_003ba9a4;
          }
          iVar1 = iVar1 + 1;
          iVar2 = FUN_003adcb8(param_2,param_2,param_4);
          if ((iVar2 == 0) || (iVar2 = FUN_003bb604(param_1,1), iVar2 == 0)) goto LAB_003ba9a4;
        }
        if (*(int *)(param_2 + 4) != 0) {
          uVar6 = *(undefined4 *)(param_3 + 0xc);
        }
        *(undefined4 *)(param_2 + 0xc) = uVar6;
        uVar6 = 1;
        *(uint *)(param_1 + 0xc) = *(uint *)(param_3 + 0xc) ^ *(uint *)(param_4 + 0xc);
      }
    }
  }
LAB_003ba9a4:
  FUN_003b311c(param_5);
  return uVar6;
}

