/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001ed6fc  name=FUN_001ed6fc  size=84  xrefs=21
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_001ed6fc(int param_1)

{
  undefined4 uVar1;
  
  if (*(int *)(param_1 + 4) < 0) {
    return 0;
  }
  uVar1 = FUN_0044e6d0(*(int *)(param_1 + 4),0,1);
  return uVar1;
}

