/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004e17c4  name=FUN_004e17c4  size=312  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


uint * FUN_004e17c4(uint *param_1,undefined4 param_2)

{
  undefined4 *puVar1;
  uint *puVar2;
  uint uVar3;
  undefined1 auStack_50 [48];
  undefined4 auStack_20 [4];
  
  auStack_20[0] = param_2;
  if ((param_1 == (uint *)0x0) && (param_1 = (uint *)FUN_004b92bc(0x18), param_1 == (uint *)0x0)) {
    return (uint *)0x0;
  }
  puVar1 = (undefined4 *)FUN_004e0efc(auStack_20,auStack_50);
  puVar2 = (uint *)0x0;
  if (puVar1 != (undefined4 *)0x0) {
    uVar3 = param_1[2];
    if ((uVar3 == 0) || (*param_1 < 0x14)) {
      uVar3 = FUN_004a849c(0x14,0xd7dae4,0xe2);
      if (uVar3 == 0) {
        FUN_004a6438(0xd,0xb9,0x41,0xd7dae4,0xe6);
        return (uint *)0x0;
      }
      if (param_1[2] == 0) {
        param_1[2] = uVar3;
      }
      else {
        FUN_004a8858();
        param_1[2] = uVar3;
      }
    }
    FUN_004bdfa0(uVar3,0x14,0xd7daf0,puVar1[5] + 0x76c,puVar1[4] + 1,puVar1[3],puVar1[2],puVar1[1],
                 *puVar1);
    uVar3 = FUN_0039b0f0(uVar3);
    *param_1 = uVar3;
    param_1[1] = 0x18;
    puVar2 = param_1;
  }
  return puVar2;
}

