/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001c9100  name=FUN_001c9100  size=616  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4
FUN_001c9100(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4,
            undefined4 param_5)

{
  undefined4 uVar1;
  undefined4 uVar2;
  undefined4 uVar3;
  undefined4 uVar4;
  undefined4 uVar5;
  int iVar6;
  undefined8 uVar7;
  undefined8 uVar8;
  undefined8 uVar9;
  
  uVar1 = FUN_00374e00(param_1,0x457ff000);
  FUN_00376648(&MMIO_40240000,0);
  uVar2 = FUN_00373f30();
  uVar3 = FUN_00374e00(param_3,0x3b03126f);
  uVar3 = FUN_00374f8c(uVar3,param_2);
  uVar4 = FUN_00374e00(param_4,0x3b03126f);
  uVar5 = FUN_00374f8c(uVar4,param_2);
  FUN_00374be4(uVar3,uVar5);
  uVar7 = FUN_00373e9c();
  uVar7 = FUN_00376e94(&MMIO_40240000,0,(int)((ulonglong)uVar7 >> 0x20),(int)uVar7);
  FUN_00374f8c(param_5,0x457ff000);
  uVar8 = FUN_00373e9c();
  FUN_0037336c((int)((ulonglong)uVar7 >> 0x20),(int)uVar7,(int)((ulonglong)uVar8 >> 0x20),(int)uVar8
              );
  uVar3 = FUN_00373f30();
  uVar1 = FUN_00374f8c(uVar1,0x457ff000);
  uVar1 = FUN_00374be8(uVar1,uVar3);
  iVar6 = FUN_00377fa8(uVar1,0x3a83126f);
  if (iVar6 < 0) {
    uVar1 = 0x3a83126f;
  }
  iVar6 = FUN_00377fa8(param_2,0x3a83126f);
  if (iVar6 < 0) {
    param_2 = 0x3a83126f;
  }
  FUN_00374f8c(param_2,0x3b03126f);
  uVar7 = FUN_00373e9c();
  FUN_00373e9c(uVar1);
  uVar8 = FUN_00376648();
  uVar9 = FUN_00373e9c(uVar2);
  uVar8 = FUN_003739c0((int)((ulonglong)uVar8 >> 0x20),(int)uVar8,(int)((ulonglong)uVar9 >> 0x20),
                       (int)uVar9);
  FUN_00374f8c(uVar4,param_2);
  uVar9 = FUN_00373e9c();
  uVar8 = FUN_00373370((int)((ulonglong)uVar8 >> 0x20),(int)uVar8,(int)((ulonglong)uVar9 >> 0x20),
                       (int)uVar9);
  FUN_00373704((int)((ulonglong)uVar7 >> 0x20),(int)uVar7,(int)((ulonglong)uVar8 >> 0x20),(int)uVar8
              );
  uVar1 = FUN_00373f30();
  uVar1 = FUN_00374f8c(uVar1,0x447fc000);
  iVar6 = FUN_00377fa8(uVar1,0);
  if (iVar6 < 0) {
    uVar1 = 0;
  }
  iVar6 = FUN_003754f4(uVar1,0x3f800000);
  if (0 < iVar6) {
    uVar1 = 0x3f800000;
  }
  return uVar1;
}

