/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003e6aa4  name=FUN_003e6aa4  size=272  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_003e6aa4(undefined4 param_1,int param_2)

{
  int iVar1;
  int iVar2;
  
  iVar1 = FUN_0039ad64(param_1,0xd6f6b4);
  while (param_2 != 0) {
    iVar2 = *(int *)(param_2 + 100);
    if ((iVar2 == 0) || ((*(byte *)(*(int *)(iVar2 + 0xc) + 0x70) & 1) == 0)) {
      param_2 = *(int *)(param_2 + 8);
    }
    else {
      FUN_003cb350(0xd6f6b8,param_2);
      FUN_003cb350(0xd6f6c0,param_1,*(undefined4 *)(iVar2 + 0xdc),*(undefined4 *)(iVar2 + 0x168));
      FUN_003e6a04(param_2 + 0x38,*(undefined2 *)(param_2 + 0x1a));
      FUN_003e6a04(param_2 + 0x28,*(undefined2 *)(param_2 + 0x18));
      if ((iVar1 == 0) && (pcRam00e28dac != reset_vector)) {
        (*pcRam00e28dac)(param_2);
      }
      FUN_003cb350(0xd37ae4);
      param_2 = *(int *)(param_2 + 8);
    }
  }
  return;
}

