/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0028120c  name=FUN_0028120c  size=532  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_0028120c(int *param_1,int param_2)

{
  int iVar1;
  undefined4 uVar2;
  int *piVar3;
  int iVar4;
  char *pcVar5;
  int *piStack_20;
  int iStack_1c;
  undefined4 uStack_18;
  undefined4 uStack_14;
  
  if (*param_1 == 0) {
    return 0;
  }
  iVar1 = FUN_002c1394();
  if (iVar1 - 1U < 2) {
    iVar4 = (**(code **)(*(int *)param_1[0x65] + 0x10))((int *)param_1[0x65],param_1[0x12] + 2);
    FUN_0039ac74(iVar4,*param_1,param_1[0x12]);
    *(undefined1 *)(iVar4 + param_1[0x12]) = 0;
    *(undefined1 *)(iVar4 + param_1[0x12] + 1) = 0;
    uVar2 = FUN_002c141c(param_1[0x65],iVar4 + 2,iVar1,0);
    piVar3 = (int *)param_1[0x65];
    if (iVar4 == 0 || piVar3 == (int *)0x0) {
      return uVar2;
    }
    iVar1 = *piVar3;
LAB_0028135c:
    (**(code **)(iVar1 + 0x14))(piVar3,iVar4);
  }
  else {
    if (iVar1 == 0) {
      iVar1 = param_1[0x65];
      iVar4 = *param_1 + 3;
    }
    else {
      iVar1 = FUN_002a7b04(param_1[0xa7]);
      if (iVar1 != 0) {
        if (param_2 == 0) {
          uVar2 = FUN_002c141c(param_1[0x65],*param_1,6,1);
          (&LAB_00001680)[param_1[0xa7]] = 1;
          return uVar2;
        }
        pcVar5 = (char *)*param_1;
        if (pcVar5 == (char *)0x0) {
          return 0;
        }
        piVar3 = (int *)param_1[0x65];
        uStack_14 = 0;
        iStack_1c = 0;
        uStack_18 = 0;
        piStack_20 = piVar3;
        if (*pcVar5 != '\0') {
          do {
            uVar2 = FUN_002a79e8(param_1[0xa7]);
            pcVar5 = (char *)FUN_0029b1d8(param_1[0x65],pcVar5,&piStack_20,uVar2,1,1,0);
          } while (*pcVar5 != '\0');
          piVar3 = (int *)param_1[0x65];
        }
        uVar2 = FUN_002c141c(piVar3,iStack_1c,6,1);
        if (iStack_1c == 0 || piStack_20 == (int *)0x0) {
          return uVar2;
        }
        iVar1 = *piStack_20;
        piVar3 = piStack_20;
        iVar4 = iStack_1c;
        goto LAB_0028135c;
      }
      iVar4 = *param_1;
      iVar1 = param_1[0x65];
    }
    uVar2 = FUN_00258c6c(iVar1,iVar4);
  }
  return uVar2;
}

