/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005c8404  name=FUN_005c8404  size=20  xrefs=5
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_005c8404(void)

{
  return 0xe3ba8c;
}

