/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002c8340  name=FUN_002c8340  size=88  xrefs=88
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002c8340(void)

{
  int iStack_10;
  int iStack_c;
  
  FUN_0043cf80(0,&iStack_10);
  iRam00ef949c = iStack_10 * 1000 + iStack_c / 1000000;
  return;
}

