/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0008612c  name=FUN_0008612c  size=64  xrefs=4
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0008612c(undefined4 param_1,int param_2,uint param_3,int param_4)

{
  int iVar1;
  uint uVar2;
  
  iVar1 = 0;
  uVar2 = 0;
  if (0 < param_4) {
    do {
      uVar2 = uVar2 + *(int *)(param_2 + iVar1 * 4);
      if (param_3 >> 1 <= uVar2) {
        return;
      }
      iVar1 = iVar1 + 1;
    } while (iVar1 < param_4);
  }
  return;
}

