/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0059d9cc  name=FUN_0059d9cc  size=36  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0059d9cc(undefined4 param_1,undefined4 param_2,undefined4 param_3)

{
  uRam00e9bfe4 = param_1;
  uRam00e9c10c = param_2;
  uRam00e3a738 = param_3;
  return;
}

