/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003b5800  name=FUN_003b5800  size=88  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_003b5800(int param_1)

{
  if (param_1 == 0) {
    return uRam00e278d0;
  }
  if (param_1 == 1) {
    return uRam00e278d8;
  }
  if (param_1 == 2) {
    return uRam00e278d4;
  }
  if (param_1 == 3) {
    return uRam00e278dc;
  }
  return 0;
}

