/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00284f10  name=FUN_00284f10  size=600  xrefs=10
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00284f10(int param_1)

{
  uint uVar1;
  int iVar2;
  uint uVar3;
  uint *puVar4;
  int iVar5;
  undefined1 auStack_20 [20];
  
  if (*(int *)(param_1 + 0x74) != 0) {
    FUN_002c38ec(auStack_20,*(undefined4 *)(param_1 + 0x18),*(undefined4 *)(param_1 + 0xac));
    (**(code **)(param_1 + 0x74))(param_1,*(undefined4 *)(param_1 + 0x78));
    FUN_002c3b54(auStack_20);
  }
  if (*(int *)(param_1 + 0x9c) != 0) {
    if (*(int *)(param_1 + 0x9c) != 0 && *(int **)(param_1 + 4) != (int *)0x0) {
      (**(code **)(**(int **)(param_1 + 4) + 0x14))();
    }
  }
  FUN_00284a80(param_1);
  FUN_0063b3ec(param_1);
  if (((*(int *)(param_1 + 0x18) != 0) && (*(int *)(param_1 + 0x1c) == 0)) &&
     (*(int *)(param_1 + 0x14) == 0)) {
    FUN_002d1614(*(undefined4 *)(*(int *)(param_1 + 0x18) + 0xc08),param_1);
  }
  if (*(int *)(param_1 + 0x7c) != 0 && *(int **)(param_1 + 4) != (int *)0x0) {
    (**(code **)(**(int **)(param_1 + 4) + 0x14))();
  }
  if (*(int *)(param_1 + 0x10) != 0) {
    *(undefined4 *)(*(int *)(param_1 + 0x10) + 4) = 0;
    FUN_00289600();
  }
  if (*(int *)(param_1 + 0xac) != 0) {
    FUN_002c1fb8();
    *(undefined4 *)(param_1 + 0xac) = 0;
  }
  if (*(int *)(param_1 + 0xb0) != 0) {
    FUN_002c1fb8();
    *(undefined4 *)(param_1 + 0xb0) = 0;
  }
  iVar2 = *(int *)(param_1 + 8);
  if (iVar2 != 0) {
    iVar5 = iVar2 + *(int *)(iVar2 + -4) * 0x10;
    while (iVar2 != iVar5) {
      FUN_002875f0(iVar5 + -0x10);
      puVar4 = *(uint **)(iVar5 + -0xc);
      if (puVar4 != (uint *)0x0) {
        uVar1 = *puVar4;
        uVar3 = ((int)(uVar1 << 1 | uVar1 >> 0x1f) >> 1) - 1;
        *puVar4 = uVar3 & 0x7fffffff | uVar1 & 0x80000000;
        if ((int)(uVar3 * 2) < 1) {
          FUN_0028a778(puVar4);
        }
      }
      iVar5 = iVar5 + -0x10;
      iVar2 = *(int *)(param_1 + 8);
    }
    FUN_00245be8(iVar2 + -8);
    *(undefined4 *)(param_1 + 8) = 0;
  }
  if (*(int *)(param_1 + 0xb4) != 0) {
    *(undefined4 *)(*(int *)(param_1 + 0xb4) + 0x54) = 0;
  }
  FUN_002875f0(param_1 + 0x48);
  puVar4 = *(uint **)(param_1 + 0x4c);
  if (puVar4 != (uint *)0x0) {
    uVar1 = *puVar4;
    uVar3 = ((int)(uVar1 << 1 | uVar1 >> 0x1f) >> 1) - 1;
    *puVar4 = uVar3 & 0x7fffffff | uVar1 & 0x80000000;
    if ((int)(uVar3 * 2) < 1) {
      FUN_0028a778();
    }
  }
  *(undefined4 *)(param_1 + 0x28) = 0xe0a7b8;
  FUN_002d10ac(param_1 + 0x28);
  return;
}

