/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001a0f08  name=FUN_001a0f08  size=72  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_001a0f08(undefined4 param_1,undefined4 param_2,undefined4 *param_3)

{
  undefined4 auStack_18 [3];
  
  auStack_18[0] = param_2;
  FUN_0019fb28(auStack_18,0xffd9);
  *param_3 = 2;
  return 0;
}

