/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004412a0  name=FUN_004412a0  size=72  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_004412a0(void)

{
  undefined4 *puVar1;
  undefined4 uVar2;
  
  puVar1 = (undefined4 *)FUN_00442914();
  uVar2 = *puVar1;
  FUN_0049b00c(0xe2922c,0x10);
  puVar1 = (undefined4 *)FUN_00442914();
  *puVar1 = uVar2;
  return 0;
}

