/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005b4f8c  name=FUN_005b4f8c  size=8  xrefs=5
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_005b4f8c(undefined4 param_1)

{
  FUN_005b4c90(param_1,1);
  return;
}

