/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001dca04  name=FUN_001dca04  size=156  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_001dca04(void)

{
  FUN_001d9204(uRam00ea28cc,0xffffffff);
  if (iRam00ea289c == 0) {
    FUN_001d92bc(uRam00ea28cc);
    return 0xffffffff;
  }
  uRam00ea28a4 = 0;
  FUN_001d92bc(uRam00ea28cc);
  return 0;
}

