/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004e3668  name=FUN_004e3668  size=248  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_004e3668(code *param_1,int param_2,byte *param_3,int param_4)

{
  byte bVar1;
  int iVar2;
  byte *pbVar3;
  undefined1 uStack_30;
  undefined1 uStack_2f;
  
  if ((param_2 != 0) && (pbVar3 = param_3 + param_4, param_3 != pbVar3)) {
    do {
      bVar1 = *param_3;
      param_3 = param_3 + 1;
      uStack_30 = *(undefined1 *)((bVar1 >> 4) + 0xd2ecd0);
      uStack_2f = *(undefined1 *)((bVar1 & 0xf) + 0xd2ecd0);
      iVar2 = (*param_1)(param_2,&uStack_30,2);
      if (iVar2 == 0) {
        return -1;
      }
    } while (param_3 != pbVar3);
  }
  return param_4 << 1;
}

