/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00555010  name=FUN_00555010  size=60  xrefs=8
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00555010(void)

{
  int iVar1;
  undefined4 uVar2;
  
  iVar1 = FUN_005ac50c();
  if (iVar1 == 0) {
    uVar2 = 0;
  }
  else {
    uVar2 = FUN_00554e24(0x830107);
  }
  return uVar2;
}

