/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0033d270  name=FUN_0033d270  size=188  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0033d270(int param_1)

{
  int iVar1;
  uint uVar2;
  
  iVar1 = FUN_0033dbe8(param_1,1);
  if (iVar1 != 0) {
    FUN_000000e8(*(undefined4 *)(param_1 + 0x40),*(undefined4 *)(iVar1 + 0x14));
    FUN_0033e738(param_1,iVar1,2);
    *(int *)(param_1 + 0x74) = iVar1;
  }
  iVar1 = FUN_0033dbe8(param_1,1);
  if (iVar1 != 0) {
    FUN_000000e8(*(int *)(param_1 + 0x40) + 4,*(undefined4 *)(iVar1 + 0x14));
    FUN_0033e738(param_1,iVar1,2);
    *(int *)(param_1 + 0x78) = iVar1;
  }
  uVar2 = FUN_000000dc(*(int *)(param_1 + 0x40) + 0x10);
  FUN_000000e8(*(int *)(param_1 + 0x40) + 0x10,uVar2 | 0x70200000);
  *(undefined4 *)(param_1 + 0xa4) = 1;
  return;
}

