/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0049c320  name=FUN_0049c320  size=36  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0049c320(void)

{
  undefined4 *puVar1;
  
  puVar1 = puRam00e2b40c;
  *puRam00e2b40c = 0x4ac344;
  puVar1[2] = 0x4ac38c;
  return;
}

