/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004819bc  name=FUN_004819bc  size=200  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4
FUN_004819bc(undefined4 param_1,undefined4 param_2,int param_3,undefined4 param_4,
            undefined4 *param_5)

{
  int iVar1;
  undefined4 uVar2;
  int iVar3;
  code *pcVar4;
  
  iVar1 = FUN_00481140();
  if (iVar1 == 0) {
    uVar2 = 0xffffffff;
  }
  else {
    iVar3 = FUN_0048134c(param_1,param_2);
    if (iVar3 == 0) {
      uVar2 = 0xffffffff;
    }
    else if ((param_3 == 0) ||
            (((*(undefined4 **)(iVar1 + 0x18) != (undefined4 *)0x0 &&
              (pcVar4 = (code *)**(undefined4 **)(iVar1 + 0x18), pcVar4 != reset_vector)) &&
             (iVar1 = (*pcVar4)(param_2,param_3,param_4), iVar1 == 0)))) {
      if (param_5 != (undefined4 *)0x0) {
        *param_5 = *(undefined4 *)(iVar3 + 0x10);
      }
      uVar2 = 0;
    }
    else {
      uVar2 = 0xffffffff;
    }
  }
  return uVar2;
}

