/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0058553c  name=FUN_0058553c  size=196  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_0058553c(int param_1)

{
  int iVar1;
  char cVar2;
  
  FUN_0035ad18(0x27d1,0x599aa8,0xf);
  if (param_1 == 0) {
    iVar1 = -7;
  }
  else if ((*(char *)(param_1 + 0x18) == *(char *)(param_1 + 0xd)) &&
          (*(char *)(param_1 + 0xd) != '\0')) {
    if (*(int *)(param_1 + 0x1c) == 0) {
      iVar1 = -1;
    }
    else {
      *(undefined1 *)(param_1 + 0x40) = 1;
      cVar2 = FUN_0058c378(param_1 + 0x14);
      FUN_0035ad18(0x27d1,0x599adc,0xf);
      iVar1 = (int)cVar2;
    }
  }
  else {
    iVar1 = -1;
  }
  return iVar1;
}

