/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00481068  name=FUN_00481068  size=216  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00481068(undefined4 param_1)

{
  undefined4 uVar1;
  int iVar2;
  int iVar3;
  
  iVar2 = FUN_004802f0(0x1c);
  if (iVar2 != 0) {
    FUN_004976dc();
    uVar1 = uRam00e3a790;
    *(undefined4 *)(iVar2 + 0x14) = 0;
    *(undefined4 *)(iVar2 + 0x10) = uVar1;
    iVar3 = FUN_005ad830(1);
    *(int *)(iVar2 + 0xc) = iVar3;
    if (iVar3 != 0) {
      iVar3 = FUN_0046ea04(param_1,0x491cba,iVar2,0x490f88);
      if (iVar3 == 0) {
        iVar2 = FUN_0048121c(param_1,uRam00e3a790,1,0);
        if (iVar2 == 0) {
          return 0;
        }
        return 0xffffffff;
      }
      FUN_005ac50c(*(undefined4 *)(iVar2 + 0xc));
    }
    FUN_0047fd2c(iVar2);
  }
  return 0xffffffff;
}

