/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x005bc02c  name=FUN_005bc02c  size=124  xrefs=11
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


char * FUN_005bc02c(char *param_1,char *param_2,int param_3)

{
  char cVar1;
  int iVar2;
  char *pcVar3;
  
  iVar2 = param_3;
  pcVar3 = param_2;
  if (param_3 == 0) {
LAB_005bc068:
    if (iVar2 != 0) goto LAB_005bc09c;
  }
  else {
    iVar2 = param_3 + -1;
    if (iVar2 != 0) {
      do {
        cVar1 = *pcVar3;
        pcVar3 = pcVar3 + 1;
        *param_1 = cVar1;
        param_1 = param_1 + 1;
        if (cVar1 == '\0') break;
        iVar2 = iVar2 + -1;
      } while (iVar2 != 0);
      goto LAB_005bc068;
    }
  }
  if (param_3 != 0) {
    *param_1 = '\0';
  }
  cVar1 = *pcVar3;
  while (cVar1 != '\0') {
    pcVar3 = pcVar3 + 1;
    cVar1 = *pcVar3;
  }
  pcVar3 = pcVar3 + 1;
LAB_005bc09c:
  return pcVar3 + (-1 - (int)param_2);
}

