/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004bbee8  name=FUN_004bbee8  size=196  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_004bbee8(int param_1,uint param_2)

{
  undefined1 *puVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  uint uVar6;
  
  iVar5 = ((int)param_2 >> 1) + (uint)((int)param_2 < 0 && (param_2 & 1) != 0);
  if ((param_2 == 0) || (*(char *)(param_1 + param_2 + -1) != '\0')) {
    iVar5 = iVar5 + 1;
  }
  iVar3 = FUN_004a849c(iVar5,0xd7a368,0x5c);
  iVar4 = 0;
  if (iVar3 != 0) {
    iVar4 = 0;
    if (0 < (int)param_2) {
      uVar6 = param_2 + 1 >> 1;
      do {
        puVar1 = (undefined1 *)(param_1 + 1 + iVar4);
        iVar2 = iVar4 >> 1;
        iVar4 = iVar4 + 2;
        *(undefined1 *)(iVar3 + iVar2) = *puVar1;
        uVar6 = uVar6 - 1;
      } while (uVar6 != 0);
    }
    *(undefined1 *)(iVar3 + iVar5 + -1) = 0;
    iVar4 = iVar3;
  }
  return iVar4;
}

