/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00444bac  name=FUN_00444bac  size=220  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00444bac(int param_1,int param_2)

{
  undefined4 uVar1;
  undefined4 *puVar2;
  undefined4 *puVar3;
  undefined4 *puVar4;
  int iVar5;
  uint uVar6;
  
  uVar6 = param_2 + 1;
  if (((param_1 == 0) || ((int)uVar6 < 2)) || (0x1ffffff < uVar6)) {
    uVar1 = 0xffffffff;
  }
  else {
    puVar2 = (undefined4 *)FUN_0045964c(0x80,uVar6 * 0x80);
    if (puVar2 == (undefined4 *)0x0) {
      uVar1 = 0xffffffff;
    }
    else {
      FUN_0039acec(puVar2,0,uVar6 * 0x80);
      puVar3 = puVar2 + uVar6 * 0x20;
      puVar4 = (undefined4 *)0x0;
      iVar5 = param_2;
      do {
        iVar5 = iVar5 + -1;
        puVar3[-0x20] = puVar4;
        puVar3 = puVar3 + -0x20;
        puVar4 = puVar3;
      } while (0 < iVar5);
      puVar2[1] = param_2;
      FUN_0036fd0c();
      *puVar2 = *(undefined4 *)(param_1 + 0x18);
      *(undefined4 **)(param_1 + 0x18) = puVar2;
      FUN_0036fd24();
      FUN_00444b00(param_1 + 0xc,puVar2 + 0x20,puVar2 + 0x20 + param_2 * 0x20 + -0x20);
      uVar1 = 0;
    }
  }
  return uVar1;
}

