/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003bf144  name=FUN_003bf144  size=88  xrefs=6
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_003bf144(int *param_1)

{
  code *pcVar1;
  
  pcVar1 = (code *)**(undefined4 **)(*(int *)(*(int *)(iRam00e9c6a4 + 4) + *param_1 * 4) + 0x3c);
  if (pcVar1 != reset_vector) {
    (*pcVar1)(param_1[2]);
  }
  return;
}

