/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0027a098  name=FUN_0027a098  size=96  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0027a098(int *param_1)

{
  bool bVar1;
  char cVar2;
  int iVar3;
  
  do {
    iVar3 = param_1[2];
    bVar1 = false;
    cVar2 = '\0';
    if ((-1 < iVar3) && ((param_1[9] == 0x7fffffff || (iVar3 + 1 <= param_1[9])))) {
      bVar1 = true;
    }
    if (bVar1) {
      cVar2 = *(char *)(*param_1 + iVar3);
      param_1[2] = iVar3 + 1;
    }
  } while (cVar2 != '\0');
  return;
}

