/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003f40a4  name=FUN_003f40a4  size=84  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_003f40a4(undefined1 *param_1)

{
  char cVar1;
  char *pcVar2;
  char *pcVar3;
  
  pcVar3 = param_1 + 7;
  *param_1 = 0;
  if (param_1 + 4 <= pcVar3) {
    pcVar2 = pcVar3 + (1 - (int)param_1);
    do {
      cVar1 = *pcVar3;
      pcVar3 = pcVar3 + -1;
      if (cVar1 != '\0') {
        *param_1 = (char)pcVar2;
        return;
      }
      pcVar2 = pcVar2 + -1;
    } while (param_1 + 4 <= pcVar3);
  }
  return;
}

