/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0045ab34  name=FUN_0045ab34  size=376  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_0045ab34(undefined4 param_1,undefined4 param_2)

{
  int iVar1;
  int iVar2;
  undefined4 uVar3;
  undefined4 uVar4;
  code *pcVar5;
  
  iVar1 = FUN_004456c8(uRam00e295c0);
  if (iVar1 == 0) {
    return 0;
  }
  iVar2 = FUN_0045aa38(iVar1,param_1,param_2);
  if (iVar2 == -1) {
    FUN_0045a114(iVar1,1);
    return 0;
  }
  if (iRam00e29390 == 0) {
    return iVar1;
  }
  if (((uRam00e9c3d0 & 0x10000007) == 0x10000007) && ((*(ushort *)(iVar1 + 8) & 4) != 0)) {
    iVar2 = FUN_005bad5c(iVar1,uRam00e295c0);
    if (iVar2 == 0) {
      iVar2 = FUN_005bad5c(iVar1,uRam00e295c0);
      if ((iVar2 != 0) || ((*(ushort *)(iVar1 + 8) & 4) == 0)) goto LAB_0045ac3c;
      uVar3 = 0x2730;
      uVar4 = param_2;
      pcVar5 = *(code **)(*(int *)(iVar1 + 0x30) + 0x1c);
    }
    else {
      uVar3 = 0x275d;
      uVar4 = uRam00e295c0;
      pcVar5 = pcRam00e9c6cc;
    }
    (*pcVar5)(uVar3,2,iVar1,uVar4);
  }
LAB_0045ac3c:
  if ((uRam00e9bffc & 0x10000100) == 0x10000100) {
    (*pcRam00e9bf80)(0x2730,2,iVar1,iVar1,param_2,0,0,0);
  }
  return iVar1;
}

