/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0049caf0  name=FUN_0049caf0  size=172  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_0049caf0(int param_1,undefined4 param_2,int param_3,int param_4)

{
  int iVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  int aiStack_28 [2];
  
  iVar6 = 0;
  iVar5 = 0;
  iVar1 = FUN_0049c9a4();
  while( true ) {
    iVar2 = FUN_0049c7c0(param_1 + iVar5 * 2,iVar1,param_2,aiStack_28);
    if (iVar2 < 1) {
      return -2;
    }
    iVar4 = aiStack_28[0];
    iVar3 = FUN_0049c6b0(aiStack_28[0],param_3 + iVar6,param_4);
    if (iVar3 < 1) break;
    iVar6 = iVar6 + iVar3;
    iVar5 = iVar5 + iVar2;
    param_4 = param_4 - iVar3;
    iVar1 = iVar1 - iVar2;
    if (iVar4 == 0) {
      return iVar6;
    }
  }
  return iVar3;
}

