/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x0041f7ac  name=FUN_0041f7ac  size=516  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_0041f7ac(int param_1,undefined2 *param_2,int *param_3,int param_4)

{
  int *piVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  
  iVar3 = (uint)(ushort)param_2[9] + param_4 + -1;
  do {
    if (iVar3 < 0) break;
    piVar1 = param_3 + 3;
    if (iVar3 < *piVar1) {
      iVar4 = *(int *)(*(int *)(param_1 + 0xc) + 0x5c);
      iVar2 = param_3[2] + iVar3;
      *(undefined1 *)(iVar4 + 0xc1) = *(undefined1 *)(param_3[2] + iVar3);
      *(byte *)(iVar4 + 0xc0) = *(byte *)(iVar4 + 0xc0) | 1;
      FUN_0036c8ac(iVar2 + 1,iVar2,(param_3[3] - iVar3) + -1);
      param_3[3] = param_3[3] + -1;
      if ((*(ushort *)((int)param_3 + 0x12) & 2) == 0) {
        return;
      }
      param_3[7] = param_3[7] + -1;
      return;
    }
    param_3 = (int *)*param_3;
    iVar3 = iVar3 - *piVar1;
  } while (param_3 != (int *)0x0);
  if ((((iRam00e29390 != 0) && ((uRam00e9c3d0 & 0x1000000f) == 0x1000000f)) &&
      ((*(byte *)(iRam00e9bf84 + 7) & 2) != 0)) &&
     (iVar3 = (*pcRam00e9c080)(0,*param_2,param_2[1]), iVar3 != 0)) {
    uRam00fc16dc = 1;
    uRam00fc16dd = *(undefined1 *)(param_1 + 0x44);
    uRam00fc16de = (undefined1)*(undefined2 *)(param_1 + 0x44);
    uRam00fc16df = (undefined1)((uint)*(undefined4 *)(param_1 + 0x44) >> 8);
    uRam00fc16d8 = 0xa0082a09;
    uRam00fc16e0 = (undefined1)*(undefined4 *)(param_1 + 0x44);
    uRam00fc16e4 = 0;
    uRam00fc16e5 = 10;
    uRam00fc16e1 = 10;
    uRam00fc16e3 = 0;
    uRam00fc16e2 = 0;
    (*pcRam00e9c4d0)(0x4fb0,3,0xa0082a09,0x42f7ac,5,0,0,0,0xc,0xfc16dc);
  }
  FUN_00419de0(0xd724fc);
  return;
}

