/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002753a0  name=FUN_002753a0  size=260  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_002753a0(undefined4 *param_1,undefined4 param_2,int param_3,int *param_4,int param_5)

{
  int iVar1;
  undefined1 auStack_90 [48];
  undefined1 auStack_60 [48];
  int aiStack_30 [6];
  
  aiStack_30[0] = 0;
  if (param_5 == 0) {
    FUN_00275198(param_1,param_3,auStack_90);
  }
  else {
    FUN_0039ac74(auStack_90,param_5,0x2c);
  }
  FUN_00270f48(*param_1,aiStack_30);
  FUN_0039ac74(auStack_60,auStack_90,0x2c);
  FUN_00275288(param_3,param_2,auStack_60,*param_4,aiStack_30[0]);
  FUN_0025b10c(*param_1,param_3 + 0x9c);
  *(int *)(param_3 + 0x9c) = aiStack_30[0];
  iVar1 = *param_4;
  if (iVar1 == 0) {
    iVar1 = 1;
  }
  FUN_002fffb0(param_2,0,aiStack_30[0],iVar1);
  *param_4 = aiStack_30[0];
  return;
}

