/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x002f9a1c  name=FUN_002f9a1c  size=48  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


int FUN_002f9a1c(int param_1)

{
  int iVar1;
  int iVar2;
  int iVar3;
  
  iVar3 = *(int *)(param_1 + 8);
  iVar2 = *(int *)(param_1 + 0xc);
  iVar1 = iVar2 - iVar3;
  if (iVar2 < iVar3) {
    iVar1 = (iVar2 + *(int *)(param_1 + 4)) - iVar3;
  }
  return iVar1;
}

