/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001755c8  name=FUN_001755c8  size=432  xrefs=2
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_001755c8(int *param_1,undefined4 param_2,int param_3,uint param_4)

{
  undefined4 *puVar1;
  int extraout_r4;
  uint uVar2;
  uint uVar3;
  int iVar4;
  uint uVar5;
  undefined8 uVar6;
  
  if (*(char *)((int)param_1 + 0x31) == '\0') {
    puVar1 = (undefined4 *)FUN_00442914();
    *puVar1 = 5;
  }
  else {
    iVar4 = param_1[0x12];
    uVar5 = param_1[0x13];
    uVar3 = param_4 - uVar5;
    uVar2 = param_3 - (iVar4 + (uint)(param_4 < uVar5));
    if ((uVar2 < 0xbac) && ((uVar2 != 0xbab || (uVar3 < 0x4f6f3001)))) {
      uVar5 = (uint)*(byte *)(param_1 + 2);
      FUN_003ce56c(uVar5 * uVar2 + (int)((ulonglong)uVar5 * (ulonglong)uVar3 >> 0x20),uVar5 * uVar3,
                   0,0x46cf710);
      (**(code **)(*param_1 + 0x24))(param_1,param_1 + 0xd);
      (**(code **)(*param_1 + 0x34))(param_1,extraout_r4 + 2);
      return 0;
    }
    uVar6 = FUN_003ce56c(uVar2,uVar3,0x5d5,0xa7b79800);
    FUN_0005e784(0,3,10,0xd50e88,0x663334,0x152,0xd50eb0,0x663334,uVar6,param_3,param_4,iVar4,uVar5)
    ;
    *(undefined1 *)((int)param_1 + 0x31) = 0;
    puVar1 = (undefined4 *)FUN_00442914();
    *puVar1 = 0x26;
  }
  return 0xffffffff;
}

