/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004ada34  name=FUN_004ada34  size=100  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_004ada34(void)

{
  if (iRam00e33784 == 0) {
    return;
  }
  iRam00e33784 = 0;
  FUN_004a5874(0,0xe3370c);
  FUN_004a5874(0,0xe336f4);
  return;
}

