/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x004a6ebc  name=FUN_004a6ebc  size=28  xrefs=7
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_004a6ebc(undefined4 param_1,undefined4 param_2,undefined4 param_3)

{
  FUN_004a6dd0(param_1,1,0,param_2,param_3);
  return;
}

