/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x003ba2f4  name=FUN_003ba2f4  size=24  xrefs=6
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_003ba2f4(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  FUN_003ba0d0(0,param_1,param_2,param_3,param_4);
  return;
}

