/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x001d34a4  name=FUN_001d34a4  size=976  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


uint FUN_001d34a4(int param_1,uint param_2,undefined4 param_3)

{
  uint uVar1;
  int iVar2;
  undefined4 uVar3;
  int iVar4;
  uint uVar5;
  uint uVar6;
  char acStack_170 [32];
  uint auStack_150 [64];
  undefined4 uStack_50;
  undefined4 uStack_4c;
  
  memset(auStack_150,0x100);
  uVar1 = *(uint *)(param_1 + 8);
  uVar6 = uVar1 >> 3 & 0x1ffffffc;
  *(uint *)((int)auStack_150 + uVar6) = *(uint *)((int)auStack_150 + uVar6) | 1 << (uVar1 & 0x1f);
  uStack_4c = 1000000;
  uStack_50 = 0;
  iVar2 = FUN_004560f0(uVar1 + 1,auStack_150,0,0,&uStack_50);
  if (iVar2 == 1) {
    iVar2 = FUN_0044e144(*(undefined4 *)(param_1 + 8),acStack_170,1);
    uVar3 = 0xd55be4;
    if (iVar2 == 1) {
      if (acStack_170[0] != '\0') {
        FUN_003cb350(0xd5626c,0x66830c,acStack_170[0]);
      }
      uStack_50 = 0;
      uStack_4c = 500000;
      iVar2 = FUN_004560f0(*(int *)(param_1 + 8) + 1,auStack_150,0,0,&uStack_50);
      if (iVar2 != 1) {
        uVar3 = 0xd56350;
        goto LAB_001d3820;
      }
      iVar2 = FUN_0044e144(*(undefined4 *)(param_1 + 8),acStack_170 + 1,1);
      uVar3 = 0xd56190;
      if (iVar2 == 1) {
        iVar2 = FUN_004560f0(*(int *)(param_1 + 8) + 1,auStack_150,0,0,&uStack_50);
        if (iVar2 != 1) {
          uVar3 = 0xd56390;
          goto LAB_001d3820;
        }
        iVar2 = FUN_0044e144(*(undefined4 *)(param_1 + 8),acStack_170 + 2,1);
        uVar3 = 0xd561e4;
        if (iVar2 == 1) {
          uVar1 = (uint)(byte)acStack_170[2];
          if (0xd < uVar1) {
            FUN_003cb350(0xd563c0,0x66830c,uVar1,0xd);
            return 0xffffffff;
          }
          iVar2 = uVar1 + 1;
          if (iVar2 != 0) {
            do {
              iVar4 = FUN_004560f0(*(int *)(param_1 + 8) + 1,auStack_150,0,0,&uStack_50);
              if (iVar4 != 1) {
                uVar3 = 0xd562e8;
                goto LAB_001d3820;
              }
              iVar4 = FUN_0044e144(*(undefined4 *)(param_1 + 8),acStack_170 + ((uVar1 + 4) - iVar2),
                                   iVar2);
              iVar2 = iVar2 - iVar4;
              if (iVar4 < 1) {
                uVar3 = 0xd56298;
                goto LAB_001d37a8;
              }
            } while (0 < iVar2);
          }
          uVar6 = (uint)(byte)acStack_170[1];
          if (uVar6 != param_2) {
            FUN_003cb350(0xd56238,0x66830c,uVar6,param_2);
          }
          if (uVar1 != 0) {
            FUN_0039ac74(param_3,acStack_170 + 3,uVar1);
          }
          uVar5 = FUN_001d3464(param_1,0,param_2,param_3,uVar1,acStack_170[0]);
          if ((byte)acStack_170[uVar1 + 3] == uVar5) {
            if (uVar6 == param_2 && acStack_170[0] == '\0') {
              return uVar1;
            }
            return 0xffffffff;
          }
          uVar3 = FUN_001d3464(param_1,0,param_2,param_3,uVar1,acStack_170[0]);
          FUN_003cb350(0xd55d18,0x66830c,acStack_170[uVar1 + 3],uVar3);
          return 0xffffffff;
        }
      }
    }
LAB_001d37a8:
    FUN_003cb350(uVar3,0x66830c);
  }
  else {
    uVar3 = 0xd56318;
LAB_001d3820:
    FUN_003cb350(uVar3,0x66830c);
  }
  return 0xffffffff;
}

