/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00236f8c  name=FUN_00236f8c  size=312  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00236f8c(int *param_1,uint param_2,int param_3)

{
  int iVar1;
  uint uVar2;
  uint uVar3;
  int iVar4;
  
  iVar1 = *(int *)((int)param_1 + *(int *)(*param_1 + -0xc) + 8);
  while( true ) {
    if (iVar1 != 0) {
      return 0;
    }
    uVar2 = FUN_00639c3c(param_1);
    if (uVar2 == param_2) break;
    if ((int)uVar2 < 1) {
      return 0;
    }
    FUN_00603f40(param_1);
    uVar3 = *(uint *)(param_3 + 0x14);
    if (~uVar3 < 2) {
      FUN_002513e0(param_3);
      uVar3 = *(uint *)(param_3 + 0x14);
    }
    iVar4 = uVar3 + 1;
    iVar1 = FUN_005f0030(param_3,iVar4,0);
    if (iVar1 != 0) {
      iVar1 = param_3 + 4;
      if (0xf < *(uint *)(param_3 + 0x18)) {
        iVar1 = *(int *)(param_3 + 4);
      }
      FUN_0039acec(iVar1 + *(int *)(param_3 + 0x14),uVar2 & 0xff,1);
      iVar1 = param_3 + 4;
      if (0xf < *(uint *)(param_3 + 0x18)) {
        iVar1 = *(int *)(param_3 + 4);
      }
      *(int *)(param_3 + 0x14) = iVar4;
      *(undefined1 *)(iVar1 + iVar4) = 0;
    }
    iVar1 = *(int *)((int)param_1 + *(int *)(*param_1 + -0xc) + 8);
  }
  return 1;
}

