/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00360c84  name=FUN_00360c84  size=228  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00360c84(undefined4 param_1)

{
  int iVar1;
  uint uVar2;
  uint uVar3;
  
  FUN_00555188(uRam00e9c064,0xffffffff);
  iVar1 = FUN_0035d0b0(param_1);
  if ((iVar1 == 0) || (uVar2 = 0, *(int *)(iVar1 + 0x408) == 0)) {
    FUN_003984ac(0xd69e50);
  }
  else {
    do {
      FUN_003cb350(0xd69f70,uVar2);
      FUN_00360b10(param_1,uVar2 & 0xff);
      uVar3 = uVar2 + 1;
      if ((int)(uint)*(byte *)(iVar1 + 0x3f0) < (int)uVar3) break;
      FUN_003cb350(0xd69f70,uVar3);
      FUN_00360b10(param_1,uVar3 & 0xff);
      uVar2 = uVar2 + 2;
    } while ((int)uVar2 <= (int)(uint)*(byte *)(iVar1 + 0x3f0));
  }
  FUN_005551e8(uRam00e9c064);
  return;
}

