/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00327678  name=FUN_00327678  size=164  xrefs=4
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00327678(int *param_1)

{
  char cVar1;
  int iVar2;
  
  iVar2 = *param_1;
  if (*(char *)((int)param_1 + 0x737) == '\0') {
    cVar1 = *(char *)(param_1 + 0x1ce);
  }
  else {
    FUN_004568e4(param_1[4] * 0x94 + iVar2 + 0xeb0,0);
    cVar1 = *(char *)(param_1 + 0x1ce);
  }
  if (cVar1 == '\0') {
    return;
  }
  FUN_004568e4(param_1[4] * 0x94 + iVar2 + 0xeb0,1);
  return;
}

