/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00447778  name=FUN_00447778  size=96  xrefs=3
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


void FUN_00447778(undefined4 param_1)

{
  undefined4 uVar1;
  
  if (pcRam00e293bc == reset_vector) {
    uVar1 = 0xffffffff;
  }
  else {
    uVar1 = (*pcRam00e293bc)();
  }
  FUN_00447544(param_1,uVar1,0);
  return;
}

