/* AUTO-GENERATED by ghidra_decompile_all.py
 * address=0x00281420  name=FUN_00281420  size=60  xrefs=1
 * Firmware: RED ONE MX build_32/software.bin (PowerPC 405F6, VxWorks 6.x)
 * This is Ghidra decompiler pseudocode — not original source.
 */


undefined4 FUN_00281420(char *param_1,int param_2)

{
  undefined4 uVar1;
  
  uVar1 = 0;
  if (((1 < param_2) && (*param_1 == -1)) && (param_1[1] == -0x28)) {
    uVar1 = 1;
  }
  return uVar1;
}

